import { reviewed } from "@/lib/training/reviewed/define";
import type { ReviewedQuestion } from "@/lib/training/reviewed/types";

export const AI_ASSISTANT_QUESTIONS: readonly ReviewedQuestion[] = [
  reviewed({
    id: "ai-ge-b01",
    roleGroup: "general-employees",
    difficulty: "Beginner",
    topicTags: ["ai-security", "data-privacy"],
    technologyTags: ["ai-assistants"],
    contextTags: ["saas", "third-party-providers"],
    frameworks: ["NIST AI RMF", "GDPR Art. 5"],
    title: "Public AI rewrite of a customer complaint",
    situation:
      "You want a public AI assistant to rewrite a customer complaint containing names and claim numbers.",
    question: "What should you do?",
    options: [
      "Use an approved tool and remove data not needed for the task.",
      "Paste the full complaint.",
      "Replace only the customer's first name.",
    ],
    correct: "a",
    guidance: "AI input must follow data-classification and approved-use rules.",
    consequence:
      "The rewrite uses an approved tool and only the text that is needed, so names and claim numbers stay out of an unapproved service.",
  }),
  reviewed({
    id: "ai-ge-b02",
    roleGroup: "general-employees",
    difficulty: "Beginner",
    topicTags: ["ai-security"],
    technologyTags: ["ai-assistants"],
    contextTags: ["saas"],
    frameworks: ["NIST AI RMF"],
    title: "Confident AI policy answer without a source",
    situation: "An AI assistant gives a confident policy answer without a source.",
    question: "What should you do?",
    options: [
      "Verify it against the official policy.",
      "Treat confidence as proof.",
      "Forward it as an approved decision.",
    ],
    correct: "a",
    guidance: "Fluent output can still be inaccurate or outdated.",
    consequence:
      "The official policy is checked before anyone acts, so a fluent answer is not treated as a decision.",
  }),
  reviewed({
    id: "ai-ge-b03",
    roleGroup: "general-employees",
    difficulty: "Beginner",
    topicTags: ["ai-security"],
    technologyTags: ["ai-assistants"],
    contextTags: ["saas"],
    frameworks: ["NIST AI RMF"],
    title: "AI-drafted customer message",
    situation: "An AI assistant has drafted a customer message.",
    question: "What is required before sending?",
    options: [
      "Human review for facts, tone and authorised content.",
      "Send automatically because grammar is correct.",
      "Send it without review because the assistant drafted it.",
    ],
    correct: "a",
    guidance: "The employee remains responsible for the communication.",
    consequence:
      "A person checks facts, tone and what they are allowed to say before the customer receives the message.",
  }),
  reviewed({
    id: "ai-ge-b04",
    roleGroup: "general-employees",
    difficulty: "Beginner",
    topicTags: ["ai-security", "phishing"],
    technologyTags: ["ai-assistants"],
    contextTags: ["saas"],
    frameworks: ["OWASP GenAI", "NIST AI RMF"],
    title: "Uploaded document tells the AI to reveal other files",
    situation:
      "A document uploaded to an assistant contains text telling the AI to reveal other files.",
    question: "What should you assume?",
    options: [
      "The document is untrusted input and may contain prompt injection.",
      "Document instructions outrank company rules.",
      "Hidden text cannot affect AI.",
    ],
    correct: "a",
    guidance: "Retrieved content can manipulate model behaviour.",
    consequence:
      "The file is treated as untrusted, and the assistant is not allowed to follow its instructions to open other files.",
  }),
  reviewed({
    id: "ai-ge-c01",
    roleGroup: "general-employees",
    difficulty: "Intermediate",
    topicTags: ["ai-security"],
    technologyTags: ["ai-assistants", "microsoft-365"],
    contextTags: ["saas"],
    frameworks: ["NIST AI RMF"],
    title: "AI meeting summary invents an owner",
    situation: "An AI summary omits a decision and invents an owner.",
    question: "What should happen?",
    options: [
      "Correct it against the recording or notes before distribution.",
      "Keep it because AI is neutral.",
      "Delete the original notes.",
    ],
    correct: "a",
    guidance: "Summaries need human verification when they drive action.",
    consequence:
      "The circulated summary matches the notes, so nobody is assigned work the meeting never agreed.",
  }),
  reviewed({
    id: "ai-ge-c02",
    roleGroup: "general-employees",
    difficulty: "Intermediate",
    topicTags: ["ai-security", "data-privacy"],
    technologyTags: ["ai-assistants", "microsoft-365"],
    contextTags: ["saas"],
    frameworks: ["NIST AI RMF", "CIS 3"],
    title: "Assistant can search every SharePoint file you can open",
    situation: "An assistant can search every SharePoint file the user can access.",
    question: "What risk matters?",
    options: [
      "Existing oversharing may become easier to discover and combine.",
      "AI automatically fixes permissions.",
      "Search access cannot expose information.",
    ],
    correct: "a",
    guidance: "AI can amplify weak access governance without creating new permissions.",
    consequence:
      "Overshared sites are treated as a discovery risk, and access is reviewed before the assistant is relied on.",
  }),
  reviewed({
    id: "ai-ge-c03",
    roleGroup: "general-employees",
    difficulty: "Intermediate",
    topicTags: ["ai-security"],
    technologyTags: ["ai-assistants"],
    contextTags: ["internal-applications"],
    frameworks: ["NIST AI RMF"],
    title: "AI suggests denying a claim without clear reasoning",
    situation: "An AI suggests denying a claim, but its reasoning is unclear.",
    question: "What should the employee do?",
    options: [
      "Escalate for authorised human review and supporting evidence.",
      "Apply the decision automatically.",
      "Ask the AI to sound more certain.",
    ],
    correct: "a",
    guidance: "High-impact decisions need accountable review and an evidentiary basis.",
    consequence:
      "A person with authority reviews the evidence before the customer is told the claim is denied.",
  }),
  reviewed({
    id: "ai-ge-c04",
    roleGroup: "general-employees",
    difficulty: "Intermediate",
    topicTags: ["ai-security", "phishing"],
    technologyTags: ["ai-assistants"],
    contextTags: ["saas"],
    frameworks: ["OWASP GenAI"],
    title: "Assistant offers to submit a form on your behalf",
    situation: "An assistant offers to submit a form on your behalf.",
    question: "What should you verify?",
    options: [
      "Destination, data, permissions and final action before transmission.",
      "Only that the assistant finished quickly.",
      "Nothing if the task is convenient.",
    ],
    correct: "a",
    guidance: "Agentic actions can create external effects and require deliberate approval.",
    consequence:
      "You see where the form will go and what it will send before the assistant transmits anything.",
  }),
  reviewed({
    id: "ai-fh-b01",
    roleGroup: "finance-hr",
    difficulty: "Beginner",
    topicTags: ["ai-security", "data-privacy"],
    technologyTags: ["ai-assistants"],
    contextTags: ["saas", "internal-applications"],
    frameworks: ["NIST AI RMF", "GDPR Art. 5"],
    title: "AI analysis of a payroll export",
    situation: "Finance wants AI to find anomalies in a payroll export.",
    question: "What is the first check?",
    options: [
      "Approved tool, purpose, minimum required fields and access.",
      "Upload the full file to any chatbot.",
      "Remove the filename only.",
    ],
    correct: "a",
    guidance: "Salary and identity data require controlled processing.",
    consequence:
      "Only an approved tool sees the minimum payroll fields needed, instead of a full export in a public chatbot.",
  }),
  reviewed({
    id: "ai-fh-b02",
    roleGroup: "finance-hr",
    difficulty: "Beginner",
    topicTags: ["ai-security", "phishing"],
    technologyTags: ["ai-assistants"],
    contextTags: ["saas"],
    frameworks: ["NIST AI RMF", "CIS 14"],
    title: "AI says an invoice looks genuine",
    situation: "An AI assistant says an invoice looks genuine.",
    question: "What should Finance do?",
    options: [
      "Continue the normal verification and approval process.",
      "Treat AI as payment approval.",
      "Skip supplier checks.",
    ],
    correct: "a",
    guidance: "AI pattern recognition does not replace financial controls.",
    consequence:
      "Supplier details and approvals still follow the finance process, even if the assistant called the invoice genuine.",
  }),
  reviewed({
    id: "ai-fh-b03",
    roleGroup: "finance-hr",
    difficulty: "Beginner",
    topicTags: ["ai-security", "data-privacy"],
    technologyTags: ["ai-assistants"],
    contextTags: ["saas"],
    frameworks: ["NIST AI RMF", "GDPR Art. 5"],
    title: "AI interview summary includes facts not discussed",
    situation: "AI produces an interview summary with facts not discussed.",
    question: "What should HR do?",
    options: [
      "Correct or discard unsupported content.",
      "Store it as the official record.",
      "Ask AI to add more detail.",
    ],
    correct: "a",
    guidance: "Invented information can unfairly affect employment decisions.",
    consequence:
      "The file only contains what was discussed, so an invented remark cannot affect the candidate.",
  }),
  reviewed({
    id: "ai-fh-b04",
    roleGroup: "finance-hr",
    difficulty: "Beginner",
    topicTags: ["ai-security", "data-privacy"],
    technologyTags: ["ai-assistants"],
    contextTags: ["saas", "third-party-providers"],
    frameworks: ["NIST AI RMF"],
    title: "Vendor offers automatic applicant ranking",
    situation: "A vendor offers automatic applicant ranking.",
    question: "What is needed before use?",
    options: [
      "Defined purpose, data review, testing, human oversight and accountability.",
      "A faster contract signature.",
      "No review if the vendor calls it unbiased.",
    ],
    correct: "a",
    guidance: "High-impact AI requires governance beyond model accuracy.",
    consequence:
      "Ranking stays off until purpose, data, tests and a human owner are agreed, regardless of vendor claims.",
  }),
  reviewed({
    id: "ai-fh-c01",
    roleGroup: "finance-hr",
    difficulty: "Intermediate",
    topicTags: ["ai-security", "data-privacy"],
    technologyTags: ["ai-assistants"],
    contextTags: ["saas", "third-party-providers"],
    frameworks: ["NIST AI RMF"],
    title: "Recruitment model trained on past hiring outcomes",
    situation: "A recruitment model is trained on past hiring outcomes.",
    question: "What risk should be assessed?",
    options: [
      "Historical decisions may reproduce unfair patterns.",
      "Older data is always neutral.",
      "More rows automatically remove bias.",
    ],
    correct: "a",
    guidance: "Training data reflects the processes that produced it.",
    consequence:
      "HR reviews whether past hiring patterns would be repeated before the model ranks new applicants.",
  }),
  reviewed({
    id: "ai-fh-c02",
    roleGroup: "finance-hr",
    difficulty: "Intermediate",
    topicTags: ["ai-security", "phishing"],
    technologyTags: ["ai-assistants"],
    contextTags: ["internal-applications"],
    frameworks: ["NIST AI RMF", "CIS 6"],
    title: "AI agent can change supplier bank details",
    situation: "An AI agent can change supplier bank details.",
    question: "What is the safer architecture?",
    options: [
      "Read-only analysis with separate verified human approval for changes.",
      "Full write access using a shared account.",
      "System-prompt instructions only.",
    ],
    correct: "a",
    guidance: "Limit agency and keep high-impact actions behind independent controls.",
    consequence:
      "The agent can flag anomalies, but bank-detail changes still need a separate verified approval.",
  }),
  reviewed({
    id: "ai-fh-c03",
    roleGroup: "finance-hr",
    difficulty: "Intermediate",
    topicTags: ["ai-security", "data-privacy"],
    technologyTags: ["ai-assistants"],
    contextTags: ["internal-applications"],
    frameworks: ["NIST AI RMF", "GDPR Art. 5"],
    title: "AI contributes to a decision affecting an employee",
    situation: "AI contributes to a decision affecting an employee.",
    question: "What governance matters?",
    options: [
      "Traceable rationale, authorised human responsibility and a review or appeal path.",
      "Hiding AI involvement.",
      "Deleting input data immediately without a record.",
    ],
    correct: "a",
    guidance: "Affected people and decision-makers need meaningful accountability.",
    consequence:
      "The employee can see who decided, on what basis, and how to request a review.",
  }),
  reviewed({
    id: "ai-fh-c04",
    roleGroup: "finance-hr",
    difficulty: "Intermediate",
    topicTags: ["ai-security", "data-privacy"],
    technologyTags: ["ai-assistants"],
    contextTags: ["saas", "third-party-providers"],
    frameworks: ["NIST AI RMF", "GDPR Art. 5"],
    title: "Provider may retain prompts for service improvement",
    situation: "A provider may retain prompts for service improvement.",
    question: "What should be decided before uploading HR data?",
    options: [
      "Contractual use, retention, security, legal basis and approved configuration.",
      "Only prompt length.",
      "Whether the provider's documentation is well written.",
    ],
    correct: "a",
    guidance: "Vendor data use can change the risk and lawfulness of processing.",
    consequence:
      "HR data is uploaded only if the contract, retention and legal basis are approved for that configuration.",
  }),
  reviewed({
    id: "ai-dd-b01",
    roleGroup: "developers-devops",
    difficulty: "Beginner",
    topicTags: ["ai-security", "secure-development"],
    technologyTags: ["ai-assistants", "github"],
    contextTags: ["saas"],
    frameworks: ["OWASP GenAI", "CIS 6"],
    title: "Coding assistant asked to debug code with a production token",
    situation: "A developer asks an AI assistant to debug code containing a production token.",
    question: "What should happen?",
    options: [
      "Revoke the token and use sanitised code in an approved tool.",
      "Continue because code is technical.",
      "Ask AI not to remember it.",
    ],
    correct: "a",
    guidance: "Secrets remain sensitive regardless of the prompt's purpose.",
    consequence:
      "The token is revoked and later debugging uses sanitised samples in an approved assistant.",
  }),
  reviewed({
    id: "ai-dd-b02",
    roleGroup: "developers-devops",
    difficulty: "Beginner",
    topicTags: ["ai-security", "supply-chain"],
    technologyTags: ["ai-assistants"],
    contextTags: ["saas", "third-party-providers"],
    frameworks: ["NIST SSDF", "OWASP GenAI"],
    title: "AI suggests installing an unfamiliar package",
    situation: "AI suggests installing an unfamiliar package.",
    question: "What should the developer do?",
    options: [
      "Verify existence, provenance, maintenance and security before use.",
      "Install it because the code compiles.",
      "Disable dependency scanning.",
    ],
    correct: "a",
    guidance: "Models can hallucinate packages or recommend risky dependencies.",
    consequence:
      "The package is checked before install, so a hallucinated or malicious name never reaches the lockfile.",
  }),
  reviewed({
    id: "ai-dd-b03",
    roleGroup: "developers-devops",
    difficulty: "Beginner",
    topicTags: ["ai-security", "secure-development"],
    technologyTags: ["ai-assistants"],
    contextTags: ["internal-applications"],
    frameworks: ["OWASP GenAI"],
    title: "AI creates a SQL query for production",
    situation: "AI creates a SQL query used against production.",
    question: "What should happen first?",
    options: [
      "Review, test with least privilege and validate affected data.",
      "Execute as database owner.",
      "Trust comments in the query.",
    ],
    correct: "a",
    guidance: "Generated code is untrusted until reviewed and tested.",
    consequence:
      "The query runs only after review and a least-privilege test, not as a database owner.",
  }),
  reviewed({
    id: "ai-dd-b04",
    roleGroup: "developers-devops",
    difficulty: "Beginner",
    topicTags: ["ai-security", "secure-development"],
    technologyTags: ["ai-assistants"],
    contextTags: ["internal-applications"],
    frameworks: ["OWASP GenAI"],
    title: "LLM Markdown rendered as HTML",
    situation: "An LLM returns Markdown that becomes HTML.",
    question: "What should the app do?",
    options: [
      "Validate and sanitise for the output context.",
      "Trust model output.",
      "Leave the HTML unchanged except for headings.",
    ],
    correct: "a",
    guidance: "Improper output handling can turn model text into executable content.",
    consequence:
      "Rendered pages cannot execute unexpected markup even if the model includes it.",
  }),
  reviewed({
    id: "ai-dd-c01",
    roleGroup: "developers-devops",
    difficulty: "Intermediate",
    topicTags: ["ai-security", "secure-development"],
    technologyTags: ["ai-assistants"],
    contextTags: ["internal-applications"],
    frameworks: ["OWASP GenAI"],
    title: "Retrieved document tells the model to call an admin tool",
    situation:
      "A retrieved document tells the model to ignore policy and call an admin tool.",
    question: "What is needed?",
    options: [
      "Treat retrieval as untrusted, constrain tools and require policy outside the model.",
      "A longer system prompt only.",
      "Full admin access for consistency.",
    ],
    correct: "a",
    guidance: "Prompt injection cannot be solved by instructions alone.",
    consequence:
      "Retrieved text cannot grant admin tools, because authorisation lives outside the model.",
  }),
  reviewed({
    id: "ai-dd-c02",
    roleGroup: "developers-devops",
    difficulty: "Intermediate",
    topicTags: ["ai-security", "secure-development"],
    technologyTags: ["ai-assistants", "github"],
    contextTags: ["saas"],
    frameworks: ["OWASP GenAI", "CIS 6"],
    title: "Coding agent can modify repositories and deploy",
    situation: "An agent can modify repositories and deploy.",
    question: "What is the better boundary?",
    options: [
      "Scoped repositories and tokens, sandboxed execution and approval for privileged writes.",
      "Organisation owner access.",
      "Permanent production credentials.",
    ],
    correct: "a",
    guidance: "Agent authority should be constrained through external access controls.",
    consequence:
      "The agent can draft in a limited repo, but production writes still need a scoped token and human approval.",
  }),
  reviewed({
    id: "ai-dd-c03",
    roleGroup: "developers-devops",
    difficulty: "Intermediate",
    topicTags: ["ai-security", "secure-development"],
    technologyTags: ["ai-assistants"],
    contextTags: ["internal-applications"],
    frameworks: ["NIST AI RMF", "OWASP GenAI"],
    title: "AI feature passed happy-path tests",
    situation: "An AI feature passed happy-path tests.",
    question: "What else should be measured?",
    options: [
      "Misuse, prompt injection, data leakage, unsafe output and failure behaviour.",
      "Only response speed.",
      "Only the number of happy-path tests that already pass.",
    ],
    correct: "a",
    guidance: "AI security evaluation must cover adversarial and harmful scenarios.",
    consequence:
      "Release evidence includes injection, leakage and failure tests, not only speed or passing demos.",
  }),
  reviewed({
    id: "ai-dd-c04",
    roleGroup: "developers-devops",
    difficulty: "Intermediate",
    topicTags: ["ai-security", "secure-development"],
    technologyTags: ["ai-assistants"],
    contextTags: ["saas", "third-party-providers"],
    frameworks: ["NIST AI RMF"],
    title: "Provider changes the model behind an API",
    situation: "A provider changes the model behind an API.",
    question: "What should the team do?",
    options: [
      "Re-evaluate critical behaviour and monitor for changed risk.",
      "Assume identical results.",
      "Remove version tracking.",
    ],
    correct: "a",
    guidance: "Model and service changes can alter system behaviour without code changes.",
    consequence:
      "Critical behaviour is re-checked and versions stay tracked after the provider change.",
  }),
  reviewed({
    id: "ai-it-b01",
    roleGroup: "it-security",
    difficulty: "Beginner",
    topicTags: ["ai-security", "data-privacy"],
    technologyTags: ["ai-assistants"],
    contextTags: ["saas", "third-party-providers"],
    frameworks: ["NIST AI RMF"],
    title: "Employees use unapproved AI tools with company data",
    situation: "Employees use unapproved AI tools with company data.",
    question: "What should security do?",
    options: [
      "Combine clear approved alternatives, policy, education and proportionate monitoring.",
      "Ignore it.",
      "Publish employee prompts.",
    ],
    correct: "a",
    guidance: "Governance works better when secure use is practical and understood.",
    consequence:
      "People have an approved tool and known rules, and monitoring looks for data leaving without publishing prompts.",
  }),
  reviewed({
    id: "ai-it-b02",
    roleGroup: "it-security",
    difficulty: "Beginner",
    topicTags: ["ai-security", "data-privacy"],
    technologyTags: ["ai-assistants"],
    contextTags: ["internal-applications"],
    frameworks: ["CIS 8", "NIST AI RMF"],
    title: "What to log for a business AI application",
    situation: "The team is defining logs for a business AI application.",
    question: "What should be logged?",
    options: [
      "Relevant identity, tool actions, data access, policy outcomes and incidents with appropriate privacy controls.",
      "Every raw prompt and completion with no access limit.",
      "No application logs, because model output cannot be reconstructed.",
    ],
    correct: "a",
    guidance: "Logs should support accountability without creating unnecessary sensitive data.",
    consequence:
      "Investigators can see who used which tools and whether policy blocked an action, without hoarding unrestricted prompts.",
  }),
  reviewed({
    id: "ai-it-b03",
    roleGroup: "it-security",
    difficulty: "Beginner",
    topicTags: ["ai-security", "phishing"],
    technologyTags: ["ai-assistants"],
    contextTags: ["internal-applications"],
    frameworks: ["NIST SP 800-61r3", "OWASP GenAI"],
    title: "Repeated attempts to make the assistant reveal secrets",
    situation:
      "Monitoring sees repeated attempts to make the assistant reveal secrets.",
    question: "What should happen?",
    options: [
      "Investigate source, exposed functions and whether any output or action succeeded.",
      "Block the word ignore only.",
      "Retrain all employees immediately.",
    ],
    correct: "a",
    guidance: "Detection must assess actual system boundaries and impact.",
    consequence:
      "Responders check whether secrets or tools were reached, instead of only filtering one word.",
  }),
  reviewed({
    id: "ai-it-b04",
    roleGroup: "it-security",
    difficulty: "Beginner",
    topicTags: ["ai-security"],
    technologyTags: ["ai-assistants"],
    contextTags: ["internal-applications"],
    frameworks: ["CIS 6", "NIST AI RMF"],
    title: "Assistant uses one broad service account for every tool",
    situation: "An assistant uses one broad service account for every tool.",
    question: "What should change?",
    options: [
      "Separate scoped identities and authorisation per action and data domain.",
      "Add more permissions.",
      "Share the account with users.",
    ],
    correct: "a",
    guidance: "Tool identity determines the blast radius of model manipulation.",
    consequence:
      "Each tool runs as a scoped identity, so a prompt cannot inherit every backend permission.",
  }),
  reviewed({
    id: "ai-it-c01",
    roleGroup: "it-security",
    difficulty: "Intermediate",
    topicTags: ["ai-security", "phishing"],
    technologyTags: ["ai-assistants"],
    contextTags: ["saas"],
    frameworks: ["OWASP GenAI"],
    title: "Malicious web page influences an AI browser agent",
    situation: "A malicious web page influences an AI browser agent.",
    question: "What control is most important?",
    options: [
      "Treat external content as data, constrain actions and require confirmation for sensitive effects.",
      "Trust the model to recognise every attack.",
      "Hide the system prompt.",
    ],
    correct: "a",
    guidance: "External content must not become authority.",
    consequence:
      "Page text cannot submit forms or send data until a person confirms the action.",
  }),
  reviewed({
    id: "ai-it-c02",
    roleGroup: "it-security",
    difficulty: "Intermediate",
    topicTags: ["ai-security", "data-privacy"],
    technologyTags: ["ai-assistants"],
    contextTags: ["internal-applications", "saas"],
    frameworks: ["NIST SP 800-61r3", "OWASP GenAI"],
    title: "Assistant returned another customer's data",
    situation: "An assistant returned another customer's data.",
    question: "What should responders investigate?",
    options: [
      "Retrieval scope, access control, prompts, logs, affected records and containment.",
      "Only the wording of the answer.",
      "Only model temperature.",
    ],
    correct: "a",
    guidance:
      "Data leakage may arise from application permissions and retrieval design, not only the model.",
    consequence:
      "Access and retrieval are contained and scoped, so the incident is not closed as a wording issue.",
  }),
  reviewed({
    id: "ai-it-c03",
    roleGroup: "it-security",
    difficulty: "Intermediate",
    topicTags: ["ai-security", "business-continuity"],
    technologyTags: ["ai-assistants"],
    contextTags: ["internal-applications"],
    frameworks: ["OWASP GenAI", "CIS 8"],
    title: "Inputs cause extreme token and tool use",
    situation: "Attackers submit inputs causing extreme token and tool use.",
    question: "What should the architecture provide?",
    options: [
      "Rate, cost, recursion and resource limits with monitoring.",
      "Unlimited context.",
      "Production administrator access.",
    ],
    correct: "a",
    guidance: "AI workloads need operational abuse controls as well as content controls.",
    consequence:
      "Cost and recursion limits stop the workload from exhausting shared capacity, with alerts when they fire.",
  }),
  reviewed({
    id: "ai-it-c04",
    roleGroup: "it-security",
    difficulty: "Intermediate",
    topicTags: ["ai-security"],
    technologyTags: ["ai-assistants"],
    contextTags: ["internal-applications"],
    frameworks: ["OWASP GenAI", "CIS 6"],
    title: "Model reveals its system instructions",
    situation: "The model reveals its system instructions.",
    question: "What should security conclude?",
    options: [
      "Prompts must not contain secrets or serve as the only security boundary.",
      "Every revealed prompt is a full breach.",
      "Prompt secrecy replaces access control.",
    ],
    correct: "a",
    guidance: "Enforce security outside model instructions.",
    consequence:
      "Secrets are removed from prompts, and access control still sits in tools and identity, not in hidden text.",
  }),
  reviewed({
    id: "ai-lr-b01",
    roleGroup: "leaders-risk",
    difficulty: "Beginner",
    topicTags: ["ai-security", "business-continuity"],
    technologyTags: ["ai-assistants"],
    contextTags: ["internal-applications"],
    frameworks: ["NIST AI RMF", "NIST GV"],
    title: "Who owns an AI-assisted business process",
    situation: "A business process now uses an AI assistant.",
    question: "Who should own it?",
    options: [
      "An accountable business owner supported by technical, legal and risk specialists.",
      "The model vendor alone.",
      "Nobody because AI makes recommendations.",
    ],
    correct: "a",
    guidance: "Accountability remains with the organisation using the system.",
    consequence:
      "A named business owner remains accountable, with specialists supporting controls rather than the vendor owning the process.",
  }),
  reviewed({
    id: "ai-lr-b02",
    roleGroup: "leaders-risk",
    difficulty: "Beginner",
    topicTags: ["ai-security", "business-continuity"],
    technologyTags: ["ai-assistants"],
    contextTags: ["saas", "internal-applications"],
    frameworks: ["NIST AI RMF"],
    title: "Why maintain an inventory of AI use cases",
    situation: "Teams are adopting AI assistants without a central list.",
    question: "Why maintain an inventory of AI use cases?",
    options: [
      "To know purpose, data, owners, providers, impact and controls.",
      "To count how many employees have opened a chatbot.",
      "To treat listing a system as proof it is safe.",
    ],
    correct: "a",
    guidance: "Unknown AI use cannot be governed consistently.",
    consequence:
      "Leadership can see what each use does, who owns it and what data it touches, instead of counting chatbot opens.",
  }),
  reviewed({
    id: "ai-lr-b03",
    roleGroup: "leaders-risk",
    difficulty: "Beginner",
    topicTags: ["ai-security", "business-continuity"],
    technologyTags: ["ai-assistants"],
    contextTags: ["saas"],
    frameworks: ["NIST AI RMF"],
    title: "AI pilot saves time before scale-up",
    situation: "An AI pilot saves time.",
    question: "What else is needed before scale-up?",
    options: [
      "Risk, quality, security, privacy, oversight and failure testing.",
      "Only more licences.",
      "Removal of human review.",
    ],
    correct: "a",
    guidance: "Benefit evidence does not answer every trustworthiness question.",
    consequence:
      "Scale-up waits on tested quality, privacy and oversight, not licence count or removing reviewers.",
  }),
  reviewed({
    id: "ai-lr-b04",
    roleGroup: "leaders-risk",
    difficulty: "Beginner",
    topicTags: ["ai-security"],
    technologyTags: ["ai-assistants"],
    contextTags: ["saas"],
    frameworks: ["NIST AI RMF"],
    title: "Customers interact with an assistant",
    situation: "Customers interact with an assistant.",
    question: "What should be clear?",
    options: [
      "Its role, limitations and route to a responsible human where relevant.",
      "That it is always correct.",
      "That no employee is accountable.",
    ],
    correct: "a",
    guidance: "Transparency supports appropriate reliance and escalation.",
    consequence:
      "Customers know they are speaking with an assistant and how to reach a person when the answer matters.",
  }),
  reviewed({
    id: "ai-lr-c01",
    roleGroup: "leaders-risk",
    difficulty: "Intermediate",
    topicTags: ["ai-security", "business-continuity"],
    technologyTags: ["ai-assistants"],
    contextTags: ["internal-applications"],
    frameworks: ["NIST AI RMF"],
    title: "Assistant can approve payouts",
    situation: "An assistant can approve payouts.",
    question: "What should leadership require?",
    options: [
      "Defined authority, tested limits, human approval for high impact, monitoring and recovery.",
      "A longer system prompt instead of action limits.",
      "Full autonomy from launch.",
    ],
    correct: "a",
    guidance: "Business impact should determine the strength of oversight and action controls.",
    consequence:
      "High-value payouts still need human approval, tested limits and a way to stop the assistant.",
  }),
  reviewed({
    id: "ai-lr-c02",
    roleGroup: "leaders-risk",
    difficulty: "Intermediate",
    topicTags: ["ai-security", "business-continuity"],
    technologyTags: ["ai-assistants"],
    contextTags: ["saas", "third-party-providers"],
    frameworks: ["DORA", "NIST GV.SC"],
    title: "Critical process depends on one model API",
    situation: "A critical process depends on one model API.",
    question: "What should be assessed?",
    options: [
      "Service and data dependency, changes, incident obligations, alternatives and exit feasibility.",
      "Only price per token.",
      "Only benchmark ranking.",
    ],
    correct: "a",
    guidance: "AI services are ICT third-party dependencies with operational risk.",
    consequence:
      "Leaders know how an API outage or silent model change would hit the process and how exit would work.",
  }),
  reviewed({
    id: "ai-lr-c03",
    roleGroup: "leaders-risk",
    difficulty: "Intermediate",
    topicTags: ["ai-security", "data-privacy"],
    technologyTags: ["ai-assistants"],
    contextTags: ["saas", "third-party-providers"],
    frameworks: ["NIST AI RMF"],
    title: "Vendor claims the model is unbiased without context-specific tests",
    situation:
      "A vendor claims its model is unbiased but provides no context-specific test.",
    question: "Is that enough?",
    options: [
      "No, the organisation needs relevant evaluation and ongoing monitoring.",
      "Yes, vendor assurance transfers accountability.",
      "Yes, if accuracy is high.",
    ],
    correct: "a",
    guidance: "Trustworthiness depends on the actual use, population and consequences.",
    consequence:
      "The organisation tests the model on its own use and keeps monitoring, instead of accepting a vendor claim.",
  }),
  reviewed({
    id: "ai-lr-c04",
    roleGroup: "leaders-risk",
    difficulty: "Intermediate",
    topicTags: ["ai-security", "business-continuity"],
    technologyTags: ["ai-assistants"],
    contextTags: ["internal-applications"],
    frameworks: ["NIST AI RMF", "NIST GV"],
    title: "AI control gap cannot be fixed before launch",
    situation: "An AI control gap cannot be fixed before launch.",
    question: "What is defensible?",
    options: [
      "Explicit impact assessment, accountable acceptance, compensating controls and a short remediation deadline.",
      "Hide the gap.",
      "Remove it from the risk register.",
    ],
    correct: "a",
    guidance: "Residual AI risk needs the same disciplined ownership as other enterprise risk.",
    consequence:
      "The gap stays visible with an owner, compensating controls and a date to close it, instead of disappearing from the register.",
  }),
];
