import { reviewed } from "@/lib/training/reviewed/define";
import type { ReviewedQuestion } from "@/lib/training/reviewed/types";

export const AWS_QUESTIONS: readonly ReviewedQuestion[] = [
  reviewed({
    id: "aws-dd-b01",
    roleGroup: "developers-devops",
    difficulty: "Beginner",
    topicTags: ["cloud-security", "secure-development", "supply-chain"],
    technologyTags: ["aws", "github", "cicd"],
    contextTags: ["saas", "internal-applications"],
    frameworks: ["NIST SSDF", "CIS 6"],
    title: "GitHub Actions IAM user access key",
    situation:
      "A GitHub Actions workflow deploys to AWS using a long-lived IAM user access key stored as a repository secret.",
    question: "What is the stronger pattern?",
    options: [
      "Create a second long-lived IAM user access key as a backup secret.",
      "Use GitHub OIDC to assume a narrowly scoped IAM role with temporary credentials.",
      "Put the access key in the workflow file.",
    ],
    correct: "b",
    guidance:
      "Federation with GitHub OIDC issues short-lived credentials and removes a standing IAM key from the repository.",
    consequence:
      "The job assumes a scoped role for the run, so no long-lived AWS key sits in GitHub to leak from logs or secrets.",
  }),
  reviewed({
    id: "aws-dd-b02",
    roleGroup: "developers-devops",
    difficulty: "Beginner",
    topicTags: ["cloud-security", "secure-development"],
    technologyTags: ["aws"],
    contextTags: ["internal-applications"],
    frameworks: ["CIS 6"],
    title: "ECS task needs a database password",
    situation: "An ECS service needs a database password at runtime.",
    question: "Where should it obtain the secret?",
    options: [
      "AWS Secrets Manager through the task role.",
      "A value committed to the Dockerfile.",
      "A developer local .env file copied into the image.",
    ],
    correct: "a",
    guidance: "The task identity should retrieve secrets at runtime instead of baking them into the image.",
    consequence:
      "The password is fetched through the task role and can be rotated without rebuilding or committing credentials.",
  }),
  reviewed({
    id: "aws-dd-b03",
    roleGroup: "developers-devops",
    difficulty: "Beginner",
    topicTags: ["cloud-security", "supply-chain"],
    technologyTags: ["aws", "cicd"],
    contextTags: ["internal-applications"],
    frameworks: ["CIS 3", "CIS 6"],
    title: "Pipeline stores release packages in S3",
    situation: "A pipeline stores release packages in an S3 bucket.",
    question: "How should that bucket be protected?",
    options: [
      "Allow public read so any environment can pull packages.",
      "Block public access, encrypt the bucket and grant the pipeline role only the required actions.",
      "Share one root-account access key with every pipeline.",
    ],
    correct: "b",
    guidance: "Release artefacts need least-privilege access, encryption and no public exposure.",
    consequence:
      "Only the pipeline role can write or read the packages, and the bucket cannot be opened by a public ACL or policy.",
  }),
  reviewed({
    id: "aws-dd-b04",
    roleGroup: "developers-devops",
    difficulty: "Beginner",
    topicTags: ["cloud-security", "supply-chain"],
    technologyTags: ["aws"],
    contextTags: ["internal-applications"],
    frameworks: ["NIST SSDF"],
    title: "Kubernetes deploys app:latest from ECR",
    situation: "A Kubernetes workload is configured to deploy app:latest from Amazon ECR.",
    question: "What improves integrity?",
    options: [
      "Deploy the approved immutable image digest.",
      "Trust the latest tag permanently.",
      "Let every developer overwrite the production tag.",
    ],
    correct: "a",
    guidance: "An immutable digest binds the cluster to the artefact that was reviewed and tested.",
    consequence:
      "The cluster runs the tested digest even if someone later retags latest in ECR.",
  }),
  reviewed({
    id: "aws-dd-b05",
    roleGroup: "developers-devops",
    difficulty: "Beginner",
    topicTags: ["cloud-security", "secure-development"],
    technologyTags: ["aws", "cicd"],
    contextTags: ["internal-applications"],
    frameworks: ["CIS 6", "NIST SSDF"],
    title: "CodeBuild logs contain a token",
    situation: "CodeBuild logs include environment variables and a live access token.",
    question: "What should happen?",
    options: [
      "Treat the token as exposed, revoke it and stop secrets being written to logs.",
      "Make the log group public so others can help review it.",
      "Rename the build project and keep using the token.",
    ],
    correct: "a",
    guidance: "A credential in a log is already available to anyone who can read that log.",
    consequence:
      "The token is revoked, logging is tightened, and a rename is not treated as containment.",
  }),
  reviewed({
    id: "aws-dd-b06",
    roleGroup: "developers-devops",
    difficulty: "Beginner",
    topicTags: ["cloud-security"],
    technologyTags: ["aws"],
    contextTags: ["internal-applications"],
    frameworks: ["CIS 6"],
    title: "EKS workload needs one S3 bucket",
    situation: "An EKS workload only needs to read objects from one S3 bucket.",
    question: "Which identity design is preferable?",
    options: [
      "Give the EKS node instance role AdministratorAccess.",
      "Use EKS Pod Identity or IRSA with a role limited to that bucket.",
      "Mount a developer's AWS credentials into the pod.",
    ],
    correct: "b",
    guidance: "Workload identity should grant only the actions and resources that pod actually needs.",
    consequence:
      "The pod assumes a role that can read that bucket, without node-wide admin or a developer's long-lived keys.",
  }),
  reviewed({
    id: "aws-dd-b07",
    roleGroup: "developers-devops",
    difficulty: "Beginner",
    topicTags: ["cloud-security", "secure-development"],
    technologyTags: ["aws"],
    contextTags: ["internal-applications"],
    frameworks: ["CIS 3", "CIS 4"],
    title: "Terraform disables S3 Block Public Access",
    situation: "A Terraform pull request disables S3 Block Public Access on a bucket that holds internal data.",
    question: "What should the pipeline do?",
    options: [
      "Merge because the change is declarative infrastructure.",
      "Fail the policy check and require a documented, reviewed exception.",
      "Apply the change manually outside version control.",
    ],
    correct: "b",
    guidance: "Preventive policy should stop unintended public access before it is applied.",
    consequence:
      "The change never reaches the account unless an owned exception is recorded and reviewed.",
  }),
  reviewed({
    id: "aws-dd-b08",
    roleGroup: "developers-devops",
    difficulty: "Beginner",
    topicTags: ["cloud-security"],
    technologyTags: ["aws"],
    contextTags: ["internal-applications"],
    frameworks: ["CIS 6"],
    title: "Lambda role allows dynamodb:* on *",
    situation:
      "A Lambda function only reads one DynamoDB table, but its role allows dynamodb:* on all resources.",
    question: "What should change?",
    options: [
      "Restrict actions and resources to the actual table and operations needed.",
      "Add EC2 administrator permissions as a backup.",
      "Share the same role with every Lambda in the account.",
    ],
    correct: "a",
    guidance: "IAM roles should match the function's real data-plane need, not a wildcard for convenience.",
    consequence:
      "Compromise of that function can only reach the intended table, not every DynamoDB resource in the account.",
  }),
  reviewed({
    id: "aws-dd-c01",
    roleGroup: "developers-devops",
    difficulty: "Intermediate",
    topicTags: ["cloud-security", "secure-development"],
    technologyTags: ["aws", "github", "cicd"],
    contextTags: ["saas", "internal-applications"],
    frameworks: ["CIS 6", "NIST SSDF"],
    title: "GitHub OIDC role trusts every repository",
    situation:
      "GitHub OIDC is enabled, but the AWS IAM role trust policy accepts every repository in the organisation.",
    question: "What should be tightened?",
    options: [
      "Conditions for the expected repository, branch or environment, and audience.",
      "Document the trust in a wiki page.",
      "Change the role's display name.",
    ],
    correct: "a",
    guidance: "OIDC only helps if the trust policy cannot be assumed by an unrelated repository or workflow.",
    consequence:
      "Only the intended repository and environment can assume the role, so a forked or unrelated workflow cannot deploy.",
  }),
  reviewed({
    id: "aws-dd-c02",
    roleGroup: "developers-devops",
    difficulty: "Intermediate",
    topicTags: ["cloud-security", "secure-development"],
    technologyTags: ["aws", "cicd"],
    contextTags: ["internal-applications"],
    frameworks: ["CIS 6", "NIST SSDF"],
    title: "One pipeline deploys to dev and prod accounts",
    situation: "A central pipeline deploys into both development and production AWS accounts.",
    question: "What is the stronger access model?",
    options: [
      "Store root-account access keys for both accounts in the pipeline.",
      "Assume separate environment-specific roles with distinct permissions and production approval.",
      "Use the same administrator IAM user in every account.",
    ],
    correct: "b",
    guidance: "Production should require a different identity, narrower permissions and a stronger approval gate.",
    consequence:
      "A compromised development job cannot use production administrator rights, and production still needs approval.",
  }),
  reviewed({
    id: "aws-dd-c03",
    roleGroup: "developers-devops",
    difficulty: "Intermediate",
    topicTags: ["cloud-security"],
    technologyTags: ["aws"],
    contextTags: ["internal-applications"],
    frameworks: ["CIS 3", "CIS 6"],
    title: "Service can kms:Decrypt on every key",
    situation: "A service role can call kms:Decrypt on every KMS key in the account.",
    question: "What is the risk?",
    options: [
      "Compromise could expose unrelated encrypted data.",
      "Encryption makes broad decrypt permission safe.",
      "CloudTrail automatically blocks decrypt.",
    ],
    correct: "a",
    guidance: "KMS encryption still requires least-privileged decrypt on the keys that service actually uses.",
    consequence:
      "The role is limited to the keys it needs, so one compromise cannot unwrap unrelated ciphertext.",
  }),
  reviewed({
    id: "aws-dd-c04",
    roleGroup: "developers-devops",
    difficulty: "Intermediate",
    topicTags: ["cloud-security", "supply-chain"],
    technologyTags: ["aws", "cicd"],
    contextTags: ["internal-applications", "third-party-providers"],
    frameworks: ["NIST SSDF", "CIS 6"],
    title: "Malicious dependency in an AWS deploy job",
    situation: "A malicious dependency executed during an AWS deployment job.",
    question: "What should the team assume?",
    options: [
      "Every credential and artefact available to that job may be exposed or altered.",
      "Only the dependency name in the lockfile matters.",
      "Temporary credentials cannot be abused before they expire.",
    ],
    correct: "a",
    guidance: "Code running in a privileged job can use whatever identity, secrets and artefacts that job can reach.",
    consequence:
      "The job identity is treated as exposed, artefacts are rechecked, and remaining session credentials are revoked.",
  }),
  reviewed({
    id: "aws-dd-c05",
    roleGroup: "developers-devops",
    difficulty: "Intermediate",
    topicTags: ["cloud-security", "supply-chain"],
    technologyTags: ["aws", "cicd"],
    contextTags: ["internal-applications"],
    frameworks: ["NIST SSDF"],
    title: "Locally modified CloudFormation before deploy",
    situation:
      "A reviewed CloudFormation template is replaced with a locally modified copy immediately before deploy.",
    question: "What is missing?",
    options: [
      "Deploy the reviewed artefact by digest or commit from a controlled pipeline.",
      "Use a longer stack name.",
      "Give the deployer more AWS console access.",
    ],
    correct: "a",
    guidance: "Review has little value if a different template is what CloudFormation actually applies.",
    consequence:
      "Production receives the pipeline artefact that passed review, not an unreviewed laptop copy.",
  }),
  reviewed({
    id: "aws-dd-c06",
    roleGroup: "developers-devops",
    difficulty: "Intermediate",
    topicTags: ["cloud-security"],
    technologyTags: ["aws"],
    contextTags: ["internal-applications"],
    frameworks: ["CIS 4", "CIS 6"],
    title: "RDS security group opened to 0.0.0.0/0",
    situation:
      "A team cannot connect to RDS and opens the database security group to 0.0.0.0/0 to restore access.",
    question: "What should happen instead?",
    options: [
      "Keep the group open and rely on the database password.",
      "Diagnose routing and security-group references, then allow only the required source.",
      "Move the database password into source code.",
    ],
    correct: "b",
    guidance: "Fix the connectivity path without discarding the network boundary around the database.",
    consequence:
      "The application or bastion that should connect is allowed, and the database is not reachable from the internet.",
  }),
  reviewed({
    id: "aws-dd-c07",
    roleGroup: "developers-devops",
    difficulty: "Intermediate",
    topicTags: ["cloud-security"],
    technologyTags: ["aws"],
    contextTags: ["internal-applications"],
    frameworks: ["CIS 3", "CIS 6"],
    title: "Seven-day pre-signed URLs for sensitive reports",
    situation: "An application generates S3 pre-signed URLs that remain valid for seven days for sensitive reports.",
    question: "What should be assessed?",
    options: [
      "Whether validity, object scope and recipient flow match the business need.",
      "Whether the URL is short.",
      "Whether the bucket has a cost tag.",
    ],
    correct: "a",
    guidance: "A pre-signed URL is an access grant; its lifetime and object scope must match who should still be able to open it.",
    consequence:
      "URLs are shortened or scoped if seven days and the object set are wider than the business need.",
  }),
  reviewed({
    id: "aws-dd-c08",
    roleGroup: "developers-devops",
    difficulty: "Intermediate",
    topicTags: ["cloud-security", "supply-chain"],
    technologyTags: ["aws"],
    contextTags: ["internal-applications"],
    frameworks: ["NIST SSDF"],
    title: "ECR scan finds a critical base-image vulnerability",
    situation:
      "Amazon ECR image scanning reports a critical vulnerability in the base image used by a production service.",
    question: "What should the team do?",
    options: [
      "Assess exploitability, rebuild from a fixed base, rerun tests and redeploy a verified digest.",
      "Delete the finding without changing the image.",
      "Retag the existing image as safe.",
    ],
    correct: "a",
    guidance: "A scanner finding is not closed by renaming or hiding it; the running artefact has to change if the risk is real.",
    consequence:
      "Production runs a rebuilt, tested digest, and the old vulnerable image is no longer what the service deploys.",
  }),
  reviewed({
    id: "aws-it-b01",
    roleGroup: "it-security",
    difficulty: "Beginner",
    topicTags: ["cloud-security"],
    technologyTags: ["aws"],
    contextTags: ["internal-applications"],
    frameworks: ["CIS 5", "CIS 6"],
    title: "How to treat the AWS root user",
    situation: "The organisation is deciding how the AWS account root user should be used.",
    question: "What is appropriate?",
    options: [
      "Use it for daily administration.",
      "Protect it strongly, avoid routine use and monitor any root activity.",
      "Share the root credentials with the service desk.",
    ],
    correct: "b",
    guidance: "Root bypasses IAM permission boundaries and should be a break-glass identity, not an operations login.",
    consequence:
      "Day-to-day work uses IAM roles, and any root sign-in is treated as an exceptional event to investigate.",
  }),
  reviewed({
    id: "aws-it-b02",
    roleGroup: "it-security",
    difficulty: "Beginner",
    topicTags: ["cloud-security", "ransomware"],
    technologyTags: ["aws"],
    contextTags: ["internal-applications"],
    frameworks: ["CIS 10", "NIST SP 800-61r3"],
    title: "GuardDuty unusual API activity from an IAM role",
    situation: "GuardDuty reports unusual API activity from an IAM role.",
    question: "What should responders do?",
    options: [
      "Validate the finding, identify the role's permissions and contain suspected access.",
      "Disable GuardDuty to stop the alerts.",
      "Delete the related CloudTrail events.",
    ],
    correct: "a",
    guidance: "A detection is a starting point: confirm it, then limit what that identity can still do and keep the evidence.",
    consequence:
      "The role is scoped or revoked from evidence, and CloudTrail remains available for the investigation.",
  }),
  reviewed({
    id: "aws-it-b03",
    roleGroup: "it-security",
    difficulty: "Beginner",
    topicTags: ["cloud-security"],
    technologyTags: ["aws"],
    contextTags: ["internal-applications"],
    frameworks: ["CIS 8"],
    title: "What CloudTrail primarily records",
    situation: "Responders are choosing which AWS log to pull first.",
    question: "What does CloudTrail primarily show?",
    options: [
      "API activity by users, roles and AWS services.",
      "The contents of every application database.",
      "Whether backups can restore a workload.",
    ],
    correct: "a",
    guidance: "CloudTrail is control-plane and selected data-event evidence; it does not replace application or restore tests.",
    consequence:
      "The team uses CloudTrail for who did what in the API, and still collects database and recovery evidence elsewhere.",
  }),
  reviewed({
    id: "aws-it-b04",
    roleGroup: "it-security",
    difficulty: "Beginner",
    topicTags: ["cloud-security"],
    technologyTags: ["aws"],
    contextTags: ["internal-applications"],
    frameworks: ["CIS 3"],
    title: "Account-level S3 Block Public Access disabled",
    situation: "Account-level S3 Block Public Access is disabled.",
    question: "What does that mean?",
    options: [
      "Every bucket is definitely public.",
      "Public exposure is possible; assess effective bucket, access-point, account and organisation settings.",
      "S3 cannot be secured in this account.",
    ],
    correct: "b",
    guidance: "Block Public Access is a control layer; effective exposure depends on every layer that can still grant public access.",
    consequence:
      "The team checks account, organisation, access-point and bucket settings instead of assuming every object is already public or already safe.",
  }),
  reviewed({
    id: "aws-it-b05",
    roleGroup: "it-security",
    difficulty: "Beginner",
    topicTags: ["cloud-security"],
    technologyTags: ["aws"],
    contextTags: ["internal-applications"],
    frameworks: ["CIS 6"],
    title: "What IAM Access Analyzer is for",
    situation: "The security team is choosing a control to review external sharing of AWS resources.",
    question: "What is IAM Access Analyzer designed to do?",
    options: [
      "Identify public or cross-account access and help validate policies.",
      "Replace multi-factor authentication.",
      "Restore EC2 instances.",
    ],
    correct: "a",
    guidance: "Access Analyzer evaluates resource policies for external access; it does not replace identity or recovery controls.",
    consequence:
      "External grants are reviewed and tightened, while MFA and backup remain separate controls.",
  }),
  reviewed({
    id: "aws-it-b06",
    roleGroup: "it-security",
    difficulty: "Beginner",
    topicTags: ["cloud-security"],
    technologyTags: ["aws"],
    contextTags: ["internal-applications"],
    frameworks: ["CIS 4"],
    title: "Evidence that production security groups stay in policy",
    situation:
      "The security team needs evidence that production security groups remain within policy over time.",
    question: "Which AWS capability is designed for that?",
    options: [
      "AWS Config recording and rules.",
      "Route 53 DNS records only.",
      "AWS Budgets only.",
    ],
    correct: "a",
    guidance: "Config evaluates and records resource configuration; DNS and cost tools do not prove security-group posture.",
    consequence:
      "Configuration history and rules show whether production groups drifted, without treating Route 53 or Budgets as that evidence.",
  }),
  reviewed({
    id: "aws-it-b07",
    roleGroup: "it-security",
    difficulty: "Beginner",
    topicTags: ["cloud-security"],
    technologyTags: ["aws"],
    contextTags: ["internal-applications"],
    frameworks: ["CIS 8", "CIS 10"],
    title: "GuardDuty compared with Security Hub CSPM",
    situation: "A stakeholder asks whether GuardDuty and Security Hub CSPM do the same job.",
    question: "How do they differ?",
    options: [
      "GuardDuty detects suspicious activity; Security Hub CSPM aggregates and prioritises findings and checks.",
      "They are backup and restore products.",
      "Both only track billing anomalies.",
    ],
    correct: "a",
    guidance: "Threat detection and posture management are complementary; neither replaces backups or billing controls.",
    consequence:
      "Unusual API or network behaviour is investigated from GuardDuty, while posture gaps are tracked through Security Hub.",
  }),
  reviewed({
    id: "aws-it-b08",
    roleGroup: "it-security",
    difficulty: "Beginner",
    topicTags: ["cloud-security"],
    technologyTags: ["aws"],
    contextTags: ["internal-applications"],
    frameworks: ["CIS 8"],
    title: "What VPC Flow Logs contain",
    situation: "Responders are deciding whether VPC Flow Logs will show what an attacker sent.",
    question: "What do VPC Flow Logs primarily provide?",
    options: [
      "Metadata about accepted and rejected network flows.",
      "Full application payloads and passwords.",
      "A list of HR employees.",
    ],
    correct: "a",
    guidance: "Flow logs describe who talked to whom, not the contents of the packets or people data.",
    consequence:
      "The team uses flow logs for network paths and still collects application, identity and endpoint evidence for payload or people questions.",
  }),
  reviewed({
    id: "aws-it-c01",
    roleGroup: "it-security",
    difficulty: "Intermediate",
    topicTags: ["cloud-security", "ransomware"],
    technologyTags: ["aws"],
    contextTags: ["internal-applications"],
    frameworks: ["NIST SP 800-61r3", "CIS 6"],
    title: "Role temporary credentials from an unknown location",
    situation: "Temporary credentials for an IAM role are used from an unknown location.",
    question: "What should containment include?",
    options: [
      "Restrict or revoke the role's effective access, stop the compromised workload or session path, and preserve CloudTrail and related evidence.",
      "Wait for the credentials to expire.",
      "Rename the role only.",
    ],
    correct: "a",
    guidance: "STS sessions can be reused until they expire or are denied; a display-name change does not stop them.",
    consequence:
      "The identity path is blocked and evidence is kept, so expiry or a rename is not treated as containment.",
  }),
  reviewed({
    id: "aws-it-c02",
    roleGroup: "it-security",
    difficulty: "Intermediate",
    topicTags: ["cloud-security"],
    technologyTags: ["aws"],
    contextTags: ["internal-applications"],
    frameworks: ["CIS 4", "CIS 6"],
    title: "Accounts keep creating internet-exposed resources",
    situation: "Member accounts repeatedly create internet-exposed resources despite local guidance.",
    question: "What reduces recurrence?",
    options: [
      "Service control policies combined with account-level controls and monitoring.",
      "One shared administrator password across accounts.",
      "A spreadsheet reminder to owners.",
    ],
    correct: "a",
    guidance: "Organisation guardrails prevent the action; reminders and shared passwords do not.",
    consequence:
      "SCPs and account controls block the public exposure pattern, and monitoring still flags attempts.",
  }),
  reviewed({
    id: "aws-it-c03",
    roleGroup: "it-security",
    difficulty: "Intermediate",
    topicTags: ["cloud-security", "ransomware"],
    technologyTags: ["aws"],
    contextTags: ["internal-applications"],
    frameworks: ["CIS 8"],
    title: "Organisation trails in a log-archive account",
    situation:
      "CloudTrail organisation trails are delivered to a dedicated log-archive account with restricted write and delete.",
    question: "Why design it that way?",
    options: [
      "To make incident evidence harder for a compromised workload account to alter.",
      "To eliminate the need for retention.",
      "To make API calls anonymous.",
    ],
    correct: "a",
    guidance: "Separate log custody stops the account under investigation from deleting its own history.",
    consequence:
      "A compromised workload account cannot quietly wipe the organisation trail, and retention still has to be defined.",
  }),
  reviewed({
    id: "aws-it-c04",
    roleGroup: "it-security",
    difficulty: "Intermediate",
    topicTags: ["cloud-security", "ransomware"],
    technologyTags: ["aws"],
    contextTags: ["internal-applications"],
    frameworks: ["NIST SP 800-61r3", "CIS 8"],
    title: "GuardDuty suspicious behaviour in EKS",
    situation: "GuardDuty reports suspicious behaviour in an EKS cluster.",
    question: "What should responders correlate?",
    options: [
      "Kubernetes audit and runtime findings, CloudTrail, workload identity permissions and relevant network or application logs.",
      "Only the pod name.",
      "Only the monthly AWS invoice.",
    ],
    correct: "a",
    guidance: "EKS incidents span cluster identity, AWS APIs and the network path the workload can reach.",
    consequence:
      "Scope is taken from cluster, CloudTrail and identity evidence, not from a pod label or a billing line.",
  }),
  reviewed({
    id: "aws-it-c05",
    roleGroup: "it-security",
    difficulty: "Intermediate",
    topicTags: ["cloud-security", "ransomware"],
    technologyTags: ["aws"],
    contextTags: ["internal-applications"],
    frameworks: ["NIST SP 800-61r3", "CIS 3"],
    title: "Sensitive bucket publicly reachable for four hours",
    situation: "A sensitive S3 bucket was publicly reachable for four hours.",
    question: "What should the assessment include?",
    options: [
      "Effective policy history, object sensitivity, CloudTrail data events or access logs where available, and evidence of access.",
      "Only whether anyone complained.",
      "Only the bucket creation date.",
    ],
    correct: "a",
    guidance: "Impact depends on what was exposed and whether it was retrieved, not on complaints or age of the bucket.",
    consequence:
      "The team reconstructs who could have listed or got objects and treats confirmed access as a disclosure, not a closed ticket.",
  }),
  reviewed({
    id: "aws-it-c06",
    roleGroup: "it-security",
    difficulty: "Intermediate",
    topicTags: ["cloud-security", "ransomware"],
    technologyTags: ["aws"],
    contextTags: ["internal-applications"],
    frameworks: ["NIST SP 800-61r3"],
    title: "Compromised EC2 may hold volatile evidence",
    situation: "A compromised EC2 instance may contain volatile evidence.",
    question: "What should responders do?",
    options: [
      "Apply a tested isolation playbook, preserve required evidence and avoid unnecessary destructive actions.",
      "Terminate the instance immediately in every case.",
      "Leave it fully connected until the investigation ends.",
    ],
    correct: "a",
    guidance: "Containment should reduce risk without automatically destroying memory, disks or session evidence.",
    consequence:
      "The instance is isolated according to the playbook, snapshots or memory are preserved where required, and it is not left on the network by default.",
  }),
  reviewed({
    id: "aws-it-c07",
    roleGroup: "it-security",
    difficulty: "Intermediate",
    topicTags: ["cloud-security", "ransomware"],
    technologyTags: ["aws"],
    contextTags: ["internal-applications"],
    frameworks: ["CIS 11", "NIST RC"],
    title: "Restore tests into an isolated recovery environment",
    situation:
      "The team is asked why critical AWS workloads should be restored into an isolated recovery environment.",
    question: "Why test that way?",
    options: [
      "To verify backups, dependencies, permissions and a clean recovery without trusting the affected environment.",
      "To avoid documenting recovery time objectives.",
      "To prove that every AWS region can never fail.",
    ],
    correct: "a",
    guidance: "A restore is only proven when the service can start with the right identities and dependencies away from a possibly compromised account.",
    consequence:
      "The organisation knows the backup can rebuild the workload, instead of assuming snapshots in the affected account are enough.",
  }),
  reviewed({
    id: "aws-it-c08",
    roleGroup: "it-security",
    difficulty: "Intermediate",
    topicTags: ["cloud-security", "ransomware"],
    technologyTags: ["aws"],
    contextTags: ["internal-applications"],
    frameworks: ["CIS 3", "CIS 6", "NIST SP 800-61r3"],
    title: "Unauthorised principal can use a sensitive KMS key",
    situation:
      "An unauthorised principal received permission to use a KMS key that protects sensitive data.",
    question: "What should the assessment cover?",
    options: [
      "Key policy and grants, data and services reachable with the permission, CloudTrail use and required containment.",
      "Only the key alias.",
      "Only whether ciphertext still exists.",
    ],
    correct: "a",
    guidance: "KMS permission is access to the plaintext of whatever that key still protects.",
    consequence:
      "The grant is removed, use is checked in CloudTrail, and reachable encrypted stores are treated as in-scope.",
  }),
  reviewed({
    id: "aws-lr-b01",
    roleGroup: "leaders-risk",
    difficulty: "Beginner",
    topicTags: ["cloud-security", "business-continuity"],
    technologyTags: ["aws"],
    contextTags: ["internal-applications", "third-party-providers"],
    frameworks: ["NIST GV"],
    title: "Does AWS own all security because it runs infrastructure",
    situation:
      "A business owner says AWS runs the infrastructure, so AWS is responsible for all security.",
    question: "Is that correct?",
    options: [
      "Shared responsibility depends on the service; the customer still owns identities, data and configuration.",
      "AWS owns every customer decision.",
      "The contract removes all business accountability.",
    ],
    correct: "a",
    guidance: "Managed infrastructure changes operational tasks but not organisational accountability for identity, data and setup.",
    consequence:
      "The organisation still owns IAM, data classification and configuration even when AWS operates the platform.",
  }),
  reviewed({
    id: "aws-lr-b02",
    roleGroup: "leaders-risk",
    difficulty: "Beginner",
    topicTags: ["cloud-security", "business-continuity"],
    technologyTags: ["aws"],
    contextTags: ["internal-applications"],
    frameworks: ["NIST GV"],
    title: "Business and technical owners for each AWS account",
    situation: "Several AWS accounts have no named business or technical owner.",
    question: "Why does each account need both?",
    options: [
      "So risks, costs, access, recovery and exceptions have accountable decision-makers.",
      "So the account alias is easier to remember.",
      "So vendors can use the root user.",
    ],
    correct: "a",
    guidance: "Cloud governance requires people who can accept risk, approve access and own recovery for that account.",
    consequence:
      "Each account has someone who can approve exceptions and recovery, instead of an unnamed shared environment.",
  }),
  reviewed({
    id: "aws-lr-b03",
    roleGroup: "leaders-risk",
    difficulty: "Beginner",
    topicTags: ["cloud-security", "business-continuity"],
    technologyTags: ["aws"],
    contextTags: ["internal-applications"],
    frameworks: ["NIST RC", "CIS 11"],
    title: "Automated backups without a recorded restore test",
    situation:
      "A critical AWS service has automated backups, but no restore has been recorded as tested.",
    question: "What is proven?",
    options: [
      "Recovery capability is not yet demonstrated.",
      "Backups guarantee the recovery time objective.",
      "AWS will restore the application automatically in every scenario.",
    ],
    correct: "a",
    guidance: "A successful backup job is not evidence that identities, dependencies and the application can meet recovery objectives.",
    consequence:
      "Leadership treats backup jobs as copies, and still requires a restore test of the service.",
  }),
  reviewed({
    id: "aws-lr-b04",
    roleGroup: "leaders-risk",
    difficulty: "Beginner",
    topicTags: ["cloud-security", "business-continuity"],
    technologyTags: ["aws"],
    contextTags: ["third-party-providers", "internal-applications"],
    frameworks: ["NIST GV", "CIS 6"],
    title: "Third party needs admin access to one workload",
    situation: "A third party needs administrator access to one AWS workload.",
    question: "What should be granted?",
    options: [
      "A scoped assumable role, an approved purpose, monitoring and an end date.",
      "Shared root credentials.",
      "Permanent administrator access to every account.",
    ],
    correct: "a",
    guidance: "Supplier access should be time-bound, least-privileged and observable.",
    consequence:
      "The supplier assumes a monitored role for that workload only, and access expires when the work ends.",
  }),
  reviewed({
    id: "aws-lr-b05",
    roleGroup: "leaders-risk",
    difficulty: "Beginner",
    topicTags: ["cloud-security", "business-continuity"],
    technologyTags: ["aws"],
    contextTags: ["internal-applications"],
    frameworks: ["NIST GV", "CIS 3"],
    title: "Exception to publish data from S3",
    situation: "A project wants an exception to publish data from S3.",
    question: "What should governance require?",
    options: [
      "Confirmed classification, business purpose, limited design, owner, monitoring and expiry or review.",
      "Approval because S3 supports static websites.",
      "No documentation if the request is urgent.",
    ],
    correct: "a",
    guidance: "Public data publication is a time-bound risk decision, not a feature of the storage product.",
    consequence:
      "The exception has an owner, a limited design and a review date, instead of an undocumented public bucket.",
  }),
  reviewed({
    id: "aws-lr-b06",
    roleGroup: "leaders-risk",
    difficulty: "Beginner",
    topicTags: ["cloud-security", "business-continuity"],
    technologyTags: ["aws"],
    contextTags: ["internal-applications", "third-party-providers"],
    frameworks: ["NIST RC", "DORA"],
    title: "Skills and dependencies in the AWS resilience plan",
    situation:
      "An AWS resilience plan lists services but not internal skills or external dependencies.",
    question: "Why identify both?",
    options: [
      "Recovery and exit may fail if the organisation cannot operate the required tooling and decisions.",
      "Skills are unrelated to technology risk.",
      "The provider performs every application task.",
    ],
    correct: "a",
    guidance: "A platform does not recover itself if the organisation lacks the people, suppliers or runbooks to operate it.",
    consequence:
      "The plan names who can run IAM, networking and restore steps, and which suppliers the service actually depends on.",
  }),
  reviewed({
    id: "aws-lr-b07",
    roleGroup: "leaders-risk",
    difficulty: "Beginner",
    topicTags: ["cloud-security", "business-continuity"],
    technologyTags: ["aws"],
    contextTags: ["internal-applications"],
    frameworks: ["NIST GV", "ISO 27001"],
    title: "Security Hub checks all green",
    situation: "A dashboard shows all Security Hub checks as green.",
    question: "Does that prove the organisation is compliant and resilient?",
    options: [
      "No; it is useful control evidence but must be interpreted with business scope, risks and other requirements.",
      "Yes, it proves every legal obligation.",
      "Yes, it replaces testing.",
    ],
    correct: "a",
    guidance: "Automated checks are one evidence source; they do not cover every obligation or prove recovery.",
    consequence:
      "Leaders still require scoped risk decisions and restore tests, instead of treating a green dashboard as complete assurance.",
  }),
  reviewed({
    id: "aws-lr-b08",
    roleGroup: "leaders-risk",
    difficulty: "Beginner",
    topicTags: ["cloud-security", "business-continuity"],
    technologyTags: ["aws"],
    contextTags: ["internal-applications"],
    frameworks: ["NIST GV", "NIST SP 800-61r3"],
    title: "Who can isolate a compromised AWS account",
    situation:
      "A compromised AWS account may need temporary isolation from the organisation.",
    question: "What should be decided before an incident?",
    options: [
      "Who can authorise isolation, how critical services are assessed and how access is recovered.",
      "Which chat channel name to use.",
      "That isolation can never be used.",
    ],
    correct: "a",
    guidance: "Account isolation is a business decision with operational consequences and needs pre-agreed authority.",
    consequence:
      "During an incident, named people can isolate the account and restore required access without inventing the process under pressure.",
  }),
  reviewed({
    id: "aws-lr-c01",
    roleGroup: "leaders-risk",
    difficulty: "Intermediate",
    topicTags: ["cloud-security", "business-continuity"],
    technologyTags: ["aws"],
    contextTags: ["internal-applications", "saas"],
    frameworks: ["DORA", "NIST GV.SC"],
    title: "Critical services share one org, IdP and region",
    situation:
      "Several critical services use the same AWS organisation, identity provider and region.",
    question: "What should leadership ask for?",
    options: [
      "Shared-failure analysis, recovery options, tested assumptions and accepted residual risk.",
      "Separate invoices only.",
      "A statement that AWS is large.",
    ],
    correct: "a",
    guidance: "Shared identity, organisation and region can disable otherwise separate workloads at the same time.",
    consequence:
      "Leaders know how one IdP or region failure would hit those services and what residual risk they are accepting.",
  }),
  reviewed({
    id: "aws-lr-c02",
    roleGroup: "leaders-risk",
    difficulty: "Intermediate",
    topicTags: ["cloud-security", "business-continuity"],
    technologyTags: ["aws"],
    contextTags: ["third-party-providers", "internal-applications"],
    frameworks: ["DORA Ch. V"],
    title: "Exit plan names another cloud without mapped paths",
    situation:
      "An exit plan says workloads can move to another cloud but does not cover data volumes, managed-service replacements, IAM, network dependencies or time.",
    question: "Is it credible?",
    options: [
      "Not yet; it needs executable paths, responsibilities, constraints and proportionate testing.",
      "Yes, naming another provider is enough.",
      "Yes, because data can always be copied instantly.",
    ],
    correct: "a",
    guidance: "Exit capability depends on architecture, data, contracts, people and time, not on a destination name.",
    consequence:
      "Work starts on a mapped, tested option instead of assuming a cutover during a crisis.",
  }),
  reviewed({
    id: "aws-lr-c03",
    roleGroup: "leaders-risk",
    difficulty: "Intermediate",
    topicTags: ["cloud-security", "business-continuity"],
    technologyTags: ["aws"],
    contextTags: ["internal-applications"],
    frameworks: ["NIST GV"],
    title: "Independent accounts without organisation guardrails",
    situation:
      "Business units create independent AWS accounts with inconsistent logging and no organisation guardrails.",
    question: "What is the gap?",
    options: [
      "No common control baseline, ownership and evidence across the cloud estate.",
      "Too many account names.",
      "Account aliases are not distinctive enough.",
    ],
    correct: "a",
    guidance: "Autonomy without a landing-zone baseline leaves logging, identity and evidence inconsistent when an incident spans units.",
    consequence:
      "New accounts join a shared baseline with owners and logging, instead of a private design each time.",
  }),
  reviewed({
    id: "aws-lr-c04",
    roleGroup: "leaders-risk",
    difficulty: "Intermediate",
    topicTags: ["cloud-security", "business-continuity"],
    technologyTags: ["aws"],
    contextTags: ["internal-applications"],
    frameworks: ["NIST GV", "CIS 6"],
    title: "Legacy workload needs a long-lived access key",
    situation: "A legacy AWS workload requires a long-lived access key for six months.",
    question: "What makes that defensible?",
    options: [
      "Record the constraint, reduce permissions, protect and monitor the key, assign migration ownership and set a review deadline.",
      "Ignore it because the system is old.",
      "Publish the key so everyone knows it exists.",
    ],
    correct: "a",
    guidance: "Standing credentials are exceptions that need compensating controls and an owner, not permanence by default.",
    consequence:
      "The key is narrowed, watched and scheduled for removal, instead of remaining undocumented or shared.",
  }),
  reviewed({
    id: "aws-lr-c05",
    roleGroup: "leaders-risk",
    difficulty: "Intermediate",
    topicTags: ["cloud-security", "business-continuity"],
    technologyTags: ["aws"],
    contextTags: ["internal-applications", "third-party-providers"],
    frameworks: ["NIST SP 800-61r3", "DORA"],
    title: "AWS outage on a critical financial service",
    situation:
      "An AWS outage affects a critical financial service, and the root cause and duration are still unclear.",
    question: "What should leadership do?",
    options: [
      "Activate classification and staged reporting using known facts while technical teams investigate.",
      "Wait for the final provider report before escalating.",
      "Publicly blame the provider immediately.",
    ],
    correct: "a",
    guidance: "Impact classification and internal reporting cannot wait for a complete vendor root-cause document.",
    consequence:
      "Stakeholders receive what is known, services are classified, and technical investigation continues without a premature public narrative.",
  }),
  reviewed({
    id: "aws-lr-c06",
    roleGroup: "leaders-risk",
    difficulty: "Intermediate",
    topicTags: ["cloud-security", "business-continuity"],
    technologyTags: ["aws"],
    contextTags: ["internal-applications", "third-party-providers"],
    frameworks: ["NIST GV", "DORA"],
    title: "What to map for a critical AWS-hosted service",
    situation: "Leadership asks what must be mapped for a critical AWS-hosted service.",
    question: "What should the map include?",
    options: [
      "Accounts, regions, identities, data stores, managed services, network paths, suppliers, recovery objectives and owners.",
      "Only the EC2 instance count.",
      "Only the master contract.",
    ],
    correct: "a",
    guidance: "Resilience and incident decisions need the real dependency graph, not a server count or a contract cover sheet.",
    consequence:
      "The service has named owners and a usable map of accounts, data and suppliers when an incident or outage starts.",
  }),
  reviewed({
    id: "aws-lr-c07",
    roleGroup: "leaders-risk",
    difficulty: "Intermediate",
    topicTags: ["cloud-security", "business-continuity"],
    technologyTags: ["aws"],
    contextTags: ["internal-applications"],
    frameworks: ["NIST GV", "ISO 27001"],
    title: "S3 Block Public Access claimed without evidence",
    situation:
      "A team says S3 Block Public Access is enabled but cannot show the effective organisation, account and bucket settings.",
    question: "What is missing?",
    options: [
      "Verifiable evidence of the control's scope and operation.",
      "A new policy title.",
      "A different cloud provider.",
    ],
    correct: "a",
    guidance: "A control statement is not evidence; effective settings at each layer have to be shown.",
    consequence:
      "The claim is replaced with recorded org, account and bucket settings, instead of a renamed policy or a platform change.",
  }),
  reviewed({
    id: "aws-lr-c08",
    roleGroup: "leaders-risk",
    difficulty: "Intermediate",
    topicTags: ["cloud-security", "business-continuity"],
    technologyTags: ["aws"],
    contextTags: ["internal-applications"],
    frameworks: ["NIST RC", "DORA Ch. IV"],
    title: "Multi-region design doubles operating cost",
    situation: "A multi-region design would reduce outage risk but doubles operating costs.",
    question: "What should decide the investment?",
    options: [
      "Business impact, recovery objectives, threat scenarios, alternatives and residual risk.",
      "The cheapest option alone.",
      "The architect's personal preference.",
    ],
    correct: "a",
    guidance: "Resilience spend should be tied to impact and recovery objectives, not to price or preference alone.",
    consequence:
      "The extra cost is accepted or declined against impact and tested alternatives, with residual risk recorded.",
  }),
];
