import { reviewed } from "@/lib/training/reviewed/define";
import type { ReviewedQuestion } from "@/lib/training/reviewed/types";

export const AZURE_QUESTIONS: readonly ReviewedQuestion[] = [
  reviewed({
    id: "az-dd-b01",
    roleGroup: "developers-devops",
    difficulty: "Beginner",
    topicTags: ["cloud-security"],
    technologyTags: ["azure"],
    contextTags: ["internal-applications"],
    frameworks: ["CIS 6"],
    title: "App Service reading one Storage container",
    situation: "An App Service needs to read one Storage container.",
    question: "Which authentication is preferable?",
    options: [
      "Managed Identity with scoped RBAC.",
      "A storage account key in source code.",
      "A developer's personal token.",
    ],
    correct: "a",
    guidance: "Workload identity removes reusable credentials and supports least privilege.",
    consequence:
      "The app uses a managed identity limited to that container, with no account key in source control.",
  }),
  reviewed({
    id: "az-dd-b02",
    roleGroup: "developers-devops",
    difficulty: "Beginner",
    topicTags: ["cloud-security", "secure-development"],
    technologyTags: ["azure"],
    contextTags: ["internal-applications"],
    frameworks: ["CIS 6"],
    title: "API secret from Key Vault",
    situation: "A service needs an API secret.",
    question: "Where should it obtain it?",
    options: [
      "Azure Key Vault through its managed identity.",
      "A public configuration file.",
      "A Teams message copied into the deployment.",
    ],
    correct: "a",
    guidance: "Central secret storage supports controlled access, rotation and audit.",
    consequence:
      "The secret is retrieved at runtime through the service identity instead of sitting in chat or a public file.",
  }),
  reviewed({
    id: "az-dd-b03",
    roleGroup: "developers-devops",
    difficulty: "Beginner",
    topicTags: ["cloud-security", "secure-development"],
    technologyTags: ["azure", "cicd"],
    contextTags: ["internal-applications"],
    frameworks: ["CIS 3"],
    title: "Terraform enables anonymous blob access",
    situation: "Terraform enables anonymous blob access for an internal dataset.",
    question: "What should the pipeline do?",
    options: [
      "Fail policy validation unless an approved exception exists.",
      "Deploy and review next quarter.",
      "Hide the storage account name.",
    ],
    correct: "a",
    guidance: "Preventive policy should stop unintended public access before deployment.",
    consequence:
      "The change never reaches production unless an approved exception is recorded.",
  }),
  reviewed({
    id: "az-dd-b04",
    roleGroup: "developers-devops",
    difficulty: "Beginner",
    topicTags: ["cloud-security", "supply-chain"],
    technologyTags: ["azure"],
    contextTags: ["internal-applications"],
    frameworks: ["NIST SSDF"],
    title: "AKS deploy by mutable tag",
    situation: "AKS is configured to deploy an image by mutable tag.",
    question: "What improves integrity?",
    options: [
      "Deploy the approved image digest.",
      "Use latest everywhere.",
      "Let developers overwrite the production tag.",
    ],
    correct: "a",
    guidance: "An immutable digest binds deployment to the artefact that was tested.",
    consequence:
      "AKS runs the tested digest, even if someone later retags latest.",
  }),
  reviewed({
    id: "az-dd-c01",
    roleGroup: "developers-devops",
    difficulty: "Intermediate",
    topicTags: ["cloud-security", "secure-development"],
    technologyTags: ["azure", "github", "cicd"],
    contextTags: ["saas"],
    frameworks: ["CIS 6", "NIST SSDF"],
    title: "GitHub Actions client secret for Azure",
    situation: "A GitHub Actions workflow uses a client secret for Azure.",
    question: "What is the stronger pattern?",
    options: [
      "Workload identity federation with a scoped service principal or managed identity.",
      "A longer-lived secret.",
      "The subscription owner's password.",
    ],
    correct: "a",
    guidance: "Federation provides short-lived tokens without storing an Azure credential in GitHub.",
    consequence:
      "GitHub assumes a scoped identity for the job, so no long-lived Azure secret sits in the repository.",
  }),
  reviewed({
    id: "az-dd-c02",
    roleGroup: "developers-devops",
    difficulty: "Intermediate",
    topicTags: ["cloud-security"],
    technologyTags: ["azure"],
    contextTags: ["internal-applications"],
    frameworks: ["CIS 6"],
    title: "One app can read every Key Vault secret",
    situation: "One application can read every secret in a shared Key Vault.",
    question: "What is the risk?",
    options: [
      "Compromise exposes unrelated services; separate or scope access to actual need.",
      "The vault becomes slower.",
      "Encryption stops working.",
    ],
    correct: "a",
    guidance: "Secret storage still requires least-privileged data-plane access.",
    consequence:
      "Each app only reads the secrets it needs, so one compromise does not empty the shared vault.",
  }),
  reviewed({
    id: "az-dd-c03",
    roleGroup: "developers-devops",
    difficulty: "Intermediate",
    topicTags: ["cloud-security"],
    technologyTags: ["azure"],
    contextTags: ["internal-applications"],
    frameworks: ["CIS 4", "CIS 6"],
    title: "Public network access to fix Key Vault connectivity",
    situation: "A developer proposes enabling public network access to fix Key Vault connectivity.",
    question: "What should happen?",
    options: [
      "Diagnose DNS, identity and private networking before changing exposure.",
      "Enable public access permanently.",
      "Put secrets in the image.",
    ],
    correct: "a",
    guidance: "Solve the connectivity fault without discarding the intended security boundary.",
    consequence:
      "The private endpoint keeps working after DNS or identity is fixed, without opening the vault to the internet.",
  }),
  reviewed({
    id: "az-dd-c04",
    roleGroup: "developers-devops",
    difficulty: "Intermediate",
    topicTags: ["cloud-security", "supply-chain"],
    technologyTags: ["azure", "cicd"],
    contextTags: ["internal-applications"],
    frameworks: ["NIST SSDF"],
    title: "Bicep template from a laptop",
    situation: "Production receives a Bicep template from a developer laptop instead of the reviewed pipeline.",
    question: "What is missing?",
    options: [
      "A controlled, repeatable deployment of the reviewed commit/artefact.",
      "A longer resource-group name.",
      "More subscription owners.",
    ],
    correct: "a",
    guidance: "Review has little value if a different artefact reaches production.",
    consequence:
      "The next change is deployed from the pipeline commit that passed review, not from a local copy.",
  }),
  reviewed({
    id: "az-it-b01",
    roleGroup: "it-security",
    difficulty: "Beginner",
    topicTags: ["cloud-security"],
    technologyTags: ["azure"],
    contextTags: ["internal-applications"],
    frameworks: ["CIS 6"],
    title: "Engineer who only restarts VMs in one group",
    situation: "A support engineer only restarts VMs in one resource group.",
    question: "Which access is appropriate?",
    options: [
      "A scoped role for that task and resource group.",
      "Subscription Owner.",
      "Global Administrator.",
    ],
    correct: "a",
    guidance: "Match role, action and scope to operational responsibility.",
    consequence:
      "The engineer can restart those VMs without owning the subscription or the directory.",
  }),
  reviewed({
    id: "az-it-b02",
    roleGroup: "it-security",
    difficulty: "Beginner",
    topicTags: ["cloud-security", "ransomware"],
    technologyTags: ["azure"],
    contextTags: ["internal-applications"],
    frameworks: ["CIS 8"],
    title: "What the Azure Activity Log shows",
    situation: "Responders are choosing which Azure log to pull first.",
    question: "What does the Azure Activity Log primarily show?",
    options: [
      "Subscription-level control-plane events.",
      "Every application database query.",
      "Full network packets.",
    ],
    correct: "a",
    guidance: "Combine control-plane evidence with resource, identity and application logs.",
    consequence:
      "The team uses Activity Log for control-plane actions and still collects the other telemetry the incident needs.",
  }),
  reviewed({
    id: "az-it-b03",
    roleGroup: "it-security",
    difficulty: "Beginner",
    topicTags: ["ransomware", "cloud-security"],
    technologyTags: ["azure"],
    contextTags: ["internal-applications"],
    frameworks: ["CIS 10"],
    title: "Defender for Cloud suspicious VM process",
    situation: "A VM shows suspicious process activity.",
    question: "What should responders do?",
    options: [
      "Validate, isolate through the playbook and preserve relevant evidence.",
      "Disable Defender for Cloud.",
      "Delete the VM immediately in every case.",
    ],
    correct: "a",
    guidance: "Containment should reduce risk without unnecessarily destroying evidence.",
    consequence:
      "The VM is isolated according to the playbook, and evidence remains for scoping.",
  }),
  reviewed({
    id: "az-it-b04",
    roleGroup: "it-security",
    difficulty: "Beginner",
    topicTags: ["cloud-security"],
    technologyTags: ["azure"],
    contextTags: ["internal-applications"],
    frameworks: ["CIS 4"],
    title: "What Azure Policy can enforce",
    situation: "The platform team wants a consistent configuration baseline.",
    question: "What can Azure Policy help enforce?",
    options: [
      "Required configuration such as allowed regions, encryption or diagnostic settings.",
      "User password resets.",
      "Database recovery by itself.",
    ],
    correct: "a",
    guidance: "Policy evaluates and can restrict resource configuration at scale.",
    consequence:
      "New resources are checked against the baseline instead of relying on memory after they are built.",
  }),
  reviewed({
    id: "az-it-c01",
    roleGroup: "it-security",
    difficulty: "Intermediate",
    topicTags: ["cloud-security"],
    technologyTags: ["azure"],
    contextTags: ["internal-applications"],
    frameworks: ["CIS 5", "CIS 6"],
    title: "Privileged Identity Management for Azure roles",
    situation: "High-impact Azure roles are currently standing assignments.",
    question: "Why use PIM for high-impact Azure roles?",
    options: [
      "To make privileged access time-bound, approved and auditable.",
      "To grant permanent Owner access.",
      "To avoid MFA.",
    ],
    correct: "a",
    guidance: "Just-in-time privilege reduces standing administrative exposure.",
    consequence:
      "Owner-level access is requested, approved and expires, instead of remaining attached all year.",
  }),
  reviewed({
    id: "az-it-c02",
    roleGroup: "it-security",
    difficulty: "Intermediate",
    topicTags: ["cloud-security", "ransomware"],
    technologyTags: ["azure"],
    contextTags: ["internal-applications"],
    frameworks: ["NIST SP 800-61r3", "CIS 6"],
    title: "Application credential used from an unknown source",
    situation: "An application credential is used from an unknown source.",
    question: "What should containment include?",
    options: [
      "Revoke credentials, restrict the principal, preserve sign-in/activity evidence and scope reachable resources.",
      "Rename the application only.",
      "Wait for visible damage.",
    ],
    correct: "a",
    guidance: "Effective permissions define the potential blast radius.",
    consequence:
      "The principal is stopped and scoped from evidence, so a rename does not leave the credential usable.",
  }),
  reviewed({
    id: "az-it-c03",
    roleGroup: "it-security",
    difficulty: "Intermediate",
    topicTags: ["cloud-security", "ransomware"],
    technologyTags: ["azure"],
    contextTags: ["internal-applications"],
    frameworks: ["CIS 8"],
    title: "Local logs without central retention",
    situation: "Critical resources have local logs but no central retention.",
    question: "What is the resilience gap?",
    options: [
      "A compromised resource may remove evidence; send required logs to protected central storage/SIEM.",
      "Logs make services less secure.",
      "Local logs always survive deletion.",
    ],
    correct: "a",
    guidance: "Separate log custody supports detection and investigation.",
    consequence:
      "Required logs land in protected central storage even if the resource is later wiped.",
  }),
  reviewed({
    id: "az-it-c04",
    roleGroup: "it-security",
    difficulty: "Intermediate",
    topicTags: ["cloud-security", "business-continuity"],
    technologyTags: ["azure"],
    contextTags: ["internal-applications"],
    frameworks: ["CIS 11"],
    title: "Soft-delete and purge protection for Key Vault",
    situation: "A critical vault can be deleted without recovery controls.",
    question: "Why enable appropriate soft-delete and purge-protection controls for critical vaults?",
    options: [
      "To reduce destructive loss of keys and secrets.",
      "To make every secret public.",
      "To replace backups and recovery planning.",
    ],
    correct: "a",
    guidance: "Recovery safeguards protect against accidental or malicious deletion.",
    consequence:
      "A deleted vault can still be recovered within policy, instead of losing keys immediately.",
  }),
  reviewed({
    id: "az-lr-b01",
    roleGroup: "leaders-risk",
    difficulty: "Beginner",
    topicTags: ["cloud-security", "business-continuity"],
    technologyTags: ["azure"],
    contextTags: ["internal-applications"],
    frameworks: ["NIST GV"],
    title: "Accountable owners for Azure subscriptions",
    situation: "Several Azure subscriptions have no named owner.",
    question: "Why assign accountable owners to Azure subscriptions?",
    options: [
      "To own risk, access, cost, recovery and exceptions.",
      "To choose icon colours.",
      "To delegate all accountability to Microsoft.",
    ],
    correct: "a",
    guidance: "Cloud governance requires clear business and technical ownership.",
    consequence:
      "Each subscription has someone who can accept risk, approve access and own recovery.",
  }),
  reviewed({
    id: "az-lr-b02",
    roleGroup: "leaders-risk",
    difficulty: "Beginner",
    topicTags: ["cloud-security", "business-continuity"],
    technologyTags: ["azure"],
    contextTags: ["saas", "third-party-providers"],
    frameworks: ["NIST GV"],
    title: "Does Azure transfer all security responsibility",
    situation: "A business owner says Azure runs the infrastructure so Microsoft owns all security.",
    question: "Does using Azure transfer all security responsibility to Microsoft?",
    options: [
      "No, responsibilities vary by service and the customer retains identity, data and configuration duties.",
      "Yes, for every workload.",
      "Yes, if a contract exists.",
    ],
    correct: "a",
    guidance: "Managed infrastructure changes tasks but not organisational accountability.",
    consequence:
      "The organisation still owns identity, data and configuration even when Azure operates the platform.",
  }),
  reviewed({
    id: "az-lr-b03",
    roleGroup: "leaders-risk",
    difficulty: "Beginner",
    topicTags: ["business-continuity", "cloud-security"],
    technologyTags: ["azure"],
    contextTags: ["internal-applications"],
    frameworks: ["NIST RC", "CIS 11"],
    title: "Azure Backup jobs succeed without restore tests",
    situation: "Azure Backup reports successful jobs, but no application restore has been tested.",
    question: "What is proven?",
    options: [
      "Backups exist, not that the full service can meet recovery objectives.",
      "Complete resilience.",
      "Instant cross-cloud exit.",
    ],
    correct: "a",
    guidance: "Recovery must include dependencies, access, data integrity and operations.",
    consequence:
      "Leadership treats backup jobs as evidence of copies, and still requires a restore test of the service.",
  }),
  reviewed({
    id: "az-lr-b04",
    roleGroup: "leaders-risk",
    difficulty: "Beginner",
    topicTags: ["cloud-security", "business-continuity"],
    technologyTags: ["azure"],
    contextTags: ["internal-applications"],
    frameworks: ["NIST GV", "ISO 27001"],
    title: "Critical workload cannot meet Azure Policy baseline",
    situation: "A critical workload cannot meet the standard Azure Policy baseline.",
    question: "What should happen?",
    options: [
      "Record owner, reason, risk, compensating controls and expiry/review.",
      "Disable the policy for all subscriptions.",
      "Ignore the non-compliance result.",
    ],
    correct: "a",
    guidance: "Exceptions are time-bound risk decisions, not permanent bypasses.",
    consequence:
      "The exception has an owner, compensating controls and a review date, without switching policy off everywhere.",
  }),
  reviewed({
    id: "az-lr-c01",
    roleGroup: "leaders-risk",
    difficulty: "Intermediate",
    topicTags: ["cloud-security", "business-continuity"],
    technologyTags: ["azure"],
    contextTags: ["internal-applications"],
    frameworks: ["NIST GV"],
    title: "Teams deploy into unrelated subscriptions",
    situation:
      "Teams deploy directly into unrelated subscriptions with different identity and logging designs.",
    question: "What is missing?",
    options: [
      "A governed landing-zone baseline and operating model.",
      "More resource names.",
      "One shared administrator account.",
    ],
    correct: "a",
    guidance: "Consistent guardrails enable autonomy without losing control evidence.",
    consequence:
      "New work lands in a baseline with shared identity and logging, instead of a private subscription design each time.",
  }),
  reviewed({
    id: "az-lr-c02",
    roleGroup: "leaders-risk",
    difficulty: "Intermediate",
    topicTags: ["cloud-security", "business-continuity"],
    technologyTags: ["azure", "microsoft-365"],
    contextTags: ["saas"],
    frameworks: ["DORA", "NIST GV.SC"],
    title: "Critical Azure services on one Entra tenant",
    situation:
      "Critical Azure services depend on one Entra tenant and privileged-access process.",
    question: "What should leadership assess?",
    options: [
      "Shared failure scenarios, emergency access, recovery and residual risk.",
      "Only licence count.",
      "Only region availability.",
    ],
    correct: "a",
    guidance: "Identity is a cross-cutting dependency that can disable otherwise resilient workloads.",
    consequence:
      "Leaders know how an identity failure would hit Azure workloads and how emergency access would work.",
  }),
  reviewed({
    id: "az-lr-c03",
    roleGroup: "leaders-risk",
    difficulty: "Intermediate",
    topicTags: ["business-continuity", "cloud-security"],
    technologyTags: ["azure"],
    contextTags: ["third-party-providers", "saas"],
    frameworks: ["DORA Ch. V"],
    title: "Azure exit plan without mapped services",
    situation:
      "An exit document says “move to another cloud” without mapping managed services, data paths, skills or timelines.",
    question: "Is it sufficient?",
    options: [
      "No, it needs executable options and proportionate tests.",
      "Yes, the target can be chosen during the crisis.",
      "Yes, every Azure service has an identical replacement.",
    ],
    correct: "a",
    guidance: "Exit capability depends on architecture, data, contracts, people and time.",
    consequence:
      "Work starts on a mapped, tested option instead of choosing a destination during an incident.",
  }),
  reviewed({
    id: "az-lr-c04",
    roleGroup: "leaders-risk",
    difficulty: "Intermediate",
    topicTags: ["business-continuity", "cloud-security"],
    technologyTags: ["azure"],
    contextTags: ["internal-applications"],
    frameworks: ["NIST RC", "DORA Ch. IV"],
    title: "Zone-redundant design costs more",
    situation: "Zone-redundant design costs more than the current single-zone workload.",
    question: "What should decide the investment?",
    options: [
      "Business impact, recovery objectives, failure scenarios and accepted residual risk.",
      "Lowest cost alone.",
      "Vendor popularity.",
    ],
    correct: "a",
    guidance: "Technical resilience choices should be tied to business risk.",
    consequence:
      "The extra cost is accepted or declined against impact and recovery objectives, not against price alone.",
  }),
];
