import { reviewed } from "@/lib/training/reviewed/define";
import type { ReviewedQuestion } from "@/lib/training/reviewed/types";

export const CICD_QUESTIONS: readonly ReviewedQuestion[] = [
  reviewed({
    id: "cicd-dd-b01",
    roleGroup: "developers-devops",
    difficulty: "Beginner",
    topicTags: ["secure-development", "supply-chain"],
    technologyTags: ["cicd"],
    contextTags: ["internal-applications"],
    frameworks: ["CIS 6"],
    title: "Deployment credential in a build log",
    situation: "A deployment credential appears in a build log.",
    question: "What should happen?",
    options: [
      "Revoke it, restrict logging and assess access.",
      "Hide only the log line.",
      "Keep using it until release day.",
    ],
    correct: "a",
    guidance: "Pipeline logs may expose credentials to a broad audience.",
    consequence:
      "The credential is revoked, logs are restricted, and anyone who already saw the line is treated as in-scope.",
  }),
  reviewed({
    id: "cicd-dd-b02",
    roleGroup: "developers-devops",
    difficulty: "Beginner",
    topicTags: ["secure-development"],
    technologyTags: ["cicd"],
    contextTags: ["internal-applications"],
    frameworks: ["NIST SSDF"],
    title: "Critical security test fails before release",
    situation: "A critical security test fails before release.",
    question: "What should the pipeline do?",
    options: [
      "Stop the release unless an authorised documented exception exists.",
      "Mark the job green manually.",
      "Disable the test permanently.",
    ],
    correct: "a",
    guidance: "A gate only protects production when failure has a controlled consequence.",
    consequence:
      "The release stays blocked unless an owned exception is recorded, instead of a green job or a deleted test.",
  }),
  reviewed({
    id: "cicd-dd-b03",
    roleGroup: "developers-devops",
    difficulty: "Beginner",
    topicTags: ["supply-chain", "secure-development"],
    technologyTags: ["cicd"],
    contextTags: ["internal-applications"],
    frameworks: ["NIST SSDF"],
    title: "Build from a lockfile",
    situation: "The team is choosing how production builds resolve dependencies.",
    question: "Why build from a lockfile and a controlled environment?",
    options: [
      "To reduce unreviewed dependency drift.",
      "To eliminate testing.",
      "To make every vulnerability impossible.",
    ],
    correct: "a",
    guidance: "Reproducibility supports verification but does not replace scanning and review.",
    consequence:
      "The release uses the locked versions that were reviewed, without claiming the build cannot be vulnerable.",
  }),
  reviewed({
    id: "cicd-dd-b04",
    roleGroup: "developers-devops",
    difficulty: "Beginner",
    topicTags: ["secure-development", "supply-chain"],
    technologyTags: ["cicd"],
    contextTags: ["internal-applications"],
    frameworks: ["NIST SSDF", "CIS 6"],
    title: "Who approves a high-risk production deployment",
    situation: "A high-risk production deployment is ready.",
    question: "Who should approve it?",
    options: [
      "An authorised person independent of the unreviewed change where required.",
      "Any anonymous user.",
      "The pipeline itself without policy.",
    ],
    correct: "a",
    guidance: "Approval should reflect risk and separation of duties.",
    consequence:
      "A named approver who did not author the unreviewed change records the decision before production moves.",
  }),
  reviewed({
    id: "cicd-dd-c01",
    roleGroup: "developers-devops",
    difficulty: "Intermediate",
    topicTags: ["supply-chain", "secure-development"],
    technologyTags: ["cicd"],
    contextTags: ["internal-applications"],
    frameworks: ["NIST SSDF", "NIST SP 800-204"],
    title: "Tests pass but deployment rebuilds source",
    situation: "Tests pass, but deployment rebuilds source separately.",
    question: "What is the weakness?",
    options: [
      "Production may receive a different artefact than the one tested.",
      "Tests become faster.",
      "Rebuilding at deploy time always matches the test build.",
    ],
    correct: "a",
    guidance: "Promote the verified immutable artefact rather than rebuilding it.",
    consequence:
      "The next release deploys the tested artefact digest, so a later rebuild cannot substitute different contents.",
  }),
  reviewed({
    id: "cicd-dd-c02",
    roleGroup: "developers-devops",
    difficulty: "Intermediate",
    topicTags: ["supply-chain", "secure-development"],
    technologyTags: ["cicd"],
    contextTags: ["third-party-providers", "internal-applications"],
    frameworks: ["NIST SSDF"],
    title: "Third-party build plugin changes without review",
    situation: "A third-party build plugin changes behaviour without review.",
    question: "What control helps?",
    options: [
      "Pin, verify provenance, review updates and restrict plugin permissions.",
      "Always use latest.",
      "Give the plugin production administrator access.",
    ],
    correct: "a",
    guidance: "Pipeline components are part of the software supply chain.",
    consequence:
      "The plugin runs a pinned, reviewed version with limited permissions instead of latest-with-admin rights.",
  }),
  reviewed({
    id: "cicd-dd-c03",
    roleGroup: "developers-devops",
    difficulty: "Intermediate",
    topicTags: ["supply-chain", "secure-development"],
    technologyTags: ["cicd"],
    contextTags: ["internal-applications"],
    frameworks: ["NIST SP 800-204", "CIS 6"],
    title: "Privileged deploy jobs reuse untrusted test runners",
    situation: "Privileged deployment jobs reuse runners that execute untrusted tests.",
    question: "What is the risk?",
    options: [
      "State or code can cross the trust boundary.",
      "Reuse always erases state.",
      "Deployment secrets cannot be read by processes.",
    ],
    correct: "a",
    guidance: "Separate or rebuild execution environments according to trust level.",
    consequence:
      "Untrusted tests no longer share a runner that still holds deployment secrets or leftover files.",
  }),
  reviewed({
    id: "cicd-dd-c04",
    roleGroup: "developers-devops",
    difficulty: "Intermediate",
    topicTags: ["supply-chain", "secure-development"],
    technologyTags: ["cicd"],
    contextTags: ["internal-applications"],
    frameworks: ["NIST SSDF"],
    title: "Rollback after a security-relevant failure",
    situation: "A release causes security-relevant failures.",
    question: "What should rollback use?",
    options: [
      "A known-good signed or verified artefact and a tested procedure.",
      "An arbitrary local build.",
      "The newest unreviewed commit.",
    ],
    correct: "a",
    guidance: "Recovery should not introduce a second supply-chain uncertainty.",
    consequence:
      "Production returns to a tested, verified artefact through a practised procedure, not a laptop build.",
  }),
  reviewed({
    id: "cicd-it-b01",
    roleGroup: "it-security",
    difficulty: "Beginner",
    topicTags: ["supply-chain"],
    technologyTags: ["cicd"],
    contextTags: ["internal-applications"],
    frameworks: ["CIS 6"],
    title: "Deployment account is admin on every environment",
    situation: "A deployment service account has administrator access to every environment.",
    question: "What should change?",
    options: [
      "Separate scoped identities by environment and function.",
      "Share the account more widely.",
      "Add a second administrator key.",
    ],
    correct: "a",
    guidance: "Pipeline compromise impact follows effective permissions.",
    consequence:
      "Each environment has its own scoped identity, so one stolen job cannot administer every stage.",
  }),
  reviewed({
    id: "cicd-it-b02",
    roleGroup: "it-security",
    difficulty: "Beginner",
    topicTags: ["supply-chain", "secure-development"],
    technologyTags: ["cicd"],
    contextTags: ["internal-applications"],
    frameworks: ["CIS 8", "NIST SSDF"],
    title: "Evidence a controlled deployment should retain",
    situation: "The platform team is defining what a production deployment must record.",
    question: "Which evidence should a controlled deployment retain?",
    options: [
      "Commit, approvals, checks, artefact identity and deploying principal.",
      "Only deployment time.",
      "Only developer name.",
    ],
    correct: "a",
    guidance: "Traceability connects production to reviewed source and decisions.",
    consequence:
      "Responders can say which commit, checks, artefact and identity produced the live release.",
  }),
  reviewed({
    id: "cicd-it-b03",
    roleGroup: "it-security",
    difficulty: "Beginner",
    topicTags: ["supply-chain"],
    technologyTags: ["cicd"],
    contextTags: ["internal-applications"],
    frameworks: ["NIST SSDF"],
    title: "Passed vulnerability scan as proof of safety",
    situation: "A release artefact passed a vulnerability scan.",
    question: "Does that prove the artefact is safe?",
    options: [
      "No, it is one evidence source with scope and limitations.",
      "Yes, every defect is detected.",
      "Yes, runtime monitoring is unnecessary.",
    ],
    correct: "a",
    guidance: "Assurance combines multiple preventive and detective controls.",
    consequence:
      "The scan is kept as one check, and runtime monitoring and other gates still run.",
  }),
  reviewed({
    id: "cicd-it-b04",
    roleGroup: "it-security",
    difficulty: "Beginner",
    topicTags: ["supply-chain", "ransomware"],
    technologyTags: ["cicd"],
    contextTags: ["internal-applications"],
    frameworks: ["NIST SSDF", "CIS 6"],
    title: "Urgent fix bypasses the normal pipeline",
    situation: "An urgent fix bypasses the normal pipeline.",
    question: "What should still occur?",
    options: [
      "Authorisation, traceability, minimum checks and post-change review.",
      "No record because it was urgent.",
      "Shared administrator credentials.",
    ],
    correct: "a",
    guidance: "Emergency flow should be faster, not uncontrolled.",
    consequence:
      "The change is authorised, recorded and reviewed afterwards, without a shared admin password.",
  }),
  reviewed({
    id: "cicd-it-c01",
    roleGroup: "it-security",
    difficulty: "Intermediate",
    topicTags: ["ransomware", "supply-chain"],
    technologyTags: ["cicd"],
    contextTags: ["internal-applications"],
    frameworks: ["NIST SP 800-61r3"],
    title: "Malicious script ran with release permissions",
    situation: "A malicious script ran with release permissions.",
    question: "What should responders scope?",
    options: [
      "Credentials, artefacts, repositories, runners and environments reachable from the job.",
      "Only the final console message.",
      "Only the developer laptop.",
    ],
    correct: "a",
    guidance: "CI/CD connects multiple trust zones and can amplify compromise.",
    consequence:
      "Tokens, artefacts, runners and reachable environments are treated as in-scope, not only the last log line.",
  }),
  reviewed({
    id: "cicd-it-c02",
    roleGroup: "it-security",
    difficulty: "Intermediate",
    topicTags: ["supply-chain", "ransomware"],
    technologyTags: ["cicd"],
    contextTags: ["internal-applications"],
    frameworks: ["NIST SP 800-61r3", "NIST SSDF"],
    title: "Code-signing key may be exposed",
    situation: "A code-signing key may be exposed.",
    question: "What is required?",
    options: [
      "Contain the key, identify signed artefacts, revoke or replace trust as applicable and preserve evidence.",
      "Change the pipeline display name.",
      "Re-sign only the newest release.",
    ],
    correct: "a",
    guidance: "Trust decisions may need remediation across every affected artefact.",
    consequence:
      "The key is contained, affected artefacts are listed, and trust is replaced where needed instead of renaming the pipeline.",
  }),
  reviewed({
    id: "cicd-it-c03",
    roleGroup: "it-security",
    difficulty: "Intermediate",
    topicTags: ["supply-chain"],
    technologyTags: ["cicd"],
    contextTags: ["internal-applications"],
    frameworks: ["CIS 5", "CIS 8"],
    title: "Group can disable pipeline policy checks without alerting",
    situation: "A group can disable pipeline policy checks without alerting.",
    question: "What is the gap?",
    options: [
      "Privileged bypass lacks restriction, monitoring and review.",
      "Policies are unnecessary.",
      "Developers should remember every rule.",
    ],
    correct: "a",
    guidance: "Guardrail administration is itself a high-impact control.",
    consequence:
      "Bypass is limited, logged and reviewed, so policy cannot be switched off quietly.",
  }),
  reviewed({
    id: "cicd-it-c04",
    roleGroup: "it-security",
    difficulty: "Intermediate",
    topicTags: ["supply-chain"],
    technologyTags: ["cicd"],
    contextTags: ["internal-applications"],
    frameworks: ["NIST SSDF"],
    title: "SBOM with no verifiable link to the build",
    situation: "A release has an SBOM but no verifiable link to its build.",
    question: "What remains unknown?",
    options: [
      "Whether the listed components and artefact came from the claimed controlled process.",
      "Whether the file has a name.",
      "Whether an SBOM replaces signing.",
    ],
    correct: "a",
    guidance: "Inventory and provenance answer different assurance questions.",
    consequence:
      "The team treats the SBOM as an inventory claim until it is bound to the signed, controlled build.",
  }),
  reviewed({
    id: "cicd-lr-b01",
    roleGroup: "leaders-risk",
    difficulty: "Beginner",
    topicTags: ["business-continuity", "supply-chain"],
    technologyTags: ["cicd"],
    contextTags: ["internal-applications"],
    frameworks: ["NIST GV"],
    title: "Who owns risk in a critical deployment pipeline",
    situation: "A business-critical service deploys through an automated pipeline.",
    question: "Who owns the risk?",
    options: [
      "Accountable service leadership supported by engineering and security.",
      "The CI vendor alone.",
      "Nobody because deployment is automated.",
    ],
    correct: "a",
    guidance: "Automation does not remove accountability.",
    consequence:
      "A named service owner remains accountable, with engineering and security supporting the controls.",
  }),
  reviewed({
    id: "cicd-lr-b02",
    roleGroup: "leaders-risk",
    difficulty: "Beginner",
    topicTags: ["business-continuity", "supply-chain"],
    technologyTags: ["cicd"],
    contextTags: ["internal-applications"],
    frameworks: ["NIST RC"],
    title: "Why define recovery and rollback for deployments",
    situation: "A product team has no documented rollback for production deployments.",
    question: "Why define recovery and rollback expectations?",
    options: [
      "To limit business impact when change fails.",
      "To eliminate testing.",
      "To increase administrator accounts.",
    ],
    correct: "a",
    guidance: "Delivery resilience links technical release controls to service continuity.",
    consequence:
      "Failed changes can be reversed against a stated objective instead of leaving the service in an unknown state.",
  }),
  reviewed({
    id: "cicd-lr-b03",
    roleGroup: "leaders-risk",
    difficulty: "Beginner",
    topicTags: ["supply-chain", "business-continuity"],
    technologyTags: ["cicd"],
    contextTags: ["third-party-providers"],
    frameworks: ["NIST GV.SC", "DORA"],
    title: "Pipeline depends on an external plugin",
    situation: "A pipeline depends on an external plugin.",
    question: "What should the owner know?",
    options: [
      "Criticality, permissions, update process, incident route and alternatives.",
      "Only download count.",
      "Only the plugin marketing page.",
    ],
    correct: "a",
    guidance: "Build dependencies require supplier and continuity governance.",
    consequence:
      "The owner can say what the plugin can do, how it is updated, who to call and how to replace it.",
  }),
  reviewed({
    id: "cicd-lr-b04",
    roleGroup: "leaders-risk",
    difficulty: "Beginner",
    topicTags: ["supply-chain", "business-continuity"],
    technologyTags: ["cicd"],
    contextTags: ["internal-applications"],
    frameworks: ["NIST GV"],
    title: "Pipeline called secure without approvals or test results",
    situation:
      "A team says the pipeline is secure but cannot show approvals or test results.",
    question: "What is missing?",
    options: [
      "Verifiable evidence that controls operated.",
      "A longer policy.",
      "More deployments.",
    ],
    correct: "a",
    guidance: "Assurance requires evidence, not confidence alone.",
    consequence:
      "Leadership asks for recorded approvals and test results before treating the pipeline as controlled.",
  }),
  reviewed({
    id: "cicd-lr-c01",
    roleGroup: "leaders-risk",
    difficulty: "Intermediate",
    topicTags: ["business-continuity", "supply-chain"],
    technologyTags: ["cicd"],
    contextTags: ["internal-applications", "third-party-providers"],
    frameworks: ["DORA", "NIST GV"],
    title: "Every critical service deploys through one pipeline",
    situation: "Every critical service deploys through one central pipeline.",
    question: "What should be assessed?",
    options: [
      "Shared compromise and outage impact, isolation and recovery options.",
      "Only pipeline speed.",
      "Only number of developers.",
    ],
    correct: "a",
    guidance: "Centralisation improves control but can create a common failure path.",
    consequence:
      "Leaders know how one pipeline outage or compromise would hit every critical service and how isolation would work.",
  }),
  reviewed({
    id: "cicd-lr-c02",
    roleGroup: "leaders-risk",
    difficulty: "Intermediate",
    topicTags: ["supply-chain", "business-continuity"],
    technologyTags: ["cicd"],
    contextTags: ["internal-applications"],
    frameworks: ["NIST GV", "ISO 27001"],
    title: "Signing requirement cannot be met before launch",
    situation: "A product cannot meet the signing requirement before launch.",
    question: "What is a defensible decision?",
    options: [
      "Explicit owner, impact assessment, compensating controls and a short remediation deadline.",
      "Silent bypass.",
      "Remove signing policy globally.",
    ],
    correct: "a",
    guidance: "Exceptions must be visible, bounded and owned.",
    consequence:
      "Launch proceeds only with a named owner, compensating controls and a date to meet signing, not a silent or global bypass.",
  }),
  reviewed({
    id: "cicd-lr-c03",
    roleGroup: "leaders-risk",
    difficulty: "Intermediate",
    topicTags: ["supply-chain", "business-continuity"],
    technologyTags: ["cicd"],
    contextTags: ["internal-applications"],
    frameworks: ["NIST GV"],
    title: "Secure delivery metric",
    situation: "Leadership wants a measure of secure delivery.",
    question: "Which measure better supports leadership?",
    options: [
      "Critical releases with verified provenance and time to remediate failed controls.",
      "Total pipeline jobs.",
      "Number of pipeline configuration files.",
    ],
    correct: "a",
    guidance: "Metrics should describe meaningful control coverage and outcomes.",
    consequence:
      "Leaders track whether critical releases were proven and how fast failed gates are fixed, not job volume.",
  }),
  reviewed({
    id: "cicd-lr-c04",
    roleGroup: "leaders-risk",
    difficulty: "Intermediate",
    topicTags: ["business-continuity", "supply-chain"],
    technologyTags: ["cicd"],
    contextTags: ["saas", "third-party-providers"],
    frameworks: ["DORA Ch. IV", "NIST RC"],
    title: "No one can release when the CI provider is unavailable",
    situation:
      "A tabletop shows no one can release a critical patch when the CI provider is unavailable.",
    question: "What should happen?",
    options: [
      "Assign an alternative process, test it and track remediation.",
      "Mark the exercise complete.",
      "Assume the provider will recover first.",
    ],
    correct: "a",
    guidance: "Exercises create value when gaps become owned improvements.",
    consequence:
      "A named owner has a tested alternative release path, instead of closing the exercise on discussion alone.",
  }),
];
