import { reviewed } from "@/lib/training/reviewed/define";
import type { ReviewedQuestion } from "@/lib/training/reviewed/types";

export const DEVELOPERS_DEVOPS_QUESTIONS: readonly ReviewedQuestion[] = [
  reviewed({
    id: "dd-b01",
    roleGroup: "developers-devops",
    difficulty: "Beginner",
    topicTags: ["supply-chain", "secure-development"],
    technologyTags: ["github"],
    contextTags: ["saas"],
    frameworks: ["NIST SSDF"],
    title: "API key committed to GitHub",
    situation: "A developer accidentally commits an API key.",
    question: "What should happen?",
    options: [
      "Delete the visible line only.",
      "Revoke the key, remove it from history where appropriate and investigate use.",
      "Rename the repository.",
    ],
    correct: "b",
    guidance:
      "A committed secret must be treated as exposed even if the latest commit no longer shows it.",
    consequence:
      "The key is revoked and investigated, so a copy taken from git history cannot keep working.",
  }),
  reviewed({
    id: "dd-b02",
    roleGroup: "developers-devops",
    difficulty: "Beginner",
    topicTags: ["supply-chain", "secure-development"],
    technologyTags: ["cicd"],
    contextTags: ["internal-applications"],
    frameworks: ["NIST SSDF", "CIS 16"],
    title: "Production build and the lockfile",
    situation: "A production pipeline can install dependencies with or without package-lock.json.",
    question: "Why should a production build use the lockfile?",
    options: [
      "It makes the README shorter.",
      "It supports repeatable dependency versions.",
      "It replaces vulnerability scanning.",
    ],
    correct: "b",
    guidance: "A lockfile improves reproducibility but still needs review and scanning.",
    consequence:
      "The release uses the versions that were reviewed, instead of whatever the registry returns today.",
  }),
  reviewed({
    id: "dd-b03",
    roleGroup: "developers-devops",
    difficulty: "Beginner",
    topicTags: ["secure-development", "supply-chain"],
    technologyTags: ["github"],
    contextTags: ["saas"],
    frameworks: ["NIST SSDF"],
    title: "Security-sensitive pull request",
    situation: "A security-sensitive change is ready.",
    question: "What is the best next step?",
    options: [
      "Merge directly to main.",
      "Require review and automated checks before merge.",
      "Email the code as a ZIP.",
    ],
    correct: "b",
    guidance: "Protected review and checks reduce errors and unauthorised changes.",
    consequence:
      "The change reaches main only after review and checks, with a record of who approved it.",
  }),
  reviewed({
    id: "dd-b04",
    roleGroup: "developers-devops",
    difficulty: "Beginner",
    topicTags: ["cloud-security", "secure-development"],
    technologyTags: ["azure"],
    contextTags: ["internal-applications"],
    frameworks: ["CIS 6"],
    title: "Where to store an application secret",
    situation: "An application needs a secret at runtime.",
    question: "Where should an application secret be stored?",
    options: [
      "In source code.",
      "In Azure Key Vault or the approved secret manager.",
      "In a Teams message.",
    ],
    correct: "b",
    guidance: "Secret managers provide controlled access, rotation and auditability.",
    consequence:
      "The secret is retrieved through a controlled identity instead of sitting in git or chat history.",
  }),
  reviewed({
    id: "dd-b05",
    roleGroup: "developers-devops",
    difficulty: "Beginner",
    topicTags: ["secure-development", "supply-chain", "cloud-security"],
    technologyTags: ["github", "cicd"],
    contextTags: ["saas"],
    frameworks: ["NIST SSDF"],
    title: "Workflow prints environment variables",
    situation: "A workflow prints environment variables during debugging.",
    question: "What is the risk?",
    options: [
      "Secrets may enter build logs.",
      "The pipeline becomes faster.",
      "TypeScript stops compiling.",
    ],
    correct: "a",
    guidance: "CI logs are data stores and may expose tokens or credentials.",
    consequence:
      "The team stops printing secrets and treats any leaked token as exposed.",
  }),
  reviewed({
    id: "dd-b06",
    roleGroup: "developers-devops",
    difficulty: "Beginner",
    topicTags: ["supply-chain", "secure-development"],
    technologyTags: ["github"],
    contextTags: ["saas", "third-party-providers"],
    frameworks: ["CIS 7"],
    title: "Production dependency alert",
    situation: "A dependency alert affects a package used in production.",
    question: "What should the team do?",
    options: [
      "Assess exposure, test the fix and remediate by risk.",
      "Close every alert automatically.",
      "Delete package.json.",
    ],
    correct: "a",
    guidance: "Vulnerability management needs triage, ownership and verified remediation.",
    consequence:
      "The reachable issue is fixed and tested, instead of being closed for noise or left to drift.",
  }),
  reviewed({
    id: "dd-b07",
    roleGroup: "developers-devops",
    difficulty: "Beginner",
    topicTags: ["cloud-security", "secure-development"],
    contextTags: ["internal-applications"],
    frameworks: ["CIS 4"],
    title: "Safer container choice",
    situation: "A team is packaging a web service.",
    question: "Which container choice is safer?",
    options: [
      "Run as root with every capability.",
      "Use a minimal image and non-root user.",
      "Put the database password in the image.",
    ],
    correct: "b",
    guidance: "Minimal privilege and smaller images reduce attack surface.",
    consequence:
      "A break-out from the process has fewer privileges and a smaller image to hide in.",
  }),
  reviewed({
    id: "dd-b08",
    roleGroup: "developers-devops",
    difficulty: "Beginner",
    topicTags: ["cloud-security"],
    contextTags: ["internal-applications"],
    frameworks: ["CIS 4", "CIS 6"],
    title: "Service account for one namespace",
    situation: "A web service only needs to read one namespace.",
    question: "What access should it receive?",
    options: [
      "Cluster-admin.",
      "A namespace-scoped service account with required permissions.",
      "A developer's personal kubeconfig.",
    ],
    correct: "b",
    guidance: "Workloads need their own least-privileged identities.",
    consequence:
      "A stolen workload identity can only read that namespace, not administer the cluster.",
  }),
  reviewed({
    id: "dd-b09",
    roleGroup: "developers-devops",
    difficulty: "Beginner",
    topicTags: ["secure-development"],
    contextTags: ["internal-applications"],
    frameworks: ["NIST SSDF"],
    title: "Does TypeScript prevent malicious input?",
    situation: "A TypeScript API receives data from the browser.",
    question: "Does TypeScript prevent malicious input?",
    options: [
      "Yes, types validate all runtime data.",
      "No, runtime input still needs validation.",
      "Only in development.",
    ],
    correct: "b",
    guidance: "Static types do not validate untrusted values arriving at runtime.",
    consequence:
      "The API still validates incoming values, so a crafted payload cannot skip the type-checker.",
  }),
  reviewed({
    id: "dd-b10",
    roleGroup: "developers-devops",
    difficulty: "Beginner",
    topicTags: ["secure-development"],
    contextTags: ["internal-applications"],
    frameworks: ["OWASP Input Validation"],
    title: "Zod at an API boundary",
    situation: "The team is choosing how to check request bodies.",
    question: "What is Zod useful for at an API boundary?",
    options: [
      "Validating the shape and constraints of runtime input.",
      "Encrypting the database.",
      "Replacing authentication.",
    ],
    correct: "a",
    guidance:
      "Schema validation is one layer; authentication, authorisation and safe processing remain necessary.",
    consequence:
      "Malformed requests fail at the boundary instead of reaching business logic as unexpected objects.",
  }),
  reviewed({
    id: "dd-b11",
    roleGroup: "developers-devops",
    difficulty: "Beginner",
    topicTags: ["secure-development"],
    contextTags: ["internal-applications"],
    frameworks: ["NIST SSDF"],
    title: "Security behaviour that needs a unit test",
    situation: "The team is deciding which behaviours deserve automated tests.",
    question: "Which security behaviour should have a unit test?",
    options: [
      "An unauthorised user is denied access to another customer's record.",
      "The primary button uses the brand colour.",
      "The README includes a project title.",
    ],
    correct: "a",
    guidance: "Tests should verify important security invariants, including denied paths.",
    consequence:
      "A later change that opens another customer's record fails in CI instead of in production.",
  }),
  reviewed({
    id: "dd-b12",
    roleGroup: "developers-devops",
    difficulty: "Beginner",
    topicTags: ["cloud-security", "secure-development"],
    contextTags: ["internal-applications"],
    frameworks: ["CIS 3", "CIS 6"],
    title: "Where to configure a Worker secret",
    situation: "A Cloudflare Worker needs a server-side secret.",
    question: "Where should a Worker secret be configured?",
    options: [
      "As a Wrangler secret or approved platform secret.",
      "In a public client-side variable.",
      "In Git history.",
    ],
    correct: "a",
    guidance: "Server-side secrets must not be exposed in public bundles or source control.",
    consequence:
      "The secret stays on the platform and is not shipped to every browser or git clone.",
  }),
  reviewed({
    id: "dd-c01",
    roleGroup: "developers-devops",
    difficulty: "Intermediate",
    topicTags: ["supply-chain", "secure-development"],
    technologyTags: ["github", "cicd"],
    contextTags: ["saas"],
    frameworks: ["NIST SSDF"],
    title: "Fork pull request and deployment secrets",
    situation: "A pull request from a fork can trigger a workflow with deployment secrets.",
    question: "What is the safest design?",
    options: [
      "Expose secrets to every PR.",
      "Separate untrusted build checks from privileged deployment workflows.",
      "Ask contributors not to misuse them.",
    ],
    correct: "b",
    guidance: "Untrusted code must not execute in a context containing production credentials.",
    consequence:
      "Fork builds can still be checked, but production credentials only appear in a separate, trusted workflow.",
  }),
  reviewed({
    id: "dd-c02",
    roleGroup: "developers-devops",
    difficulty: "Intermediate",
    topicTags: ["supply-chain"],
    contextTags: ["third-party-providers"],
    frameworks: ["NIST SSDF", "OWASP Supply Chain"],
    title: "Unexpected major version from a new maintainer",
    situation: "A popular package publishes an unexpected major version from a new maintainer.",
    question: "What should the team do?",
    options: [
      "Auto-update production immediately.",
      "Hold, verify provenance and changes, scan and test before adoption.",
      "Ignore all future updates.",
    ],
    correct: "b",
    guidance:
      "A change in provenance is a supply-chain signal requiring verification, not permanent paralysis.",
    consequence:
      "Production stays on a known version until the new release is reviewed, scanned and tested.",
  }),
  reviewed({
    id: "dd-c03",
    roleGroup: "developers-devops",
    difficulty: "Intermediate",
    topicTags: ["secure-development"],
    contextTags: ["internal-applications", "saas"],
    frameworks: ["OWASP Access Control"],
    title: "Hidden admin button as authorisation",
    situation: "A page hides an admin button for normal users.",
    question: "Is that sufficient authorisation?",
    options: [
      "Yes.",
      "No, the server action or API must enforce authorisation.",
      "Yes, when written in TypeScript.",
    ],
    correct: "b",
    guidance: "Client-side visibility is not a security boundary.",
    consequence:
      "Calling the API directly still fails for unauthorised users, even if they guess the hidden control.",
  }),
  reviewed({
    id: "dd-c04",
    roleGroup: "developers-devops",
    difficulty: "Intermediate",
    topicTags: ["secure-development", "cloud-security"],
    contextTags: ["saas"],
    frameworks: ["CIS 3"],
    title: "Secret in a NEXT_PUBLIC_ variable",
    situation: "A secret is placed in a NEXT_PUBLIC_ environment variable.",
    question: "What happens if a secret is exposed through a NEXT_PUBLIC_ variable?",
    options: [
      "It can be included in the browser bundle.",
      "It remains server-only.",
      "Zod encrypts it.",
    ],
    correct: "a",
    guidance: "Public-prefixed variables must contain only values safe for every browser user.",
    consequence:
      "The team treats the value as public, rotates it if it was a secret, and keeps future secrets server-side.",
  }),
  reviewed({
    id: "dd-c05",
    roleGroup: "developers-devops",
    difficulty: "Intermediate",
    topicTags: ["cloud-security"],
    technologyTags: ["azure"],
    contextTags: ["internal-applications"],
    frameworks: ["CIS 6"],
    title: "Blob Storage authentication",
    situation: "An application reads Blob Storage.",
    question: "Which authentication is preferable?",
    options: [
      "A long-lived account key in configuration.",
      "Managed identity with scoped RBAC.",
      "A developer's personal token.",
    ],
    correct: "b",
    guidance: "Workload identity removes reusable secrets and supports least privilege.",
    consequence:
      "The app gets a short-lived identity limited to that storage, with no reusable key sitting in configuration.",
  }),
  reviewed({
    id: "dd-c06",
    roleGroup: "developers-devops",
    difficulty: "Intermediate",
    topicTags: ["supply-chain", "cloud-security", "secure-development"],
    technologyTags: ["cicd"],
    contextTags: ["internal-applications"],
    frameworks: ["NIST SSDF"],
    title: "Image digest differs from the approved build",
    situation:
      "A container image passed tests, but its digest differs from the approved build.",
    question: "What should deployment do?",
    options: [
      "Deploy because the tag matches.",
      "Reject it and verify the signed artefact/digest.",
      "Retag it manually.",
    ],
    correct: "b",
    guidance: "Immutable identity and provenance matter more than a mutable tag.",
    consequence:
      "Production only receives the digest that was tested and signed, not whatever later reused the same tag.",
  }),
  reviewed({
    id: "dd-c07",
    roleGroup: "developers-devops",
    difficulty: "Intermediate",
    topicTags: ["supply-chain"],
    technologyTags: ["cicd"],
    contextTags: ["internal-applications"],
    frameworks: ["NIST SSDF"],
    title: "What an SBOM primarily provides",
    situation: "A release pipeline now produces an SBOM.",
    question: "What does an SBOM primarily provide?",
    options: [
      "An inventory of software components for risk and incident analysis.",
      "Proof that software has no vulnerabilities.",
      "Automatic legal approval.",
    ],
    correct: "a",
    guidance: "An SBOM improves visibility; it does not guarantee safety.",
    consequence:
      "The team can see what shipped and use that inventory during triage, without treating it as a clean bill of health.",
  }),
  reviewed({
    id: "dd-c08",
    roleGroup: "developers-devops",
    difficulty: "Intermediate",
    topicTags: ["ai-security", "secure-development"],
    technologyTags: ["ai-assistants", "github"],
    contextTags: ["saas"],
    frameworks: ["OWASP GenAI"],
    title: "Coding agent that opens pull requests",
    situation: "A coding agent can read repositories and open pull requests.",
    question: "What boundary is most important?",
    options: [
      "Give it production credentials for complete context.",
      "Limit repositories and tools, use short-lived tokens and require review for writes.",
      "Trust the system prompt alone.",
    ],
    correct: "b",
    guidance: "Agent authority must be constrained outside the model.",
    consequence:
      "The agent can draft changes in a limited repo, but production writes still need a short-lived token and human review.",
  }),
  reviewed({
    id: "dd-c09",
    roleGroup: "developers-devops",
    difficulty: "Intermediate",
    topicTags: ["ai-security", "secure-development"],
    technologyTags: ["ai-assistants"],
    contextTags: ["internal-applications"],
    frameworks: ["OWASP"],
    title: "LLM Markdown rendered as HTML",
    situation: "An LLM generates Markdown that is later rendered as HTML.",
    question: "What should the application do?",
    options: [
      "Trust it because the model created it.",
      "Treat output as untrusted and sanitise for the destination.",
      "Add a longer system prompt.",
    ],
    correct: "b",
    guidance: "Model output can carry unsafe content and must be handled like other untrusted input.",
    consequence:
      "Rendered HTML cannot execute unexpected markup, even if the model includes it.",
  }),
  reviewed({
    id: "dd-c10",
    roleGroup: "developers-devops",
    difficulty: "Intermediate",
    topicTags: ["cloud-security", "secure-development"],
    technologyTags: ["cicd", "azure"],
    contextTags: ["internal-applications"],
    frameworks: ["CIS 4"],
    title: "Terraform opens storage to the internet",
    situation: "A Terraform change opens a storage account to the internet.",
    question: "What should prevent release?",
    options: [
      "A policy check and review in the pipeline.",
      "A comment saying “temporary”.",
      "Manual discovery months later.",
    ],
    correct: "a",
    guidance: "Security policy should be tested before infrastructure changes reach production.",
    consequence:
      "The pipeline blocks the public opening unless an approved exception exists, before the account is exposed.",
  }),
  reviewed({
    id: "dd-c11",
    roleGroup: "developers-devops",
    difficulty: "Intermediate",
    topicTags: ["supply-chain", "secure-development", "cloud-security"],
    technologyTags: ["cicd"],
    contextTags: ["saas"],
    frameworks: ["NIST SSDF"],
    title: "Production deploy from a laptop",
    situation:
      "A production deploy is made directly from a developer laptop with an unreviewed local build.",
    question: "What is the main weakness?",
    options: [
      "Local deploys are acceptable if the developer tested on their machine.",
      "Provenance and repeatability are lost.",
      "The platform cannot run a reviewed pipeline artefact.",
    ],
    correct: "b",
    guidance: "Production should receive a reviewed, reproducible artefact from a controlled pipeline.",
    consequence:
      "The next release goes through the pipeline so reviewers can say exactly which artefact reached production.",
  }),
  reviewed({
    id: "dd-c12",
    roleGroup: "developers-devops",
    difficulty: "Intermediate",
    topicTags: ["supply-chain", "ransomware"],
    technologyTags: ["cicd"],
    contextTags: ["internal-applications", "third-party-providers"],
    frameworks: ["NIST SP 800-61r3"],
    title: "Malicious npm package in CI",
    situation: "A malicious npm package ran in CI.",
    question: "What should the team preserve and rotate?",
    options: [
      "Relevant logs, artefacts, tokens and affected runner state.",
      "Only the package name.",
      "Only screenshots from Slack.",
    ],
    correct: "a",
    guidance:
      "Supply-chain incidents may expose every credential available to the runner and require evidence-led scoping.",
    consequence:
      "Tokens are rotated, runner state is treated as untrusted, and logs remain available to scope the blast radius.",
  }),
];
