import { reviewed } from "@/lib/training/reviewed/define";
import type { ReviewedQuestion } from "@/lib/training/reviewed/types";

export const FINANCE_HR_QUESTIONS: readonly ReviewedQuestion[] = [
  reviewed({
    id: "fh-b01",
    roleGroup: "finance-hr",
    difficulty: "Beginner",
    topicTags: ["phishing"],
    technologyTags: ["microsoft-365"],
    contextTags: ["saas", "third-party-providers"],
    frameworks: ["CIS 6"],
    title: "Supplier sends new bank details",
    situation: "A supplier emails new bank details one hour before payment.",
    question: "What should Finance do?",
    options: [
      "Change them immediately.",
      "Verify using the registered contact and approval process.",
      "Reply asking “is this correct?”.",
    ],
    correct: "b",
    guidance:
      "Payment-detail changes need independent verification outside the potentially compromised email chain.",
    consequence:
      "The registered contact confirms the change on a channel the attacker does not control before money moves.",
  }),
  reviewed({
    id: "fh-b02",
    roleGroup: "finance-hr",
    difficulty: "Beginner",
    topicTags: ["data-privacy"],
    contextTags: ["internal-applications"],
    frameworks: ["GDPR Art. 5"],
    title: "Payroll export for one department",
    situation: "HR exports all employee records to answer a question about one department.",
    question: "What is better?",
    options: [
      "Export only the fields and people required.",
      "Export everything and delete it later.",
      "Send the full file to Finance.",
    ],
    correct: "a",
    guidance: "Data minimisation means using only what the task requires.",
    consequence:
      "Fewer personal records leave the system, so a later mishandling cannot expose the whole workforce.",
  }),
  reviewed({
    id: "fh-b03",
    roleGroup: "finance-hr",
    difficulty: "Beginner",
    topicTags: ["data-privacy"],
    technologyTags: ["microsoft-365"],
    contextTags: ["saas"],
    frameworks: ["CIS 3"],
    title: "Where to store a salary spreadsheet",
    situation: "You need a place to keep a salary spreadsheet.",
    question: "Where should a salary spreadsheet be stored?",
    options: [
      "In an approved restricted SharePoint location.",
      "On a personal USB drive.",
      "In a public Teams channel.",
    ],
    correct: "a",
    guidance: "Sensitive HR data requires approved storage and limited access.",
    consequence:
      "Only authorised people can open the file, and the organisation can still audit access.",
  }),
  reviewed({
    id: "fh-b04",
    roleGroup: "finance-hr",
    difficulty: "Beginner",
    topicTags: ["phishing"],
    technologyTags: ["microsoft-365"],
    contextTags: ["saas"],
    frameworks: ["CIS 14"],
    title: "CEO gift-card request",
    situation: "The CEO asks by email for an urgent gift-card purchase.",
    question: "What should you do?",
    options: [
      "Follow the normal approval and verification process.",
      "Skip controls because the CEO asked.",
      "Buy the cards privately.",
    ],
    correct: "a",
    guidance: "Seniority and urgency are common social-engineering tools.",
    consequence:
      "The normal process either confirms a genuine request or stops a business-email-compromise payment.",
  }),
  reviewed({
    id: "fh-b05",
    roleGroup: "finance-hr",
    difficulty: "Beginner",
    topicTags: ["data-privacy"],
    technologyTags: ["microsoft-365"],
    contextTags: ["saas"],
    frameworks: ["GDPR Art. 5"],
    title: "Power BI export of employee details",
    situation: "A dashboard shows personal employee details.",
    question: "Before exporting it, what should you check?",
    options: [
      "Whether the dashboard already loaded for the viewer.",
      "Whether the recipient needs the underlying personal data.",
      "Whether the export file opens in Excel.",
    ],
    correct: "b",
    guidance:
      "Dashboard access does not automatically justify exporting or redistributing detailed data.",
    consequence:
      "The export only happens if the recipient has a real need, so extra copies of personal data are not created.",
  }),
  reviewed({
    id: "fh-b06",
    roleGroup: "finance-hr",
    difficulty: "Beginner",
    topicTags: ["data-privacy", "phishing"],
    technologyTags: ["microsoft-365"],
    contextTags: ["saas"],
    frameworks: ["CIS 14"],
    title: "Medical note requested in Teams",
    situation: "A manager requests an employee's medical note in Teams.",
    question: "What is the best response?",
    options: [
      "Post it in the team channel.",
      "Use the approved restricted HR process and verify the need.",
      "Send a screenshot.",
    ],
    correct: "b",
    guidance: "Special-category data needs strict handling and a clear purpose.",
    consequence:
      "Health information stays in the restricted HR process instead of a broad chat history.",
  }),
  reviewed({
    id: "fh-b07",
    roleGroup: "finance-hr",
    difficulty: "Beginner",
    topicTags: ["phishing"],
    contextTags: ["internal-applications"],
    frameworks: ["CIS 5", "CIS 6"],
    title: "Payroll administrator accounts",
    situation: "The payroll team is setting up how they sign in.",
    question: "Which account setup is appropriate for payroll administrators?",
    options: [
      "Shared account for the whole team.",
      "Individual accounts with MFA and role-based permissions.",
      "One password written in a locked drawer.",
    ],
    correct: "b",
    guidance: "Individual identities support least privilege and accountability.",
    consequence:
      "Each action can be attributed, and a stolen password does not open the entire payroll function.",
  }),
  reviewed({
    id: "fh-b08",
    roleGroup: "finance-hr",
    difficulty: "Beginner",
    topicTags: ["phishing"],
    contextTags: ["saas", "third-party-providers"],
    frameworks: ["NIST PR.AT"],
    title: "Unfamiliar e-signature domain",
    situation: "A signed contract arrives from an unfamiliar e-signature domain.",
    question: "What should you do?",
    options: [
      "Open it because it says signed.",
      "Verify the sender and service using a known route.",
      "Forward it to a personal account.",
    ],
    correct: "b",
    guidance: "E-signature branding can be copied in phishing messages.",
    consequence:
      "The known supplier route confirms the document before anyone opens a lookalike signing site.",
  }),
  reviewed({
    id: "fh-b09",
    roleGroup: "finance-hr",
    difficulty: "Beginner",
    topicTags: ["phishing", "data-privacy"],
    contextTags: ["internal-applications", "saas"],
    frameworks: ["CIS 5"],
    title: "Departing employee access",
    situation: "An employee is leaving the organisation today.",
    question: "When should a departing employee's access normally be removed?",
    options: [
      "According to the coordinated offboarding time.",
      "At the next annual review.",
      "Only if the employee asks.",
    ],
    correct: "a",
    guidance: "Timely access removal reduces misuse and orphaned access.",
    consequence:
      "Payroll, HR and IT remove access at the agreed time, so a former account cannot keep opening systems.",
  }),
  reviewed({
    id: "fh-b10",
    roleGroup: "finance-hr",
    difficulty: "Beginner",
    topicTags: ["data-privacy"],
    technologyTags: ["microsoft-365"],
    contextTags: ["saas"],
    frameworks: ["GDPR Art. 33"],
    title: "Employee data sent to the wrong recipient",
    situation: "HR sends employee data to the wrong recipient.",
    question: "What should happen first?",
    options: [
      "Hide the mistake.",
      "Report it through the internal breach process without delay.",
      "Wait 72 hours before telling anyone.",
    ],
    correct: "b",
    guidance:
      "The organisation needs early notice to assess risk; 72 hours is not a waiting period.",
    consequence:
      "Privacy and security can start containment and a documented risk assessment immediately.",
  }),
  reviewed({
    id: "fh-b11",
    roleGroup: "finance-hr",
    difficulty: "Beginner",
    topicTags: ["phishing"],
    contextTags: ["saas", "third-party-providers"],
    frameworks: ["CIS 10"],
    title: "Invoice asks for a new PDF reader",
    situation: "An invoice asks you to install a PDF reader from a link.",
    question: "What should you do?",
    options: [
      "Install it.",
      "Use approved software and verify the invoice separately.",
      "Disable endpoint protection.",
    ],
    correct: "b",
    guidance: "Documents should not dictate software installation.",
    consequence:
      "The invoice is checked with approved tools, and a hostile installer never reaches the finance workstation.",
  }),
  reviewed({
    id: "fh-b12",
    roleGroup: "finance-hr",
    difficulty: "Beginner",
    topicTags: ["data-privacy"],
    contextTags: ["internal-applications"],
    frameworks: ["GDPR Art. 5"],
    title: "Old unsuccessful applications",
    situation:
      "A recruitment folder contains old unsuccessful applications with no current purpose.",
    question: "What is the right response?",
    options: [
      "Keep them forever.",
      "Apply the approved retention and deletion rules.",
      "Move them to a hidden personal folder.",
    ],
    correct: "b",
    guidance: "Personal data should not be retained longer than necessary.",
    consequence:
      "Records that no longer have a purpose are deleted under the approved schedule instead of lingering in extra folders.",
  }),
  reviewed({
    id: "fh-c01",
    roleGroup: "finance-hr",
    difficulty: "Intermediate",
    topicTags: ["phishing", "business-continuity"],
    contextTags: ["internal-applications", "third-party-providers"],
    frameworks: ["CIS 6"],
    title: "ERP bank account changed by a compromised user",
    situation:
      "An approved invoice is genuine, but the bank account was changed in the ERP yesterday by a compromised user.",
    question: "What control helps most?",
    options: [
      "Dual approval and independent verification of master-data changes.",
      "A clearer invoice layout.",
      "Email confirmation from the same user.",
    ],
    correct: "a",
    guidance: "Fraud controls must cover master-data changes, not only invoice approval.",
    consequence:
      "A second person and an independent check catch the account change before payment leaves the organisation.",
  }),
  reviewed({
    id: "fh-c02",
    roleGroup: "finance-hr",
    difficulty: "Intermediate",
    topicTags: ["data-privacy"],
    technologyTags: ["microsoft-365"],
    contextTags: ["saas"],
    frameworks: ["CIS 6"],
    title: "Regional workforce metrics without extra salaries",
    situation:
      "HR leaders need regional workforce metrics, but not individual salaries outside their region.",
    question: "What is the best design?",
    options: [
      "One unrestricted report.",
      "Row-level security with tested role assignments.",
      "Export separate spreadsheets manually every week.",
    ],
    correct: "b",
    guidance: "Enforce access in the data product and test that roles see only authorised rows.",
    consequence:
      "Each leader sees only their authorised rows, and a later export cannot quietly include another region's salaries.",
  }),
  reviewed({
    id: "fh-c03",
    roleGroup: "finance-hr",
    difficulty: "Intermediate",
    topicTags: ["data-privacy"],
    technologyTags: ["microsoft-365"],
    contextTags: ["saas", "third-party-providers"],
    frameworks: ["GDPR Art. 32"],
    title: "Benefits provider needs employee data",
    situation: "A benefits provider needs a file containing employee data.",
    question: "What should happen?",
    options: [
      "Use an approved restricted transfer with the correct recipient and retention terms.",
      "Create an anonymous link.",
      "Send it to the first matching email address.",
    ],
    correct: "a",
    guidance: "Security measures should match the sensitivity and recipient relationship.",
    consequence:
      "The provider receives only what was agreed, for a limited time, through a channel the organisation can evidence.",
  }),
  reviewed({
    id: "fh-c04",
    roleGroup: "finance-hr",
    difficulty: "Intermediate",
    topicTags: ["business-continuity"],
    contextTags: ["third-party-providers"],
    frameworks: ["DORA Ch. V"],
    title: "Payroll provider cannot explain recovery",
    situation:
      "A payroll provider supports a critical process but cannot explain recovery arrangements.",
    question: "What should the organisation do?",
    options: [
      "Accept the marketing brochure.",
      "Assess the dependency, contractual commitments, recovery and exit options.",
      "Ignore it because payroll is outsourced.",
    ],
    correct: "b",
    guidance: "Outsourcing a service does not outsource accountability for ICT risk.",
    consequence:
      "Leadership has a documented view of recovery, contracts and exit options before the next payroll cycle depends on hope.",
  }),
  reviewed({
    id: "fh-c05",
    roleGroup: "finance-hr",
    difficulty: "Intermediate",
    topicTags: ["phishing", "ransomware"],
    technologyTags: ["microsoft-365"],
    contextTags: ["saas"],
    frameworks: ["NIST SP 800-61r3"],
    title: "Fraudulent payment and mailbox rules",
    situation: "Finance discovers one fraudulent payment and suspicious mailbox rules.",
    question: "What is the best first coordinated action?",
    options: [
      "Preserve evidence, contain the account and activate fraud/incident contacts.",
      "Delete the mailbox.",
      "Send a company-wide accusation.",
    ],
    correct: "a",
    guidance: "Containment, evidence and financial recovery actions should start together.",
    consequence:
      "The mailbox is contained without destroying evidence, and fraud contacts can start recovery while the incident is scoped.",
  }),
  reviewed({
    id: "fh-c06",
    roleGroup: "finance-hr",
    difficulty: "Intermediate",
    topicTags: ["data-privacy"],
    contextTags: ["internal-applications"],
    frameworks: ["CIS 3"],
    title: "Hidden columns of national identification numbers",
    situation: "A workbook uses hidden columns containing national identification numbers.",
    question: "Is hiding the columns sufficient?",
    options: [
      "Yes.",
      "No; remove unnecessary data and restrict the file.",
      "Yes, if the sheet is marked confidential in the filename.",
    ],
    correct: "b",
    guidance: "Hidden data remains in the file and can be exposed.",
    consequence:
      "Unnecessary identifiers are removed and the file is restricted, so a later share cannot reveal hidden columns.",
  }),
  reviewed({
    id: "fh-c07",
    roleGroup: "finance-hr",
    difficulty: "Intermediate",
    topicTags: ["ai-security", "data-privacy"],
    technologyTags: ["ai-assistants"],
    contextTags: ["saas", "third-party-providers"],
    frameworks: ["NIST AI RMF"],
    title: "AI tool to rank applicants",
    situation: "HR wants an AI tool to rank applicants automatically.",
    question: "What should happen before use?",
    options: [
      "Define owner, purpose, data, harm scenarios, testing and human review.",
      "Use it silently for speed.",
      "Let the vendor decide all criteria.",
    ],
    correct: "a",
    guidance: "High-impact AI decisions require governance, evaluation and a meaningful human path.",
    consequence:
      "Hiring decisions keep an accountable owner, tested limits and a human review path before the tool ranks people.",
  }),
  reviewed({
    id: "fh-c08",
    roleGroup: "finance-hr",
    difficulty: "Intermediate",
    topicTags: ["data-privacy"],
    technologyTags: ["microsoft-365"],
    contextTags: ["saas"],
    frameworks: ["CIS 3"],
    title: "DLP blocks a legitimate payroll transfer",
    situation: "DLP blocks a legitimate payroll transfer.",
    question: "What is the best response?",
    options: [
      "Disable DLP for everyone.",
      "Use the documented exception and review why the rule triggered.",
      "Rename the file to bypass it.",
    ],
    correct: "b",
    guidance: "A controlled exception preserves the protection while enabling valid work.",
    consequence:
      "Payroll still moves through an approved exception, and the rule can be tuned without switching DLP off.",
  }),
  reviewed({
    id: "fh-c09",
    roleGroup: "finance-hr",
    difficulty: "Intermediate",
    topicTags: ["data-privacy", "ransomware"],
    contextTags: ["internal-applications"],
    frameworks: ["GDPR Art. 33-34"],
    title: "Stolen encrypted HR laptop",
    situation: "An encrypted laptop containing HR data is stolen.",
    question: "What determines notification needs?",
    options: [
      "The laptop price.",
      "The assessed risk to people, considering whether encryption protected the data.",
      "Whether the employee is embarrassed.",
    ],
    correct: "b",
    guidance: "Breach decisions are risk-based and must be documented.",
    consequence:
      "The organisation records a risk-based decision instead of treating price or embarrassment as the test.",
  }),
  reviewed({
    id: "fh-c10",
    roleGroup: "finance-hr",
    difficulty: "Intermediate",
    topicTags: ["business-continuity"],
    contextTags: ["internal-applications"],
    frameworks: ["DORA Ch. III"],
    title: "Payment system outage with incomplete facts",
    situation:
      "A payment system outage may be a major ICT incident, but facts are incomplete.",
    question: "What should the team do?",
    options: [
      "Start classification and escalation with known facts, updating as evidence develops.",
      "Wait for certainty.",
      "Report every minor error publicly.",
    ],
    correct: "a",
    guidance:
      "Incident processes should work with incomplete information and support phased updates.",
    consequence:
      "Classification starts on what is known, and later updates can change the picture without waiting for a perfect root cause.",
  }),
  reviewed({
    id: "fh-c11",
    roleGroup: "finance-hr",
    difficulty: "Intermediate",
    topicTags: ["data-privacy"],
    contextTags: ["internal-applications"],
    frameworks: ["CIS 6"],
    title: "Payroll API with broad employee access",
    situation:
      "An integration account can read and change every employee record although it only updates tax codes.",
    question: "What is the better design?",
    options: [
      "Keep broad access for convenience.",
      "Restrict the identity to the required fields and actions.",
      "Share the account with HR.",
    ],
    correct: "b",
    guidance: "Least privilege reduces the blast radius of a compromised integration.",
    consequence:
      "A stolen integration identity can only touch tax codes, not the rest of the employee record.",
  }),
  reviewed({
    id: "fh-c12",
    roleGroup: "finance-hr",
    difficulty: "Intermediate",
    topicTags: ["business-continuity"],
    contextTags: ["internal-applications"],
    frameworks: ["DORA", "NIST RC"],
    title: "Payroll backups without a restore test",
    situation: "Payroll has backups but no recent restore test.",
    question: "What is the key risk?",
    options: [
      "The backup may not support recovery when needed.",
      "The backup file names may be hard to search.",
      "Storage costs are the only concern.",
    ],
    correct: "a",
    guidance: "Recovery capability must be tested, not inferred from the existence of backup files.",
    consequence:
      "A restore test either proves payroll can come back or exposes the gap before the next incident.",
  }),
];
