import { reviewed } from "@/lib/training/reviewed/define";
import type { ReviewedQuestion } from "@/lib/training/reviewed/types";

export const GENERAL_EMPLOYEE_QUESTIONS: readonly ReviewedQuestion[] = [
  reviewed({
    id: "ge-b01",
    roleGroup: "general-employees",
    difficulty: "Beginner",
    topicTags: ["phishing"],
    technologyTags: ["microsoft-365"],
    contextTags: ["saas"],
    frameworks: ["CIS 14", "NIST PR.AT"],
    title: "Unexpected Microsoft 365 password expiry",
    situation:
      "An email says your Microsoft 365 password expires in ten minutes and links to a sign-in page.",
    question: "What should you do?",
    options: [
      "Open Microsoft 365 from your normal bookmark and report the email.",
      "Use the link before time runs out.",
      "Forward it to colleagues for confirmation.",
    ],
    correct: "a",
    guidance:
      "Urgency and a login link are common phishing signals; use a known route and report the message.",
    consequence:
      "The known sign-in page keeps your password off the fake site, and the report lets security warn others.",
  }),
  reviewed({
    id: "ge-b02",
    roleGroup: "general-employees",
    difficulty: "Beginner",
    topicTags: ["phishing"],
    technologyTags: ["microsoft-365"],
    contextTags: ["saas"],
    frameworks: ["CIS 14"],
    title: "Unexpected Teams file request",
    situation:
      "A colleague sends an unexpected Teams message asking for a confidential file.",
    question: "What is the safest first step?",
    options: [
      "Send it because Teams is internal.",
      "Verify the request through a known channel or call the colleague.",
      "Upload it to a public link.",
    ],
    correct: "b",
    guidance:
      "A trusted platform does not guarantee that the account or request is genuine.",
    consequence:
      "A quick check on a known channel stops a hijacked account from collecting confidential files.",
  }),
  reviewed({
    id: "ge-b03",
    roleGroup: "general-employees",
    difficulty: "Beginner",
    topicTags: ["phishing"],
    technologyTags: ["microsoft-365"],
    contextTags: ["saas"],
    frameworks: ["CIS 6"],
    title: "Unexpected Authenticator prompt",
    situation: "You receive an MFA approval prompt you did not initiate.",
    question: "What should you do?",
    options: [
      "Approve it to stop the notifications.",
      "Ignore it and continue working.",
      "Deny it and report a possible account attack.",
    ],
    correct: "c",
    guidance: "An unexpected MFA prompt can mean someone already has the password.",
    consequence:
      "Denying the prompt blocks the sign-in and gives security a chance to reset the account before it is used.",
  }),
  reviewed({
    id: "ge-b04",
    roleGroup: "general-employees",
    difficulty: "Beginner",
    topicTags: ["data-privacy", "phishing"],
    technologyTags: ["microsoft-365"],
    contextTags: ["saas"],
    frameworks: ["GDPR Art. 5", "CIS 3"],
    title: "Sharing a customer document",
    situation: "You need to share a customer document with one colleague.",
    question: "What should you choose?",
    options: [
      "A OneDrive link limited to that colleague.",
      "Anyone-with-the-link access.",
      "Your personal email.",
    ],
    correct: "a",
    guidance: "Share with the smallest necessary audience and avoid personal channels.",
    consequence:
      "Only the named colleague can open the file, and the organisation can still see who received it.",
  }),
  reviewed({
    id: "ge-b05",
    roleGroup: "general-employees",
    difficulty: "Beginner",
    topicTags: ["data-privacy"],
    technologyTags: ["microsoft-365"],
    contextTags: ["saas"],
    frameworks: ["CIS 3"],
    title: "Department-wide employee folder",
    situation:
      "You notice that an entire department can open a folder containing employee data.",
    question: "What should you do?",
    options: [
      "Assume the owner intended it.",
      "Report the access issue to the folder owner or IT.",
      "Download a copy for safekeeping.",
    ],
    correct: "b",
    guidance: "Excess access should be corrected; do not create additional copies.",
    consequence:
      "The owner or IT can tighten permissions before more people copy or share the records.",
  }),
  reviewed({
    id: "ge-b06",
    roleGroup: "general-employees",
    difficulty: "Beginner",
    topicTags: ["ransomware", "phishing"],
    contextTags: ["internal-applications"],
    frameworks: ["CIS 1", "CIS 4"],
    title: "Stolen work laptop",
    situation: "Your work laptop is stolen from a train.",
    question: "What is the best immediate action?",
    options: [
      "Wait in case it is returned.",
      "Change only your email signature.",
      "Report it immediately so access and the device can be contained.",
    ],
    correct: "c",
    guidance:
      "Fast reporting lets the organisation revoke sessions, lock the device and assess data exposure.",
    consequence:
      "IT can lock the device, end sessions and start a data-exposure check while the laptop is still missing.",
  }),
  reviewed({
    id: "ge-b07",
    roleGroup: "general-employees",
    difficulty: "Beginner",
    topicTags: ["phishing", "ransomware"],
    contextTags: ["internal-applications"],
    frameworks: ["CIS 10"],
    title: "Unknown USB drive",
    situation: "You find an unknown USB drive in the office.",
    question: "What should you do?",
    options: [
      "Plug it in to identify the owner.",
      "Hand it to IT or security without connecting it.",
      "Test it on a colleague's computer.",
    ],
    correct: "b",
    guidance: "Unknown removable media may contain malicious code.",
    consequence:
      "IT can inspect the drive in a controlled way instead of letting it run on a work computer.",
  }),
  reviewed({
    id: "ge-b08",
    roleGroup: "general-employees",
    difficulty: "Beginner",
    topicTags: ["phishing"],
    contextTags: ["saas"],
    frameworks: ["CIS 9"],
    title: "Invoice browser extension",
    situation:
      "A familiar website suddenly asks you to install a browser extension to view an invoice.",
    question: "What should you do?",
    options: [
      "Install it because the site looks familiar.",
      "Use an administrator account.",
      "Stop and verify through the official service or IT.",
    ],
    correct: "c",
    guidance: "Compromised sites and fake pages often use extensions to gain access.",
    consequence:
      "Skipping the extension keeps the browser free of extra access, and IT can confirm whether the site is genuine.",
  }),
  reviewed({
    id: "ge-b09",
    roleGroup: "general-employees",
    difficulty: "Beginner",
    topicTags: ["phishing"],
    technologyTags: ["microsoft-365"],
    contextTags: ["saas"],
    frameworks: ["CIS 5"],
    title: "Strongest password practice",
    situation: "You are setting a password for a work service.",
    question: "Which password practice is strongest?",
    options: [
      "One long unique password stored in the approved password manager.",
      "The same complex password on every service.",
      "A short password changed every week.",
    ],
    correct: "a",
    guidance: "Unique credentials limit damage when one service is breached.",
    consequence:
      "A reused password cannot open every other account if one service is later compromised.",
  }),
  reviewed({
    id: "ge-b10",
    roleGroup: "general-employees",
    difficulty: "Beginner",
    topicTags: ["phishing"],
    technologyTags: ["microsoft-365"],
    contextTags: ["saas"],
    frameworks: ["CIS 10"],
    title: "Unexpected spreadsheet macros",
    situation: "An unexpected spreadsheet asks you to enable macros.",
    question: "What should you do?",
    options: [
      "Enable them to see the content.",
      "Do not enable them; verify and report the file.",
      "Rename the file before opening it.",
    ],
    correct: "b",
    guidance: "Macros can execute malicious code; renaming does not remove the risk.",
    consequence:
      "The file stays inert, and security can inspect it without giving it a chance to run.",
  }),
  reviewed({
    id: "ge-b11",
    roleGroup: "general-employees",
    difficulty: "Beginner",
    topicTags: ["phishing"],
    technologyTags: ["microsoft-365"],
    contextTags: ["saas"],
    frameworks: ["NIST PR.AT"],
    title: "QR code company benefit",
    situation:
      "A QR code on a poster offers an urgent company benefit and opens a Microsoft login.",
    question: "What should you do?",
    options: [
      "Sign in because the poster is inside the office.",
      "Check the benefit through the official HR portal.",
      "Scan it with a private phone instead.",
    ],
    correct: "b",
    guidance: "QR phishing hides the destination; use the known official channel.",
    consequence:
      "The official HR route confirms whether the benefit is real without sending credentials to an unknown page.",
  }),
  reviewed({
    id: "ge-b12",
    roleGroup: "general-employees",
    difficulty: "Beginner",
    topicTags: ["phishing"],
    contextTags: ["internal-applications"],
    frameworks: ["NIST RS.CO"],
    title: "Clicked a suspicious link",
    situation: "You clicked a suspicious link but did not enter a password.",
    question: "Should you report it?",
    options: [
      "Yes, because the click can still provide useful incident information.",
      "No, because no password was entered.",
      "Only if the computer stops working.",
    ],
    correct: "a",
    guidance: "Early reports help security correlate activity and contain problems sooner.",
    consequence:
      "Security can check whether the link was part of a wider campaign and watch the device for follow-up activity.",
  }),
  reviewed({
    id: "ge-c01",
    roleGroup: "general-employees",
    difficulty: "Intermediate",
    topicTags: ["phishing"],
    technologyTags: ["microsoft-365"],
    contextTags: ["saas"],
    frameworks: ["NIST DE.AE"],
    title: "MFA prompt approved by mistake",
    situation:
      "You approved an MFA prompt by mistake, but the account still works normally.",
    question: "What is the best next step?",
    options: [
      "Report it immediately and follow the account-compromise process.",
      "Change the desktop background.",
      "Wait for visible damage.",
    ],
    correct: "a",
    guidance:
      "A successful login may leave no visible symptom; sessions and credentials may need revocation.",
    consequence:
      "Security can revoke sessions and reset credentials before the extra sign-in is used for mail or files.",
  }),
  reviewed({
    id: "ge-c02",
    roleGroup: "general-employees",
    difficulty: "Intermediate",
    topicTags: ["data-privacy", "phishing"],
    technologyTags: ["microsoft-365"],
    contextTags: ["saas", "third-party-providers"],
    frameworks: ["CIS 6"],
    title: "Teams guest in a project chat",
    situation: "A project chat includes an external guest. You are about to share an architecture diagram.",
    question: "Before sharing an architecture diagram, what matters most?",
    options: [
      "Whether the guest has a profile picture.",
      "Whether the guest is authorised for that specific information.",
      "Whether the file is under 10 MB.",
    ],
    correct: "b",
    guidance: "Platform membership is not the same as a business need-to-know.",
    consequence:
      "The diagram stays with people who have a current business reason to see it, including after a guest's work ends.",
  }),
  reviewed({
    id: "ge-c03",
    roleGroup: "general-employees",
    difficulty: "Intermediate",
    topicTags: ["data-privacy"],
    technologyTags: ["microsoft-365"],
    contextTags: ["saas"],
    frameworks: ["GDPR Art. 5"],
    title: "OneDrive link sent to the wrong person",
    situation:
      "A restricted link was sent to the wrong external recipient but has not been opened.",
    question: "What should you do?",
    options: [
      "Remove access and report the disclosure promptly.",
      "Delete the email from your Sent folder only.",
      "Ask the recipient to ignore it and do nothing else.",
    ],
    correct: "a",
    guidance:
      "Revoke access first and let the organisation assess whether personal data was exposed.",
    consequence:
      "The link stops working, and privacy or security can judge whether further notification is required.",
  }),
  reviewed({
    id: "ge-c04",
    roleGroup: "general-employees",
    difficulty: "Intermediate",
    topicTags: ["phishing"],
    technologyTags: ["microsoft-365"],
    contextTags: ["saas", "third-party-providers"],
    frameworks: ["CIS 14"],
    title: "Supplier changes bank details in a real thread",
    situation:
      "A supplier replies inside a real email thread with new bank details.",
    question: "What should Finance do?",
    options: [
      "Trust the thread history.",
      "Verify the change using an independently known contact method.",
      "Ask for another email confirmation in the same thread.",
    ],
    correct: "b",
    guidance:
      "Compromised mailboxes can produce convincing replies inside genuine conversations.",
    consequence:
      "Payment details are confirmed on a channel the attacker does not control, so funds are not sent to a new account in error.",
  }),
  reviewed({
    id: "ge-c05",
    roleGroup: "general-employees",
    difficulty: "Intermediate",
    topicTags: ["phishing"],
    contextTags: ["internal-applications", "saas"],
    frameworks: ["NIST PR.PS"],
    title: "Work portal certificate warning",
    situation: "A work portal shows a certificate warning.",
    question: "What is the best response?",
    options: [
      "Continue if the logo looks correct.",
      "Switch to mobile data and continue.",
      "Stop and report the warning.",
    ],
    correct: "c",
    guidance:
      "A certificate warning may indicate interception or misconfiguration and should not be bypassed casually.",
    consequence:
      "IT can inspect the warning before anyone types credentials into a page that may not be the real portal.",
  }),
  reviewed({
    id: "ge-c06",
    roleGroup: "general-employees",
    difficulty: "Intermediate",
    topicTags: ["phishing"],
    technologyTags: ["microsoft-365"],
    contextTags: ["saas"],
    frameworks: ["CIS 6"],
    title: "Caller asks for an Authenticator number",
    situation:
      "A caller claiming to be IT asks you to read an Authenticator number aloud.",
    question: "What should you do?",
    options: [
      "Read it if they know your name.",
      "Refuse and contact IT through the official support channel.",
      "Approve first and ask questions later.",
    ],
    correct: "b",
    guidance:
      "MFA numbers are part of authentication and should not be shared with an unsolicited caller.",
    consequence:
      "The official channel confirms whether IT really needs help, without handing a live sign-in code to a stranger.",
  }),
  reviewed({
    id: "ge-c07",
    roleGroup: "general-employees",
    difficulty: "Intermediate",
    topicTags: ["data-privacy"],
    technologyTags: ["microsoft-365"],
    contextTags: ["saas"],
    frameworks: ["NIST RS.AN"],
    title: "Unexpected SharePoint edits",
    situation: "A shared document contains unexpected edits and deleted sections.",
    question: "What should you do first?",
    options: [
      "Preserve the version history and report the change.",
      "Overwrite it with a local copy immediately.",
      "Delete the whole library.",
    ],
    correct: "a",
    guidance: "Version history can be important evidence and helps determine scope.",
    consequence:
      "IT can see who changed what, restore the right version, and judge whether access needs to be tightened.",
  }),
  reviewed({
    id: "ge-c08",
    roleGroup: "general-employees",
    difficulty: "Intermediate",
    topicTags: ["ai-security", "data-privacy"],
    technologyTags: ["ai-assistants"],
    contextTags: ["saas"],
    frameworks: ["NIST AI RMF", "OWASP GenAI"],
    title: "Public AI assistant rewrite",
    situation: "A public AI assistant is useful for rewriting text.",
    question: "Which input is appropriate?",
    options: [
      "Raw customer complaints with names and claim numbers.",
      "Sanitised, non-sensitive example text permitted by policy.",
      "An exported HR spreadsheet.",
    ],
    correct: "b",
    guidance:
      "Public AI tools should not receive protected business or personal data without approval and controls.",
    consequence:
      "The rewrite still helps, and customer or HR records stay out of an unapproved third-party tool.",
  }),
  reviewed({
    id: "ge-c09",
    roleGroup: "general-employees",
    difficulty: "Intermediate",
    topicTags: ["phishing"],
    technologyTags: ["microsoft-365"],
    contextTags: ["saas"],
    frameworks: ["CIS 12"],
    title: "Airport Wi-Fi and work email",
    situation: "You must access work email from airport Wi-Fi.",
    question: "What is the best option?",
    options: [
      "Use the approved managed device and required secure access controls.",
      "Disable MFA because the connection is slow.",
      "Use a shared public computer.",
    ],
    correct: "a",
    guidance:
      "Managed access and strong authentication reduce exposure on untrusted networks.",
    consequence:
      "The session stays on a managed device with the organisation's access controls, even on a public network.",
  }),
  reviewed({
    id: "ge-c10",
    roleGroup: "general-employees",
    difficulty: "Intermediate",
    topicTags: ["phishing"],
    contextTags: ["internal-applications"],
    frameworks: ["NIST PR.AT"],
    title: "Urgent call that sounds like a manager",
    situation:
      "A senior manager calls with an urgent confidential request, but the voice sounds correct.",
    question: "What should you do?",
    options: [
      "Treat voice as sufficient proof.",
      "Verify the request through the organisation's approved process.",
      "Record the call and post it in Teams.",
    ],
    correct: "b",
    guidance: "Deepfakes make familiar voices unreliable as the only verification factor.",
    consequence:
      "The approved process confirms the request before confidential work or payments move on a voice match alone.",
  }),
  reviewed({
    id: "ge-c11",
    roleGroup: "general-employees",
    difficulty: "Intermediate",
    topicTags: ["ransomware"],
    contextTags: ["internal-applications"],
    frameworks: ["NIST SP 800-61r3"],
    title: "Strange file extensions and a ransom note",
    situation: "Files suddenly receive strange extensions and a ransom note appears.",
    question: "What should the employee do?",
    options: [
      "Disconnect the device as instructed by policy and contact IT immediately.",
      "Restart repeatedly.",
      "Pay using a personal card.",
    ],
    correct: "a",
    guidance: "Rapid containment and reporting reduce spread; do not improvise recovery.",
    consequence:
      "The device is isolated according to policy, and IT can start containment before the encryption spreads further.",
  }),
  reviewed({
    id: "ge-c12",
    roleGroup: "general-employees",
    difficulty: "Intermediate",
    topicTags: ["data-privacy"],
    contextTags: ["internal-applications"],
    frameworks: ["CIS 3"],
    title: "Payroll printout in a meeting room",
    situation: "A printed payroll list is found in a meeting room.",
    question: "What is the best action?",
    options: [
      "Photograph it for evidence and share the photo widely.",
      "Secure it and notify the responsible team.",
      "Leave it because it is not digital.",
    ],
    correct: "b",
    guidance: "Information security applies to paper and digital records alike.",
    consequence:
      "The list is taken out of public view, and HR or security can recover it without creating extra copies.",
  }),
];
