import { reviewed } from "@/lib/training/reviewed/define";
import type { ReviewedQuestion } from "@/lib/training/reviewed/types";

export const GITHUB_QUESTIONS: readonly ReviewedQuestion[] = [
  reviewed({
    id: "gh-dd-b01",
    roleGroup: "developers-devops",
    difficulty: "Beginner",
    topicTags: ["supply-chain", "secure-development"],
    technologyTags: ["github"],
    contextTags: ["saas", "internal-applications"],
    frameworks: ["CIS 6"],
    title: "API key committed to GitHub",
    situation: "A GitHub commit contains an API key.",
    question: "What should happen?",
    options: [
      "Revoke it, investigate use and remove it from history where appropriate.",
      "Delete only the newest line in the latest commit.",
      "Make the repository private and keep using the key.",
    ],
    correct: "a",
    guidance: "A committed credential must be treated as exposed.",
    consequence:
      "The key is revoked, use is checked, and a clean history or rotation plan replaces the exposed secret.",
  }),
  reviewed({
    id: "gh-dd-b02",
    roleGroup: "developers-devops",
    difficulty: "Beginner",
    topicTags: ["secure-development", "supply-chain"],
    technologyTags: ["github"],
    contextTags: ["saas", "internal-applications"],
    frameworks: ["NIST SSDF"],
    title: "Security-sensitive pull request",
    situation: "A security-sensitive change is ready on a feature branch.",
    question: "What should be required before merge?",
    options: [
      "Review and automated checks before merge.",
      "Direct push to main.",
      "Approval through private chat only.",
    ],
    correct: "a",
    guidance: "Protected review creates traceable separation and verification.",
    consequence:
      "The change reaches main only after named review and checks, so a chat message cannot skip the record.",
  }),
  reviewed({
    id: "gh-dd-b03",
    roleGroup: "developers-devops",
    difficulty: "Beginner",
    topicTags: ["supply-chain", "secure-development"],
    technologyTags: ["github"],
    contextTags: ["saas", "third-party-providers"],
    frameworks: ["NIST SSDF"],
    title: "High-severity Dependabot alert",
    situation: "A production dependency has a high-severity Dependabot alert.",
    question: "What should the team do?",
    options: [
      "Assess exposure, test remediation and track ownership.",
      "Dismiss every alert.",
      "Delete the lockfile.",
    ],
    correct: "a",
    guidance: "Alerts require risk-based triage and verified remediation.",
    consequence:
      "Someone owns the reachable risk, tests the fix, and the alert is not closed as noise.",
  }),
  reviewed({
    id: "gh-dd-b04",
    roleGroup: "developers-devops",
    difficulty: "Beginner",
    topicTags: ["secure-development", "supply-chain"],
    technologyTags: ["github", "cicd"],
    contextTags: ["saas"],
    frameworks: ["CIS 6"],
    title: "GITHUB_TOKEN for a read-only workflow",
    situation: "A workflow only needs repository read access.",
    question: "What should GITHUB_TOKEN receive?",
    options: [
      "Explicit read-only permissions.",
      "Write access to every repository.",
      "Organisation owner rights.",
    ],
    correct: "a",
    guidance: "Workflow tokens should receive only required permissions.",
    consequence:
      "The job can read the repository and cannot push, create releases or change organisation settings.",
  }),
  reviewed({
    id: "gh-dd-c01",
    roleGroup: "developers-devops",
    difficulty: "Intermediate",
    topicTags: ["supply-chain", "secure-development"],
    technologyTags: ["github", "cicd"],
    contextTags: ["saas", "third-party-providers"],
    frameworks: ["NIST SSDF", "CIS 6"],
    title: "Forked pull request with workflow secrets",
    situation: "A forked pull request can execute a workflow that contains secrets.",
    question: "What is safer?",
    options: [
      "Separate untrusted checks from privileged workflows.",
      "Expose every secret to pull-request workflows.",
      "Ask contributors not to misuse access.",
    ],
    correct: "a",
    guidance: "Untrusted code must not run in a privileged secret-bearing context.",
    consequence:
      "Untrusted checks run without production secrets, and privileged jobs stay on trusted branches.",
  }),
  reviewed({
    id: "gh-dd-c02",
    roleGroup: "developers-devops",
    difficulty: "Intermediate",
    topicTags: ["supply-chain", "secure-development"],
    technologyTags: ["github", "cicd"],
    contextTags: ["saas", "third-party-providers"],
    frameworks: ["NIST SSDF"],
    title: "Third-party action on main",
    situation: "A workflow uses vendor/action@main.",
    question: "What improves supply-chain control?",
    options: [
      "Pin a reviewed action to an immutable commit and monitor updates.",
      "Trust main permanently.",
      "Copy credentials into its inputs.",
    ],
    correct: "a",
    guidance: "Mutable references can change without repository review.",
    consequence:
      "The job runs a reviewed commit hash, and later updates are compared before they ship.",
  }),
  reviewed({
    id: "gh-dd-c03",
    roleGroup: "developers-devops",
    difficulty: "Intermediate",
    topicTags: ["supply-chain", "secure-development"],
    technologyTags: ["github"],
    contextTags: ["saas", "third-party-providers"],
    frameworks: ["NIST SSDF"],
    title: "Pull request adds transitive packages",
    situation: "A pull request adds several transitive packages.",
    question: "Which control provides decision context before merge?",
    options: [
      "Dependency review plus policy and human review.",
      "Waiting for production alerts.",
      "Removing package metadata.",
    ],
    correct: "a",
    guidance: "Review the security impact while the dependency change is still proposed.",
    consequence:
      "Reviewers see new packages and licence or advisory risk before the merge, not after production alerts.",
  }),
  reviewed({
    id: "gh-dd-c04",
    roleGroup: "developers-devops",
    difficulty: "Intermediate",
    topicTags: ["supply-chain", "secure-development"],
    technologyTags: ["github", "cicd"],
    contextTags: ["saas", "internal-applications"],
    frameworks: ["NIST SSDF", "CIS 6"],
    title: "Workflow deploys after any branch push",
    situation: "A workflow can deploy production after any branch push.",
    question: "What should change?",
    options: [
      "Protected environments with restricted branches, approval and scoped secrets.",
      "More repository collaborators.",
      "Let any branch use the production environment.",
    ],
    correct: "a",
    guidance: "Production deployment requires a stronger trust boundary than ordinary CI.",
    consequence:
      "Only approved branches and people can reach production secrets, so a feature-branch push cannot deploy.",
  }),
  reviewed({
    id: "gh-it-b01",
    roleGroup: "it-security",
    difficulty: "Beginner",
    topicTags: ["supply-chain", "ransomware"],
    technologyTags: ["github"],
    contextTags: ["saas"],
    frameworks: ["CIS 6", "NIST SP 800-61r3"],
    title: "Secret-scanning alert for a cloud token",
    situation: "GitHub detects a cloud token in a repository.",
    question: "What is the first priority?",
    options: [
      "Revoke or rotate the token and assess use.",
      "Close the alert because the file was deleted.",
      "Rename the repository.",
    ],
    correct: "a",
    guidance: "Removal does not invalidate a credential already copied.",
    consequence:
      "The token stops working, use is checked, and a deleted file is not treated as containment.",
  }),
  reviewed({
    id: "gh-it-b02",
    roleGroup: "it-security",
    difficulty: "Beginner",
    topicTags: ["supply-chain"],
    technologyTags: ["github"],
    contextTags: ["saas", "third-party-providers"],
    frameworks: ["CIS 6"],
    title: "Contractor assignment ended",
    situation: "A contractor's assignment ended.",
    question: "What should the GitHub offboarding process include?",
    options: [
      "Remove organisation and team access and review owned tokens and keys.",
      "Change the display name.",
      "Leave access for convenience.",
    ],
    correct: "a",
    guidance: "Source and pipeline access must follow the identity lifecycle.",
    consequence:
      "The contractor cannot reach repositories or leftover PATs after the assignment ends.",
  }),
  reviewed({
    id: "gh-it-b03",
    roleGroup: "it-security",
    difficulty: "Beginner",
    topicTags: ["supply-chain"],
    technologyTags: ["github"],
    contextTags: ["saas"],
    frameworks: ["CIS 5", "CIS 6"],
    title: "Ruleset bypass on every repository",
    situation: "A user can bypass required reviews on every repository.",
    question: "What is the concern?",
    options: [
      "The exception is too broad and should be limited and monitored.",
      "Bypass improves separation of duties.",
      "Required reviews no longer matter.",
    ],
    correct: "a",
    guidance: "Administrative bypasses are privileged access and need governance.",
    consequence:
      "Bypass is narrowed, logged and reviewed, so one account cannot skip review everywhere.",
  }),
  reviewed({
    id: "gh-it-b04",
    roleGroup: "it-security",
    difficulty: "Beginner",
    topicTags: ["ransomware", "supply-chain"],
    technologyTags: ["github"],
    contextTags: ["saas"],
    frameworks: ["CIS 8"],
    title: "What the GitHub organisation audit log supports",
    situation: "Responders are choosing evidence sources after a GitHub incident.",
    question: "What can the GitHub organisation audit log support?",
    options: [
      "Investigation of administrative and repository actions.",
      "Full endpoint forensics.",
      "Database restoration.",
    ],
    correct: "a",
    guidance: "Audit evidence should be centrally retained and correlated with identity and CI logs.",
    consequence:
      "The team uses the audit log for admin and repository actions and still collects endpoint and database evidence elsewhere.",
  }),
  reviewed({
    id: "gh-it-c01",
    roleGroup: "it-security",
    difficulty: "Intermediate",
    topicTags: ["ransomware", "supply-chain"],
    technologyTags: ["github"],
    contextTags: ["saas"],
    frameworks: ["NIST SP 800-61r3", "CIS 6"],
    title: "Fine-grained personal access token exposed",
    situation: "A fine-grained personal access token is exposed.",
    question: "What should responders determine?",
    options: [
      "Repositories, permissions, activity, owner and required revocation.",
      "Only the token's name.",
      "Whether the README changed.",
    ],
    correct: "a",
    guidance: "Token scope and observed use define the likely impact.",
    consequence:
      "The token is revoked and scoped from evidence, so a README check is not treated as containment.",
  }),
  reviewed({
    id: "gh-it-c02",
    roleGroup: "it-security",
    difficulty: "Intermediate",
    topicTags: ["supply-chain", "ransomware"],
    technologyTags: ["github"],
    contextTags: ["saas", "third-party-providers"],
    frameworks: ["NIST SP 800-61r3", "CIS 6"],
    title: "Unknown GitHub App with write access",
    situation: "An unknown GitHub App has write access to many repositories.",
    question: "What should happen?",
    options: [
      "Review installation source, permissions and activity, then suspend or revoke as required.",
      "Trust it because it is an App.",
      "Rotate developer passwords only.",
    ],
    correct: "a",
    guidance: "Installed applications can hold durable organisation-wide authority.",
    consequence:
      "The App is checked and suspended if needed, so password rotation alone does not leave its write token active.",
  }),
  reviewed({
    id: "gh-it-c03",
    roleGroup: "it-security",
    difficulty: "Intermediate",
    topicTags: ["supply-chain", "ransomware"],
    technologyTags: ["github", "cicd"],
    contextTags: ["saas", "internal-applications"],
    frameworks: ["NIST SSDF", "CIS 6"],
    title: "Public repository jobs on a persistent self-hosted runner",
    situation: "A public repository sends jobs to a persistent self-hosted runner.",
    question: "What is the risk?",
    options: [
      "Untrusted code may reach internal networks, residue and credentials.",
      "Public repositories cannot run code.",
      "Runner state is always erased.",
    ],
    correct: "a",
    guidance: "Runner placement, isolation and lifecycle must match the trust level of the code.",
    consequence:
      "Public jobs stop landing on a persistent internal runner that still holds network paths and leftover credentials.",
  }),
  reviewed({
    id: "gh-it-c04",
    roleGroup: "it-security",
    difficulty: "Intermediate",
    topicTags: ["supply-chain", "secure-development"],
    technologyTags: ["github"],
    contextTags: ["saas", "internal-applications"],
    frameworks: ["NIST SSDF"],
    title: "CodeQL finding dismissed without evidence",
    situation: "A critical code-scanning alert is dismissed as a false positive without evidence.",
    question: "What is missing?",
    options: [
      "Documented triage, reviewer accountability and validation.",
      "Change the alert severity for convenience.",
      "Ignore it because the repository is popular.",
    ],
    correct: "a",
    guidance: "Security exceptions must be explainable and reviewable.",
    consequence:
      "The dismissal has a named reviewer and evidence, so a later audit can see why the finding was closed.",
  }),
  reviewed({
    id: "gh-lr-b01",
    roleGroup: "leaders-risk",
    difficulty: "Beginner",
    topicTags: ["business-continuity", "supply-chain"],
    technologyTags: ["github"],
    contextTags: ["saas", "internal-applications"],
    frameworks: ["NIST GV"],
    title: "Named owners for business-critical repositories",
    situation: "Several business-critical repositories have no named owner.",
    question: "Why assign named owners?",
    options: [
      "To own access, review, dependencies, recovery and exceptions.",
      "To pick a repository icon.",
      "To transfer accountability to GitHub.",
    ],
    correct: "a",
    guidance: "Source code is a critical asset requiring lifecycle ownership.",
    consequence:
      "Each critical repository has someone who can approve access, own recovery and accept exceptions.",
  }),
  reviewed({
    id: "gh-lr-b02",
    roleGroup: "leaders-risk",
    difficulty: "Beginner",
    topicTags: ["supply-chain", "business-continuity"],
    technologyTags: ["github"],
    contextTags: ["saas"],
    frameworks: ["NIST GV"],
    title: "Does a private repository eliminate risk",
    situation: "A business owner says a private GitHub repository is fully protected.",
    question: "Does a private repository eliminate security risk?",
    options: [
      "No, access, tokens, dependencies and workflows still require controls.",
      "Yes, private means fully protected.",
      "Yes, review is unnecessary.",
    ],
    correct: "a",
    guidance: "Visibility setting is only one control.",
    consequence:
      "Leaders still require access, token, dependency and workflow controls on private repositories.",
  }),
  reviewed({
    id: "gh-lr-b03",
    roleGroup: "leaders-risk",
    difficulty: "Beginner",
    topicTags: ["supply-chain", "business-continuity"],
    technologyTags: ["github"],
    contextTags: ["saas", "internal-applications"],
    frameworks: ["NIST GV", "ISO 27001"],
    title: "Permanent direct push to production code",
    situation: "A team wants permanent direct-push access to production code.",
    question: "What should governance require?",
    options: [
      "A narrow reason, compensating controls, owner and review date.",
      "Approval without documentation.",
      "Removal of all branch protections.",
    ],
    correct: "a",
    guidance: "Exceptions should not silently become the operating model.",
    consequence:
      "The exception is time-bound and owned, without switching branch protection off for everyone.",
  }),
  reviewed({
    id: "gh-lr-b04",
    roleGroup: "leaders-risk",
    difficulty: "Beginner",
    topicTags: ["business-continuity", "supply-chain"],
    technologyTags: ["github"],
    contextTags: ["saas", "third-party-providers"],
    frameworks: ["NIST RC", "DORA"],
    title: "Critical deployments depend on GitHub",
    situation: "Critical deployments depend on GitHub.",
    question: "What should continuity planning consider?",
    options: [
      "Impact, cached artefacts, emergency changes and recovery communications.",
      "Only repository size.",
      "That GitHub can never be unavailable.",
    ],
    correct: "a",
    guidance: "Development platforms can become critical operational dependencies.",
    consequence:
      "Leaders know how a GitHub outage would hit releases and how emergency changes would be communicated.",
  }),
  reviewed({
    id: "gh-lr-c01",
    roleGroup: "leaders-risk",
    difficulty: "Intermediate",
    topicTags: ["business-continuity", "supply-chain"],
    technologyTags: ["github"],
    contextTags: ["saas", "third-party-providers"],
    frameworks: ["DORA", "NIST GV.SC"],
    title: "Source, issues, Actions and approvals on one organisation",
    situation:
      "Source, issues, Actions and deployment approvals all depend on one GitHub organisation.",
    question: "What should leadership assess?",
    options: [
      "Shared failure and compromise scenarios plus recovery options.",
      "Only licence utilisation.",
      "Only commit count.",
    ],
    correct: "a",
    guidance: "Tool consolidation can create a correlated control dependency.",
    consequence:
      "Leaders know how one organisation failure would stop code, issues and approvals, and what recovery would look like.",
  }),
  reviewed({
    id: "gh-lr-c02",
    roleGroup: "leaders-risk",
    difficulty: "Intermediate",
    topicTags: ["business-continuity", "supply-chain"],
    technologyTags: ["github"],
    contextTags: ["saas", "internal-applications"],
    frameworks: ["NIST RC", "CIS 11"],
    title: "Backups assumed because developers have clones",
    situation:
      "A policy says repositories are backed up because developers have local clones.",
    question: "Is that sufficient?",
    options: [
      "No, test recovery of code, metadata, permissions and required workflows.",
      "Yes, every clone is complete.",
      "Yes, issues and settings do not matter.",
    ],
    correct: "a",
    guidance: "Operational recovery extends beyond Git objects.",
    consequence:
      "A restore test covers code, settings, permissions and workflows, not only a laptop clone.",
  }),
  reviewed({
    id: "gh-lr-c03",
    roleGroup: "leaders-risk",
    difficulty: "Intermediate",
    topicTags: ["supply-chain", "business-continuity"],
    technologyTags: ["github"],
    contextTags: ["saas", "third-party-providers"],
    frameworks: ["NIST GV.SC", "DORA Ch. V"],
    title: "Third-party GitHub App for critical builds",
    situation: "A third-party GitHub App supports critical builds.",
    question: "What should be governed?",
    options: [
      "Permissions, data access, security expectations, incident notice and exit or removal.",
      "Only app price.",
      "Only Marketplace rating.",
    ],
    correct: "a",
    guidance: "Integrated applications become part of the software supply chain.",
    consequence:
      "The App has agreed permissions, incident notice and a removal path, not only a price and a rating.",
  }),
  reviewed({
    id: "gh-lr-c04",
    roleGroup: "leaders-risk",
    difficulty: "Intermediate",
    topicTags: ["supply-chain", "business-continuity"],
    technologyTags: ["github"],
    contextTags: ["saas"],
    frameworks: ["NIST GV"],
    title: "GitHub metric for risk decisions",
    situation: "Leadership wants a GitHub metric that supports risk decisions.",
    question: "Which measure is more useful?",
    options: [
      "Time to remediate critical reachable findings and percentage of protected critical repositories.",
      "Total commits.",
      "Number of comments on pull requests.",
    ],
    correct: "a",
    guidance: "Metrics should connect control performance to important assets.",
    consequence:
      "Leaders track how fast critical findings close and how many critical repos are protected, not activity volume.",
  }),
];
