import { reviewed } from "@/lib/training/reviewed/define";
import type { ReviewedQuestion } from "@/lib/training/reviewed/types";

export const IT_SECURITY_QUESTIONS: readonly ReviewedQuestion[] = [
  reviewed({
    id: "it-b01",
    roleGroup: "it-security",
    difficulty: "Beginner",
    topicTags: ["phishing"],
    technologyTags: ["microsoft-365"],
    contextTags: ["saas"],
    frameworks: ["CIS 5", "CIS 6"],
    title: "Unexpected MFA prompt reported to IT",
    situation: "A user reports an unexpected MFA prompt.",
    question: "What should IT investigate first?",
    options: [
      "Sign-in activity and possible credential compromise.",
      "Whether the user's printer is online.",
      "Whether the user's display settings changed.",
    ],
    correct: "a",
    guidance: "Unexpected MFA activity can indicate that the password is already known to an attacker.",
    consequence:
      "Sign-in logs show whether an attacker already has the password, so sessions can be revoked quickly.",
  }),
  reviewed({
    id: "it-b02",
    roleGroup: "it-security",
    difficulty: "Beginner",
    topicTags: ["ransomware"],
    technologyTags: ["microsoft-365"],
    contextTags: ["internal-applications"],
    frameworks: ["CIS 10"],
    title: "EDR flags ransomware on one laptop",
    situation: "EDR flags ransomware behaviour on one laptop.",
    question: "What is the best immediate action?",
    options: [
      "Isolate the device through the approved response process.",
      "Disable EDR.",
      "Reboot every server.",
    ],
    correct: "a",
    guidance: "Targeted isolation can limit spread while preserving evidence.",
    consequence:
      "The laptop is isolated without wiping evidence or taking unrelated systems down.",
  }),
  reviewed({
    id: "it-b03",
    roleGroup: "it-security",
    difficulty: "Beginner",
    topicTags: ["ransomware", "cloud-security"],
    technologyTags: ["microsoft-365", "azure"],
    contextTags: ["saas"],
    frameworks: ["CIS 8"],
    title: "Why send logs to a central SIEM",
    situation: "Identity, endpoint and cloud logs currently sit in separate consoles.",
    question: "Why send identity, endpoint and cloud logs to a central SIEM?",
    options: [
      "To correlate events across systems.",
      "To replace backups.",
      "To make users change passwords daily.",
    ],
    correct: "a",
    guidance: "Individual events become more useful when connected into an incident story.",
    consequence:
      "A sign-in, an endpoint alert and a cloud change can be read as one incident instead of three tickets.",
  }),
  reviewed({
    id: "it-b04",
    roleGroup: "it-security",
    difficulty: "Beginner",
    topicTags: ["phishing", "cloud-security"],
    technologyTags: ["microsoft-365"],
    contextTags: ["saas"],
    frameworks: ["CIS 4"],
    title: "Non-compliant mobile device",
    situation: "A mobile device accessing company data is no longer compliant.",
    question: "What should Conditional Access do?",
    options: [
      "Apply the approved restriction or remediation requirement.",
      "Ignore compliance state.",
      "Grant global administrator.",
    ],
    correct: "a",
    guidance: "Device trust should influence access to protected services.",
    consequence:
      "The device is blocked or limited until it meets the organisation's access rule.",
  }),
  reviewed({
    id: "it-b05",
    roleGroup: "it-security",
    difficulty: "Beginner",
    topicTags: ["cloud-security"],
    technologyTags: ["azure"],
    contextTags: ["internal-applications"],
    frameworks: ["CIS 6"],
    title: "Support technician who only manages VMs",
    situation: "A support technician only manages virtual machines.",
    question: "Which role design is best?",
    options: [
      "Global administrator.",
      "A scoped role for the required VM tasks.",
      "A shared owner account.",
    ],
    correct: "b",
    guidance: "Scope permissions to the actual operational responsibility.",
    consequence:
      "The technician can restart VMs without holding directory-wide power if the account is later abused.",
  }),
  reviewed({
    id: "it-b06",
    roleGroup: "it-security",
    difficulty: "Beginner",
    topicTags: ["phishing", "ransomware"],
    technologyTags: ["microsoft-365"],
    contextTags: ["saas"],
    frameworks: ["CIS 5"],
    title: "User leaves the company today",
    situation: "A user leaves the company today.",
    question: "What should the offboarding process include?",
    options: [
      "Disable access, revoke sessions and transfer required ownership.",
      "Change the display name only.",
      "Wait for licence renewal.",
    ],
    correct: "a",
    guidance: "Offboarding must address active sessions, data ownership and access.",
    consequence:
      "The account cannot keep open sessions or mailboxes after the person has left.",
  }),
  reviewed({
    id: "it-b07",
    roleGroup: "it-security",
    difficulty: "Beginner",
    topicTags: ["cloud-security", "secure-development"],
    technologyTags: ["azure"],
    contextTags: ["internal-applications"],
    frameworks: ["CIS 6"],
    title: "Application secret exposed",
    situation: "An application secret has been exposed.",
    question: "What is the first technical priority?",
    options: [
      "Rotate or revoke the secret and assess use.",
      "Rename the vault.",
      "Delete audit logs.",
    ],
    correct: "a",
    guidance: "Contain the credential before investigating the full timeline.",
    consequence:
      "The leaked secret stops working, and logs remain available to see whether it was used.",
  }),
  reviewed({
    id: "it-b08",
    roleGroup: "it-security",
    difficulty: "Beginner",
    topicTags: ["ransomware", "business-continuity"],
    contextTags: ["internal-applications"],
    frameworks: ["CIS 11"],
    title: "What proves a backup can recover",
    situation: "Backups complete every night and the storage icon is healthy.",
    question: "What proves a backup can support recovery?",
    options: [
      "A successful, documented restore test.",
      "A healthy storage status.",
      "The age of the backup server.",
    ],
    correct: "a",
    guidance: "Backup existence and recoverability are different claims.",
    consequence:
      "A restore test either proves the service can return or shows the gap before the next incident.",
  }),
  reviewed({
    id: "it-b09",
    roleGroup: "it-security",
    difficulty: "Beginner",
    topicTags: ["ransomware", "cloud-security"],
    contextTags: ["internal-applications"],
    frameworks: ["CIS 7"],
    title: "Which vulnerability to prioritise",
    situation: "The team has a mixed list of vulnerability findings.",
    question: "Which finding should normally be prioritised first?",
    options: [
      "An actively exploited internet-facing vulnerability on a critical system.",
      "A low-risk issue on an isolated test machine.",
      "The finding with the longest advisory title.",
    ],
    correct: "a",
    guidance: "Prioritisation should combine exploitability, exposure and business impact.",
    consequence:
      "The internet-facing, actively exploited issue is treated first, before quieter test-lab findings.",
  }),
  reviewed({
    id: "it-b10",
    roleGroup: "it-security",
    difficulty: "Beginner",
    topicTags: ["ransomware", "cloud-security"],
    contextTags: ["internal-applications"],
    frameworks: ["CIS 12", "CIS 13"],
    title: "Separating user devices from critical servers",
    situation: "User laptops and critical servers currently share a flat network.",
    question: "Why separate user devices from critical servers?",
    options: [
      "To limit movement after one device is compromised.",
      "To improve display settings.",
      "To eliminate all need for identity controls.",
    ],
    correct: "a",
    guidance: "Segmentation limits blast radius but remains one layer of defence.",
    consequence:
      "A compromised laptop cannot walk straight onto the servers that run the business.",
  }),
  reviewed({
    id: "it-b11",
    roleGroup: "it-security",
    difficulty: "Beginner",
    topicTags: ["ransomware"],
    contextTags: ["internal-applications"],
    frameworks: ["NIST SP 800-61r3"],
    title: "What an initial incident record should contain",
    situation: "A new incident ticket is being opened.",
    question: "What should an initial incident record contain?",
    options: [
      "Known facts, time, source, affected assets and current actions.",
      "A final root cause before investigation.",
      "Personal guesses presented as facts.",
    ],
    correct: "a",
    guidance: "Separate evidence from assumptions and update the record as the picture changes.",
    consequence:
      "The next responder can see what is known, what is still open, and what has already been done.",
  }),
  reviewed({
    id: "it-b12",
    roleGroup: "it-security",
    difficulty: "Beginner",
    topicTags: ["phishing"],
    technologyTags: ["microsoft-365"],
    contextTags: ["saas"],
    frameworks: ["CIS 5", "CIS 6"],
    title: "How administrators should do everyday email",
    situation: "Administrators also need ordinary email and collaboration.",
    question: "How should administrators perform everyday email work?",
    options: [
      "With the same privileged account used for servers.",
      "With a normal account, reserving privileged identity for admin tasks.",
      "Through a shared administrator mailbox.",
    ],
    correct: "b",
    guidance: "Separate privileged and ordinary activity to reduce exposure.",
    consequence:
      "A phishing click on everyday mail does not immediately hand over server-admin rights.",
  }),
  reviewed({
    id: "it-c01",
    roleGroup: "it-security",
    difficulty: "Intermediate",
    topicTags: ["phishing", "cloud-security"],
    technologyTags: ["microsoft-365"],
    contextTags: ["saas"],
    frameworks: ["CIS 6"],
    title: "Correct MFA from an impossible location",
    situation:
      "A sign-in uses correct MFA but originates from an impossible location and unmanaged device.",
    question: "What should the control do?",
    options: [
      "Treat MFA as sufficient.",
      "Apply risk-based access controls and investigate.",
      "Disable logging.",
    ],
    correct: "b",
    guidance: "Authentication strength is one signal; context and device state also matter.",
    consequence:
      "The sign-in is challenged or blocked, and the account is investigated instead of trusted on MFA alone.",
  }),
  reviewed({
    id: "it-c02",
    roleGroup: "it-security",
    difficulty: "Intermediate",
    topicTags: ["phishing"],
    technologyTags: ["microsoft-365"],
    contextTags: ["saas"],
    frameworks: ["NIST DE.AE"],
    title: "Failed login, inbox rule and unusual download",
    situation:
      "Sentinel shows a failed login, new inbox rule and unusual SharePoint download for one user.",
    question: "What is the best interpretation?",
    options: [
      "Three unrelated low events.",
      "A correlated account-compromise hypothesis requiring investigation.",
      "Normal because each service worked.",
    ],
    correct: "b",
    guidance: "Correlation turns weak signals into a credible attack chain.",
    consequence:
      "The account is investigated as a possible compromise rather than three closed low-priority tickets.",
  }),
  reviewed({
    id: "it-c03",
    roleGroup: "it-security",
    difficulty: "Intermediate",
    topicTags: ["ransomware", "business-continuity"],
    contextTags: ["internal-applications"],
    frameworks: ["NIST SP 800-61r3"],
    title: "Infected endpoint on a warehouse process",
    situation: "An infected endpoint supports a critical warehouse process.",
    question: "What is the best containment decision?",
    options: [
      "Leave it online without controls.",
      "Isolate it while activating the tested manual continuity process.",
      "Shut down the entire company automatically.",
    ],
    correct: "b",
    guidance: "Containment and business continuity should be coordinated rather than treated as opposites.",
    consequence:
      "The infected device is isolated, and the warehouse keeps moving on the tested manual process.",
  }),
  reviewed({
    id: "it-c04",
    roleGroup: "it-security",
    difficulty: "Intermediate",
    topicTags: ["cloud-security"],
    technologyTags: ["azure"],
    contextTags: ["internal-applications"],
    frameworks: ["CIS 3"],
    title: "Year-long shared access signature",
    situation:
      "A storage account is private, but a shared access signature remains valid for one year.",
    question: "What is the concern?",
    options: [
      "The token is a long-lived bearer credential.",
      "Private networking cancels all token risk.",
      "The URL is difficult to bookmark.",
    ],
    correct: "a",
    guidance: "Reduce token lifetime and permissions even when network controls exist.",
    consequence:
      "The SAS is shortened and scoped, so a leaked link cannot grant a year of access.",
  }),
  reviewed({
    id: "it-c05",
    roleGroup: "it-security",
    difficulty: "Intermediate",
    topicTags: ["business-continuity", "ransomware"],
    contextTags: ["internal-applications", "third-party-providers"],
    frameworks: ["DORA Ch. III"],
    title: "Financial service disruption and delayed transactions",
    situation:
      "A financial service is disrupted and customer transactions are delayed.",
    question: "What should the incident team do alongside containment?",
    options: [
      "Begin classification, evidence capture and regulatory escalation assessment.",
      "Wait for full recovery before recording anything.",
      "Let the cloud provider decide whether the entity must report.",
    ],
    correct: "a",
    guidance: "The regulated entity retains responsibility for classification and reporting.",
    consequence:
      "Classification and evidence start while systems are still being recovered, without waiting for a vendor to decide.",
  }),
  reviewed({
    id: "it-c06",
    roleGroup: "it-security",
    difficulty: "Intermediate",
    topicTags: ["business-continuity"],
    contextTags: ["internal-applications"],
    frameworks: ["DORA Ch. IV"],
    title: "Disaster recovery used undocumented steps",
    situation:
      "A disaster-recovery exercise succeeds only because engineers used undocumented steps.",
    question: "What is the correct conclusion?",
    options: [
      "The plan is proven.",
      "Capture the gap, update the plan and retest.",
      "Delete the exercise evidence.",
    ],
    correct: "b",
    guidance: "Tests are valuable when findings become remediation and verified improvement.",
    consequence:
      "The real steps are written into the plan and tested again, so the next recovery does not depend on memory.",
  }),
  reviewed({
    id: "it-c07",
    roleGroup: "it-security",
    difficulty: "Intermediate",
    topicTags: ["cloud-security", "business-continuity"],
    technologyTags: ["azure"],
    contextTags: ["internal-applications"],
    frameworks: ["DORA ICT risk"],
    title: "Legacy application cannot use modern authentication",
    situation: "A critical legacy application cannot support modern authentication.",
    question: "What should architecture do?",
    options: [
      "Accept the risk permanently.",
      "Document dependency and risk, add compensating controls and plan treatment or replacement.",
      "Hide it from the asset inventory.",
    ],
    correct: "b",
    guidance: "Known technical constraints require explicit ownership and treatment.",
    consequence:
      "The legacy dependency is visible, compensated and scheduled for treatment instead of remaining an unofficial exception.",
  }),
  reviewed({
    id: "it-c08",
    roleGroup: "it-security",
    difficulty: "Intermediate",
    topicTags: ["business-continuity"],
    contextTags: ["saas", "third-party-providers"],
    frameworks: ["NIST GV.SC", "DORA Ch. V"],
    title: "Critical SaaS provider with repeated outages",
    situation: "A critical SaaS provider suffers repeated outages.",
    question: "What evidence is needed for a decision?",
    options: [
      "Service dependency, incident history, contractual commitments, recovery and exit feasibility.",
      "Only the sales presentation.",
      "The provider's public popularity.",
    ],
    correct: "a",
    guidance: "Supplier risk decisions need operational evidence and credible alternatives.",
    consequence:
      "Leadership can decide from dependency, recovery and exit evidence rather than from a brochure.",
  }),
  reviewed({
    id: "it-c09",
    roleGroup: "it-security",
    difficulty: "Intermediate",
    topicTags: ["ransomware", "phishing"],
    contextTags: ["saas"],
    frameworks: ["CIS 8"],
    title: "Authentication logs kept for seven days",
    situation:
      "Authentication logs are retained for seven days, but investigations often start later.",
    question: "What should the organisation do?",
    options: [
      "Align retention with threat, legal and investigation needs.",
      "Keep seven days because it is the default.",
      "Turn off collection.",
    ],
    correct: "a",
    guidance: "Retention should support detection and investigation while respecting data obligations.",
    consequence:
      "Investigations can still use sign-in evidence when they start after the first week.",
  }),
  reviewed({
    id: "it-c10",
    roleGroup: "it-security",
    difficulty: "Intermediate",
    topicTags: ["cloud-security", "ransomware"],
    contextTags: ["internal-applications"],
    frameworks: ["NIST SP 800-61r3"],
    title: "Stolen Kubernetes service-account token",
    situation: "A pod used a stolen service-account token.",
    question: "Which scope question matters?",
    options: [
      "What permissions, namespaces and external systems the token could reach.",
      "Which developer chose the pod name.",
      "Whether the dashboard looked normal.",
    ],
    correct: "a",
    guidance: "Effective permissions define the potential blast radius.",
    consequence:
      "Responders know which namespaces and systems to contain, instead of guessing from the pod name.",
  }),
  reviewed({
    id: "it-c11",
    roleGroup: "it-security",
    difficulty: "Intermediate",
    topicTags: ["ransomware", "business-continuity"],
    contextTags: ["internal-applications"],
    frameworks: ["NIST RC"],
    title: "Restore after ransomware with unknown access path",
    situation:
      "Systems are restored after ransomware, but the original access path is unknown.",
    question: "Should normal operations resume fully?",
    options: [
      "Yes, availability is enough.",
      "Only with risk-based safeguards, monitoring and continued eradication work.",
      "Never restore anything.",
    ],
    correct: "b",
    guidance: "Recovery without addressing persistence can recreate the incident.",
    consequence:
      "Services return with extra monitoring and remaining eradication work, instead of a full reopen that invites the same path back.",
  }),
  reviewed({
    id: "it-c12",
    roleGroup: "it-security",
    difficulty: "Intermediate",
    topicTags: ["ransomware"],
    contextTags: ["internal-applications"],
    frameworks: ["NIST SP 800-61r3"],
    title: "Who collected an image or log export",
    situation: "An image and a log export are being collected for later review.",
    question: "Why document who collected an image or log export and when?",
    options: [
      "To support integrity, repeatability and later review.",
      "To make the report longer.",
      "To replace technical analysis.",
    ],
    correct: "a",
    guidance: "Evidence handling should make findings defensible and traceable.",
    consequence:
      "A later reviewer can trust where the evidence came from and repeat the collection if needed.",
  }),
];
