import { reviewed } from "@/lib/training/reviewed/define";
import type { ReviewedQuestion } from "@/lib/training/reviewed/types";

export const LEADERS_RISK_QUESTIONS: readonly ReviewedQuestion[] = [
  reviewed({
    id: "lr-b01",
    roleGroup: "leaders-risk",
    difficulty: "Beginner",
    topicTags: ["business-continuity", "ransomware"],
    contextTags: ["internal-applications"],
    frameworks: ["NIST CSF 2.0 GV"],
    title: "Who owns cybersecurity risk",
    situation: "The board is discussing who is accountable for cyber risk.",
    question: "Who owns cybersecurity risk?",
    options: [
      "Only the security team.",
      "Leadership owns the risk while specialists advise and operate controls.",
      "The software vendor.",
    ],
    correct: "b",
    guidance: "Cybersecurity is enterprise risk and needs accountable decision-makers.",
    consequence:
      "Leaders stay accountable for risk decisions, with specialists advising and operating the controls.",
  }),
  reviewed({
    id: "lr-b02",
    roleGroup: "leaders-risk",
    difficulty: "Beginner",
    topicTags: ["business-continuity", "cloud-security"],
    contextTags: ["internal-applications"],
    frameworks: ["NIST ID", "CIS 1-2"],
    title: "Why leadership needs an inventory",
    situation: "Important systems and data are not listed in one place.",
    question: "Why does leadership need an inventory of important systems and data?",
    options: [
      "To understand what the organisation depends on and protects.",
      "To count workstation models.",
      "To replace risk assessment.",
    ],
    correct: "a",
    guidance: "Unknown assets and dependencies cannot be governed reliably.",
    consequence:
      "Risk discussions start from what the organisation actually depends on, not from an incomplete mental list.",
  }),
  reviewed({
    id: "lr-b03",
    roleGroup: "leaders-risk",
    difficulty: "Beginner",
    topicTags: ["business-continuity"],
    contextTags: ["internal-applications"],
    frameworks: ["ISO 27001", "NIST GV"],
    title: "A known risk cannot be removed immediately",
    situation: "A known risk cannot be removed immediately.",
    question: "What should happen?",
    options: [
      "Ignore it.",
      "Record the risk, treatment, owner, deadline and authorised acceptance if needed.",
      "Delete the finding.",
    ],
    correct: "b",
    guidance: "Residual risk requires explicit ownership and review.",
    consequence:
      "The risk stays visible with an owner and a review date, instead of disappearing from the register.",
  }),
  reviewed({
    id: "lr-b04",
    roleGroup: "leaders-risk",
    difficulty: "Beginner",
    topicTags: ["business-continuity"],
    contextTags: ["internal-applications"],
    frameworks: ["NIST RC"],
    title: "What is an RTO",
    situation: "A continuity paper mentions RTO without defining it.",
    question: "What is an RTO?",
    options: [
      "The target time for restoring a service after disruption.",
      "The maximum number of passwords.",
      "A supplier invoice code.",
    ],
    correct: "a",
    guidance: "Recovery objectives connect technical recovery to business needs.",
    consequence:
      "Technical teams restore against a business time target, not an undefined hope that the service returns.",
  }),
  reviewed({
    id: "lr-b05",
    roleGroup: "leaders-risk",
    difficulty: "Beginner",
    topicTags: ["business-continuity"],
    contextTags: ["internal-applications", "third-party-providers"],
    frameworks: ["DORA", "NIST ID"],
    title: "What a BIA should identify",
    situation: "The organisation is starting a business impact analysis.",
    question: "What should a BIA identify?",
    options: [
      "Critical activities, dependencies and impact of disruption.",
      "Only hardware age.",
      "Employee holiday requests.",
    ],
    correct: "a",
    guidance: "Continuity planning starts with what the business must keep delivering.",
    consequence:
      "Recovery plans are built around critical activities and their dependencies, not around equipment age alone.",
  }),
  reviewed({
    id: "lr-b06",
    roleGroup: "leaders-risk",
    difficulty: "Beginner",
    topicTags: ["ransomware", "business-continuity"],
    contextTags: ["internal-applications"],
    frameworks: ["NIST SP 800-61r3"],
    title: "Incident decision rights before an attack",
    situation: "Incident roles have not been written down.",
    question: "Why define incident decision rights before an attack?",
    options: [
      "So escalation and action do not wait for improvised authority.",
      "To avoid documenting decisions.",
      "To let everyone issue public statements.",
    ],
    correct: "a",
    guidance: "Clear authority reduces delay and conflicting actions.",
    consequence:
      "The named people can isolate, speak or spend without waiting for an ad-hoc chain of command.",
  }),
  reviewed({
    id: "lr-b07",
    roleGroup: "leaders-risk",
    difficulty: "Beginner",
    topicTags: ["business-continuity"],
    contextTags: ["internal-applications"],
    frameworks: ["DORA Art. 13"],
    title: "Who receives digital operational resilience training",
    situation: "A financial entity is planning DORA-oriented training.",
    question: "Who should receive digital operational resilience training in a financial entity?",
    options: [
      "Only penetration testers.",
      "Staff and senior management, with complexity suited to their responsibilities.",
      "Only new employees.",
    ],
    correct: "b",
    guidance: "Training should reflect the remit of the learner and include leadership.",
    consequence:
      "Leaders and staff both receive training that matches what they actually decide or operate.",
  }),
  reviewed({
    id: "lr-b08",
    roleGroup: "leaders-risk",
    difficulty: "Beginner",
    topicTags: ["business-continuity"],
    contextTags: ["third-party-providers", "saas"],
    frameworks: ["NIST GV.SC"],
    title: "Accountability for an outsourced critical service",
    situation: "A critical service is outsourced.",
    question: "Who remains accountable for the business risk?",
    options: [
      "The organisation using the service.",
      "Only the supplier.",
      "Nobody after contract signature.",
    ],
    correct: "a",
    guidance: "Contracts allocate duties but do not remove the organisation's responsibility.",
    consequence:
      "The using organisation still owns the business risk and the evidence that the supplier is managed.",
  }),
  reviewed({
    id: "lr-b09",
    roleGroup: "leaders-risk",
    difficulty: "Beginner",
    topicTags: ["data-privacy"],
    contextTags: ["internal-applications", "saas"],
    frameworks: ["GDPR Art. 32"],
    title: "What appropriate security depends on",
    situation: "Legal asks what GDPR means by appropriate security.",
    question: "What does “appropriate security” depend on?",
    options: [
      "Risk, context, state of the art and impact.",
      "One mandatory product.",
      "The cheapest available control.",
    ],
    correct: "a",
    guidance: "GDPR requires risk-appropriate technical and organisational measures.",
    consequence:
      "Controls are chosen against the actual risk and impact, not against a single product name or lowest price.",
  }),
  reviewed({
    id: "lr-b10",
    roleGroup: "leaders-risk",
    difficulty: "Beginner",
    topicTags: ["ransomware", "business-continuity"],
    contextTags: ["internal-applications"],
    frameworks: ["DORA Art. 14", "NIST RS.CO"],
    title: "What an early incident update should contain",
    situation: "Leadership needs an update while facts are still incomplete.",
    question: "What should an early incident update contain?",
    options: [
      "Confirmed facts, known impact, current action and next update time.",
      "An unverified root cause.",
      "A promise that nothing was lost.",
    ],
    correct: "a",
    guidance: "Credible communication distinguishes known facts from uncertainty.",
    consequence:
      "Stakeholders can act on what is known and expect a next update, without a premature root-cause story.",
  }),
  reviewed({
    id: "lr-b11",
    roleGroup: "leaders-risk",
    difficulty: "Beginner",
    topicTags: ["business-continuity"],
    contextTags: ["internal-applications"],
    frameworks: ["NIST GV"],
    title: "A useful metric for leadership",
    situation: "Security is preparing a leadership dashboard.",
    question: "Which metric is more useful to leadership?",
    options: [
      "Number of firewall rules.",
      "Restore success for critical services against agreed objectives.",
      "Number of security slides.",
    ],
    correct: "b",
    guidance: "Metrics should connect controls to business outcomes.",
    consequence:
      "Leaders see whether critical services can actually be restored, not how many rules or slides exist.",
  }),
  reviewed({
    id: "lr-b12",
    roleGroup: "leaders-risk",
    difficulty: "Beginner",
    topicTags: ["ransomware", "business-continuity"],
    contextTags: ["internal-applications"],
    frameworks: ["NIST RS.IM"],
    title: "What makes a post-incident review useful",
    situation: "The incident is closed and a review is being scheduled.",
    question: "What makes a post-incident review useful?",
    options: [
      "Assigned improvements with owners and follow-up.",
      "Finding one person to blame.",
      "Closing the incident without actions.",
    ],
    correct: "a",
    guidance: "Learning becomes resilience only when actions are implemented and checked.",
    consequence:
      "Named owners take improvements into the next review instead of repeating the same gap.",
  }),
  reviewed({
    id: "lr-c01",
    roleGroup: "leaders-risk",
    difficulty: "Intermediate",
    topicTags: ["business-continuity"],
    contextTags: ["internal-applications"],
    frameworks: ["DORA Ch. II"],
    title: "Policies without a link to critical services",
    situation:
      "A financial entity has many technical policies but no clear link to critical business services.",
    question: "What is missing?",
    options: [
      "A risk framework connecting functions, assets, dependencies, controls and recovery.",
      "More policy pages.",
      "A redesigned cover page.",
    ],
    correct: "a",
    guidance: "Operational resilience is organised around critical services and their dependencies.",
    consequence:
      "Controls and recovery work are tied to the services the business must keep running.",
  }),
  reviewed({
    id: "lr-c02",
    roleGroup: "leaders-risk",
    difficulty: "Intermediate",
    topicTags: ["business-continuity"],
    contextTags: ["third-party-providers"],
    frameworks: ["DORA Ch. V"],
    title: "Why map contracts for critical functions",
    situation: "Contracts sit in a procurement archive with little operational mapping.",
    question: "Why map contracts supporting critical or important functions?",
    options: [
      "To understand concentration, dependencies, obligations and exit exposure.",
      "To count suppliers for procurement.",
      "To transfer accountability to vendors.",
    ],
    correct: "a",
    guidance: "Third-party risk requires an operational view, not only a contract archive.",
    consequence:
      "Leaders can see which suppliers sit on critical paths and what exit would actually require.",
  }),
  reviewed({
    id: "lr-c03",
    roleGroup: "leaders-risk",
    difficulty: "Intermediate",
    topicTags: ["business-continuity", "cloud-security"],
    contextTags: ["saas", "third-party-providers"],
    frameworks: ["DORA Ch. V"],
    title: "Cloud exit plan with no path or test",
    situation:
      "A cloud exit plan says “migrate to another provider” but has no target, data path, skills or test.",
    question: "Is it credible?",
    options: [
      "Yes, the sentence is enough.",
      "No, the organisation needs an executable and proportionate exit capability.",
      "Yes, if the contract is long.",
    ],
    correct: "b",
    guidance:
      "An exit document is weaker than demonstrated options, dependencies and tested procedures.",
    consequence:
      "Work starts on a real path, skills and a proportionate test instead of a one-line migration sentence.",
  }),
  reviewed({
    id: "lr-c04",
    roleGroup: "leaders-risk",
    difficulty: "Intermediate",
    topicTags: ["business-continuity"],
    contextTags: ["internal-applications"],
    frameworks: ["NIS2 Art. 20-21"],
    title: "Leadership's role in cybersecurity risk measures",
    situation: "Management wants to know what NIS2 expects of them.",
    question: "What is leadership's role in cybersecurity risk measures?",
    options: [
      "Approve and oversee them and receive relevant training.",
      "Delegate all accountability permanently.",
      "Review only after an incident.",
    ],
    correct: "a",
    guidance: "NIS2 explicitly connects management bodies to approval and oversight.",
    consequence:
      "The management body approves measures, oversees them and receives training before the next incident.",
  }),
  reviewed({
    id: "lr-c05",
    roleGroup: "leaders-risk",
    difficulty: "Intermediate",
    topicTags: ["ransomware", "business-continuity"],
    contextTags: ["internal-applications"],
    frameworks: ["NIS2 Art. 23"],
    title: "Incomplete facts during a significant incident",
    situation: "Facts are incomplete during a significant incident.",
    question: "What should governance ensure?",
    options: [
      "Timely staged reporting through the defined process.",
      "Silence until the final root cause.",
      "Public attribution immediately.",
    ],
    correct: "a",
    guidance: "Reporting processes must support early warning and later updates as facts mature.",
    consequence:
      "Early notice goes through the defined process, with later updates as the picture becomes clearer.",
  }),
  reviewed({
    id: "lr-c06",
    roleGroup: "leaders-risk",
    difficulty: "Intermediate",
    topicTags: ["data-privacy", "ransomware"],
    contextTags: ["internal-applications"],
    frameworks: ["GDPR Art. 33-34"],
    title: "Who decides notification after a personal data incident",
    situation: "A personal data incident has been confirmed, but impact is still being assessed.",
    question: "Who should decide whether affected people or the authority must be notified?",
    options: [
      "A documented cross-functional assessment led by the accountable organisation.",
      "The attacker.",
      "The first employee who notices the event.",
    ],
    correct: "a",
    guidance: "Notification is a risk and legal assessment supported by technical facts.",
    consequence:
      "The organisation records a cross-functional decision instead of leaving notification to chance or the attacker.",
  }),
  reviewed({
    id: "lr-c07",
    roleGroup: "leaders-risk",
    difficulty: "Intermediate",
    topicTags: ["business-continuity", "cloud-security"],
    contextTags: ["internal-applications"],
    frameworks: ["NIST CSF Profiles"],
    title: "Identical control priorities for different units",
    situation: "Two business units have different threats and dependencies.",
    question: "Should they receive identical control priorities?",
    options: [
      "Always.",
      "Not necessarily; target profiles and risk priorities should reflect context.",
      "Neither needs controls.",
    ],
    correct: "b",
    guidance: "Framework outcomes are tailored to organisational risk rather than copied blindly.",
    consequence:
      "Investment follows each unit's threats and dependencies instead of a copied control list.",
  }),
  reviewed({
    id: "lr-c08",
    roleGroup: "leaders-risk",
    difficulty: "Intermediate",
    topicTags: ["business-continuity"],
    contextTags: ["internal-applications"],
    frameworks: ["CIS Implementation Groups"],
    title: "Value of CIS Implementation Groups",
    situation: "A paper proposes using CIS Implementation Groups.",
    question: "What is the value of CIS Implementation Groups?",
    options: [
      "They help prioritise safeguards according to risk and resources.",
      "They certify legal compliance.",
      "They eliminate the need for governance.",
    ],
    correct: "a",
    guidance: "CIS IG1 is foundational cyber hygiene; higher groups build on it for greater risk.",
    consequence:
      "The organisation uses IG as a prioritisation aid, not as a substitute for legal or governance decisions.",
  }),
  reviewed({
    id: "lr-c09",
    roleGroup: "leaders-risk",
    difficulty: "Intermediate",
    topicTags: ["business-continuity"],
    contextTags: ["internal-applications"],
    frameworks: ["DORA Ch. IV"],
    title: "No one can authorise an after-hours shutdown",
    situation:
      "A tabletop identifies that no one can authorise a customer shutdown after hours.",
    question: "What should happen?",
    options: [
      "Record, assign and retest the decision-right gap.",
      "Mark the exercise successful because discussion occurred.",
      "Remove the finding from the report.",
    ],
    correct: "a",
    guidance: "Exercises should produce owned remediation and evidence of improvement.",
    consequence:
      "A named person can authorise the shutdown, and the next exercise checks that the gap is closed.",
  }),
  reviewed({
    id: "lr-c10",
    roleGroup: "leaders-risk",
    difficulty: "Intermediate",
    topicTags: ["ai-security"],
    technologyTags: ["ai-assistants"],
    contextTags: ["internal-applications", "saas"],
    frameworks: ["NIST AI RMF"],
    title: "Claims AI pilot without harm or appeal review",
    situation:
      "A claims AI pilot performs well technically, but no one has assessed customer harm or appeal.",
    question: "Is it ready?",
    options: [
      "Yes, accuracy is sufficient.",
      "No; ownership, context, harm, measurement and management controls are incomplete.",
      "Yes, if the vendor accepts responsibility.",
    ],
    correct: "b",
    guidance: "AI risk includes impacts on people and processes, not only model performance.",
    consequence:
      "The pilot stays limited until harm, appeal and ownership are defined, regardless of vendor assurances.",
  }),
  reviewed({
    id: "lr-c11",
    roleGroup: "leaders-risk",
    difficulty: "Intermediate",
    topicTags: ["business-continuity", "cloud-security"],
    contextTags: ["saas", "third-party-providers"],
    frameworks: ["DORA", "NIST GV.SC"],
    title: "Several services depend on one identity platform",
    situation: "Several critical services depend on the same cloud identity platform.",
    question: "What should leadership ask?",
    options: [
      "How failure affects services, what alternatives exist and how recovery is tested.",
      "Whether the provider is popular.",
      "Whether each contract uses a different template.",
    ],
    correct: "a",
    guidance: "Concentration risk concerns shared failure paths and realistic resilience options.",
    consequence:
      "Leaders see the shared failure path, alternatives and tested recovery instead of treating popularity as resilience.",
  }),
  reviewed({
    id: "lr-c12",
    roleGroup: "leaders-risk",
    difficulty: "Intermediate",
    topicTags: ["business-continuity"],
    contextTags: ["internal-applications"],
    frameworks: ["NIST GV"],
    title: "Which cyber report supports a decision",
    situation: "The board pack currently lists every alert.",
    question: "Which cyber report best supports a decision?",
    options: [
      "A list of every alert.",
      "Critical service exposure, trend, control evidence, scenarios, decisions required and residual risk.",
      "A single unexplained score.",
    ],
    correct: "b",
    guidance: "Leadership needs evidence and decision context, not dashboard theatre.",
    consequence:
      "The next board paper asks for a decision against exposure, evidence and residual risk, not a unexplained number.",
  }),
];
