import { reviewed } from "@/lib/training/reviewed/define";
import type { ReviewedQuestion } from "@/lib/training/reviewed/types";

export const MICROSOFT_365_QUESTIONS: readonly ReviewedQuestion[] = [
  reviewed({
    id: "m365-ge-b01",
    roleGroup: "general-employees",
    difficulty: "Beginner",
    topicTags: ["phishing"],
    technologyTags: ["microsoft-365"],
    contextTags: ["saas"],
    frameworks: ["CIS 6"],
    title: "Unexpected Outlook sign-in",
    situation: "Outlook warns that a new sign-in occurred from another country.",
    question: "What should you do?",
    options: [
      "Use the official security page and report unexpected activity.",
      "Reply to the warning email with your password.",
      "Ignore it if Outlook still opens.",
    ],
    correct: "a",
    guidance: "Unexpected sign-ins can indicate account compromise even when normal access still works.",
    consequence:
      "The official security page and a report let IT revoke the extra session before mail or files are used.",
  }),
  reviewed({
    id: "m365-ge-b02",
    roleGroup: "general-employees",
    difficulty: "Beginner",
    topicTags: ["phishing"],
    technologyTags: ["microsoft-365"],
    contextTags: ["saas"],
    frameworks: ["CIS 14"],
    title: "Unusual Teams file request",
    situation: "A familiar colleague asks in Teams for a restricted file, but the wording is unusual.",
    question: "What is the safest first step?",
    options: [
      "Verify through a known channel before sharing.",
      "Share because Teams is internal.",
      "Create an anonymous OneDrive link.",
    ],
    correct: "a",
    guidance: "A trusted platform does not prove the account or request is genuine.",
    consequence:
      "A known channel confirms the request before a hijacked Teams account receives the restricted file.",
  }),
  reviewed({
    id: "m365-ge-b03",
    roleGroup: "general-employees",
    difficulty: "Beginner",
    topicTags: ["data-privacy"],
    technologyTags: ["microsoft-365"],
    contextTags: ["saas"],
    frameworks: ["CIS 3", "GDPR Art. 5"],
    title: "OneDrive sharing with one colleague",
    situation: "You need to share a customer document with one named colleague.",
    question: "Which setting is appropriate?",
    options: [
      "Specific people with only required permissions.",
      "Anyone with the link.",
      "Public access until tomorrow.",
    ],
    correct: "a",
    guidance: "Use the narrowest recipient and permission scope that supports the task.",
    consequence:
      "Only the named colleague can open the file, and the link cannot be forwarded as an open share.",
  }),
  reviewed({
    id: "m365-ge-b04",
    roleGroup: "general-employees",
    difficulty: "Beginner",
    topicTags: ["phishing"],
    technologyTags: ["microsoft-365"],
    contextTags: ["saas"],
    frameworks: ["CIS 6"],
    title: "Unsolicited Authenticator prompt",
    situation: "You receive an approval request you did not initiate.",
    question: "What should you do?",
    options: [
      "Deny it and report the event.",
      "Approve it to stop notifications.",
      "Send a screenshot to a public channel.",
    ],
    correct: "a",
    guidance: "An unsolicited MFA prompt can mean an attacker already knows the password.",
    consequence:
      "The sign-in is denied and security can reset the account before the attacker gets a session.",
  }),
  reviewed({
    id: "m365-ge-c01",
    roleGroup: "general-employees",
    difficulty: "Intermediate",
    topicTags: ["phishing"],
    technologyTags: ["microsoft-365"],
    contextTags: ["saas", "third-party-providers"],
    frameworks: ["CIS 14"],
    title: "Real thread with changed payment details",
    situation: "A supplier replies inside a genuine Outlook conversation with new bank details.",
    question: "What should happen?",
    options: [
      "Verify through an independently known contact method.",
      "Trust the existing thread.",
      "Ask for confirmation in the same potentially compromised mailbox.",
    ],
    correct: "a",
    guidance: "Mailbox compromise can produce convincing messages inside authentic threads.",
    consequence:
      "Payment details are confirmed outside the thread, so funds are not sent to an attacker-controlled account.",
  }),
  reviewed({
    id: "m365-ge-c02",
    roleGroup: "general-employees",
    difficulty: "Intermediate",
    topicTags: ["data-privacy"],
    technologyTags: ["microsoft-365"],
    contextTags: ["saas", "third-party-providers"],
    frameworks: ["CIS 6"],
    title: "External Teams guest after assignment ends",
    situation: "An external guest remains in a project Team after their assignment ends.",
    question: "What should you do before posting sensitive material?",
    options: [
      "Confirm current authorisation and request access removal if no longer needed.",
      "Assume membership is permanent approval.",
      "Hide the file name only.",
    ],
    correct: "a",
    guidance: "Guest access and business need must be reviewed over time.",
    consequence:
      "The guest is removed if the work has ended, so later posts do not keep reaching an old contractor.",
  }),
  reviewed({
    id: "m365-ge-c03",
    roleGroup: "general-employees",
    difficulty: "Intermediate",
    topicTags: ["data-privacy"],
    technologyTags: ["microsoft-365"],
    contextTags: ["saas"],
    frameworks: ["GDPR Art. 5"],
    title: "Restricted OneDrive link sent to the wrong person",
    situation: "A restricted link was sent to the wrong person but has not been opened.",
    question: "What should you do first?",
    options: [
      "Revoke the link and report the disclosure.",
      "Delete your sent email only.",
      "Wait to see whether it is opened.",
    ],
    correct: "a",
    guidance: "Remove access promptly and let the organisation assess exposure.",
    consequence:
      "The link stops working immediately, and privacy can judge whether further action is required.",
  }),
  reviewed({
    id: "m365-ge-c04",
    roleGroup: "general-employees",
    difficulty: "Intermediate",
    topicTags: ["ai-security", "data-privacy"],
    technologyTags: ["microsoft-365", "ai-assistants"],
    contextTags: ["saas"],
    frameworks: ["NIST AI RMF"],
    title: "Copilot summary of sensitive customer data",
    situation:
      "You want Microsoft 365 Copilot to summarise a document containing sensitive customer data.",
    question: "What should you check?",
    options: [
      "Whether the use, permissions and data handling are approved.",
      "Whether the prompt is short.",
      "Whether Copilot gives a confident answer.",
    ],
    correct: "a",
    guidance: "AI access follows the user's permissions and can amplify existing oversharing.",
    consequence:
      "Copilot is only used if the document and the task are approved, so extra discovery of overshared files is avoided.",
  }),
  reviewed({
    id: "m365-fh-b01",
    roleGroup: "finance-hr",
    difficulty: "Beginner",
    topicTags: ["data-privacy"],
    technologyTags: ["microsoft-365"],
    contextTags: ["saas"],
    frameworks: ["CIS 3"],
    title: "Payroll workbook in SharePoint",
    situation: "HR needs a home for a payroll workbook.",
    question: "Where should a payroll workbook be stored?",
    options: [
      "An approved restricted SharePoint site.",
      "A public Teams channel.",
      "A personal OneDrive account.",
    ],
    correct: "a",
    guidance: "Salary data needs approved storage and limited access.",
    consequence:
      "Payroll stays in a restricted site instead of a public channel or personal account.",
  }),
  reviewed({
    id: "m365-fh-b02",
    roleGroup: "finance-hr",
    difficulty: "Beginner",
    topicTags: ["data-privacy"],
    technologyTags: ["microsoft-365"],
    contextTags: ["saas"],
    frameworks: ["GDPR Art. 5"],
    title: "Power BI export of individual salaries",
    situation: "A report shows individual salaries.",
    question: "What should be checked before exporting?",
    options: [
      "Whether the recipient needs row-level personal data.",
      "Whether Excel is installed.",
      "Whether the chart has a legend.",
    ],
    correct: "a",
    guidance: "Permission to view a report does not automatically justify redistribution.",
    consequence:
      "The export only happens if the recipient needs the underlying rows, so extra salary files are not created.",
  }),
  reviewed({
    id: "m365-fh-b03",
    roleGroup: "finance-hr",
    difficulty: "Beginner",
    topicTags: ["phishing"],
    technologyTags: ["microsoft-365"],
    contextTags: ["saas"],
    frameworks: ["CIS 14"],
    title: "Director gift-card request in Outlook",
    situation: "A director urgently asks Finance to buy gift cards.",
    question: "What should Finance do?",
    options: [
      "Follow the normal verification and approval process.",
      "Skip controls because the request is urgent.",
      "Pay privately and claim later.",
    ],
    correct: "a",
    guidance: "Seniority and urgency are common business-email-compromise tactics.",
    consequence:
      "Verification either confirms a genuine request or stops a fraudulent payment.",
  }),
  reviewed({
    id: "m365-fh-b04",
    roleGroup: "finance-hr",
    difficulty: "Beginner",
    topicTags: ["data-privacy"],
    technologyTags: ["microsoft-365"],
    contextTags: ["saas"],
    frameworks: ["CIS 14", "GDPR Art. 5"],
    title: "Medical note requested in a broad Team",
    situation: "A manager asks HR to post an employee medical note in a broad Team.",
    question: "What is appropriate?",
    options: [
      "Use the restricted HR process and verify the need.",
      "Post it because the manager requested it.",
      "Send a screenshot with the name cropped.",
    ],
    correct: "a",
    guidance: "Health information requires a clear purpose and tightly controlled handling.",
    consequence:
      "The note stays in the restricted HR process instead of a Team that many people can search later.",
  }),
  reviewed({
    id: "m365-fh-c01",
    roleGroup: "finance-hr",
    difficulty: "Intermediate",
    topicTags: ["data-privacy"],
    technologyTags: ["microsoft-365"],
    contextTags: ["saas"],
    frameworks: ["CIS 3"],
    title: "Purview DLP blocks a payroll transfer",
    situation: "DLP blocks a legitimate payroll transfer.",
    question: "What should happen?",
    options: [
      "Use the documented exception process and review why the rule triggered.",
      "Disable DLP for the tenant.",
      "Rename the file to bypass detection.",
    ],
    correct: "a",
    guidance: "Controlled exceptions enable work without removing protection for everyone.",
    consequence:
      "Payroll proceeds through an approved exception, and the rule can be reviewed without turning DLP off.",
  }),
  reviewed({
    id: "m365-fh-c02",
    roleGroup: "finance-hr",
    difficulty: "Intermediate",
    topicTags: ["data-privacy"],
    technologyTags: ["microsoft-365"],
    contextTags: ["saas"],
    frameworks: ["CIS 6", "GDPR Art. 32"],
    title: "Payroll folder inherits broad parent access",
    situation: "A payroll folder inherits access from a broad parent site.",
    question: "What is the best response?",
    options: [
      "Redesign permissions and test effective access.",
      "Hide the folder from navigation.",
      "Rely on employees not to open it.",
    ],
    correct: "a",
    guidance: "Security depends on effective permissions, not whether a link is visible.",
    consequence:
      "Effective access is tested so people who should not see payroll cannot open it by browsing the parent site.",
  }),
  reviewed({
    id: "m365-fh-c03",
    roleGroup: "finance-hr",
    difficulty: "Intermediate",
    topicTags: ["data-privacy"],
    technologyTags: ["microsoft-365"],
    contextTags: ["saas"],
    frameworks: ["CIS 6"],
    title: "Power BI row-level security for regional managers",
    situation: "Regional managers need metrics but should only see their own employees.",
    question: "What is the better design?",
    options: [
      "Tested row-level security tied to managed identities/groups.",
      "One unrestricted report.",
      "Weekly manual exports.",
    ],
    correct: "a",
    guidance: "Enforce access in the data product and verify role assignments.",
    consequence:
      "Each manager's view is enforced in the report and tested, instead of depending on weekly manual files.",
  }),
  reviewed({
    id: "m365-fh-c04",
    roleGroup: "finance-hr",
    difficulty: "Intermediate",
    topicTags: ["phishing", "data-privacy"],
    technologyTags: ["microsoft-365"],
    contextTags: ["saas"],
    frameworks: ["NIST SP 800-61r3"],
    title: "Suspicious forwarding rules after a fraudulent request",
    situation: "Suspicious forwarding rules appear after a fraudulent request.",
    question: "What should the response combine?",
    options: [
      "Account containment, evidence preservation and assessment of exposed HR data.",
      "Delete the rules and close the case.",
      "Send a warning from the compromised account.",
    ],
    correct: "a",
    guidance: "Mail rules can support persistence and data theft beyond the initial message.",
    consequence:
      "The account is contained, rules are kept as evidence, and HR can see what data may have left.",
  }),
  reviewed({
    id: "m365-it-b01",
    roleGroup: "it-security",
    difficulty: "Beginner",
    topicTags: ["phishing"],
    technologyTags: ["microsoft-365"],
    contextTags: ["saas"],
    frameworks: ["CIS 6"],
    title: "Entra risky sign-in with MFA prompts",
    situation: "A user reports MFA prompts and Entra shows an unfamiliar sign-in.",
    question: "What should IT do?",
    options: [
      "Investigate and follow the account-compromise playbook.",
      "Disable all tenant logging.",
      "Change only the display name.",
    ],
    correct: "a",
    guidance: "Identity evidence should drive session revocation, credential reset and scoping.",
    consequence:
      "Sessions are revoked and the account is scoped using Entra evidence, not a cosmetic name change.",
  }),
  reviewed({
    id: "m365-it-b02",
    roleGroup: "it-security",
    difficulty: "Beginner",
    topicTags: ["phishing"],
    technologyTags: ["microsoft-365"],
    contextTags: ["saas"],
    frameworks: ["CIS 10"],
    title: "Defender for Office 365 malicious link",
    situation: "A malicious link was delivered to several inboxes.",
    question: "What should responders do?",
    options: [
      "Investigate recipients, remove the message where possible and assess clicks.",
      "Block the sender name only.",
      "Ask users to delete it manually without tracking.",
    ],
    correct: "a",
    guidance: "Containment and exposure assessment must cover every recipient.",
    consequence:
      "The message is removed where possible, and clicks are checked instead of hoping users tidy their own inboxes.",
  }),
  reviewed({
    id: "m365-it-b03",
    roleGroup: "it-security",
    difficulty: "Beginner",
    topicTags: ["cloud-security", "data-privacy"],
    technologyTags: ["microsoft-365"],
    contextTags: ["saas"],
    frameworks: ["CIS 6"],
    title: "Unmanaged device accessing SharePoint",
    situation: "An unmanaged device attempts to access sensitive SharePoint data.",
    question: "What should enforce the organisation's rule?",
    options: [
      "Conditional Access with the approved device/session requirements.",
      "The user's judgement alone.",
      "A shared password.",
    ],
    correct: "a",
    guidance: "Access decisions should combine identity, device and risk signals.",
    consequence:
      "The unmanaged device is blocked or limited by policy instead of relying on the user to refuse it.",
  }),
  reviewed({
    id: "m365-it-b04",
    roleGroup: "it-security",
    difficulty: "Beginner",
    topicTags: ["phishing", "cloud-security"],
    technologyTags: ["microsoft-365"],
    contextTags: ["saas"],
    frameworks: ["CIS 5", "CIS 6"],
    title: "Occasional user administration for the service desk",
    situation: "A service-desk employee needs occasional user administration.",
    question: "What is preferable?",
    options: [
      "Time-limited, scoped privileged access.",
      "Permanent Global Administrator.",
      "The root password in a vault shared by the team.",
    ],
    correct: "a",
    guidance: "Limit both the scope and duration of privileged access.",
    consequence:
      "The service desk can complete the task without holding standing Global Administrator rights.",
  }),
  reviewed({
    id: "m365-it-c01",
    roleGroup: "it-security",
    difficulty: "Intermediate",
    topicTags: ["phishing"],
    technologyTags: ["microsoft-365"],
    contextTags: ["saas"],
    frameworks: ["CIS 6"],
    title: "Password reset after possible token theft",
    situation:
      "A user's password was reset, but an attacker may hold a valid Microsoft 365 session token.",
    question: "What else is required?",
    options: [
      "Revoke sessions and investigate token/session activity.",
      "Wait for the token to disappear.",
      "Rename the mailbox.",
    ],
    correct: "a",
    guidance: "Password changes alone may not terminate existing sessions.",
    consequence:
      "Existing sessions are revoked, so a stolen token cannot keep reading mail after the password change.",
  }),
  reviewed({
    id: "m365-it-c02",
    roleGroup: "it-security",
    difficulty: "Intermediate",
    topicTags: ["phishing", "cloud-security"],
    technologyTags: ["microsoft-365"],
    contextTags: ["saas", "third-party-providers"],
    frameworks: ["CIS 6"],
    title: "Unknown OAuth app reading mail",
    situation: "An unknown app has permission to read mail for several users.",
    question: "What should IT assess?",
    options: [
      "Consent source, permissions, affected users, activity and required revocation.",
      "Only the app logo.",
      "Whether the app has a website.",
    ],
    correct: "a",
    guidance: "Malicious OAuth consent can provide durable access without a password.",
    consequence:
      "The app is revoked if it is not legitimate, and affected mailboxes are scoped from consent and activity evidence.",
  }),
  reviewed({
    id: "m365-it-c03",
    roleGroup: "it-security",
    difficulty: "Intermediate",
    topicTags: ["data-privacy"],
    technologyTags: ["microsoft-365"],
    contextTags: ["saas"],
    frameworks: ["CIS 8", "GDPR Art. 32"],
    title: "Sensitive data shared across Teams, SharePoint and email",
    situation: "Sensitive data may have been shared through Teams, SharePoint and email.",
    question: "What is needed?",
    options: [
      "Correlated audit and data-protection evidence across the services.",
      "Only endpoint antivirus logs.",
      "Only the user's memory.",
    ],
    correct: "a",
    guidance: "Microsoft 365 incidents often cross multiple collaboration services.",
    consequence:
      "The investigation can see where the data moved, instead of stopping at one service or a recollection.",
  }),
  reviewed({
    id: "m365-it-c04",
    roleGroup: "it-security",
    difficulty: "Intermediate",
    topicTags: ["cloud-security", "business-continuity"],
    technologyTags: ["microsoft-365"],
    contextTags: ["saas"],
    frameworks: ["CIS 5", "CIS 6"],
    title: "Break-glass emergency access accounts",
    situation: "The tenant's privileged access process could fail.",
    question: "Why maintain tightly controlled emergency access accounts?",
    options: [
      "To recover administrative access when normal identity controls fail.",
      "For daily administrator convenience.",
      "To avoid monitoring privileged use.",
    ],
    correct: "a",
    guidance: "Emergency accounts need strong protection, monitoring and regular validation.",
    consequence:
      "Administrators can still recover the tenant in a control failure, without using break-glass accounts every day.",
  }),
  reviewed({
    id: "m365-lr-b01",
    roleGroup: "leaders-risk",
    difficulty: "Beginner",
    topicTags: ["data-privacy", "business-continuity"],
    technologyTags: ["microsoft-365"],
    contextTags: ["saas"],
    frameworks: ["NIST GV"],
    title: "Who decides which Teams areas hold sensitive data",
    situation: "New Teams and SharePoint areas are being created across the business.",
    question: "Who should decide which Teams and SharePoint areas contain sensitive data?",
    options: [
      "Accountable business owners supported by IT and security.",
      "Microsoft alone.",
      "The newest employee.",
    ],
    correct: "a",
    guidance: "Technology controls require business ownership and classification.",
    consequence:
      "Each area has a business owner who can classify it, with IT and security supporting the controls.",
  }),
  reviewed({
    id: "m365-lr-b02",
    roleGroup: "leaders-risk",
    difficulty: "Beginner",
    topicTags: ["data-privacy", "business-continuity"],
    technologyTags: ["microsoft-365"],
    contextTags: ["saas", "third-party-providers"],
    frameworks: ["NIST GV.SC", "CIS 3"],
    title: "Broad external collaboration on Microsoft 365",
    situation: "Leadership wants broad external collaboration enabled.",
    question: "What should accompany the decision?",
    options: [
      "Risk-based sharing rules, ownership, review and monitoring.",
      "Anonymous links everywhere.",
      "No expiry or review.",
    ],
    correct: "a",
    guidance: "Collaboration benefits require governed access and lifecycle controls.",
    consequence:
      "External sharing is possible under owned rules, review and monitoring instead of permanent anonymous links.",
  }),
  reviewed({
    id: "m365-lr-b03",
    roleGroup: "leaders-risk",
    difficulty: "Beginner",
    topicTags: ["business-continuity"],
    technologyTags: ["microsoft-365"],
    contextTags: ["saas"],
    frameworks: ["DORA Art. 14", "NIST RS.CO"],
    title: "Tenant-wide outage affecting customer service",
    situation: "A tenant-wide outage affects customer service.",
    question: "What should an early update contain?",
    options: [
      "Known impact, current actions, uncertainty and next update time.",
      "An unverified root cause.",
      "A promise that no data is affected.",
    ],
    correct: "a",
    guidance: "Credible updates separate confirmed facts from assumptions.",
    consequence:
      "Customer-service leaders can plan around known impact and a next update time without a guessed root cause.",
  }),
  reviewed({
    id: "m365-lr-b04",
    roleGroup: "leaders-risk",
    difficulty: "Beginner",
    topicTags: ["business-continuity", "cloud-security"],
    technologyTags: ["microsoft-365"],
    contextTags: ["saas"],
    frameworks: ["NIST GV"],
    title: "Does a high Secure Score prove compliance",
    situation: "A dashboard shows a high Microsoft Secure Score.",
    question: "Does a high Microsoft Secure Score prove compliance?",
    options: [
      "No, it is useful posture evidence but not complete assurance.",
      "Yes, it certifies every regulation.",
      "Yes, it replaces risk assessment.",
    ],
    correct: "a",
    guidance: "Product scores must be interpreted within organisational scope and risk.",
    consequence:
      "The score is used as posture evidence alongside risk assessment, not as a compliance certificate.",
  }),
  reviewed({
    id: "m365-lr-c01",
    roleGroup: "leaders-risk",
    difficulty: "Intermediate",
    topicTags: ["business-continuity", "cloud-security"],
    technologyTags: ["microsoft-365"],
    contextTags: ["saas", "third-party-providers"],
    frameworks: ["DORA Ch. V", "NIST GV.SC"],
    title: "Email, files and identity all on Microsoft 365",
    situation: "Email, files, identity and collaboration all depend on Microsoft 365.",
    question: "What should leadership assess?",
    options: [
      "Shared failure paths, recovery procedures, alternative communications and residual risk.",
      "Only licence price.",
      "Only mailbox size.",
    ],
    correct: "a",
    guidance: "One platform can create correlated operational dependencies.",
    consequence:
      "Leaders know how a tenant failure would hit services, what communications remain, and what risk they accept.",
  }),
  reviewed({
    id: "m365-lr-c02",
    roleGroup: "leaders-risk",
    difficulty: "Intermediate",
    topicTags: ["ai-security", "data-privacy"],
    technologyTags: ["microsoft-365", "ai-assistants"],
    contextTags: ["saas"],
    frameworks: ["NIST AI RMF"],
    title: "Copilot rollout before SharePoint access review",
    situation: "A Copilot rollout is proposed before SharePoint access has been reviewed.",
    question: "What is the main concern?",
    options: [
      "AI may surface information users can technically access but should not broadly discover.",
      "Copilot will change every file.",
      "Prompts are always public.",
    ],
    correct: "a",
    guidance: "AI can magnify existing permission and classification weaknesses.",
    consequence:
      "Access is reviewed before Copilot is switched on, so overshared sites are not easier to discover.",
  }),
  reviewed({
    id: "m365-lr-c03",
    roleGroup: "leaders-risk",
    difficulty: "Intermediate",
    topicTags: ["data-privacy", "business-continuity"],
    technologyTags: ["microsoft-365"],
    contextTags: ["saas"],
    frameworks: ["GDPR Art. 5", "NIST GV"],
    title: "Conflicting Microsoft 365 retention periods",
    situation: "Legal, HR and business teams request different Microsoft 365 retention periods.",
    question: "What is needed?",
    options: [
      "Documented ownership and rules based on purpose, law and business requirements.",
      "Keep everything forever.",
      "Let each user decide.",
    ],
    correct: "a",
    guidance: "Retention is a governed information-lifecycle decision.",
    consequence:
      "Retention rules have owners and a legal/business basis, instead of every mailbox keeping everything.",
  }),
  reviewed({
    id: "m365-lr-c04",
    roleGroup: "leaders-risk",
    difficulty: "Intermediate",
    topicTags: ["business-continuity"],
    technologyTags: ["microsoft-365"],
    contextTags: ["saas", "third-party-providers"],
    frameworks: ["DORA Ch. V"],
    title: "Microsoft 365 supporting a critical financial process",
    situation: "Microsoft 365 supports a critical financial process.",
    question: "What should DORA-oriented governance maintain?",
    options: [
      "Dependency records, contractual obligations, incident routes, continuity assumptions and exit considerations.",
      "Only the purchase order.",
      "A generic vendor brochure.",
    ],
    correct: "a",
    guidance: "Critical ICT dependencies need operational and contractual oversight.",
    consequence:
      "The register shows how the financial process depends on Microsoft 365, who to call, and what exit would mean.",
  }),
];
