import { option, question, scoreTriple } from "../build";
import type { AnswerOption, AnswerQuality, Question, ScorePoints, StoryPhase } from "../types";

const ALL = ["lo-campus", "lo-warehouse", "lo-friday"] as const;
const KEYS = ["containment", "operations", "trust"] as const;

function pts(
  a: ScorePoints,
  b: ScorePoints,
  c: ScorePoints,
): Record<string, ScorePoints> {
  return scoreTriple(a, b, c, KEYS);
}

function o(
  id: string,
  quality: AnswerQuality,
  title: string,
  summary: string,
  scores: [ScorePoints, ScorePoints, ScorePoints],
  consequence: string,
  explanation: string,
  recommendedAction: string,
  whyRecommended: string,
  learningPoint: string,
  npcReaction: string,
): AnswerOption {
  return option(
    id,
    quality,
    title,
    summary,
    pts(...scores),
    consequence,
    explanation,
    recommendedAction,
    whyRecommended,
    learningPoint,
    npcReaction,
  );
}

function q(
  id: string,
  phase: StoryPhase,
  title: string,
  situation: string,
  npcLine: string,
  frameworks: readonly string[],
  options: readonly [AnswerOption, AnswerOption, AnswerOption],
  scenarioIds: readonly string[] = ALL,
): Question {
  return question("locked-out", id, phase, scenarioIds, title, situation, npcLine, frameworks, options);
}

const rec = "Name a coordinator, freeze routine changes, and contain with evidence in mind.";

export const LOCKED_OUT_QUESTIONS: Question[] = [
  q("lo-01", "start", "Screens go dark",
    "Reception phones light up. Warehouse PCs show a yellow lock banner. Someone asks if we tried turning the ransomware off and on again.",
    "Have you tried turning the ransomware off and on again?",
    ["NIST CSF Detect", "DORA Art. 17"],
    [
      o("lo-01-a", "weak", "Reboot the estate", "If it worked on my machine, it should work in the warehouse.", [1, 1, 1], "Reboots spread the lock and wipe useful logs.", "A reboot is not an incident plan.", rec, "A named lead beats a hallway reboot.", "First minutes are for orientation, not DIY restarts.", "The intern is already holding the power strip."),
      o("lo-01-b", "high-risk", "Wait quietly for IT", "No need to scare people on a busy morning.", [0, 0, 0], "Encryption continues while you wait.", "Silence is not a control.", rec, "Early coordination limits spread.", "Delay is a decision.", "Sales has started a rumour spreadsheet."),
      o("lo-01-c", "strong", "Open the incident channel", "Freeze changes. Name a coordinator. Stop 'just checking' admin tools.", [3, 2, 3], "People stop improvising. Evidence stays put.", "A named incident lead beats a hallway rumour.", rec, "This is the baseline for the next seven decisions.", "Command first, then technical moves.", "The megaphone intern sits down. Mostly."),
    ]),
  q("lo-02", "start", "The Excel from 'Finance'",
    "An intern swears the first lock followed Invoice_FINAL(2).xlsm from a mailbox that almost looks like finance.",
    "It had macros. Macros are basically documentation.",
    ["NIST CSF Identify"],
    [
      o("lo-02-a", "strong", "Sandbox the sample", "Copy it to an isolated box. Keep the original.", [3, 2, 2], "You get a sample without feeding production.", "Malware analysis needs a sandbox, not a laptop.", "Preserve the file, block the hash, treat the mailbox as a lead.", "You learn without multiplying the problem.", "Office files are still a common foothold.", "Finance would like it known they do not send sequels."),
      o("lo-02-b", "high-risk", "Forward it as a warning", "If they see the name they will not click it.", [0, 1, 1], "You mailed the payload to more inboxes.", "Do not redistribute live malware as awareness training.", "Preserve the file, block the hash, treat the mailbox as a lead.", "A hash block is safer than a viral warning.", "Awareness is not an attachment.", "The intern has 40 new replies."),
      o("lo-02-c", "defensible", "Block every xlsm for now", "Excel is cancelled until further notice.", [2, 1, 1], "Some risk drops. Legitimate macros freeze.", "Broad blocks buy time if you name the blast radius.", "Preserve the file, block the hash, treat the mailbox as a lead.", "A targeted sample plus a temporary block is cleaner.", "Temporary blocks need owners and an expiry.", "Accounting is using paper. They are not fine."),
    ]),
  q("lo-03", "start", "Friday 16:40 deploy",
    "A developer admits they pushed a tiny change at 16:40 because the change window is a social construct. The banner arrived twenty minutes later.",
    "It was a YOLO deployment. Tiny. Harmless. Ish.",
    ["NIST CSF Protect", "DORA"],
    [
      o("lo-03-a", "defensible", "Roll it back now", "Undo the change and hope the banner vanishes.", [2, 2, 1], "Rollback may help or just add noise.", "Correlate before you thrash production.", "Freeze deploys and snapshot the change record.", "You want the artefact, not just the undo.", "Friday deploys collide badly with incident clocks.", "The pipeline is already packing a sequel."),
      o("lo-03-b", "strong", "Freeze and snapshot", "Keep the artefact. Do not keep shipping.", [3, 3, 2], "You have a timeline without extra blast radius.", "Change freeze is a containment tool.", "Freeze deploys and snapshot the change record.", "This keeps options open.", "Incidents are not a release train.", "Release captain has been offered a chair."),
      o("lo-03-c", "high-risk", "YOLO deployment, part two", "Ship the hotfix for the hotfix. Momentum.", [0, 0, 0], "You mix attacker activity with your own chaos.", "Do not debug ransomware with more deploys.", "Freeze deploys and snapshot the change record.", "Stop adding variables.", "More change hides the plot.", "Someone named the branch `fix-fix-final`."),
    ],
    ["lo-friday"]),
  q("lo-04", "start", "Admin for everyone",
    "Warehouse supervisors have local admin because printers. One of those accounts is still signed in on a locked PC.",
    "The printers only listen to administrators. And threats.",
    ["least privilege"],
    [
      o("lo-04-a", "high-risk", "Leave admin so they can fix PCs", "They know the printers better than IT.", [0, 1, 0], "Privileged malware loves helpful supervisors.", "Local admin is not customer service.", "Revoke standing admin and keep a break-glass path.", "Cut default admin without stranding responders.", "Standing admin turns one PC into a campus tour.", "A supervisor is installing 'helper tools'."),
      o("lo-04-b", "strong", "Revoke standing admin", "Keep a documented break-glass path.", [3, 2, 2], "Lateral movement slows.", "Least privilege still needs an emergency hatch.", "Revoke standing admin and keep a break-glass path.", "This is the privilege baseline.", "Printers do not need domain admin.", "The printer still prints. A miracle."),
      o("lo-04-c", "weak", "Reset every password", "New sticky notes for everyone.", [1, 0, 1], "You cause an outage and miss live sessions.", "Password spray is not session kill.", "Revoke standing admin and keep a break-glass path.", "Kill sessions, then rotate.", "Identity moves need targeting.", "The sticky-note budget is in ruins."),
    ]),
  q("lo-05", "assess", "What is actually down?",
    "Ops wants a map. Some scanners work. Billing does not. Someone has drawn the outage on a napkin.",
    "The napkin is our CMDB now.",
    ["NIST CSF Detect", "DORA"],
    [
      o("lo-05-a", "weak", "Assume the whole campus is lost", "Pull every plug you can reach.", [1, 0, 1], "Healthy work stops. The real island is still fuzzy.", "Over-containment is still a decision.", "Inventory affected versus working services with owners.", "Name what still moves goods.", "You cannot contain what you have not named.", "Someone unplugged the coffee machine. Morale drops."),
      o("lo-05-b", "strong", "Inventory affected vs working", "Name owners. Mark what still ships.", [3, 3, 2], "Decisions get a shared picture.", "Impact mapping is incident hygiene.", "Inventory affected versus working services with owners.", "Shared pictures beat heroic guesses.", "Scope before spectacle.", "The napkin is photocopied, officially."),
      o("lo-05-c", "high-risk", "Trust the green ERP dashboard", "If the dashboard is green, we are fine.", [0, 1, 0], "Warehouse PCs keep dying off-dashboard.", "Dashboards lie when agents are dead.", "Inventory affected versus working services with owners.", "Look at the floor, not only the chart.", "Telemetry gaps are findings.", "The dashboard is extremely proud of itself."),
    ]),
  q("lo-06", "assess", "The lucky scanner",
    "One handheld scanner keeps working on a guest VLAN nobody documented. A picker calls it the lucky gun.",
    "Do not look a gift barcode in the mouth.",
    ["network segmentation"],
    [
      o("lo-06-a", "high-risk", "Ignore it — lucky is lucky", "Let it keep beeping.", [0, 2, 0], "An unmanaged path stays in play.", "Undocumented connectivity is a finding.", "Document, restrict, and watch the path.", "Lifelines still need owners.", "Shadow networks survive incidents for a reason.", "The lucky gun has a fan club."),
      o("lo-06-b", "strong", "Document, restrict, keep it watched", "Allowlist the path. Give it an expiry.", [2, 3, 2], "Ops keeps a trickle of work under watch.", "Temporary exceptions need owners.", "Document, restrict, and watch the path.", "This balances ops and containment.", "Exceptions are controls when they expire.", "Someone finally draws the mystery VLAN."),
      o("lo-06-c", "defensible", "Smash the lucky gun", "If we cannot explain it, it dies.", [3, 1, 1], "You close a hole and a workaround.", "Containment can be blunt if you accept the ops hit.", "Document, restrict, and watch the path.", "A watched exception is usually kinder.", "Blunt isolation has a cost. Name it.", "The picker is in mourning."),
    ],
    ["lo-warehouse", "lo-campus"]),
  q("lo-07", "assess", "Logs or legends",
    "The SIEM is missing an hour. A contractor says the collector gets moody. Nobody has the last backup time written down.",
    "The collector is an artist.",
    ["evidence preservation"],
    [
      o("lo-07-a", "strong", "Keep capturing, note the gap", "Snapshot collectors. Write the missing hour on the board.", [2, 2, 3], "You can still reconstruct a partial timeline.", "A documented gap is better than a silent one.", "Preserve what you have and stop overwriting disks.", "Evidence likes honesty.", "Forgotten backups are how stories replace evidence.", "The board now has a sad little blank box."),
      o("lo-07-b", "high-risk", "Factory-reset the SIEM", "Have you tried turning logging off and on again?", [0, 0, 0], "You delete the remaining breadcrumb trail.", "Do not wash the crime scene.", "Preserve what you have and stop overwriting disks.", "Moodiness is not a restore button.", "Collectors are evidence stores.", "The contractor looks strangely refreshed."),
      o("lo-07-c", "weak", "Rely on people's memories", "The intern saw a popup. That is basically a log.", [1, 1, 1], "Memory does not survive a regulator.", "Anecdotes are not telemetry.", "Preserve what you have and stop overwriting disks.", "Write what you can still prove.", "Human recall is a perishable control.", "Three people remember three popups."),
    ]),
  q("lo-08", "assess", "Who is in charge?",
    "IT, security, warehouse, and a confident intern all think they are running the call. The intern has a megaphone.",
    "I brought slides.",
    ["NIST CSF Respond", "DORA"],
    [
      o("lo-08-a", "high-risk", "Let the loudest voice win", "Momentum looks like leadership.", [0, 0, 0], "Contradictory orders hit the floor.", "Authority needs a name, not volume.", "Appoint a commander and a scribe.", "One voice out, one log in.", "Unclear command creates three containments and zero decisions.", "The megaphone has entered a second life."),
      o("lo-08-b", "weak", "Split ownership with no clock", "Security owns tech, warehouse owns trucks, nobody owns the room.", [1, 1, 1], "Handoffs fall through the cracks.", "Split ownership still needs a single clock.", "Appoint a commander and a scribe.", "A room still needs a chair.", "Handoffs are where incidents hide.", "Two war rooms open. Neither has biscuits."),
      o("lo-08-c", "strong", "Commander plus scribe", "One voice out. One log in.", [3, 3, 3], "People know where to bring facts.", "Command and record-keeping travel together.", "Appoint a commander and a scribe.", "This unblocks every later choice.", "Name the role before the tools.", "The intern is now the scribe. Growth."),
    ]),
  q("lo-09", "contain", "Pull the plug?",
    "A technician stands at a switch with a dramatic look. Pulling it stops encryption on one aisle — and the last healthy pick line.",
    "This cable is doing a villain laugh.",
    ["containment"],
    [
      o("lo-09-a", "weak", "Yank every uplink", "If it has a cable, it is a suspect.", [2, 0, 1], "Encryption slows. So does the company.", "Broad isolation needs an ops plan.", "Isolate known-bad segments and identity first.", "Surgery, not a building fire alarm.", "Containment is targeting plus a pulse.", "The building is very quiet. Too quiet."),
      o("lo-09-b", "strong", "Isolate known-bad islands", "Cut the infected VLAN. Watch the rest.", [3, 2, 2], "Spread slows without a total blackout.", "Targeted containment beats theatrics.", "Isolate known-bad segments and identity first.", "Keep a documented ops path if it is safe.", "You can be both fast and precise.", "The switch gets a labelled sticky note, not a funeral."),
      o("lo-09-c", "high-risk", "Leave it up so orders ship", "Customers will never know.", [0, 3, 0], "The malware uses your uptime as a highway.", "Availability without isolation is a gift to the attacker.", "Isolate known-bad segments and identity first.", "Shipping is not a substitute for segmentation.", "Uptime can be attacker infrastructure.", "A pallet leaves. It contains encrypted feelings."),
    ]),
  q("lo-10", "contain", "VPN still hugging home",
    "Remote staff are still on the corporate VPN, cheerfully syncing OneDrive. One of them is on a train with a sticker that says admin.",
    "I am in a tunnel but very productive.",
    ["identity", "DORA"],
    [
      o("lo-10-a", "strong", "Kill risky sessions, pause bulk sync", "Keep break-glass VPN for responders.", [3, 2, 2], "Home PCs stop feeding the worm.", "Session control is containment.", "Revoke risky sessions and pause broad sync.", "Remote access is part of the campus now.", "Identity is a network edge.", "The train sticker is confiscated, spiritually."),
      o("lo-10-b", "weak", "Ask people nicely to disconnect", "A Slack emoji should do it.", [1, 2, 1], "Half stay connected for one email.", "Voluntary disconnect is not a control.", "Revoke risky sessions and pause broad sync.", "Force the session end.", "Politeness is not MFA.", "Fourteen people reply 'one sec'."),
      o("lo-10-c", "high-risk", "Open guest Wi-Fi as a workaround", "Work from the cafe SSID.", [0, 1, 0], "You add an unmonitored path.", "Workarounds need security review too.", "Revoke risky sessions and pause broad sync.", "Do not invent a second campus.", "Guest Wi-Fi is not a BCP.", "The cafe is thrilled. The logs are not."),
    ]),
  q("lo-11", "contain", "Backup cupboard lore",
    "Finance swears backups are in the cloud. Ops swears they are on a USB in a drawer labelled Snacks. Nobody has tested a restore this year.",
    "The snacks drawer is a tier-1 vault.",
    ["NIST CSF Recover"],
    [
      o("lo-11-a", "high-risk", "Promise Monday go-live", "The USB has good vibes.", [1, 0, 0], "You commit to a date you cannot defend.", "Recovery dates need evidence.", "Locate, protect, and test-restore a copy before promising dates.", "Proof before poetry.", "A backup you have not restored is a rumour.", "Someone is already printing the Monday banner."),
      o("lo-11-b", "strong", "Find copies and test a restore", "One file. One system. Proof.", [2, 3, 3], "You learn what is actually recoverable.", "Test restores beat folklore.", "Locate, protect, and test-restore a copy before promising dates.", "This is how you earn a date.", "Immutability only matters if you can find the copy.", "The snacks drawer contains crisps and a mystery stick."),
      o("lo-11-c", "weak", "Restore everything at once", "More jobs, more hope.", [1, 1, 1], "You may restore malware with the data.", "Restore order is a control.", "Locate, protect, and test-restore a copy before promising dates.", "Sequence beats volume.", "Flood restores hide failures.", "Twelve restore jobs enter a knife fight."),
    ]),
  q("lo-12", "contain", "Criminal helpdesk",
    "The note includes a helpdesk email and a countdown. Legal has not spoken. Someone drafts a witty reply.",
    "They have a loyalty programme, maybe.",
    ["extortion"],
    [
      o("lo-12-a", "high-risk", "Reply with a joke and a Bitcoin question", "Build rapport.", [0, 0, 0], "You create a messy trail and leak intent.", "Do not freelance extortion talks.", "Preserve the note, do not reply yet, call counsel.", "Silence can be a control.", "Criminal helpdesks are not your commander.", "The draft includes a GIF. It is not helping."),
      o("lo-12-b", "strong", "Preserve, no reply, call counsel", "Decisions wait for a logged legal path.", [2, 2, 3], "You keep options without feeding the actor.", "Process beats improvisation.", "Preserve the note, do not reply yet, call counsel.", "This keeps you inside a defensible path.", "Extortion is a legal track.", "Legal arrives with a calendar and a frown."),
      o("lo-12-c", "weak", "Pay a small test amount", "Just to see if the portal works.", [0, 1, 0], "You start a payment path without a decision.", "Test payments are still payments.", "Preserve the note, do not reply yet, call counsel.", "Do not poke the portal for science.", "Curiosity is expensive here.", "Finance asks which cost centre is 'crime'."),
    ]),
  q("lo-13", "control", "Service account BACKUP_GOD",
    "A service account named BACKUP_GOD is authenticating from a coffee shop ASN. It has more rights than the CISO's badge.",
    "It likes oat milk. And domain admin.",
    ["identity"],
    [
      o("lo-13-a", "strong", "Disable, rotate, review siblings", "Assume the family is messy.", [3, 2, 2], "A likely pivot path closes.", "Credential hygiene is containment.", "Disable or rotate the account and review standing privileges.", "Treat service accounts as people, the scary kind.", "Names are not controls.", "BACKUP_GOD is mortally offended."),
      o("lo-13-b", "high-risk", "Rename it BACKUP_GOD2", "Attackers hate sequels.", [0, 1, 0], "Same keys, new hat.", "Renames are not rotations.", "Disable or rotate the account and review standing privileges.", "Rotate secrets, do not rebrand them.", "Identity changes must invalidate old material.", "The coffee shop ASN is still invited."),
      o("lo-13-c", "defensible", "Watch it for a bit", "Maybe it likes coffee.", [2, 2, 1], "You might learn more and also leak more.", "Monitoring without a kill plan is a stall.", "Disable or rotate the account and review standing privileges.", "Watch only with a ready kill switch.", "Observation needs an abort.", "A dashboard is named 'god-watch'. Nobody likes this."),
    ]),
  q("lo-14", "control", "Patch theatre",
    "A well-meaning admin wants to patch every server now, including boxes you are still imaging for evidence.",
    "Green ticks are soothing.",
    ["change freeze"],
    [
      o("lo-14-a", "high-risk", "Patch evidence boxes first", "Make them look healthy.", [0, 1, 0], "You destroy forensic value.", "Healthy is not the same as preserved.", "Snapshot, then patch by exposure.", "Do not fix the crime scene first.", "Patching the patient mid-autopsy is a plot twist.", "The evidence box is now 'compliant' and empty."),
      o("lo-14-b", "strong", "Snapshot, then patch by exposure", "Crown jewels first, with a log.", [3, 2, 2], "You harden without erasing the plot.", "Order of operations matters.", "Snapshot, then patch by exposure.", "This is the safe sequence.", "Incident freeze is not forever, but it is ordered.", "A patch window appears on the board like a grown-up."),
      o("lo-14-c", "weak", "No patches until next quarter", "Freeze means freeze.", [1, 1, 1], "Known holes stay open.", "Incident freeze is not a season.", "Snapshot, then patch by exposure.", "Thaw with a list.", "Unpatched forever is also a risk.", "The admin starts a sad countdown calendar."),
    ]),
  q("lo-15", "control", "The missing MFA",
    "Half the admins still log in with passwords that are also their dog's name. The dog is called Admin.",
    "Admin is a very good dog and a very bad password.",
    ["MFA"],
    [
      o("lo-15-a", "strong", "MFA on privileged and remote now", "Document break-glass.", [3, 2, 2], "Stolen passwords bounce.", "Identity is the new perimeter, even in a warehouse.", "Enforce MFA on privileged paths before celebrating any reopen.", "Do this before the victory lap.", "Passwords named Admin are not a control family.", "Admin the dog is promoted to mascot, demoted from IAM."),
      o("lo-15-b", "weak", "MFA later, after we sleep", "People are tired.", [1, 2, 1], "The attacker is not tired.", "Fatigue is not a compensating control.", "Enforce MFA on privileged paths before celebrating any reopen.", "Tired people still need factors.", "Delay here is a second incident.", "Someone is already snoring on the jump host."),
      o("lo-15-c", "high-risk", "SMS to a shared brick phone", "Close enough.", [0, 1, 0], "Shared factors are shared incidents.", "MFA needs unshared authenticators.", "Enforce MFA on privileged paths before celebrating any reopen.", "Shared bricks are not authenticators.", "Possession must be personal.", "The brick phone has 26 unread codes and a crack."),
    ]),
  q("lo-16", "control", "Vendor named maybe-Dave",
    "The scanner vendor offers a free remote session from an engineer named maybe-Dave.",
    "Dave is real. We think.",
    ["third party"],
    [
      o("lo-16-a", "high-risk", "AnyDesk on a warehouse PC", "Speed.", [0, 2, 0], "You add an untracked admin.", "Remote tools are identity events.", "Time-bound jump host, MFA, ticket, watched session.", "Help should arrive inside your controls.", "Helpful vendors are still third parties.", "maybe-Dave has brought stickers."),
      o("lo-16-b", "strong", "Jump host, MFA, ticket, watch", "Time-bound access only.", [3, 2, 2], "Help arrives inside your controls.", "Third parties inherit your incident.", "Time-bound jump host, MFA, ticket, watched session.", "This is how you say yes safely.", "Refuse uncontrolled access, not all help.", "Dave is on a leash. A professional leash."),
      o("lo-16-c", "weak", "Refuse all vendor help", "Zero trust, zero scanners.", [2, 0, 1], "You keep purity and lose expertise.", "Refuse the uncontrolled path, not the people.", "Time-bound jump host, MFA, ticket, watched session.", "You can accept help with rails.", "Expertise is allowed; mystery admin is not.", "The scanners remain spiritually pure and physically sad."),
    ]),
  q("lo-17", "evidence", "USB labelled NOT MALWARE",
    "Someone wants to just peek at the ransomware core with a USB stick labelled NOT MALWARE.",
    "The label is a control. A tiny one.",
    ["forensics"],
    [
      o("lo-17-a", "high-risk", "USB reconnaissance, live and loud", "NOT MALWARE is basically a policy.", [0, 0, 0], "You may trigger more encryption.", "Do not plug gifts into the patient.", "Out-of-band inspection with snapshots, read-only where you can.", "Plan the peek.", "Curiosity is not a containment tool.", "The USB LED is winking in a threatening way."),
      o("lo-17-b", "strong", "Out-of-band inspection", "Snapshots. Read-only where you can.", [3, 2, 2], "You learn without feeding it.", "Plan the peek.", "Out-of-band inspection with snapshots, read-only where you can.", "This is how you look without poking.", "Access the core with a logged method.", "The core keeps dancing, but you have photos."),
      o("lo-17-c", "weak", "Ignore the core and hope", "Maybe it will go outside.", [1, 1, 1], "The beacon keeps pulsing.", "Hope is not a control objective.", "Out-of-band inspection with snapshots, read-only where you can.", "Look, carefully.", "Unobserved malware does not get bored.", "The beacon has learned jazz."),
    ]),
  q("lo-18", "evidence", "Police would like a copy",
    "Police cyber may want logs. A vendor wants the same copy for a blog post. You have one tired disk.",
    "Evidence is not a party favour.",
    ["chain of custody"],
    [
      o("lo-18-a", "high-risk", "Email the image to whoever asked first", "Speed is professionalism.", [1, 1, 0], "Chain of custody evaporates.", "Copies need a ledger.", "Hashed copies, custody log, named approver.", "Process is the product.", "Share with a process, not a mood.", "The blog post drafts itself in your nightmares."),
      o("lo-18-b", "strong", "Hashed copies and a custody log", "Police path first if required.", [2, 2, 3], "You can show who touched what.", "Process is the product.", "Hashed copies, custody log, named approver.", "This survives questions later.", "Evidence handling is an IR skill.", "The tired disk gets a little blanket. And a hash."),
      o("lo-18-c", "weak", "Refuse all copies forever", "What they cannot have cannot leak.", [2, 1, 1], "You may block legitimate investigation.", "Share with a process, not a mood.", "Hashed copies, custody log, named approver.", "Controlled sharing beats a sulk.", "Refusal still needs a legal owner.", "The disk is lonely and legally confusing."),
    ]),
  q("lo-19", "evidence", "Insurer timeline soup",
    "The cyber insurer wants a timeline that matches the ransom note, the napkin, and three Slack threads.",
    "They have interns too.",
    ["DORA"],
    [
      o("lo-19-a", "high-risk", "Send the nicest Slack thread", "Brand-safe chronology.", [1, 1, 0], "You create a false record.", "Do not curate reality.", "Reconcile sources into one timeline and mark conflicts.", "Honesty includes uncertainty.", "Insurers read contradictions for breakfast.", "The nice thread had an emoji. It is not evidence."),
      o("lo-19-b", "strong", "Reconcile sources, mark conflicts", "One timeline, sources attached.", [2, 2, 3], "Your story can be checked.", "Honesty includes uncertainty.", "Reconcile sources into one timeline and mark conflicts.", "This is the record you wanted.", "A single spine beats fan fiction.", "The napkin is scanned at 600 dpi, heroically."),
      o("lo-19-c", "defensible", "Send all raw exports", "No narrative, only pain.", [2, 1, 2], "Complete, painful, easy to misread.", "Raw dumps still need a cover note.", "Reconcile sources into one timeline and mark conflicts.", "A short cover note still helps.", "Volume is not clarity.", "Someone's laptop fans take off."),
    ]),
  q("lo-20", "communicate", "Customers on hold",
    "A retailer wants to know if their shipment left. Sales wants a cheerful tweet. Comms wants a nap.",
    "Use a shrug emoji. It is professional.",
    ["stakeholder communication", "DORA"],
    [
      o("lo-20-a", "high-risk", "Tweet that it is a routine outage", "Keep it light.", [1, 1, 0], "Customers and regulators remember the shrug.", "Humour is not a disclosure strategy.", "Send factual approved updates and a next-update time.", "Cadence beats charisma.", "Vacuum communication gets filled by rumours.", "The tweet has 4 likes, all internal."),
      o("lo-20-b", "strong", "Approved facts, next update time", "One channel. One clock.", [2, 2, 3], "Partners can plan around you.", "Cadence beats charisma.", "Send factual approved updates and a next-update time.", "This is the comms baseline.", "Tell what you know, nothing you do not.", "Sales is handed a script. They miss the emoji."),
      o("lo-20-c", "defensible", "Tell only the biggest customer", "VIP treatment.", [2, 2, 1], "You help one partner and create a fairness problem.", "Selective honesty has a half-life.", "Send factual approved updates and a next-update time.", "Fairness is also trust.", "Secret briefings leak.", "The second-biggest customer has ears."),
    ]),
  q("lo-21", "communicate", "Staff WhatsApp poll",
    "A warehouse group chat has a screenshot of the ransom note and a poll: pay or pray.",
    "Democracy!",
    ["insider comms"],
    [
      o("lo-21-a", "weak", "Ban phones and hope", "No phones, no leaks, no picking either.", [1, 0, 1], "You crush morale and lose useful photos.", "Policy without a channel fails.", "Give an internal brief and an official screenshot drop.", "Staff are sensors and a leak surface.", "Your people need a place to put what they saw.", "Phones go into a bucket. The bucket is not encrypted."),
      o("lo-21-b", "strong", "Internal brief plus screenshot drop", "Thank people. Kill the poll.", [2, 2, 3], "Rumour slows down.", "Staff are part of the response.", "Give an internal brief and an official screenshot drop.", "This treats people as allies.", "A meme thread is not a briefing.", "The poll is closed. The stickers remain."),
      o("lo-21-c", "high-risk", "Join as definitely-not-IR", "Undercover meme lord.", [0, 1, 0], "You look untrustworthy and leak more.", "Do not troll your own incident.", "Give an internal brief and an official screenshot drop.", "Be present as yourself.", "Trust dies in costume.", "Your alias is immediately obvious."),
    ]),
  q("lo-22", "communicate", "Regulator o'clock",
    "Someone mentions DORA and looks at you like you are a search engine. The clock is already running.",
    "Can you Ctrl+F the law?",
    ["DORA Art. 19"],
    [
      o("lo-22-a", "high-risk", "Wait until we know everything", "Perfect briefs only.", [1, 1, 0], "The deadline does not wait for poetry.", "Early, factual, incomplete is a valid first notice.", "Start the notification clock with facts versus unknowns.", "Process beats panic.", "Notification is a process, not a press release.", "The perfect brief is still a blank page."),
      o("lo-22-b", "strong", "Start the clock, log unknowns", "Counsel in the room.", [2, 2, 3], "You stay inside the duty of care.", "Process beats panic.", "Start the notification clock with facts versus unknowns.", "This is how grown-ups notify.", "Clocks do not pause for style.", "A timer appears. It is rude and useful."),
      o("lo-22-c", "weak", "Send a 40-page log dump", "Transparency.", [1, 1, 1], "Nobody can act on a log slurry.", "Notifications need a human summary.", "Start the notification clock with facts versus unknowns.", "Summarise, then attach.", "Volume is not a filing.", "A regulator intern weeps, but productively."),
    ]),
  q("lo-23", "communicate", "Board vibe check",
    "A board member forwards the ransom note to a journalist for a vibe check.",
    "They have LinkedIn Premium.",
    ["governance"],
    [
      o("lo-23-a", "high-risk", "Let the board handle press", "Directors have opinions.", [1, 1, 0], "The story leaves the building without a spine.", "One spokesperson.", "Re-brief the board and lock outbound comms to approved channels.", "Directors need a briefing, not a megaphone.", "Governance includes who may narrate.", "The journalist already has a headline."),
      o("lo-23-b", "strong", "Re-brief and lock outbound comms", "Facts in. Speculation out.", [2, 2, 3], "Narrative control returns.", "One spokesperson.", "Re-brief the board and lock outbound comms to approved channels.", "This protects trust.", "Reputation is an incident track.", "The board pack is suddenly one page and true."),
      o("lo-23-c", "weak", "Ignore it and focus on packets", "Tech will save reputation.", [2, 1, 1], "Packets do not call journalists back.", "Reputation is an incident track.", "Re-brief the board and lock outbound comms to approved channels.", "Packets and press both need owners.", "You can lose the story while winning the disk.", "The packets are thriving. The story is not."),
    ]),
  q("lo-24", "recover", "Paper picking",
    "Someone proposes clipboards and heroic jogging between aisles. It might move pallets. It might invent a second set of books.",
    "We will remember the pallets.",
    ["business continuity"],
    [
      o("lo-24-a", "high-risk", "Hero clipboards, no reconciliation", "Jog faster.", [1, 1, 0], "You ship the wrong freight with confidence.", "Manual ops need a paper trail.", "Use a documented manual lane with later reconciliation.", "Workarounds need controls or they become a second incident.", "Continuity is designed, not improvised.", "A clipboard becomes legally interesting."),
      o("lo-24-b", "strong", "Documented manual lane", "Small volume, named owners, photos.", [2, 3, 2], "Critical goods move without inventing data.", "Continuity is designed, not improvised.", "Use a documented manual lane with later reconciliation.", "This keeps a pulse without a second incident.", "Heroism is not a control.", "Photos of pallets. The glamorous part of IR."),
      o("lo-24-c", "weak", "Stop all physical work", "Safety first, revenue never.", [2, 0, 1], "You protect systems and starve the business.", "Containment should leave a pulse.", "Use a documented manual lane with later reconciliation.", "A designed trickle is better than a halt-forever.", "Name the ops cost of purity.", "The yard is peaceful. The customers are not."),
    ]),
  q("lo-25", "recover", "Rebuild vs haunted image",
    "A vendor offers to image the whole estate from last month. Last month includes that Excel macro culture.",
    "Nostalgia is a backup strategy.",
    ["clean rebuild"],
    [
      o("lo-25-a", "high-risk", "Restore last month everywhere", "Ancient means innocent.", [0, 1, 0], "You may reintroduce the foothold.", "Age is not cleanliness.", "Rebuild critical services from known-good images; restore data after checks.", "Restoring a haunted image relocates the ghost.", "Gold images first.", "The macros wave as they return home."),
      o("lo-25-b", "strong", "Gold images, then checked data", "Priority services only.", [3, 2, 2], "You come back narrower and cleaner.", "Rebuild is slower and safer.", "Rebuild critical services from known-good images; restore data after checks.", "This is the recovery spine.", "Clean rebuild beats haunted nostalgia.", "The gold image is boring. That is the point."),
      o("lo-25-c", "weak", "Mix live infected disks with new VMs", "Hybrid cloud, hybrid malware.", [1, 1, 1], "The old disks keep coughing.", "Do not dual-boot an incident.", "Rebuild critical services from known-good images; restore data after checks.", "Do not keep pets that bite.", "Hybrid is not a strategy here.", "A VM and a ghost share a VLAN."),
    ]),
  q("lo-26", "recover", "Partial reopen",
    "Sales wants billing online this afternoon because a key account is being very understanding, but not that understanding.",
    "Monitoring is a feeling.",
    ["safe restart"],
    [
      o("lo-26-a", "high-risk", "Turn billing on and watch Slack", "Green emoji means safe.", [0, 2, 0], "You may re-infect a clean island.", "Reopen needs instrumentation.", "Open a narrow monitored slice with rollback.", "A partial reopen is a controlled experiment.", "A vibe is not observability.", "Slack has many eyeballs and no packet capture."),
      o("lo-26-b", "strong", "Narrow monitored slice plus rollback", "One service. One owner. One abort.", [3, 3, 2], "Revenue trickles without a second blast.", "Safe restart is a design.", "Open a narrow monitored slice with rollback.", "This is how you reopen on purpose.", "Controlled experiments beat hopes.", "Billing blinks once, politely, under a watch."),
      o("lo-26-c", "defensible", "Keep everything dark until next month", "Maximum safety, minimum company.", [3, 0, 1], "You avoid reinfection and also customers.", "Over-caution has a cost you should name.", "Open a narrow monitored slice with rollback.", "Name the cost if you wait.", "Purity can starve the business.", "The cafe remains open. The ERP does not."),
    ]),
  q("lo-27", "recover", "Lessons while lights flicker",
    "Someone wants a 60-slide retro before the core is quiet. Someone else wants to never speak of this again.",
    "We will process this in Q4.",
    ["improvement"],
    [
      o("lo-27-a", "strong", "Short living log with owners", "Three pages, not a novel.", [2, 2, 3], "Fixes have names.", "Improvement is part of response.", "Capture a short living log now: what worked, what failed, what changes in 72 hours.", "Learning delayed is learning denied.", "Write while the coffee is still bad.", "The living log is ugly and true."),
      o("lo-27-b", "weak", "Schedule a retro in Q4", "When the trauma has aged.", [1, 1, 1], "Details evaporate.", "Memory is a perishable control.", "Capture a short living log now: what worked, what failed, what changes in 72 hours.", "Capture now, polish later.", "Delay deletes lessons.", "Q4 is already fully booked with other regrets."),
      o("lo-27-c", "high-risk", "Blame the intern in writing", "Accountability.", [0, 0, 0], "People hide the next incident.", "Scapegoats are useless.", "Capture a short living log now: what worked, what failed, what changes in 72 hours.", "Blameless is not consequence-free, but hunting interns fails.", "Culture is a control.", "The intern updates their CV in the war room."),
    ]),
  q("lo-28", "close", "Open the core?",
    "The door light is still red. The beacon is yellow. The ransomware core is still doing a little dance.",
    "Kick it. That is a patch.",
    ["NIST CSF Recover"],
    [
      o("lo-28-a", "high-risk", "Kick the door, smash the box", "Physical access is the best patch.", [0, 0, 0], "You destroy evidence and maybe the last clean backup mount.", "Violence is not IR.", "Enter with isolate, preserve, rebuild — no victory lap on live malware.", "The destination is a procedure.", "The last mile is still a playbook.", "The box is very smashed and very unhelpful."),
      o("lo-28-b", "strong", "Isolate, preserve, rebuild", "Quiet the core. Keep the story.", [3, 3, 3], "The campus can start coming back on purpose.", "Containment has a last mile.", "Enter with isolate, preserve, rebuild — no victory lap on live malware.", "This is the close you wanted.", "A boss fight is still a change ticket.", "The core sits down. Professionally."),
      o("lo-28-c", "weak", "Leave it pulsing, reopen the cafe", "Morale pastry first.", [1, 2, 1], "The core keeps radiating risk.", "Pastry is not a compensating control.", "Enter with isolate, preserve, rebuild — no victory lap on live malware.", "Hydrate, then contain.", "Morale does not isolate malware.", "The pastries are excellent. The beacon disagrees."),
    ]),
  q("lo-29", "close", "Declare victory?",
    "A VP wants the all-clear banner. Telemetry still has mystery beacons. The intern printed WE WON hats.",
    "Winners do not look at logs.",
    ["monitoring"],
    [
      o("lo-29-a", "high-risk", "Hats on, monitoring off", "Close the war room.", [0, 1, 0], "You will miss the sequel.", "Closure needs criteria.", "Declare controlled recovery with heightened monitoring, not a party.", "All-clear is a monitoring decision.", "Recovery is a phase, not a mood.", "The hats are one size too triumphant."),
      o("lo-29-b", "strong", "Controlled recovery, extra eyes 72h", "Hats optional. Alerts mandatory.", [3, 3, 3], "You can reopen without lying to yourselves.", "Recovery is a phase, not a mood.", "Declare controlled recovery with heightened monitoring, not a party.", "This is an honest close.", "Criteria before confetti.", "The intern keeps one hat. For later."),
      o("lo-29-c", "defensible", "Stay in incident mode forever", "Sleep is for other industries.", [3, 1, 2], "You stay safe and burn the team.", "Name an exit criterion.", "Declare controlled recovery with heightened monitoring, not a party.", "You can be careful without becoming nocturnal forever.", "Burnout is also an incident outcome.", "The war room acquires a toaster and a union."),
    ]),
  q("lo-30", "close", "Backup labelled DO NOT DELETE (old)",
    "You find a backup from 2019 that includes a lot of feelings.",
    "Ancient means innocent.",
    ["backup"],
    [
      o("lo-30-a", "high-risk", "Restore 2019 because it predates this", "Time travel as IR.", [0, 0, 0], "You lose years of operations and maybe keep old malware.", "Oldest is not cleanest.", "Use the newest proven-clean copy. Archive the museum piece.", "Provenance beats folklore.", "Backup humour stops being funny at restore time.", "2019 would like its printers back."),
      o("lo-30-b", "strong", "Newest clean restore, keep 2019 offline", "Museum in the archive.", [3, 3, 2], "You recover a company, not a time capsule.", "Provenance beats folklore.", "Use the newest proven-clean copy. Archive the museum piece.", "This is the restore you can defend.", "Proven-clean beats merely old.", "The museum stick is labelled, finally."),
      o("lo-30-c", "weak", "Merge 2019 and today in Excel", "What is the worst that could happen.", [1, 1, 0], "You invent a third universe of data.", "Excel is not a merge tool for estates.", "Use the newest proven-clean copy. Archive the museum piece.", "Do not hand-merge realities.", "Spreadsheets are not time machines.", "Excel is sweating."),
    ]),
];
