import { option, question, scoreTriple } from "../build";
import type { AnswerOption, AnswerQuality, Question, ScorePoints, StoryPhase } from "../types";

const ALL = ["lo-campus", "lo-warehouse", "lo-friday"] as const;
const KEYS = ["containment", "operations", "trust"] as const;

function pts(
  a: ScorePoints,
  b: ScorePoints,
  c: ScorePoints,
): Record<string, ScorePoints> {
  return scoreTriple(a, b, c, KEYS);
}

function o(
  id: string,
  quality: AnswerQuality,
  title: string,
  summary: string,
  scores: [ScorePoints, ScorePoints, ScorePoints],
  consequence: string,
  explanation: string,
  recommendedAction: string,
  whyRecommended: string,
  learningPoint: string,
  npcReaction: string,
): AnswerOption {
  return option(
    id,
    quality,
    title,
    summary,
    pts(...scores),
    consequence,
    explanation,
    recommendedAction,
    whyRecommended,
    learningPoint,
    npcReaction,
  );
}

function q(
  id: string,
  phase: StoryPhase,
  title: string,
  situation: string,
  npcLine: string,
  prompt: string,
  frameworks: readonly string[],
  options: readonly [AnswerOption, AnswerOption, AnswerOption],
  scenarioIds: readonly string[] = ALL,
): Question {
  return question("locked-out", id, phase, scenarioIds, title, situation, npcLine, frameworks, options, { prompt });
}

const rec01 = "Name an incident coordinator, freeze unplanned changes, and contain with evidence preservation in mind.";
const rec02 = "Preserve the original file, analyse a copy in a sandbox, block the hash, and treat the lookalike mailbox as a lead.";
const rec03 = "Freeze further deployments and snapshot the change record before any rollback or hotfix.";
const rec04 = "Isolate the affected PC, revoke the privileged session, and preserve logs. After containment, replace permanent local administrator access with managed elevation, just-in-time access, or a documented emergency-access process.";
const rec05 = "Inventory affected versus working services with named owners before further containment.";
const rec06 = "Document the undocumented path, restrict it with an allowlist, assign an owner, and set an expiry.";
const rec07 = "Preserve remaining logs, stop overwriting disks, and record the missing collection window in the incident log.";
const rec08 = "Appoint one incident commander and a scribe so orders and facts have a single home.";
const rec09 = "Isolate known-infected segments and identity first; keep a documented operations path only if it is still safe.";
const rec10 = "Revoke risky remote sessions, pause bulk file sync, and keep a watched break-glass VPN path for responders only.";
const rec11 = "Locate backup copies, protect them from further change, and test-restore a sample before promising a recovery date.";
const rec12 = "Preserve the ransom note, do not reply or pay, and involve legal counsel before any contact with the actor.";
const rec13 = "Disable or rotate the unexpected service account, kill its sessions, and review sibling accounts with similar privileges.";
const rec14 = "Snapshot evidence hosts first, then patch remaining exposed systems by business impact, with a logged change.";
const rec15 = "Enforce MFA on privileged and remote paths before any reopen, with a documented break-glass account.";
const rec16 = "Accept vendor help only through a ticketed, time-bound jump host with MFA and a watched session.";
const rec17 = "Inspect the sample out-of-band from snapshots, using read-only methods where possible, on an isolated analysis host.";
const rec18 = "Share hashed copies under a chain-of-custody log with a named approver; treat law-enforcement requests through counsel.";
const rec19 = "Reconcile tickets, telemetry and messages into one timeline, and mark conflicts instead of hiding them.";
const rec20 = "Issue factual, approved updates through one channel, with a next-update time, and say only what is known.";
const rec21 = "Give staff an internal brief and an official screenshot channel; close unofficial polls and rumours.";
const rec22 = "Start the regulatory notification clock with facts versus unknowns, and keep counsel in the room.";
const rec23 = "Re-brief the board and lock outbound communications to approved spokespersons and channels.";
const rec24 = "If physical work continues, use a documented manual procedure with named owners, limited volume, and later reconciliation.";
const rec25 = "Rebuild critical services from known-good hardened images and restore data only after integrity checks.";
const rec26 = "Reopen a narrow, monitored service slice with a named owner and a rollback plan.";
const rec27 = "Capture a short living log now: what worked, what failed, and which changes are due within 72 hours, with owners.";
const rec28 = "Isolate the remaining infected core, preserve evidence, then rebuild from known-good media — do not destroy the host or leave the process running.";
const rec29 = "Declare controlled recovery with heightened monitoring for at least 72 hours; do not stand down detection to announce an all-clear.";
const rec30 = "Restore from the newest copy that has passed a clean-restore test; keep older archive media offline and labelled.";

export const LOCKED_OUT_QUESTIONS: Question[] = [
  q("lo-01", "start", "Lock banners on multiple warehouse workstations",
    "Reception and the warehouse helpdesk are receiving calls that PCs display a lock banner demanding payment. At least six devices are still powered on. Staff are asking whether they should restart the machines to clear the message.",
    "We have lock banners on at least six warehouse PCs already.",
    "What should the incident team do in the first minutes?",
    ["NIST CSF Detect", "DORA Art. 17"],
    [
      o("lo-01-a", "weak", "Restart every affected PC from the floor", "Treat the banners as a local glitch and power-cycle the estate.", [1, 1, 1], "Reboots interrupt encryption mid-write, wipe volatile evidence, and do not stop spread to other hosts.", "Restarting looks decisive but is not containment. It can destroy memory artefacts and does not appoint a coordinator or freeze further admin activity. A named lead and an evidence-aware pause are required before technical improvisation.", rec01, "Command and a change freeze limit further damage in the first minutes.", "The opening minutes of a ransomware event are for orientation and coordination, not DIY recovery.", "Helpdesk reports more banners while machines are still cycling."),
      o("lo-01-b", "high-risk", "Wait until the morning rush ends before involving IT", "Avoid alarming staff on a busy receiving shift.", [0, 0, 0], "Encryption and lateral movement continue while the organisation stays silent.", "Delay is a decision, not neutrality. Without an incident channel, staff improvise, evidence is overwritten, and the attacker keeps time on the network. Early coordination is a control.", rec01, "Early coordination limits spread and rumour.", "Silence during an active lock-out is not a control.", "Warehouse supervisors start issuing their own restart instructions."),
      o("lo-01-c", "strong", "Open a named incident and freeze unplanned changes", "Appoint a coordinator. Stop ad-hoc admin tools. Keep affected systems powered for evidence.", [3, 2, 3], "Improvised restarts stop. Evidence stays on disk. The next hour has a single clock.", "A named incident lead, a freeze on routine change, and an instruction not to reboot are the baseline for every later technical move. Restarting or waiting both cede time to the encrypting process.", rec01, "This is the organisation you need before isolation, identity and recovery decisions.", "Command first, then technical containment.", "IT and Security join one call and start an incident log."),
    ]),
  q("lo-02", "start", "Macro-enabled spreadsheet from a lookalike finance mailbox",
    "An intern reports that Invoice_FINAL(2).xlsm arrived from an address that almost matches the finance shared mailbox. The first lock banner appeared on that intern's PC shortly after macros were enabled. The original message is still in the inbox.",
    "The file asked me to enable macros so the invoice would display.",
    "How should the suspected malware sample be handled?",
    ["NIST CSF Identify"],
    [
      o("lo-02-a", "strong", "Sandbox a copy and preserve the original", "Analyse on an isolated host. Keep the mailbox message and file as evidence.", [3, 2, 2], "You obtain behavioural indicators without spreading the payload on production.", "Malware analysis belongs on an isolated sandbox, not a laptop or a forwarded warning. Preserving the original supports hash blocking, mailbox investigation and later forensics. A blanket .xlsm block can follow as a temporary control once the sample is secured.", rec02, "You learn from the sample without multiplying the incident.", "Office documents with macros remain a common initial-access path.", "The sample is hashed and the lookalike domain is added to the hunt list."),
      o("lo-02-b", "high-risk", "Forward the file to other teams as a warning", "Show colleagues the filename so they know not to open it.", [0, 1, 1], "Live malware is copied into more inboxes and more endpoints.", "Redistributing a live payload is not awareness training. It expands the blast radius, contaminates more mailboxes and may execute again. Block the hash and warn through a channel that does not carry the file.", rec02, "A hash block and an official warning are safer than a viral attachment.", "Awareness must not transport the sample.", "Several additional mailboxes now hold the same .xlsm."),
      o("lo-02-c", "defensible", "Temporarily block all .xlsm attachments at the gateway", "Stop every macro-enabled workbook until further notice.", [2, 1, 1], "Some risk drops, but legitimate finance macros fail and the original sample is still unanalysed.", "A broad block can buy time if it has an owner and an expiry, but it is not a substitute for preserving and analysing the specific file. Without a sample and a mailbox lead, you still do not know the initial-access path.", rec02, "A targeted sample plus a time-limited block is cleaner than a block alone.", "Temporary gateway blocks need an owner, a scope and an expiry.", "Accounts payable reports that legitimate workbooks are now bouncing."),
    ]),
  q("lo-03", "start", "Unauthorised change deployed shortly before lock banners",
    "A developer confirms they pushed a small configuration change to a warehouse integration service at 16:40, outside the approved change window. Lock banners began appearing about twenty minutes later. The change ticket is incomplete and further pipeline jobs are queued.",
    "It was a small configuration tweak. I did not think it needed a ticket.",
    "How should the unauthorised change be treated during this incident?",
    ["NIST CSF Protect", "DORA"],
    [
      o("lo-03-a", "defensible", "Roll the change back immediately", "Undo the 16:40 configuration and expect the lock banners to clear.", [2, 2, 1], "Rollback may remove a contributing misconfiguration, or it may add a second uncontrolled change on top of attacker activity.", "Rollback can be reasonable once the artefact is snapshotted, but doing it first mixes your change with the incident timeline. Freeze and preserve, then decide on rollback with a complete record. A second hotfix would be worse.", rec03, "You need the change artefact, not only an undo.", "Friday and out-of-window deploys collide badly with incident clocks.", "Release engineering waits for a snapshot before touching the pipeline again."),
      o("lo-03-b", "strong", "Freeze further deployments and snapshot the change artefacts", "Stop the pipeline. Keep the configuration, logs and ticket as evidence.", [3, 3, 2], "You hold a timeline without adding blast radius, and later rollback remains possible.", "A change freeze is a containment tool: it stops new variables while you correlate the 16:40 push with lock-banner timing. Immediate rollback without a snapshot, or another hotfix, both mix operator change with attacker activity.", rec03, "This keeps options open for both investigation and a controlled undo.", "Incidents are not a release train.", "The pipeline is paused and the 16:40 artefacts are copied to the incident store."),
      o("lo-03-c", "high-risk", "Push a second hotfix to reverse the first", "Ship a follow-up change immediately to restore the previous configuration.", [0, 0, 0], "Attacker activity and two uncontrolled deploys now share the same hour, and evidence of the first change is overwritten.", "Do not debug a suspected ransomware event with more production changes. Additional deploys hide indicators, bypass change control and can reintroduce or worsen the condition. Freeze, snapshot, then decide.", rec03, "Stop adding variables until the incident lead agrees a change.", "More change during an incident conceals both attacker and operator actions.", "A second job is already packing in the pipeline."),
    ],
    ["lo-friday"]),
  q("lo-04", "start", "Suspicious activity on a privileged warehouse PC",
    "An endpoint alert shows an unknown process making outbound connections from a warehouse PC. A supervisor is currently signed in with a local administrator account that is normally used to maintain legacy printer software.",
    "The supervisor account is still signed in on that PC.",
    "What should IT and Security do first?",
    ["least privilege"],
    [
      o("lo-04-a", "high-risk", "Ask the supervisor to sign out and reinstall the printer software", "This may remove useful evidence and does not contain a process that may already be malicious.", [0, 1, 0], "The unknown process keeps a network path, and reinstalling software overwrites artefacts on the host.", "Signing out and reinstalling looks like a local fix but does not isolate the endpoint or preserve logs. If the process is already malicious, the privileged session remains a lateral-movement path until it is revoked and the device is taken off the network.", rec04, "Contain the host and the session before any rebuild or privilege-programme work.", "An active privileged session on an alerting PC is an incident, not a printer ticket.", "The supervisor begins a software repair while the process is still calling out."),
      o("lo-04-b", "strong", "Isolate the PC and revoke the active privileged session", "Disconnect the device from the network, revoke the session and preserve the relevant logs for investigation.", [3, 2, 2], "The unknown process loses its network path. The privileged session cannot be reused. Logs remain for investigation.", "The immediate priority is to contain the potentially compromised endpoint while preserving evidence. Removing administrator rights estate-wide, or asking the user to reinstall software, either delays containment or destroys artefacts. After the incident is controlled, replace permanent local administrator access with managed elevation, just-in-time access or a documented emergency-access process.", rec04, "Containment and evidence come before longer-term privilege redesign.", "Standing local administrator rights turn one infected PC into a warehouse-wide opportunity.", "Network isolation is in place and the supervisor session has been revoked."),
      o("lo-04-c", "weak", "Remove administrator rights from every warehouse PC immediately", "Reducing permanent privileges is a sensible follow-up improvement, but it does not contain or investigate the currently affected device.", [1, 0, 1], "You start a wide identity change while the alerting host and live session stay on the network.", "Least privilege is the right follow-up, not the first move against a live unknown process. Estate-wide rights removal can also disrupt response and overwrite session evidence if it is not sequenced after isolation. Contain this PC, then redesign standing admin.", rec04, "Kill the live path, then reduce standing privilege with a planned emergency-access process.", "Privilege reduction is a control programme; isolation is incident response.", "A directory change is queued while the warehouse PC continues outbound connections."),
    ]),
  q("lo-05", "assess", "Incomplete picture of which services still work",
    "Operations wants a shared impact map. Handheld scanners in two aisles still scan. Billing cannot post invoices. The ERP status page is green. Nobody has a named owner for each affected service, and reports from the floor conflict with the dashboard.",
    "We keep getting different answers depending on who we ask.",
    "How should the team establish incident scope before further containment?",
    ["NIST CSF Detect", "DORA"],
    [
      o("lo-05-a", "weak", "Treat the entire campus as lost and disconnect everything reachable", "Pull every uplink and assume no service is still healthy.", [1, 0, 1], "Healthy pick lines and safety systems stop, and you still do not know which island was actually infected.", "Over-containment is still a decision with an operations cost. Without an affected-versus-working inventory you cannot target isolation, brief the business, or protect what still ships. Map first, then cut with intent.", rec05, "Name what still moves goods before you take it down.", "You cannot contain what you have not named.", "Receiving is dark, including aisles that had no lock banners."),
      o("lo-05-b", "strong", "Inventory affected versus working services with named owners", "Build one list: what is down, what still runs, and who owns each item.", [3, 3, 2], "Containment, communications and continuity share the same picture.", "Impact mapping is incident hygiene. A green dashboard can lie when agents are dead, and a campus-wide pull stops work you may still need. A named inventory is the input to targeted isolation.", rec05, "A shared picture beats heroic guesses from any single dashboard.", "Establish scope before you isolate.", "Operations and Security agree a single affected-versus-working board."),
      o("lo-05-c", "high-risk", "Treat the green ERP dashboard as proof that systems are healthy", "If the status page is green, keep working to the dashboard.", [0, 1, 0], "Warehouse PCs continue to fail off-dashboard while leadership is told the estate is fine.", "Dashboards lie when agents are dead, logs are delayed, or the monitored tier is not the one encrypting. Floor reports of lock banners are evidence. Telemetry gaps are findings, not reassurance.", rec05, "Look at the floor and at owners, not only the chart.", "A green dashboard is not a scope decision.", "Billing remains unable to post while the ERP page stays green."),
    ]),
  q("lo-06", "assess", "Handheld scanner still working on an undocumented network",
    "One handheld scanner continues to reach the warehouse management system over a guest VLAN that does not appear in the network diagrams. A picker is using it to keep a pick line moving. Security has no monitoring or access control on that VLAN.",
    "This scanner is the only one still talking to the WMS.",
    "How should the undocumented scanner path be handled?",
    ["network segmentation"],
    [
      o("lo-06-a", "high-risk", "Leave the scanner in use without documenting or monitoring it", "Keep the pick line moving and treat the path as a lucky exception.", [0, 2, 0], "An unmanaged route into the WMS stays available to whoever finds it, including an attacker.", "Undocumented connectivity is a finding, not a gift. Operational value does not cancel the need for an owner, an allowlist and monitoring. Ignoring it preserves throughput and the hole.", rec06, "Lifelines still need owners and expiry dates.", "Shadow networks survive incidents because nobody writes them down.", "The guest VLAN remains unmonitored while picking continues."),
      o("lo-06-b", "strong", "Document, restrict and monitor the path with a time-limited exception", "Allowlist the scanner, assign an owner, watch the VLAN, and set an expiry.", [2, 3, 2], "A trickle of picking continues under watch instead of as an unknown back door.", "Temporary exceptions are controls when they have an owner, a restriction and an end time. Switching the device off is defensible if you accept the operations hit; leaving it undocumented is not. This balances continuity and containment.", rec06, "This is how you keep a workaround from becoming a second incident.", "Exceptions are only controls when they expire and are monitored.", "Network records now show the guest VLAN, the scanner identity and a review time."),
      o("lo-06-c", "defensible", "Take the scanner offline immediately", "If the path cannot be explained, remove it from the network now.", [3, 1, 1], "You close an unmanaged hole and also lose the last working pick line.", "Blunt isolation is legitimate containment if leadership accepts the operations cost. A watched, time-limited exception is usually kinder to the business and still reduces risk. Either choice beats leaving the path unnamed.", rec06, "If you isolate, name the operations impact in the incident log.", "Containment can be blunt; the cost should be explicit.", "Aisle picking stops. The undocumented VLAN is disconnected pending a diagram."),
    ],
    ["lo-warehouse", "lo-campus"]),
  q("lo-07", "assess", "SIEM collector missing an hour of logs",
    "The SIEM has a gap covering roughly 07:00–08:00, the window when lock banners first appeared. A contractor says the collector sometimes drops events when disk is full. The time of the last successful log backup is not recorded.",
    "We may have lost the hour that matters most.",
    "What is the priority for evidence while the collector is incomplete?",
    ["evidence preservation"],
    [
      o("lo-07-a", "strong", "Keep capturing, snapshot remaining logs and record the gap", "Stop rotation where you can. Write the missing hour in the incident log.", [2, 2, 3], "You can still reconstruct a partial timeline and you are honest about what is missing.", "A documented gap is a fact; a reset or a memory-only story is not. Remaining collector data and host logs may still cover parts of the window. Honesty about the hole is required for insurers, regulators and later reconstruction.", rec07, "Evidence handling includes recording what you do not have.", "Forgotten backups and silent wipes are how stories replace telemetry.", "The incident board now shows a recorded 07:00–08:00 collection gap."),
      o("lo-07-b", "high-risk", "Factory-reset the SIEM to restore collection", "Wipe the collector and bring it up clean so logging can resume.", [0, 0, 0], "Remaining breadcrumbs from before and after the gap are deleted.", "Do not destroy the evidence store to fix the collector. A reset may restore forwarding and erase what you still have. Repair forwarding after a snapshot, and record the gap rather than pretending it never happened.", rec07, "Moodiness or disk pressure is not a reason to wipe the SIEM.", "Collectors are evidence stores during an incident.", "The SIEM is empty and forwarding again, with no retained events."),
      o("lo-07-c", "weak", "Reconstruct the missing hour from staff recollections only", "Interview the intern and supervisors and treat that as the log.", [1, 1, 1], "You obtain conflicting anecdotes and no defensible telemetry for the gap.", "Human recall is perishable and will not survive regulatory or legal scrutiny as a substitute for logs. Interviews can supplement a snapshot; they cannot replace preservation of what the collector still holds.", rec07, "Write what you can still prove, including the existence of the gap.", "Anecdotes are not telemetry.", "Three witnesses describe three different popup times."),
    ]),
  q("lo-08", "assess", "Multiple teams claiming incident command",
    "IT operations, security, warehouse supervisors and a helpdesk agent are all issuing instructions on the same call. Isolation orders conflict. There is no incident log and no named commander.",
    "I am not sure whose instruction we should follow on the floor.",
    "How should command and record-keeping be organised?",
    ["NIST CSF Respond", "DORA"],
    [
      o("lo-08-a", "high-risk", "Let whoever speaks first on the call set direction", "Treat momentum as leadership and execute the latest verbal order.", [0, 0, 0], "Contradictory isolation and keep-open orders hit the warehouse floor.", "Authority needs a named role, not volume. Without a commander and a scribe, three containments and zero decisions is a typical result. Appoint the roles before more technical moves.", rec08, "One voice out and one log in prevent colliding orders.", "Unclear command is itself an incident amplifier.", "Aisle leads receive two opposite instructions within five minutes."),
      o("lo-08-b", "weak", "Split ownership by function with no shared clock", "Security owns technology, warehouse owns trucks, and nobody owns the room.", [1, 1, 1], "Handoffs fail: isolation is delayed because each group thinks the other owns the next step.", "Functional expertise is necessary, but split ownership without a single clock and a scribe drops decisions between teams. A commander still chairs the room even when specialists own workstreams.", rec08, "A room still needs a chair and a record.", "Handoffs are where incidents stall.", "Two parallel calls open and neither has a complete picture."),
      o("lo-08-c", "strong", "Appoint one incident commander and a scribe", "One voice for orders. One log for facts, times and decisions.", [3, 3, 3], "People know where to bring evidence and which instruction to follow.", "Command and record-keeping travel together. This unblocks later isolation, identity and communications choices. Volume or an informal split of the room will not produce a defensible timeline.", rec08, "Named roles unblock every later technical and business choice.", "Name the role before the tools.", "The call has a chair, a decision log and a next-update time."),
    ]),
  q("lo-09", "contain", "Isolating an infected aisle would stop the last healthy pick line",
    "A technician is at the warehouse access switch. Disconnecting VLAN-WMS-3 would stop encryption on aisle C. That VLAN also carries the last pick line that is still scanning. Neighbouring VLANs show no encryption alerts yet.",
    "If I disconnect this uplink, aisle C stops — including the line that is still working.",
    "Which containment approach should the team take at the switch?",
    ["containment"],
    [
      o("lo-09-a", "weak", "Disconnect every warehouse uplink as a precaution", "Treat every cable as hostile and isolate the whole floor.", [2, 0, 1], "Encryption slows across the building, and so does every remaining operational path, including ones with no alert.", "Broad isolation can be justified as a last resort, but it needs an explicit operations plan and a business decision. Here you already have a known-bad segment. Targeted isolation plus monitoring of neighbours is faster and more precise.", rec09, "Containment is targeting plus a pulse, not a building-wide pull by default.", "Over-isolation is still a decision with a named cost.", "The warehouse is dark, including aisles with no encryption alerts."),
      o("lo-09-b", "strong", "Isolate the known-infected segment and monitor the rest", "Cut VLAN-WMS-3. Watch neighbouring VLANs and identity for spread.", [3, 2, 2], "Spread on aisle C slows without a total blackout of still-healthy segments.", "Targeted containment beats both a campus-wide pull and leaving the infected VLAN up for shipping. You can keep a documented path elsewhere if telemetry stays clean. Surgery first; a wider shutdown remains available if neighbours light up.", rec09, "Keep a documented operations path only if it is still safe.", "You can be both fast and precise.", "VLAN-WMS-3 is isolated. Neighbouring segments remain up under watch."),
      o("lo-09-c", "high-risk", "Leave the infected VLAN up so orders can still ship", "Prioritise today's pallets and assume encryption will stay in aisle C.", [0, 3, 0], "The malware uses the still-up VLAN as a highway to shares and identity.", "Availability without isolation is a gift to the attacker. Shipping is not a substitute for segmentation. Once encryption is observed on a segment, that path is hostile until it is cut.", rec09, "Throughput on an infected segment is attacker infrastructure.", "Uptime can be an incident amplifier.", "Aisle C continues encrypting while pallets leave."),
    ]),
  q("lo-10", "contain", "Remote staff still connected over corporate VPN",
    "Endpoint telemetry shows remote laptops still on the corporate VPN, including OneDrive sync of shared warehouse folders. One session belongs to a warehouse supervisor whose laptop is on public Wi-Fi. That account has local administrator rights on several warehouse PCs.",
    "Remote users are still syncing files from home and public networks.",
    "How should remote access be contained without stranding responders?",
    ["identity", "DORA"],
    [
      o("lo-10-a", "strong", "Revoke risky sessions and pause bulk sync; keep break-glass VPN for responders", "Force-end the supervisor session and other high-risk connections. Leave a watched path for the incident team.", [3, 2, 2], "Home and public-network PCs stop feeding warehouse shares, and responders can still reach tools.", "Session control is containment. Voluntary disconnects will be incomplete; guest Wi-Fi adds an unmonitored campus. Revoke, pause sync, and keep a named exception for people who must act.", rec10, "Remote access is part of the campus during ransomware.", "Identity is a network edge.", "Risky VPN sessions are revoked and OneDrive sync of warehouse libraries is paused."),
      o("lo-10-b", "weak", "Ask staff in chat to disconnect themselves", "Send a message requesting that people drop VPN until further notice.", [1, 2, 1], "Half the users stay connected to finish one email; the supervisor session remains active on public Wi-Fi.", "Voluntary disconnect is not a control. Privileged and syncing sessions need forced revocation. Polite requests leak time to the attacker and cannot be evidenced as containment.", rec10, "Force the session end, then communicate.", "Courtesy is not session termination.", "Fourteen people reply that they will disconnect after one more file."),
      o("lo-10-c", "high-risk", "Move remaining work onto guest Wi-Fi as a workaround", "Tell remote staff to use the cafe or guest SSID instead of VPN.", [0, 1, 0], "You add an unmonitored path with no logging, MFA posture or DLP.", "Workarounds need security review too. Guest Wi-Fi is not a business-continuity plan for privileged warehouse access. You would trade a logged VPN problem for a blind one.", rec10, "Do not invent a second, unmonitored campus.", "Guest networks are not an incident-response access method.", "Staff move to guest SSIDs that Security cannot see."),
    ]),
  q("lo-11", "contain", "Backup locations unconfirmed and unrestored",
    "Finance says warehouse backups sit in a cloud vault. Operations believes a copy may exist on an encrypted drive in the server room. No restore has been tested this year. Leadership is asking whether systems will be back on Monday.",
    "Nobody here can point to a backup we have actually restored.",
    "What should be done before any recovery date is promised?",
    ["NIST CSF Recover"],
    [
      o("lo-11-a", "high-risk", "Promise Monday go-live based on the assumed copies", "Give leadership a date from the catalogue entries without a restore test.", [1, 0, 0], "You commit to a date you cannot defend if the vault is incomplete or the drive is unreadable.", "Recovery dates need evidence. Catalogue folklore and an untested drive are not a go-live plan. Locate, protect and test-restore a sample first, then offer a range with confidence language that matches the proof.", rec11, "Proof before any public or board date.", "A backup you have not restored is a rumour.", "Monday is already being briefed to a key customer."),
      o("lo-11-b", "strong", "Locate copies, protect them and test-restore a sample", "Prove one file and one system restore before any date is offered.", [2, 3, 3], "You learn what is actually recoverable and you stop further backup jobs from overwriting good copies.", "Test restores beat folklore. Restoring everything at once may bring malware back with the data; promising Monday without a test sets a false clock. Immutability only matters if you can find and boot the copy.", rec11, "This is how you earn a date you can stand behind.", "Proven-clean beats merely listed in a catalogue.", "A sample restore is running against an isolated recovery host."),
      o("lo-11-c", "weak", "Start restoring every system in parallel", "Launch all backup jobs at once to save time.", [1, 1, 1], "Failures hide in volume, restore order is lost, and infected data may return onto still-connected networks.", "Restore order is a control: critical services first, onto clean, isolated infrastructure, after a sample works. Flood restores hide failures and can reintroduce the foothold.", rec11, "Sequence beats volume.", "Parallel restore without isolation is not speed; it is noise.", "Twelve restore jobs compete and two fail without an owner noticing."),
    ]),
  q("lo-12", "contain", "Extortion note with a payment portal and countdown",
    "A ransom note on affected PCs includes a Tor payment URL, an email address and a 72-hour countdown. Legal has not been briefed. A staff member has drafted a reply asking whether a test file can be decrypted.",
    "Someone was about to send a reply to that address.",
    "How should the extortion contact be handled?",
    ["extortion"],
    [
      o("lo-12-a", "high-risk", "Reply to the actor to test whether they will decrypt a file", "Open a conversation and ask for proof of decryption before leadership decides.", [0, 0, 0], "You create an uncontrolled trail, leak intent and may start a negotiation with no authority or record.", "Do not freelance extortion talks. Contact, even for 'proof', is a legal and strategic decision. Preserve the note, keep the draft unsent, and put counsel and the incident lead on a logged path.", rec12, "Silence can be a control until counsel agrees a path.", "Criminal payment portals are not an incident-command channel.", "An unauthorised reply is already on its way to the actor."),
      o("lo-12-b", "strong", "Preserve the note, do not reply, and call counsel", "No contact and no payment until a logged legal and leadership path exists.", [2, 2, 3], "You keep options without feeding the actor or starting a payment trail.", "Process beats improvisation. A test reply or a test payment both create facts you cannot take back. Preservation of the note supports later investigation and any regulated notification.", rec12, "This keeps the organisation inside a defensible path.", "Extortion is a legal and executive track, not a helpdesk thread.", "Counsel is on the call and the note is hashed into the evidence store."),
      o("lo-12-c", "weak", "Send a small test payment to see whether the portal works", "Transfer a token amount so finance can confirm the wallet and process.", [0, 1, 0], "You start a payment path without a decision, and the actor treats it as engagement.", "Test payments are still payments. They have sanctions, accounting, insurance and criminal implications. Curiosity is not a control. Preserve, do not pay, wait for counsel.", rec12, "Do not probe the portal 'for science'.", "A proof-of-life payment is still a payment decision.", "Finance asks which cost centre should hold an unauthorised transfer."),
    ]),
  q("lo-13", "control", "Privileged backup account authenticating from an unexpected location",
    "Identity logs show a backup service account with domain-level rights authenticating from an ASN associated with a public cafe network. The account has not been rotated in 18 months. Similar service accounts exist for tape and cloud backup jobs.",
    "That account should only run from the backup server on the internal network.",
    "What should identity and security do about the unexpected authentication?",
    ["identity"],
    [
      o("lo-13-a", "strong", "Disable or rotate the account and review sibling service accounts", "Kill sessions, replace credentials, and check other backup identities for the same pattern.", [3, 2, 2], "A likely pivot path closes, and related accounts are not left as copies of the same problem.", "Credential hygiene is containment for a privileged identity used off its expected host. Renaming without rotation leaves the secret valid. Watching without a kill plan leaks more. Assume the family of backup accounts may be messy.", rec13, "Treat service accounts as privileged identities, not background noise.", "Account names and comments are not access controls.", "The unexpected session is dead and a review of related backup identities is under way."),
      o("lo-13-b", "high-risk", "Rename the account and leave the existing credentials in place", "Change the display name so the original identifier is harder to find.", [0, 1, 0], "The same secret still works from the cafe ASN under a new label.", "Renames are not rotations. Identity changes must invalidate old material. The attacker already has the credential; a new name is camouflage for operators, not for the actor.", rec13, "Rotate secrets; do not rebrand them.", "Identity changes must invalidate old material.", "The cafe ASN still authenticates successfully after the rename."),
      o("lo-13-c", "defensible", "Monitor the account without disabling it yet", "Collect more telemetry on the unexpected ASN before taking the account down.", [2, 2, 1], "You may learn a command-and-control pattern and also allow further data access.", "Observation without a ready kill switch is a stall. It can be defensible for a short, named window with an abort. Given domain-level backup rights from a public ASN, disable or rotate first.", rec13, "Watch only with a pre-agreed abort and a short clock.", "Monitoring is not a substitute for containing a privileged credential.", "The account remains active while analysts watch the cafe ASN."),
    ]),
  q("lo-14", "control", "Patching proposed on hosts still being imaged for evidence",
    "An administrator wants to apply overdue security patches to every server, including two warehouse file servers that forensics is still imaging. Those hosts show signs of the encrypting process. A change freeze was declared two hours ago.",
    "If we patch now, at least the vulnerability dashboard will go green.",
    "In what order should preservation and patching happen?",
    ["change freeze"],
    [
      o("lo-14-a", "high-risk", "Patch the evidence hosts first so they look healthy", "Apply updates on the two file servers currently being imaged.", [0, 1, 0], "Patching overwrites forensic value on the systems that still tell the story of the attack.", "Healthy is not the same as preserved. Do not remediate hosts still being imaged. Snapshot and image, then patch remaining exposed systems by impact, under the incident change process.", rec14, "Do not patch the hosts that still hold forensic evidence.", "Incident freeze is ordered work, not a ban on all future patching.", "The evidence servers reboot mid-image with a new patch baseline."),
      o("lo-14-b", "strong", "Snapshot first, then patch remaining exposed systems by priority", "Finish images on the two file servers. Patch other crown-jewel hosts with a logged change.", [3, 2, 2], "You harden what is still exposed without erasing the investigation.", "Order of operations matters: preserve, then reduce exposure. Blocking all patches until next quarter leaves known holes open. Patching evidence boxes first destroys the case.", rec14, "This is the safe sequence during an incident freeze.", "Incident freeze is not forever, but it is ordered.", "Images complete. A logged patch window is scheduled for remaining exposed systems."),
      o("lo-14-c", "weak", "Block all patching until next quarter", "Treat the freeze as a seasonal ban on any security update.", [1, 1, 1], "Known exploitable holes stay open on systems that are not evidence stores.", "An incident freeze is a sequencing tool, not a quarter-long holiday. After snapshots, thaw with a list ordered by exposure. Unpatched forever is also a risk.", rec14, "Thaw with a prioritised list once evidence is secured.", "A freeze without an exit is a second vulnerability.", "The vulnerability backlog continues to grow on non-evidence hosts."),
    ]),
  q("lo-15", "control", "Privileged accounts still authenticating with passwords only",
    "Directory reports show half of the warehouse administrator accounts, including remote VPN admins, have no MFA enrolled. Several of those passwords are short and reused. Reopening of remote administration tools is being discussed for the recovery window.",
    "Privileged sign-in is still password-only for several warehouse admins.",
    "When should MFA be enforced on privileged and remote access?",
    ["MFA"],
    [
      o("lo-15-a", "strong", "Enforce MFA on privileged and remote paths now, with documented break-glass", "Block password-only admin and VPN before celebrating any reopen.", [3, 2, 2], "Stolen or reused passwords bounce on the paths that matter most.", "Identity is the perimeter even in a warehouse. Delaying MFA because people are tired, or substituting a shared SMS handset, both leave a second incident in place. Document a break-glass account so response is not stranded.", rec15, "Do this before any remote-tool reopen.", "Passwords alone are not a privileged-access control family.", "MFA enrolment is mandatory for remaining admin and VPN accounts before reopen."),
      o("lo-15-b", "weak", "Delay MFA until the team has rested", "Leave password-only admin in place overnight and revisit tomorrow.", [1, 2, 1], "The attacker is not constrained by staff fatigue; password reuse remains live.", "Fatigue is not a compensating control. Stolen passwords work at 03:00 as well as at 15:00. Enforce MFA on privileged paths now, with break-glass, then rest in shifts.", rec15, "Tired people still need a second factor.", "Delay here is often the start of a second incident.", "Password-only admin sessions continue overnight."),
      o("lo-15-c", "high-risk", "Use SMS codes to a shared on-call handset as MFA", "Put one brick phone in the warehouse office and share the codes.", [0, 1, 0], "A shared factor is a shared incident: whoever holds the handset holds the estate.", "MFA needs unshared authenticators bound to a person or a named, logged break-glass process. A shared SMS device is not possession that is personal. It also fails phishing-resistant guidance.", rec15, "Shared handsets are not authenticators.", "Possession must be personal, or break-glass must be logged and rare.", "Twenty unused codes sit on a shared desk phone."),
    ]),
  q("lo-16", "control", "Scanner vendor offering an unsolicited remote support session",
    "The handheld-scanner vendor emails that an engineer can connect immediately via an unmanaged remote-support tool to get picking back online. There is no open support ticket, no named engineer in the contract, and no jump-host procedure for this vendor.",
    "They say they can be on a warehouse PC in ten minutes.",
    "Under what conditions should vendor remote access be accepted during the incident?",
    ["third party"],
    [
      o("lo-16-a", "high-risk", "Allow the vendor remote tool directly on a warehouse PC", "Accept the unmanaged client so picking can resume faster.", [0, 2, 0], "You add an untracked administrator on an already-untrusted floor.", "Remote tools are identity events. Speed does not justify an unmonitored third-party admin during ransomware. Help should arrive inside your jump host, MFA, ticket and watch.", rec16, "Helpful vendors are still third parties.", "Uncontrolled remote access is a second incident path.", "An unmanaged remote-support client is installed on a warehouse PC."),
      o("lo-16-b", "strong", "Time-bound jump host, MFA, ticket and a watched session", "Name the engineer, expire the access, and keep your staff on the session.", [3, 2, 2], "Expertise arrives inside your controls instead of as mystery admin.", "Refuse the uncontrolled path, not all help. A blanket refusal loses skills you may need; a direct vendor tool on a warehouse PC is an untracked admin. Rails are how you say yes safely.", rec16, "This is how you accept help without inheriting a second breach.", "Third parties inherit your incident; they do not get to redefine access.", "The vendor is on a jump host with an expiry and a named watcher."),
      o("lo-16-c", "weak", "Refuse all vendor assistance for the duration of the incident", "Allow no supplier access of any kind until the estate is fully clean.", [2, 0, 1], "You keep purity and lose expertise that may be required to restore scanners safely.", "Refuse uncontrolled access, not the people. Expertise is allowed; mystery admin is not. A ticketed, watched path is the middle that actually contains risk.", rec16, "You can accept help with rails.", "Zero vendor contact is not the same as zero-trust access design.", "Scanner restoration stalls for lack of vendor knowledge."),
    ]),
  q("lo-17", "evidence", "Uncontrolled inspection of a suspected ransomware sample",
    "A technician proposes copying the encrypting binary from an affected PC onto a personal USB drive so they can inspect it on their laptop. The drive has been used on home systems. Memory of the affected host has not been captured.",
    "I can take a copy on this USB and check it on my machine.",
    "How should the suspected sample be examined?",
    ["forensics"],
    [
      o("lo-17-a", "high-risk", "Copy the live binary to a personal USB and inspect it on a laptop", "Move the sample onto removable media that has already been used off-site.", [0, 0, 0], "You may trigger further encryption, contaminate the laptop and break chain of custody.", "Do not plug unmanaged media into a live patient or take the payload home. Curiosity is not a containment tool. Plan an out-of-band look from snapshots on an isolated analysis host.", rec17, "Plan the inspection; do not improvise with personal media.", "Access the core with a logged, isolated method.", "The USB is connected to the affected PC while the encrypting process is still running."),
      o("lo-17-b", "strong", "Inspect out-of-band from snapshots, read-only where possible", "Use an isolated analysis host and preserve memory and disk first.", [3, 2, 2], "You learn behaviour and indicators without feeding the live process or contaminating other devices.", "This is how you look without poking the patient. Ignoring the sample leaves the beacon uncharacterised; a personal USB is how you spread it. Logged, read-only methods keep evidence and staff laptops intact.", rec17, "This is how you examine malware without multiplying it.", "Forensic access is a method, not a shortcut.", "A snapshot is mounted read-only on the analysis VLAN."),
      o("lo-17-c", "weak", "Defer malware analysis until operations are restored", "Skip sample inspection and wait for encryption activity to subside on its own.", [1, 1, 1], "The beacon keeps pulsing and you still have no indicators to hunt elsewhere.", "Waiting is not a control objective. Unobserved malware does not pause because operations are busy. A careful out-of-band inspection is how you obtain hashes, command-and-control indicators and sibling hosts without making the situation worse.", rec17, "Examine the sample carefully on an isolated host.", "Unobserved malware continues on its own clock.", "No new indicators are produced while other warehouse hosts start showing the same process."),
    ]),
  q("lo-18", "evidence", "Competing requests for a single forensic disk image",
    "Law enforcement cyber has asked for a copy of the imaged warehouse file server. A scanner vendor also wants the same image for an internal write-up. You have one verified disk image and no chain-of-custody log yet.",
    "Two parties want the same image and we have not logged who would receive it.",
    "How should copies of the forensic image be shared?",
    ["chain of custody"],
    [
      o("lo-18-a", "high-risk", "Email the image to whoever asked first", "Send the file as soon as a request arrives so you appear responsive.", [1, 1, 0], "Chain of custody evaporates and an uncontrolled copy may be published or mishandled.", "Copies need a ledger, hashes and a named approver. Speed is not professionalism if the image becomes a blog post or an untracked attachment. Counsel should gate law-enforcement and vendor requests.", rec18, "Process is the product in evidence handling.", "Share with a process, not a queue position.", "An unhashed image is in an external mailbox with no custody record."),
      o("lo-18-b", "strong", "Produce hashed copies with a custody log and a named approver", "Prioritise any legally required law-enforcement path; vendor copies wait on the same log.", [2, 2, 3], "You can show who touched what, when, and why.", "Evidence handling is an incident-response skill. Refusing all copies may block a legitimate investigation; emailing the first requester destroys the ledger. Hashes and a log survive later questions.", rec18, "This is the record that survives insurers, regulators and court.", "Chain of custody is how a disk image remains evidence.", "Hashes are recorded and counsel confirms the law-enforcement path."),
      o("lo-18-c", "weak", "Refuse all copies indefinitely", "Keep the only image on the analysis host and share it with nobody.", [2, 1, 1], "You may block a legitimate investigation and still have no custody log for the copy you hold.", "Controlled sharing beats a blanket refusal. Law-enforcement requests need a legal owner, not a sulk. Build the log even if the first external share is delayed.", rec18, "Refusal still needs a legal owner and a recorded reason.", "What they cannot have cannot leak — and may also be evidence they are entitled to.", "The image sits unlogged while a formal request waits without a decision."),
    ]),
  q("lo-19", "evidence", "Insurer requesting a single incident timeline",
    "The cyber insurer has asked for a chronology that reconciles the ransom-note timestamp, helpdesk tickets, SIEM data including the missing hour, and three internal chat threads that disagree on when encryption started.",
    "They want one timeline. Our sources do not currently agree.",
    "How should the timeline be prepared for the insurer?",
    ["DORA"],
    [
      o("lo-19-a", "high-risk", "Send only the most favourable chat thread", "Provide a clean chronology that omits the SIEM gap and conflicting tickets.", [1, 1, 0], "You create a false record that will not survive comparison with tickets and telemetry.", "Do not curate reality. Insurers compare sources. Honesty includes uncertainty: one spine, sources attached, conflicts marked. A raw dump without a cover note is harder to read but still better than a polished fiction.", rec19, "Honesty includes uncertainty.", "A single invented chronology is not a claim file.", "The insurer later matches the omitted SIEM gap to your 'complete' story."),
      o("lo-19-b", "strong", "Reconcile sources into one timeline and mark conflicts", "Attach tickets, telemetry and messages. Show where they disagree.", [2, 2, 3], "Your story can be checked, including the missing collection hour.", "A single spine with marked conflicts beats both a brand-safe thread and an unexplained raw dump. Volume is not clarity; omission is worse. This is the record you wanted for insurers and later regulators.", rec19, "This is the chronology you can defend.", "A checkable timeline is an incident artefact, not a communications product.", "Conflicts and the SIEM gap are visible on the insurer chronology."),
      o("lo-19-c", "defensible", "Send all raw exports without a covering narrative", "Forward tickets, chats and SIEM dumps and let the insurer assemble the story.", [2, 1, 2], "The file is complete and easy to misread; delays follow while they reconstruct what you could have summarised.", "Raw dumps still need a short cover note: facts, unknowns and known conflicts. Completeness helps, but you remain responsible for a human-readable spine. This is defensible if you lack time, not if you are hiding disagreements.", rec19, "A short cover note still helps a complete export.", "Volume is not clarity.", "The insurer asks for a one-page spine after opening a large export."),
    ]),
  q("lo-20", "communicate", "Retail customer asking whether their shipment left",
    "A key retailer is on hold asking if today's shipment left the yard. Sales wants a public social post saying everything is fine. Communications has no approved holding statement. Warehouse status is mixed: some pallets are loaded, billing is offline.",
    "Sales is drafting a post that calls this a brief technical glitch.",
    "What should external updates look like at this stage?",
    ["stakeholder communication", "DORA"],
    [
      o("lo-20-a", "high-risk", "Post that this is a routine outage", "Keep the public line light and deny a security incident.", [1, 1, 0], "Customers and regulators remember the understatement when the fuller picture emerges.", "Humour and minimisation are not a disclosure strategy. Vacuum communication gets filled by rumours; a false 'routine outage' is worse. Approved facts, one channel, a next-update time.", rec20, "Cadence beats charisma.", "Tell what you know, and nothing you do not.", "A public post calling it a glitch is already live."),
      o("lo-20-b", "strong", "Issue approved facts through one channel with a next-update time", "Say what still ships, what does not, and when the next statement is due.", [2, 2, 3], "Partners can plan around you without being misled.", "Cadence beats charisma. Briefing only the largest customer creates a fairness and leak problem; calling it routine is a trust crater. One spokesperson, known facts only.", rec20, "This is the communications baseline during an incident.", "Partners need a clock, not optimism.", "The retailer receives a factual holding line and a time for the next update."),
      o("lo-20-c", "defensible", "Brief only the largest customer privately", "Give the key account a fuller picture and stay silent with everyone else.", [2, 2, 1], "You help one partner and create a fairness problem that will leak.", "Selective honesty has a half-life. Secret briefings leak, and smaller customers still need a holding line. Prefer one approved channel; a private VIP call can supplement, not replace, that cadence.", rec20, "Fairness is also trust.", "Secret briefings leak.", "The second-largest customer hears a different story from the yard."),
    ]),
  q("lo-21", "communicate", "Staff group chat circulating a ransom-note screenshot",
    "A warehouse messaging group contains a screenshot of the ransom note and an informal poll about whether the company should pay. Several photos of lock screens are also in the thread. There has been no official internal briefing.",
    "The floor is discussing the note in a group chat we do not control.",
    "How should unofficial staff discussion of the incident be handled?",
    ["insider comms"],
    [
      o("lo-21-a", "weak", "Ban personal phones on the floor immediately", "Confiscate devices so screenshots and polls cannot continue.", [1, 0, 1], "Morale drops, useful photos of lock screens are lost, and the poll simply moves to another channel.", "Policy without an official channel fails. Staff are both sensors and a leak surface: they need a place to put what they saw. A brief plus an official drop treats them as allies; a phone ban only drives the conversation underground.", rec21, "Your people need a sanctioned place for what they observed.", "A device ban is not an internal communications plan.", "Phones disappear from view; the poll continues on another group."),
      o("lo-21-b", "strong", "Issue an internal brief and an official screenshot drop; close the poll", "Thank people, tell them what to do and not to do, and provide a single internal source.", [2, 2, 3], "Rumour slows. Staff know where to send photos and that payment is not a floor vote.", "Staff are part of the response. Joining under an alias destroys trust; banning phones without a brief loses sensors. An official channel plus a closed poll is how you treat people as allies.", rec21, "This treats employees as part of containment, not as the enemy.", "A meme thread is not a briefing.", "An internal note is out and the unofficial poll is closed with a pointer to the official channel."),
      o("lo-21-c", "high-risk", "Join the group chat under an alias to monitor staff", "Observe the poll covertly without identifying as incident response.", [0, 1, 0], "You look untrustworthy if discovered, and you may leak more by engaging in character.", "Do not troll or undercover your own incident. Be present as the organisation. Trust dies in costume, and you still have not given people an official brief.", rec21, "Be present as yourself and as the official channel.", "Covert monitoring of staff chat is not internal communications.", "The alias is recognised and trust on the floor drops."),
    ]),
  q("lo-22", "communicate", "Regulatory notification clock under DORA",
    "Counsel notes that a significant ICT-related incident may need notification under DORA Article 19. The first lock banners appeared more than two hours ago. Impact, data theft and root cause are still incomplete. Nobody has started a notification log.",
    "The notification window may already be running and we do not have a full picture.",
    "How should the first regulatory notice be approached?",
    ["DORA Art. 19"],
    [
      o("lo-22-a", "high-risk", "Wait until every fact is confirmed before any notice", "Hold the filing until impact, theft and root cause are complete.", [1, 1, 0], "The deadline does not wait for a perfect brief; you risk late notification.", "Early, factual and incomplete is a valid first notice. Perfect briefs only is how clocks are missed. Start the log: knowns, unknowns, counsel in the room. A raw log dump is also not a filing.", rec22, "Process beats panic and beats perfectionism.", "Notification is a process, not a press release.", "The notification log is still blank while the clock runs."),
      o("lo-22-b", "strong", "Start the notification clock, log facts versus unknowns, keep counsel in the room", "File what you know, mark what you do not, and schedule updates.", [2, 2, 3], "You stay inside the duty of care without inventing certainty.", "Clocks do not pause for style. Waiting for poetry misses the window; a 40-page dump is not a human summary. Facts versus unknowns, with counsel, is how first notices work.", rec22, "This is how a first notice is done under time pressure.", "Incomplete and honest beats late and polished.", "A notification log exists with timestamps, knowns and unknowns."),
      o("lo-22-c", "weak", "Send a raw multi-page log export as the notice", "Forward SIEM and ticket dumps and call it transparency.", [1, 1, 1], "Nobody can act on a slurry of logs, and you still may not have started the formal clock correctly.", "Notifications need a human summary, then attachments. Volume is not a filing. Start the clock with facts versus unknowns; do not substitute a dump for a notice.", rec22, "Summarise, then attach.", "Volume is not a regulatory filing.", "A large export is sent with no cover summary of impact or unknowns."),
    ]),
  q("lo-23", "communicate", "Board member forwarded the ransom note to a journalist",
    "A non-executive director forwarded the ransom note to a technology journalist asking whether it looks serious. Communications was not copied. The journalist has already replied requesting a comment.",
    "A journalist now has the note and is asking for a comment.",
    "How should outbound communications from leadership be brought back under control?",
    ["governance"],
    [
      o("lo-23-a", "high-risk", "Let the board member continue as an informal spokesperson", "Leave directors to handle press because they already have the contact.", [1, 1, 0], "The story leaves the building without a factual spine or a single spokesperson.", "One spokesperson. Directors need a briefing, not an unofficial press role. Governance includes who may speak. Ignoring the press while only chasing packets also loses the story.", rec23, "Directors need a briefing, not an unofficial press role.", "Reputation is an incident track with an owner.", "The journalist already has a quote from the forwarded thread."),
      o("lo-23-b", "strong", "Re-brief the board and lock outbound communications to approved channels", "Facts in. Speculation out. Named spokesperson only.", [2, 2, 3], "Narrative control returns and further unofficial forwards stop.", "This protects trust. Letting the board handle press, or ignoring the journalist to focus only on packets, both abandon the communications track. Re-brief, lock channels, answer through the approved path.", rec23, "This is how governance includes who may speak.", "Reputation is an incident workstream, not a side effect of technical work.", "The board pack is one page of verified facts and a named spokesperson."),
      o("lo-23-c", "weak", "Ignore the press contact and focus only on technical containment", "Leave communications unowned while isolation continues.", [2, 1, 1], "Packets do not call journalists back; the story runs without you.", "You can lose the story while winning the disk. Reputation needs an owner in the same hour as containment. Re-brief the board; do not pretend press will wait for a clean network.", rec23, "Packets and press both need owners.", "Technical success does not automatically produce a true public record.", "Isolation proceeds while an unowned comment deadline passes."),
    ]),
  q("lo-24", "recover", "Manual picking proposed without a reconciliation process",
    "Warehouse operations proposes clipboards and verbal aisle calls so a few priority pallets can still leave. There is no written procedure, no photo confirmation of what ships, and warehouse-management stock records are already out of date.",
    "We can keep a few lorries moving if people write the pallet IDs down.",
    "Under what conditions should manual warehouse work continue?",
    ["business continuity"],
    [
      o("lo-24-a", "high-risk", "Start informal clipboard picking with no reconciliation", "Move freight on verbal calls and loose paper with no later match to stock.", [1, 1, 0], "You ship the wrong freight with confidence and invent a second set of books.", "Manual operations need a paper trail, named owners and later reconciliation. Heroism is not a control. Stopping all physical work is safer for systems but starves the business; informal paper is a second incident.", rec24, "Workarounds need controls or they become a second incident.", "Continuity is designed, not improvised.", "Pallets leave against paper that cannot be matched to the WMS."),
      o("lo-24-b", "strong", "Use a documented manual lane with named owners, limited volume and later reconciliation", "Small, photographed movements with an agreed catch-up into systems.", [2, 3, 2], "Critical goods move without inventing unreconcilable stock.", "Continuity is designed. Informal clipboards invent data; a total halt may be unnecessary if a controlled trickle is possible. Name owners, volume caps and how records will be rebuilt.", rec24, "This keeps a pulse without a second incident.", "A designed workaround is a control; an undocumentable one is not.", "A written manual-pick procedure is in use with photo confirmation and a reconciliation owner."),
      o("lo-24-c", "weak", "Stop all physical warehouse work until systems return", "Halt every pallet so no unofficial records can be created.", [2, 0, 1], "You protect systems and starve delivery with no attempt at a controlled pulse.", "Containment should leave a pulse where it is safe. Purity has an operations cost you should name. A documented trickle is usually better than halt-forever, provided stock can later be reconciled.", rec24, "Name the operations cost if you choose a full halt.", "Safety of records matters; so does a designed continuity path.", "The yard is still. Priority customers have no delivery window."),
    ]),
  q("lo-25", "recover", "Vendor offering a full restore from last month's image",
    "The managed-service vendor offers to reimage every warehouse PC from a gold image dated last month. That image predates this encryption event but includes the same unpatched software and the macro-enabled Office configuration used on the intern's PC.",
    "They say last month's image is clean because this attack had not started yet.",
    "How should estate rebuild and data restore be sequenced?",
    ["clean rebuild"],
    [
      o("lo-25-a", "high-risk", "Restore last month's image everywhere without review", "Treat age as innocence and reimage the estate from that snapshot.", [0, 1, 0], "You may reintroduce the same foothold: unpatched software and macro-enabled Office.", "Age is not cleanliness. Restoring an unreviewed pre-incident image can reintroduce the same weaknesses. Rebuild critical services from known-good hardened images; restore data after checks. Mixing live infected disks with new VMs is also unsafe.", rec25, "Gold, hardened images first — not merely older ones.", "A pre-incident image can still carry the conditions that allowed the incident.", "Warehouse PCs return with last month's macro policy intact."),
      o("lo-25-b", "strong", "Rebuild critical services from known-good hardened images, then restore data after checks", "Priority services only, on clean infrastructure, with data restored once integrity is verified.", [3, 2, 2], "You come back narrower and cleaner instead of relocating last month's weaknesses.", "Rebuild is slower and safer. Last month is not a known-good image if it still allows the same initial access. Dual-running infected disks with new VMs keeps the old infection on the network.", rec25, "This is the recovery spine.", "Clean rebuild beats restoring an older, unhardened image.", "Priority services are being built from a hardened image with macros restricted."),
      o("lo-25-c", "weak", "Mix still-infected live disks with newly built virtual machines on the same network", "Run a hybrid estate so some users stay on familiar hardware.", [1, 1, 1], "The old disks keep the encrypting process adjacent to clean rebuilds.", "Do not dual-boot an incident. Hybrid is not a strategy when one side is still hostile. Known-good images, then checked data, on isolated rebuild networks.", rec25, "Do not keep infected pets next to the rebuild.", "A mixed estate is how a clean island is re-infected.", "New VMs and still-active infected disks share a VLAN."),
    ]),
  q("lo-26", "recover", "Pressure to reopen billing the same afternoon",
    "Sales wants the billing service brought back this afternoon for a key account. The billing cluster has been rebuilt but is not yet on a monitored, isolated slice. There is no rollback plan. Endpoint telemetry still shows unexplained outbound connections on the warehouse VLAN.",
    "The account will wait until close of play, not until tomorrow.",
    "What conditions should a partial reopen meet?",
    ["safe restart"],
    [
      o("lo-26-a", "high-risk", "Turn billing on and watch a chat channel for problems", "Rely on staff messages as the detection control once the service is live.", [0, 2, 0], "You may re-infect a clean island; chat is not packet capture or EDR.", "Reopen needs instrumentation and a rollback, not a vibe. A narrow monitored slice with an owner is a controlled experiment. Watching Slack is not observability. Indefinite darkness has a cost you should name, but it is safer than a blind reopen.", rec26, "A partial reopen is a controlled experiment, not a hope.", "A chat channel is not a detection control.", "Billing is reachable from the still-noisy warehouse VLAN."),
      o("lo-26-b", "strong", "Open a narrow monitored slice with a named owner and a rollback", "One service, one abort path, telemetry before customers.", [3, 3, 2], "Revenue can trickle without a second blast radius.", "Safe restart is a design. Chat-watch reopens are how clean islands die; keeping everything dark until next month may be defensible if you name the business cost. Here a monitored slice is available if you finish isolation and rollback first.", rec26, "This is how you reopen on purpose.", "Controlled experiments beat hopes and beat indefinite freeze when a slice is ready.", "Billing is on a watched slice with a documented abort."),
      o("lo-26-c", "defensible", "Keep all customer-facing services dark until next month", "Refuse any reopen until the entire estate is proven clean.", [3, 0, 1], "You avoid reinfection and also lose customers you might have served from a safe slice.", "Over-caution has a cost you should name. If a narrow monitored slice with rollback is ready, using it is usually better. Full darkness remains defensible when telemetry is still hostile and no slice is actually isolated.", rec26, "Name the cost if you wait, and review it on a clock.", "Purity can starve the business; say so if you choose it.", "No billing window is offered; the key account is told to wait until next month."),
    ]),
  q("lo-27", "recover", "Lessons-learned discussion while containment is incomplete",
    "A manager wants a sixty-slide retrospective scheduled before the encrypting process is fully stopped. Another manager wants no written review at all. Key facts about initial access and backup gaps are still in people's heads, not in the incident log.",
    "If we wait until things are calm, we will forget what actually happened this morning.",
    "How should learning be captured while the incident is still active?",
    ["improvement"],
    [
      o("lo-27-a", "strong", "Keep a short living log with owners and 72-hour actions", "Three pages: what worked, what failed, what changes, who owns each item.", [2, 2, 3], "Fixes have names while memories are still accurate.", "Improvement is part of response. A quarterly retro lets detail evaporate; a blame note naming the intern makes people hide the next incident. Capture now, polish later. Blameless is not consequence-free, but hunting individuals fails.", rec27, "Learning delayed is learning denied.", "Write while facts are still in the room.", "A living log exists with owners and dated 72-hour actions."),
      o("lo-27-b", "weak", "Schedule a full retrospective for next quarter", "Wait until the trauma has aged and calendars are free.", [1, 1, 1], "Details evaporate and backup-gap owners are never named.", "Memory is a perishable control. Capture a short living log now; hold a fuller retro later if needed. Delay deletes lessons. Blame notes are worse, but silence until next quarter is still a loss.", rec27, "Capture now, polish later.", "Delay deletes lessons.", "The only booking is a vague slot in next quarter's calendar."),
      o("lo-27-c", "high-risk", "Write a blame note naming the intern who opened the spreadsheet", "Record individual fault as the primary outcome of the incident.", [0, 0, 0], "People hide the next incident; systemic gaps in mail filtering and privilege go unfixed.", "Scapegoats are useless. Culture is a control. The intern may have been the initial click; the organisation still allowed macros, standing admin and untested backups. A living log with owners beats a hunt for a name.", rec27, "Blameless review is not the absence of accountability; it is how you find the real controls that failed.", "Hunting individuals hides the next event.", "Staff stop volunteering facts to the incident log."),
    ]),
  q("lo-28", "close", "Encrypting process still active on the core file server",
    "The warehouse file server that holds shared pick lists still shows the encrypting process and an outbound beacon. Physical access to the server room is available. Someone suggests force-powering the host to stop the beacon, or leaving it running while non-IT facilities reopen.",
    "The core file server is still encrypting and still on the network.",
    "What is the correct last-mile action on the remaining infected core?",
    ["NIST CSF Recover"],
    [
      o("lo-28-a", "high-risk", "Force-power the host and destroy the disk to stop the beacon", "Use physical destruction as the containment method for the core.", [0, 0, 0], "You destroy evidence and may lose the last clean backup mount or recovery keys on that host.", "Violence is not incident response. The last mile is still isolate, preserve, rebuild. Destruction can halt a beacon and also halt forensics and recovery. Leaving the process running is the other failure mode.", rec28, "The destination is a procedure, not a destroyed box.", "The last mile of ransomware response is still a playbook.", "The disk is gone and so is the evidence it held."),
      o("lo-28-b", "strong", "Isolate the host, preserve evidence, then rebuild from known-good media", "Quiet the core without leaving live malware on the network.", [3, 3, 3], "The campus can start coming back on purpose, with a story you can still investigate.", "Containment has a last mile. Force-power and destruction erase evidence; leaving the beacon up while non-IT facilities reopen leaves risk on the network. Isolate, image, rebuild.", rec28, "This is the close you wanted.", "A remaining infected core is still a change-controlled procedure.", "The file server is isolated, imaged and queued for rebuild from known-good media."),
      o("lo-28-c", "weak", "Leave the process running and reopen non-IT facilities first", "Prioritise canteen and morale spaces while the beacon continues.", [1, 2, 1], "The core keeps radiating risk onto any path still connected.", "Morale is not a compensating control for live encryption. Hydrate the team, then contain. Facilities can wait behind isolation of the remaining infected core.", rec28, "Stabilise people, then finish containment of the core.", "Facilities reopen is not isolation of malware.", "The beacon remains active while non-IT spaces reopen."),
    ]),
  q("lo-29", "close", "Leadership wants an all-clear despite unexplained beacons",
    "A vice president wants an all-clear message to staff and customers. Endpoint telemetry still shows unexplained beacons from two warehouse hosts. Heightened monitoring has not been staffed. A draft banner says the incident is over.",
    "Telemetry is not clean, but they want to tell the business we are finished.",
    "What recovery declaration is justified by the current evidence?",
    ["monitoring"],
    [
      o("lo-29-a", "high-risk", "Declare the incident closed and stand down monitoring", "Send the all-clear and return the war room to business as usual.", [0, 1, 0], "You will miss follow-on activity; unexplained beacons go unwatched.", "Closure needs criteria. All-clear is a monitoring decision, not a mood. Controlled recovery with extra eyes is honest; remaining in incident mode forever burns the team — but standing down now is worse.", rec29, "Recovery is a phase, not a mood.", "Declare recovery against monitoring criteria, not a banner.", "The all-clear is out and the two beacons are no longer triaged."),
      o("lo-29-b", "strong", "Declare controlled recovery with heightened monitoring for at least 72 hours", "Reopen what is safe. Keep alerts mandatory and staffed. No all-clear yet.", [3, 3, 3], "You can restart work without lying to yourselves about unexplained beacons.", "This is an honest close. Standing down monitoring misses follow-on activity; infinite incident mode burns people. Name exit criteria: clean telemetry, owned hunt, then a later all-clear.", rec29, "This is a close you can defend to auditors and to staff.", "Recovery is declared against criteria, not against a banner.", "Controlled recovery is declared; a 72-hour heightened watch is staffed."),
      o("lo-29-c", "defensible", "Remain in full incident mode indefinitely", "Keep the war room open with no exit criterion until every anomaly is gone.", [3, 1, 2], "You stay safe and burn the team; decisions slow because nobody is allowed to stand down.", "Name an exit criterion. You can be careful without becoming nocturnal forever. Burnout is also an incident outcome. Heightened monitoring for a defined window is the usual middle.", rec29, "You can be careful without an endless war room.", "Burnout is also an incident outcome.", "The war room has no end date and staff are past a safe shift pattern."),
    ]),
  q("lo-30", "close", "Decade-old archive backup proposed as the restore source",
    "A labelled archive disk from 2019 is found in the backup cupboard. It predates this attack. It also predates several years of warehouse master data, customer records and security hardening. A newer backup from last week exists but has not yet completed a clean-restore test.",
    "This 2019 copy is offline, so some people want to restore from that.",
    "Which backup should be used for recovery?",
    ["backup"],
    [
      o("lo-30-a", "high-risk", "Restore the 2019 copy because it predates the attack", "Treat oldest offline media as the cleanest recovery source.", [0, 0, 0], "You lose years of operations and may still restore old malware or weak configurations.", "Oldest is not cleanest. Provenance beats folklore. Use the newest copy that passes a clean-restore test; keep the 2019 disk offline as an archive. Hand-merging eras in a spreadsheet invents a third universe of data.", rec30, "Proven-clean beats merely old.", "Backup age is not an integrity control.", "2019 master data is being written over current warehouse records."),
      o("lo-30-b", "strong", "Use the newest proven-clean copy and keep the 2019 disk offline as an archive", "Finish the clean-restore test on last week's backup. Do not restore the 2019 archive into production.", [3, 3, 2], "You recover the company you had last week, not a time capsule, and you still have the archive if needed.", "This is the restore you can defend. 2019 predates the attack and also predates the business. Merging by hand in a spreadsheet is not an estate-recovery tool.", rec30, "Finish the clean-restore test, then recover forward from that point.", "Proven-clean beats merely offline and old.", "Last week's backup is under clean-restore test; the 2019 disk stays offline and labelled."),
      o("lo-30-c", "weak", "Manually merge 2019 data with current fragments in a spreadsheet", "Build a combined warehouse master by hand from both eras.", [1, 1, 0], "You invent a third, unreconcilable set of records that neither backup nor production can explain.", "Spreadsheets are not merge tools for estates. Do not hand-merge two eras of master data. Use the newest proven-clean copy, keep the 2019 disk offline, and reconcile through controlled systems — not a workbook.", rec30, "Do not hand-merge two eras of master data.", "A spreadsheet is not a recovery platform.", "A workbook now contains conflicting stock and customer rows with no system of record."),
    ]),
];
