import { option, question, scoreTriple } from "../build";
import type { AnswerOption, AnswerQuality, Question, ScorePoints, StoryPhase } from "../types";

const ALL = ["cave-package", "cave-secret", "cave-cloud"] as const;
const KEYS = ["buildIntegrity", "deliveryResilience", "visibility"] as const;

function pts(a: ScorePoints, b: ScorePoints, c: ScorePoints): Record<string, ScorePoints> {
  return scoreTriple(a, b, c, KEYS);
}

function o(
  id: string,
  quality: AnswerQuality,
  title: string,
  summary: string,
  scores: [ScorePoints, ScorePoints, ScorePoints],
  consequence: string,
  explanation: string,
  recommendedAction: string,
  whyRecommended: string,
  learningPoint: string,
  npcReaction: string,
): AnswerOption {
  return option(id, quality, title, summary, pts(...scores), consequence, explanation, recommendedAction, whyRecommended, learningPoint, npcReaction);
}

function q(
  id: string,
  phase: StoryPhase,
  title: string,
  situation: string,
  npcLine: string,
  prompt: string,
  frameworks: readonly string[],
  options: readonly [AnswerOption, AnswerOption, AnswerOption],
  scenarioIds: readonly string[] = ALL,
): Question {
  return question("dependency-depths", id, phase, scenarioIds, title, situation, npcLine, frameworks, options, { prompt });
}

export const DEPENDENCY_DEPTHS_QUESTIONS: Question[] = [
  q("dd-01", "start", "Unverified major version of a UI helper",
    "A widely used UI helper published two major versions overnight. The changelog cites performance work. The integrity hash no longer matches last week's pin, and the install now fetches an extra archive the team did not request.",
    "The build is green on my workstation. The new tarball pulled itself in during install.",
    "How should the team handle this version jump before it enters the release pipeline?",
    ["dependency scanning", "OWASP"],
    [
      o("dd-01-a", "high-risk", "Ship the new version without verifying the pin", "Customers are waiting, so skip integrity checks and merge.", [0, 3, 0], "A package whose hash does not match the pin rides the release train.", "Pins exist to catch unreviewed substitution.", "Pin the last known-good version, verify provenance, and scan before the package joins the build.", "Integrity checks belong before velocity.", "An unexpected version still needs provenance.", "The release manager records that the pin was bypassed."),
      o("dd-01-b", "strong", "Hold the merge, verify, scan, then proceed", "Restore the last known-good pin and explain the delay with a verification plan.", [3, 2, 3], "The unverified package stays out of the artefact. Delivery still has a dated path.", "A pause with a verification plan is still delivery.", "Pin the last known-good version, verify provenance, and scan before the package joins the build.", "This is how you keep shipping without accepting unknown bits.", "Supply-chain checks are part of the product.", "The pin is restored and the scanner is run against the candidate."),
      o("dd-01-c", "weak", "Delete local dependencies and stop the pipeline", "If the team cannot see the package, it cannot affect the release.", [2, 0, 1], "Work moves to laptops and informal copies. The pipeline is no longer the control point.", "Destroying the workspace is not a pipeline control.", "Pin the last known-good version, verify provenance, and scan before the package joins the build.", "Keep the pipeline; clean the input.", "You can refuse a package without refusing engineering.", "Someone copies node_modules onto a personal drive to keep working."),
    ],
    ["cave-package"]),
  q("dd-02", "start", "Cloud key printed in a public pull request",
    "CI logs include a cloud access key. The job author called it a debug echo. The log is in a public pull request, so the value is already off the build agent.",
    "It was only a debug statement. We can tidy the log after merge.",
    "What is the correct response to the leaked cloud key?",
    ["secrets management"],
    [
      o("dd-02-a", "weak", "Edit the log and assume the key is forgotten", "Delete the comment and treat the leak as closed.", [1, 1, 1], "The key remains valid and copies already exist outside the repository.", "Editing a log is not rotation.", "Rotate and revoke the key, purge caches, and stop jobs from echoing secrets.", "Anyone who fetched the pull request may still hold the value.", "A leaked secret is an incident, not a typo.", "The pull request remains in cloned copies and notification mail."),
      o("dd-02-b", "strong", "Rotate, revoke, and stop the echo", "Treat the key as compromised. Fix the job so secrets cannot print again.", [3, 2, 3], "The leaked credential is unusable and the job no longer prints secrets.", "Rotation is the control that matches a public leak.", "Rotate and revoke the key, purge caches, and stop jobs from echoing secrets.", "This is incident response for CI.", "Debug logs are data stores.", "A pipeline check is added that fails the job if secret patterns appear in output."),
      o("dd-02-c", "high-risk", "Leave the key in place because it is labelled non-production", "Non-production credentials are treated as out of scope.", [0, 2, 0], "The key still opens whatever it can reach, and attackers do not honour environment labels.", "A label is not isolation.", "Rotate and revoke the key, purge caches, and stop jobs from echoing secrets.", "Burn exposed credentials regardless of environment tag.", "There is no safe public key.", "An unrecognised client authenticates with the printed credential."),
    ],
    ["cave-secret"]),
  q("dd-03", "start", "Broad deploy role and silent containers",
    "The cloud application is approaching release. The deploy role can create, delete, and reconfigure almost every service 'just in case'. Application and audit logging is planned for after go-live. The container process runs as root.",
    "The container runs as root so we do not hit permission issues on the night.",
    "Which launch controls should be in place before this service goes live?",
    ["cloud IAM", "container security"],
    [
      o("dd-03-a", "high-risk", "Release with the broad role and add logging later", "Ship now; restrict IAM and enable logs after customers are on.", [0, 3, 0], "You launch a highly privileged, poorly observed system.", "Post-release hardening rarely arrives on the original date.", "Apply least privilege, run non-root, and enable logs before release.", "Release is a security event, not only a product event.", "You cannot detect what you refused to record.", "The first production incident has no usable audit trail."),
      o("dd-03-b", "strong", "Least privilege, non-root process, logs enabled", "Narrow the role, drop container privileges, and turn on the audit trail before traffic.", [3, 2, 3], "The service launches with a smaller blast radius and a usable trail.", "This is how cloud launches stay boring on purpose.", "Apply least privilege, run non-root, and enable logs before release.", "Boring operations are the goal.", "Architecture choices belong on the release checklist.", "The container starts as an unprivileged user with logging already on."),
      o("dd-03-c", "defensible", "Keep the broad machine role; require MFA for humans", "People must use MFA. The pipeline identity stays unrestricted.", [1, 2, 1], "The pipeline identity still holds standing admin at any hour.", "MFA on people does not constrain machine credentials.", "Apply least privilege, run non-root, and enable logs before release.", "Machine identities need least privilege too.", "Pipelines are users.", "The deploy role remains able to rewrite the estate without a human challenge."),
    ],
    ["cave-cloud"]),
  q("dd-04", "start", "Maintainer takeover on a transitive dependency",
    "CI network logs show an unrecognised transitive package opening outbound connections during the build. Registry metadata records that the maintainer account was transferred yesterday. The parent library's changelog does not mention the new dependency, and no one on the team selected it.",
    "A maintainer transfer changes who can publish. It does not, by itself, prove the new publisher is legitimate.",
    "How should the team treat this transitive dependency before the next production build?",
    ["third-party components", "SLSA"],
    [
      o("dd-04-a", "strong", "Block, pin, and replace", "Treat the transfer as unverified until provenance is confirmed. Quarantine the package, pin known-good versions, and plan a replacement.", [3, 2, 3], "The package is quarantined and a known-good pin keeps delivery moving.", "Maintainer account takeovers are a documented supply-chain pattern.", "Block the new package, pin known-good versions, and plan a replacement.", "You can keep delivering without accepting an unverified publisher.", "Transitive dependencies are still in the artefact you ship.", "The release manager records the pin and opens a replacement ticket."),
      o("dd-04-b", "weak", "Block outbound network from CI only", "Stop the builder from making connections and continue to ship the package.", [2, 1, 2], "CI no longer shows the traffic, and the same package still ships to customers.", "Isolating the builder does not isolate the product.", "Block the new package, pin known-good versions, and plan a replacement.", "Fix the artefact, not only the pipeline plumbing.", "The shipped application can still make the same calls at runtime.", "CI is quiet. Production still initiates the connections."),
      o("dd-04-c", "high-risk", "Trust the transfer without verification", "Accept the new maintainer and keep the latest version in the build.", [0, 2, 0], "The unverified package proceeds toward production.", "A registry transfer is not an attestation of integrity.", "Block the new package, pin known-good versions, and plan a replacement.", "Provenance must be checked after a change of custody.", "Account transfers require extra scrutiny, not less.", "The new maintainer's release is promoted with no independent check."),
    ]),
  q("dd-05", "assess", "No generated inventory of the artefact",
    "Nobody can list the libraries inside the release artefact. A spreadsheet named libs_final_v3 is offered as the inventory. It was last edited before the current sprint.",
    "I can identify a native library by filename if we unpack the build by hand.",
    "How should the team produce a trustworthy software inventory?",
    ["SBOM", "NIST SSDF"],
    [
      o("dd-05-a", "defensible", "Maintain the inventory as a spreadsheet", "Keep libs_final_v3 as the system of record and update it in the meeting.", [2, 1, 2], "The list is stale before the meeting ends.", "Inventories that cannot be generated cannot be trusted.", "Generate SBOMs in the pipeline and keep them with the artefact.", "Automation is the inventory.", "You cannot patch what you cannot name.", "The spreadsheet gains a tab of unresolved 'maybe' entries."),
      o("dd-05-b", "strong", "Generate SBOMs in the pipeline", "Produce the inventory with the build and store it beside the artefact.", [3, 2, 3], "Each artefact has a generated component list that can be queried.", "This is how you see what you shipped.", "Generate SBOMs in the pipeline and keep them with the artefact.", "Visibility is a product of the build.", "An SBOM is a means, not a poster.", "The pipeline publishes a component list with the same identifier as the artefact."),
      o("dd-05-c", "high-risk", "Wait until a vulnerability is exploited", "Discover contents when the first incident names a library.", [0, 2, 0], "The first CVE becomes a scavenger hunt through undocumented builds.", "Incidents are a poor inventory tool.", "Generate SBOMs in the pipeline and keep them with the artefact.", "See first, then patch.", "Blind delivery is not resilience.", "External reporting identifies your versions before you can."),
    ]),
  q("dd-06", "assess", "Scanner backlog of four hundred findings",
    "The scanner reports 400 issues. One is a cryptography library on an internet-facing path. Most of the rest sit in an unused tooltip. Leadership wants a single red count on the dashboard.",
    "Leadership wants a single count they can put in the board pack, rather than a triage by exposure.",
    "How should the team prioritise this vulnerability backlog?",
    ["vulnerability prioritisation"],
    [
      o("dd-06-a", "high-risk", "Fix nothing until the count is zero", "Hold all other work until every finding is closed.", [1, 0, 1], "The reachable cryptography issue waits behind noise.", "Zero findings is not a date.", "Fix what is reachable and severe first; accept the rest with named owners.", "Prioritisation is how you keep moving.", "Counts are not risk.", "The dashboard still shows a large number while the internet-facing issue remains open."),
      o("dd-06-b", "strong", "Prioritise by reachability and severity", "Patch the internet-facing cryptography issue now. Schedule the tooltip findings with owners.", [3, 3, 3], "The critical, reachable issue is treated first without pretending the rest vanished.", "This is delivery with a triage method.", "Fix what is reachable and severe first; accept the rest with named owners.", "You can ship and still be serious about risk.", "Triage is a delivery skill.", "The internet-facing library is patched; residual findings have owners and dates."),
      o("dd-06-c", "weak", "Silence the scanner to protect morale", "Suppress findings so builds stay green.", [0, 2, 0], "The team loses the map of what is actually wrong.", "Morale is not a finding.", "Fix what is reachable and severe first; accept the rest with named owners.", "Keep the signal; change the workflow.", "Hiding findings hides work, not risk.", "The scanner is disabled. The cryptography issue is still in the artefact."),
    ]),
  q("dd-07", "assess", "SAST finding that DAST cannot reach",
    "SAST reports a dangerous sink. DAST cannot exercise the path from the current test surface. The developer wants it closed as a false positive because the function behaved as intended on their workstation.",
    "It behaved correctly on my workstation. I am treating that as sufficient review.",
    "How should the team close or keep this SAST finding?",
    ["SAST and DAST", "code review"],
    [
      o("dd-07-a", "weak", "Close as false positive with no record", "Mark it false and leave no rationale or test.", [1, 2, 1], "The next reviewer cannot replay the decision.", "False positives still need evidence.", "Review with a second person, record the rationale, and add a test if you keep the code.", "Decisions should be replayable.", "Workstation behaviour is not a review.", "The ticket disappears with no linked test or note."),
      o("dd-07-b", "strong", "Review, record the rationale, and add a test or a fix", "A second person looks. Either the bug is fixed or the exception has a name and a regression test.", [3, 2, 3], "Either the issue is removed or the accepted risk is documented and tested.", "This is how application security and delivery share a decision.", "Review with a second person, record the rationale, and add a test if you keep the code.", "Collaboration beats a mute button.", "Exceptions are first-class objects.", "A regression test now guards the sink."),
      o("dd-07-c", "high-risk", "Disable the rule for the whole organisation", "Turn the check off everywhere so this ticket can close today.", [0, 3, 0], "A class of bugs is switched off to win an afternoon.", "Organisation-wide mutes are incidents of their own.", "Review with a second person, record the rationale, and add a test if you keep the code.", "If you mute, mute narrowly.", "Rules are memory, not annoyances.", "The rule is gone, and so is the organisational memory of why it existed."),
    ]),
  q("dd-08", "assess", "Cloud front door designed without a threat model",
    "The new cloud front door was sketched in a hallway conversation. Trust boundaries are described as 'the VPC, probably'. Identities, callers, and abuse cases were not written down before IAM was requested.",
    "The hallway conversation is being treated as the architecture review.",
    "What should happen before more IAM is granted to this front door?",
    ["threat modelling", "secure-by-design"],
    [
      o("dd-08-a", "strong", "Spend an hour on a diagram and abuse cases", "Document who can call what, from where, and with which identity.", [3, 2, 3], "Trust boundaries and identities are written before more privilege is granted.", "An hour now saves a month of IAM cleanup later.", "Sketch trust boundaries, identities, and abuse cases before more IAM is granted.", "This is secure-by-design without a forty-page novel.", "Hallway talk is not a boundary.", "A diagram now names callers, identities, and the abuse cases to test."),
      o("dd-08-b", "defensible", "Copy the previous system's diagram", "Reuse last year's model so the review can finish today.", [2, 2, 1], "You inherit last year's wrong trust assumptions.", "Reuse the method, not the fiction.", "Sketch trust boundaries, identities, and abuse cases before more IAM is granted.", "Draw this system.", "Context is the point of the model.", "The copied diagram still describes a data centre that is no longer in use."),
      o("dd-08-c", "high-risk", "Skip modelling because a WAF is in place", "Treat the web application firewall as the threat model.", [0, 3, 0], "The front door stays wide, poorly specified, and hard to audit.", "A WAF does not model threats.", "Sketch trust boundaries, identities, and abuse cases before more IAM is granted.", "WAFs help; they do not replace thinking.", "Secure-by-design is a conversation with a diagram.", "IAM is granted against an undocumented trust story."),
    ],
    ["cave-cloud"]),
  q("dd-09", "contain", "Exploited library CVE against a release window",
    "A critical library CVE is being exploited in the wild. The release window closes in two hours. A developer already has the unpatched version on the release candidate.",
    "Can we apply the vendor patch as an unreviewed change in the deployment tunnel?",
    "How should the team handle this exploited CVE against the release window?",
    ["emergency patching"],
    [
      o("dd-09-a", "high-risk", "Ship the unpatched release and patch next week", "Protect the original schedule; treat the CVE as follow-up work.", [0, 3, 0], "Known exploitation rides with the customers.", "A sacred schedule still fails if the cargo is exploited.", "Patch the reachable critical issue now through a fast, reviewed path.", "A short process beats a long outage.", "Emergency paths should exist before the emergency.", "The release goes out with a library that is already being exploited."),
      o("dd-09-b", "strong", "Fast path: patch, review, and cut a small release", "Keep the window. Change only the vulnerable component, with a review.", [3, 3, 3], "The reachable critical issue is patched without abandoning review.", "This is resilience, not heroics.", "Patch the reachable critical issue now through a fast, reviewed path.", "You can be fast and reviewed.", "Emergency does not mean unreviewed.", "A small, documented release leaves with the patched library."),
      o("dd-09-c", "weak", "Stop all releases for two weeks", "Impose a maximum freeze until every related ticket is closed.", [3, 0, 2], "Other fixes stall; unofficial deploys begin on laptops.", "A freeze without a fast path relocates delivery.", "Patch the reachable critical issue now through a fast, reviewed path.", "Freeze the dangerous bit, not the company.", "Resilience includes a way through.", "Hotfixes start happening from workstations with no record."),
    ]),
  q("dd-10", "contain", "Build agent with unexpected processes and a new SSH key",
    "A builder virtual machine shows unexpected processes and a newly installed SSH key. It still produces artefacts that pass the existing tests.",
    "If the output is green, we should treat the extra process as unrelated.",
    "How should the team treat artefacts from this builder?",
    ["build provenance", "SLSA"],
    [
      o("dd-10-a", "weak", "Reboot the builder and continue", "Restart the virtual machine and keep using its output.", [1, 1, 1], "The extra key survives. The compromise remains.", "A reboot is not an attestation.", "Isolate the builder, rotate its identity, and rebuild from a known-good image.", "Treat builders as production.", "Compromised CI is upstream of everything.", "The virtual machine returns with the same unauthorised key."),
      o("dd-10-b", "strong", "Isolate, rotate identity, rebuild, and attest", "Do not trust artefacts from a compromised builder.", [3, 2, 3], "New builders, new identities, and attestations replace the compromised path.", "Provenance starts at the builder.", "Isolate the builder, rotate its identity, and rebuild from a known-good image.", "This is how you contain a pipeline compromise.", "Green tests are not integrity.", "A rebuilt image produces artefacts with fresh attestations."),
      o("dd-10-c", "high-risk", "Keep using the builder to protect the deadline", "Continue producing release artefacts from the compromised host.", [0, 3, 0], "Every artefact from this host is now untrusted.", "A deadline does not remove an unauthorised key.", "Isolate the builder, rotate its identity, and rebuild from a known-good image.", "Slip the date rather than ship from a compromised builder.", "Integrity beats the original date.", "Release artefacts continue to be signed by a host an attacker can reach."),
    ],
    ["cave-secret", "cave-package"]),
  q("dd-11", "contain", "World-readable artefact bucket",
    "A bucket labelled temporary is world-readable. It holds a container image and a notes file named oops. The bucket was created for a single transfer and never closed.",
    "Temporary storage was never meant to be a long-lived region of the estate.",
    "How should the team respond to the exposed artefact bucket?",
    ["cloud security", "least privilege"],
    [
      o("dd-11-a", "high-risk", "Leave it public because the name is obscure", "Rely on an unguessable bucket name as the access control.", [0, 2, 0], "Automated scanners do not need a memorable name.", "Obscurity is not an access-control list.", "Make the bucket private, scan what leaked, and rotate anything that was inside.", "Object storage is not a hiding place.", "Cloud storage is a front door.", "Public search already lists the oops object."),
      o("dd-11-b", "strong", "Make it private, scan, and rotate", "Treat the contents as published and respond as an incident.", [3, 2, 3], "The hole is closed and exposed material is treated as compromised.", "Unintended publication is an incident.", "Make the bucket private, scan what leaked, and rotate anything that was inside.", "This is basic cloud incident response.", "Temporary must still be closed.", "The bucket is private; image contents and any embedded secrets are rotated."),
      o("dd-11-c", "defensible", "Protect the objects with a shared URL password", "Add a secret to the link and keep the bucket otherwise reachable.", [1, 2, 1], "The link still travels in chat, tickets, and browser history.", "Shared links are shared incidents.", "Make the bucket private, scan what leaked, and rotate anything that was inside.", "Identity beats a secret URL.", "URLs leak.", "The shared password is reused from the oops filename."),
    ],
    ["cave-cloud"]),
  q("dd-12", "contain", "Direct pushes to main via standing privileged access",
    "Anyone with the organisation's 'temporary admin' role can push directly to main. Branch protection is off. The temporary role was granted three years ago and never expired.",
    "We trust ourselves. That is the control.",
    "How should access to the main branch be controlled?",
    ["branch protection", "CI/CD access"],
    [
      o("dd-12-a", "strong", "Protect main, expire the privileged role, require reviews", "Required reviews, no direct pushes to main, and time-bound privileged access.", [3, 2, 3], "Unreviewed commits to main stop being normal operations.", "Trust is not an access-control list.", "Required reviews, no direct pushes to main, and time-bound privileged roles.", "This is how you collaborate without bypassing the pipeline.", "Temporary access needs an expiry.", "The three-year privileged grant is ended and pull-request reviews become mandatory."),
      o("dd-12-b", "weak", "Ask people in chat not to push to main", "Rely on culture as the merge gate.", [1, 2, 1], "Someone force-pushes 'just this once', repeatedly.", "Culture needs a setting.", "Required reviews, no direct pushes to main, and time-bound privileged roles.", "Settings outlive memories.", "A polite request is not branch protection.", "A pinned chat message is ignored the next time a hotfix is urgent."),
      o("dd-12-c", "high-risk", "Turn protection off so hotfixes are faster", "Remove gates on main to reduce friction.", [0, 3, 0], "Hotfixes and unreviewed changes share the same unrestricted path.", "Speed without a gate is just a leak.", "Required reviews, no direct pushes to main, and time-bound privileged roles.", "Build a real emergency path instead of removing the lock.", "Hotfix paths can still be narrow.", "Main accepts any push from the standing privileged role."),
    ]),
  q("dd-13", "control", "Unsigned artefacts copied by hand to production",
    "Releases are copied by hand to a server named BOX2. Nobody signs the artefacts. BOX2 has a label that says production-ish. Arrival is treated as proof of origin.",
    "If the file arrived on BOX2, we treat it as ours.",
    "How should production verify that a release is the intended artefact?",
    ["signed packages", "SLSA"],
    [
      o("dd-13-a", "defensible", "Post checksums in a chat channel", "Paste hashes into chat and hope someone compares them.", [2, 2, 1], "You can detect some tampering if anyone actually checks.", "Chat is not a signature store.", "Sign in CI, verify on deploy, and refuse unsigned artefacts.", "Verification should be automatic.", "A hash nobody verifies is decoration.", "The chat hash is buried under unrelated messages before deploy."),
      o("dd-13-b", "strong", "Sign in CI and verify on deploy", "BOX2 rejects artefacts that lack a trusted signature.", [3, 3, 3], "Production only accepts artefacts the pipeline signed.", "Provenance is a handshake at deploy time.", "Sign in CI, verify on deploy, and refuse unsigned artefacts.", "This is integrity you can operate.", "Deploy is a verifier, not a copy-paste step.", "Unsigned copies are refused at the production host."),
      o("dd-13-c", "high-risk", "Copy the build from a laptop because it is faster", "Treat a workstation export as the release path.", [0, 3, 0], "The path is now any removable drive or laptop that can reach BOX2.", "A workstation copy is not a provenance system.", "Sign in CI, verify on deploy, and refuse unsigned artefacts.", "Hands are not attestations.", "Human copies skip the evidence.", "A USB transfer becomes the production promotion method."),
    ]),
  q("dd-14", "control", "Console changes that drifted from Terraform",
    "The cloud console has been used for live changes. The repository still has Terraform from April. The two have not been reconciled since April.",
    "The console is being treated as a second pipeline.",
    "How should the team restore a single, replayable change path?",
    ["infrastructure as code"],
    [
      o("dd-14-a", "high-risk", "Keep using the console; treat the repo as documentation", "Click the estate into shape and leave Terraform as a sketch.", [0, 2, 0], "Nobody can replay the estate after an incident.", "Documentation that cannot apply is fiction.", "Make the repository the path; import drift; block silent console changes on important resources.", "Replayability is resilience.", "If you cannot replay it, you cannot recover it.", "A console change labelled as a one-off becomes standing configuration."),
      o("dd-14-b", "strong", "Make the repository the path and import the drift", "Console access is break-glass only, logged, and imported back into code.", [3, 2, 3], "Future changes are reviewable and recoverable from the repository.", "Infrastructure as code is how you see tomorrow's change.", "Make the repository the path; import drift; block silent console changes on important resources.", "This is cloud engineering, not folklore.", "Drift is an incident type.", "Imported resources match the live estate and console edits on those resources are blocked."),
      o("dd-14-c", "weak", "Freeze the console and freeze delivery", "Ban all clicks and all releases until Terraform is perfect.", [2, 0, 2], "People open personal cloud accounts to keep moving.", "A freeze without a paved path relocates clicking.", "Make the repository the path; import drift; block silent console changes on important resources.", "Offer a paved road.", "Blocking without a road makes dirt tracks.", "A personal cloud account named temp appears beside the official one."),
    ],
    ["cave-cloud"]),
  q("dd-15", "control", "Unsegmented east-west access between services",
    "Every microservice can reach every database because segmentation was deferred. That deferred work is now due, after a foothold in a low-sensitivity service.",
    "East-west traffic was left open so teams would not wait on network tickets.",
    "How should internal network access be designed now?",
    ["network segmentation"],
    [
      o("dd-15-a", "weak", "Keep a flat allow-all interior and put a WAF in front", "Harden the front door; leave interior paths open.", [1, 2, 1], "One foothold becomes a tour of the data stores.", "A WAF does not restrict database access for you.", "Segment by sensitivity; default-deny east-west where you can.", "The interior is also a perimeter.", "Flat networks make every bug a breach.", "A compromised front-end service can query the most sensitive database."),
      o("dd-15-b", "strong", "Segment by sensitivity and default-deny east-west", "Sensitive stores are not on the same path as general services.", [3, 2, 3], "A crack in one segment stays in that segment.", "This is architecture as containment.", "Segment by sensitivity; default-deny east-west where you can.", "You can still deliver, with doors.", "Connections should be intentional.", "Database access is limited to the identities that need it."),
      o("dd-15-c", "high-risk", "Open more paths so debugging is easier", "Add standing allow rules to speed incident investigation.", [0, 3, 0], "Debugging becomes a permanent hole.", "Convenience is how holes retire into the baseline.", "Segment by sensitivity; default-deny east-west where you can.", "Debug with time-bound paths.", "Permanent debug access is production access.", "A temporary debug rule from a previous year is still in force."),
    ],
    ["cave-cloud"]),
  q("dd-16", "control", "Unsigned-library exception with no end date",
    "A security exception allowing an unsigned library is four years old. The ticket has a note that the exception is 'still fine' and no owner is assigned to close it.",
    "The original requester is no longer in the organisation. The exception is still treated as current.",
    "How should this standing exception be handled?",
    ["security exceptions"],
    [
      o("dd-16-a", "high-risk", "Renew it indefinitely with no owner", "Treat the exception as inherited policy.", [0, 2, 0], "A four-year hole remains policy.", "Age does not reduce risk.", "Time-box exceptions, name an owner, and track the exit.", "Exceptions are loans, not gifts.", "Heritage holes are still holes.", "The unsigned library remains a standing production dependency."),
      o("dd-16-b", "strong", "Time-box it, name an owner, and require an exit plan", "Keep it only if the end of the exception is visible.", [3, 2, 3], "Either the unsigned library leaves or it is replaced by a real control on a date.", "This is how exceptions stay honest.", "Time-box exceptions, name an owner, and track the exit.", "Delivery can keep a loan with a date.", "Open-ended exceptions are silent risk appetite.", "A calendar review is set and an owner is named on the ticket."),
      o("dd-16-c", "weak", "Revoke it immediately and halt the application", "Remove the library today even if the product cannot start.", [3, 0, 2], "You are correct and offline.", "A cliff is not the only exit.", "Time-box exceptions, name an owner, and track the exit.", "Plan the landing.", "You can end an exception without ending the product.", "The application is down while a replacement is improvised."),
    ]),
  q("dd-17", "evidence", "Application logs dropped at the load balancer",
    "Cloud logs stop at the load balancer because storage cost was described as too high. That cost decision was last quarter. Authentication and application events are no longer retained.",
    "If we cannot see the events, they also cannot appear on the invoice.",
    "How should logging for this service be treated?",
    ["logging and monitoring"],
    [
      o("dd-17-a", "strong", "Keep the trail, budget it, and alert on gaps", "Treat a missing log stream as an incident.", [2, 2, 3], "Authentication and application events are retained, and silence in the stream pages someone.", "Visibility is paid for on purpose.", "Log the authentication and application path; alert if the stream dies.", "This is how you find the next secret leak.", "You cannot respond in the dark.", "A budget line for retention exists and a gap alert is tested."),
      o("dd-17-b", "weak", "Log only errors into a shared inbox", "Forward failures to a mailbox and call that monitoring.", [1, 1, 1], "Nobody reads the inbox at the volume it arrives.", "Inboxes are not telemetry.", "Log the authentication and application path; alert if the stream dies.", "Machines first, inboxes later.", "Detection needs a stream.", "The shared inbox holds thousands of unread errors and no structured search."),
      o("dd-17-c", "high-risk", "Turn logs off to save the quarter", "Disable remaining collection to cut cost.", [0, 2, 0], "The next compromise is invisible.", "Quarters end. Attackers do not.", "Log the authentication and application path; alert if the stream dies.", "Save money on noise, not on evidence.", "Blindness is expensive.", "The bill is smaller. So is your ability to investigate."),
    ]),
  q("dd-18", "evidence", "Production image still runs as root with a shell",
    "The container image runs as root, includes a shell, and still contains a leftover compiler. It is smaller than last year's image, which is being treated as hardening.",
    "Root is the default user in the current base image.",
    "Which image hardening should ship with this service?",
    ["container security"],
    [
      o("dd-18-a", "high-risk", "Ship it because a thinner image is safer", "Treat reduced image size as sufficient control.", [0, 2, 0], "A smaller root process is still a privileged process in production.", "Image size is not least privilege.", "Run non-root, drop the shell in production, and remove leftover compilers.", "Hardening is a release task.", "Thin is not the same as tight.", "The leftover compiler remains available inside the running container."),
      o("dd-18-b", "strong", "Non-root user, minimal image, no leftover toolchain", "A runtime that cannot wander into a shell or a compiler.", [3, 2, 3], "The production image has a reduced attack surface and no privileged default user.", "This is practical hardening.", "Run non-root, drop the shell in production, and remove leftover compilers.", "You still deliver, with less attack surface.", "Images are attack surface.", "The shell and compiler are removed; the process starts as an unprivileged user."),
      o("dd-18-c", "defensible", "Keep root but make the filesystem read-only", "Add one control and leave the privileged user in place.", [2, 2, 1], "Better, still a privileged process.", "Read-only helps; identity still matters.", "Run non-root, drop the shell in production, and remove leftover compilers.", "Stack the controls.", "One control is not a complete meal.", "The filesystem is read-only and the process is still root."),
    ]),
  q("dd-19", "evidence", "Handwritten provenance attached to the release",
    "Someone staples a PDF to the release stating that it was built on a trustworthy laptop. There is no signature from CI and nothing for production to verify.",
    "The laptop has an asset tag, so we are treating the PDF as sufficient provenance.",
    "What provenance should production require before accepting this artefact?",
    ["build provenance"],
    [
      o("dd-19-a", "weak", "Accept the PDF as attestation", "Treat the attached document as proof of origin.", [1, 1, 1], "You cannot verify a PDF the way you verify a signature.", "Attestations need to be checkable.", "Produce signed provenance from CI and verify it at intake.", "An asset tag is not a provenance system.", "Handwritten trust does not scale.", "The PDF is filed; production still cannot cryptographically check the build."),
      o("dd-19-b", "strong", "CI-signed provenance, verified on entry", "Production checks a signature produced by the build system.", [3, 2, 3], "Only artefacts with verifiable build provenance are accepted.", "This is the destination behaving as designed.", "Produce signed provenance from CI and verify it at intake.", "This is integrity you can automate.", "SLSA is a ladder, not a poster.", "A signature from CI is verified before the artefact is promoted."),
      o("dd-19-c", "high-risk", "Skip provenance because the intern is known", "Rely on personal familiarity instead of a signature.", [0, 2, 0], "When that person leaves, so does the story of how the bits were built.", "Knowing someone is not a signature.", "Produce signed provenance from CI and verify it at intake.", "People leave. Signatures remain.", "Trust people to run systems, not to be the system.", "The intern's last day removes the only provenance the team had."),
    ]),
  q("dd-20", "communicate", "Blocked library with no offered alternative",
    "Application security blocked a library after a supply-chain finding. Engineering says the block is stopping a customer delivery. Both facts are true. No replacement or dated exception has been offered.",
    "Security is arriving only as a refusal, with no path to ship.",
    "How should the block be handled so delivery can continue safely?",
    ["developer collaboration"],
    [
      o("dd-20-a", "high-risk", "Hold the block and offer no alternative", "Leave the refusal in place with no known-good version or exception path.", [2, 0, 1], "A shadow copy of the library enters through a laptop.", "No without a path is how unofficial roads form.", "Block the unsafe path and offer a known-good version or a time-boxed exception.", "Help them ship the safe thing.", "Security that cannot say how will be routed around.", "An unreviewed copy of the library is added from a workstation."),
      o("dd-20-b", "strong", "Keep the block and offer a paved alternative", "Name the version that is acceptable, or a one-day exception with an owner.", [3, 3, 3], "People stay on the pipeline and still have a way to ship.", "This is the whole job.", "Block the unsafe path and offer a known-good version or a time-boxed exception.", "You are a delivery partner.", "The best control is a better path.", "Engineering takes the pinned known-good version and the customer date holds."),
      o("dd-20-c", "weak", "Lift the block to preserve the working relationship", "Allow the unsafe library so the conversation stays friendly.", [0, 3, 0], "The unsafe library ships with the release.", "Relationships need honesty, not surrender.", "Block the unsafe path and offer a known-good version or a time-boxed exception.", "Be specific and still constructive.", "A working relationship does not patch a library.", "The blocked finding is waived with no compensating control."),
    ],
    ["cave-package"]),
  q("dd-21", "communicate", "Partner SDK requested to skip security review",
    "A leader wants a security exception for the quarter so a partner SDK can skip review. The SDK requests network access, contact data, and write access to the local filesystem.",
    "Partners are being treated as an extension of our own engineering organisation.",
    "How should the partner SDK be admitted, if at all?",
    ["third-party components", "balancing security with delivery"],
    [
      o("dd-21-a", "defensible", "Allow it with extra production monitoring only", "Skip review and watch for misuse after it is live.", [2, 2, 1], "You might learn. Customers might also learn the hard way.", "Monitoring is not a substitute for a review you skipped.", "Review the SDK, minimise permissions, or delay the partner feature.", "Do the work or delay the feature, honestly.", "Partners are third parties. That is the point.", "The SDK is live with broad permissions and detection as the only control."),
      o("dd-21-b", "strong", "Review, minimise permissions, or delay the feature", "Ship a smaller permission set on time, or move the date.", [3, 2, 3], "The partner still launches, with a smaller blast radius.", "This is an adult trade.", "Review the SDK, minimise permissions, or delay the partner feature.", "Delivery with a smaller blast radius.", "Dates can move. Permissions should not quietly expand.", "The SDK ships with the minimum permissions the feature needs."),
      o("dd-21-c", "high-risk", "Grant full permissions and record a smile in the minutes", "Protect the quarter; skip both review and least privilege.", [0, 3, 0], "The SDK becomes an unconstrained part of the product.", "Meeting minutes are not a sandbox.", "Review the SDK, minimise permissions, or delay the partner feature.", "Do not launder risk through a calendar.", "Quarters are not threat models.", "The minutes record approval. The SDK holds network, contacts, and filesystem access."),
    ]),
  q("dd-22", "communicate", "Vendor workshop requesting standing network access",
    "Operations wants to open security groups for a vendor workshop. The workshop is four hours. The proposed group change has no ticket end date and the requested source is any address.",
    "The vendor asked for 0.0.0.0/0 so they can join from the hotel network.",
    "How should vendor access for the workshop be granted?",
    ["cloud IAM", "network segmentation"],
    [
      o("dd-22-a", "high-risk", "Open 0.0.0.0/0 until someone remembers to close it", "Grant world access with no expiry so the workshop cannot fail.", [0, 2, 0], "The workshop ends. The hole does not.", "Hospitality is not a CIDR policy.", "Time-bound, ticketed, least-access connectivity for the vendor.", "Workshops need doors that close.", "Temporary must be temporary.", "The security group remains open after the vendors have left."),
      o("dd-22-b", "strong", "Time-bound, ticketed, least-access grant", "Four hours, one port, an alarm if it fails to close.", [3, 2, 3], "The vendor still connects. The hole has an owner and an end time.", "This is how cloud access should be granted.", "Time-bound, ticketed, least-access connectivity for the vendor.", "You can be welcoming and finite.", "Expiry is a control.", "The change ticket includes an automatic close and a failure alarm."),
      o("dd-22-c", "weak", "Refuse the workshop entirely", "Block all vendor access, including a designed four-hour path.", [2, 0, 2], "The vendor screenshares over a personal hotspot instead.", "Refuse the standing hole, not the learning.", "Time-bound, ticketed, least-access connectivity for the vendor.", "Design the access.", "Learning can happen inside a fence.", "Someone's phone becomes the unmanaged path into the session."),
    ],
    ["cave-cloud"]),
  q("dd-23", "recover", "Production running a bad package with no tagged rollback",
    "The bad package is in production. Rollback is described as 'redeploy yesterday's build'. Yesterday's artefact is untagged in storage, and nobody can point to a last-known-good digest.",
    "We will recognise the good build when we see it in the artefact listing.",
    "How should rollback be performed, and what should be true next time?",
    ["rollback"],
    [
      o("dd-23-a", "weak", "Hunt yesterday's artefact from memory", "Ask whoever last deployed to identify the file by recollection.", [1, 1, 1], "You may roll forward into a different mess.", "Memory is not a tag.", "Tag releases, keep last-known-good, and rehearse rollback.", "Myths are not runbooks.", "If you cannot go back, you cannot go fast.", "Two candidate artefacts are debated while production stays on the bad package."),
      o("dd-23-b", "strong", "Restore a tagged last-known-good and rehearse the path", "A real artefact identifier, a real owner, and a practised button.", [3, 3, 3], "Customers receive yesterday's known-good build on purpose.", "This is delivery resilience.", "Tag releases, keep last-known-good, and rehearse rollback.", "Practice is the control.", "Rollback is a product feature.", "The tagged digest is redeployed and the runbook is marked as exercised."),
      o("dd-23-c", "high-risk", "Patch forward with an unreviewed one-line change", "Keep momentum by editing production from the incident channel.", [0, 2, 0], "You stack unknown on unknown.", "Forward is not always better.", "Tag releases, keep last-known-good, and rehearse rollback.", "One-line changes still need a path.", "Unknown plus unknown is a genre of outage.", "The one-line change is deployed with a comment that it should be safe."),
    ]),
  q("dd-24", "recover", "Release choice after a compromised dependency",
    "You can release a reduced build without the bad package, delay for a clean rebuild, or ship the original artefact because marketing has already announced the date.",
    "The launch event is being treated as a go-live criterion.",
    "Which release decision protects customers without abandoning delivery?",
    ["secure release decisions"],
    [
      o("dd-24-a", "high-risk", "Ship the original artefact to protect the announcement", "Keep the date. Keep the compromised package.", [0, 3, 0], "The launch event and the compromised package share a stage.", "Marketing is not an attestator.", "Prefer a reduced clean build or a short delay with a named date.", "Dates can be honest.", "An announcement is optional. Integrity is not.", "The original artefact goes live with the known-bad dependency."),
      o("dd-24-b", "strong", "Ship a reduced clean build today", "Cut the risky feature and keep the promise you can keep.", [3, 3, 3], "Customers receive a smaller artefact that does not include the compromised package.", "This is balancing security with delivery.", "Prefer a reduced clean build or a short delay with a named date.", "Ship the safe subset.", "A smaller yes beats a large maybe.", "The reduced build is signed and released; the risky feature is deferred."),
      o("dd-24-c", "defensible", "Delay with a public date", "Hold the full feature and say when it will ship.", [3, 1, 3], "Trust holds. Revenue waits.", "A named delay is a control.", "Prefer a reduced clean build or a short delay with a named date.", "If you cannot reduce, delay in public.", "Silence is worse than a later date.", "The new date is published in a normal font with an owner."),
    ]),
  q("dd-25", "recover", "Rotated CI secret still baked into forgotten jobs",
    "You rotated the CI secret. Deployments still fail because three forgotten jobs have the old value baked into their configuration. Those jobs keep presenting the revoked credential.",
    "We rotated. Why are deployments still authenticating with the previous value?",
    "What does a complete rotation require in this pipeline?",
    ["secrets management", "CI/CD access"],
    [
      o("dd-25-a", "strong", "Inventory baked secrets, retire those jobs, issue short-lived credentials", "Find every use, then replace with a new generation that expires.", [3, 2, 3], "Jobs return with credentials that are not copied into configuration.", "Rotation is a search problem.", "Inventory uses of the secret, replace with short-lived credentials, and watch for old use.", "This is how rotation actually works.", "Forgotten jobs are living fossils.", "The three jobs are found, rebuilt, and no longer store a long-lived secret."),
      o("dd-25-b", "weak", "Restore the old secret so deploys succeed", "Put the burned credential back to recover availability.", [0, 3, 0], "You un-rotate a leaked secret.", "Availability of a burned key is an incident encore.", "Inventory uses of the secret, replace with short-lived credentials, and watch for old use.", "Do not unburn keys.", "Rollback of a leak is not a restore of the leak.", "The old key is valid again and appears in fresh logs."),
      o("dd-25-c", "defensible", "Rotate the long-lived secret by hand every day", "Add a calendar reminder instead of changing the credential model.", [2, 1, 2], "People will skip a day. Attackers will not.", "Toil is not a control family.", "Inventory uses of the secret, replace with short-lived credentials, and watch for old use.", "Automate short-lived credentials instead of heroic calendars.", "Humans are a poor cron.", "A calendar reminder named rotate-credentials is the only remaining control."),
    ],
    ["cave-secret"]),
  q("dd-26", "close", "Admission policy for the trusted build path",
    "The Trusted Build Exit is ahead. You can admit attested builds only, leave the gate open for the quarter, or close it entirely and tell engineers to deploy from laptops.",
    "Laptop deploys would move production onto unmanaged workstations.",
    "Which admission policy should the trusted build path use?",
    ["NIST SSDF", "SLSA"],
    [
      o("dd-26-a", "weak", "Close the trusted path and deploy from laptops", "If the central builder is untrusted, abandon it.", [1, 0, 1], "The supply chain becomes whatever is on each workstation.", "Leaving the paved road is not safety.", "Open the path for attested builds and keep a narrow emergency hatch.", "The vault is the safe path.", "Central builds exist so laptops are not production.", "A workstation LED is now the promotion mechanism."),
      o("dd-26-b", "strong", "Attested builds only, with a narrow emergency hatch", "The door recognises signatures. Emergencies still have a form.", [3, 3, 3], "Only signed, attested artefacts proceed, and break-glass has an owner.", "This is the destination used well.", "Open the path for attested builds and keep a narrow emergency hatch.", "You made delivery safer and still possible.", "A control people can use will be used.", "Unsigned artefacts are refused; the emergency hatch requires two-person approval."),
      o("dd-26-c", "high-risk", "Leave the gate open for the rest of the quarter", "Defer attestation until the next planning cycle.", [0, 3, 0], "The door is decoration.", "A quarter is not a lock.", "Open the path for attested builds and keep a narrow emergency hatch.", "Friction now is cheaper than informal process later.", "Open doors are incidents waiting for a calendar.", "An unsigned package is promoted because the gate does not check."),
    ]),
  q("dd-27", "close", "What to write down after the supply-chain incident",
    "Someone wants the package incident never mentioned again. Someone else wants a ninety-page SSDF mapping. Neither artefact currently has owners or a review date.",
    "Can we put culture in the report and close the incident?",
    "What record should remain after this incident?",
    ["NIST CSF", "NIST SSDF"],
    [
      o("dd-27-a", "high-risk", "Do not record the incident", "Close with no written controls, owners, or follow-up.", [0, 1, 0], "The next package will find you unprepared.", "Silence is not a control objective.", "Write a short living list: pins, provenance, IAM, logs — with owners.", "Memory is a pipeline feature.", "If it is not written, it did not happen.", "No owners are named. The same gap remains in the next sprint."),
      o("dd-27-b", "strong", "A short living list with owners", "Four controls, four names, one date to review.", [3, 2, 3], "The improvements remain visible after the incident channel goes quiet.", "This is improvement as operations.", "Write a short living list: pins, provenance, IAM, logs — with owners.", "Short and owned beats long and abandoned.", "Learning is a delivery system.", "The ninety-page draft is reduced to one owned page with a review date."),
      o("dd-27-c", "defensible", "A ninety-page mapping with no owners", "Map every control statement and assign no names.", [2, 1, 2], "It will be admired and unused.", "Mappings need names to move.", "Write a short living list: pins, provenance, IAM, logs — with owners.", "Frameworks are for steering, not for weight.", "Volume is not adoption.", "An auditor is already lost on page 47 with no named owner to call."),
    ]),
  q("dd-28", "close", "Proposal to pause SBOMs until the company is larger",
    "Product wants to skip software bills of materials until the organisation is bigger. You already ship to customers and already cannot list every transitive library in the last release.",
    "Early-stage teams are being described as having zip files, not supply chains.",
    "Should SBOM generation stay in the pipeline at the current scale?",
    ["SBOM", "balancing security with delivery"],
    [
      o("dd-28-a", "strong", "Keep generating SBOMs as a small habit", "A short list now, a small cost, a large advantage when you must patch.", [3, 3, 3], "You remain able to name what you shipped as you grow.", "Habits are cheaper than archaeology.", "Keep generating SBOMs; they are how you stay able to patch.", "This is enablement for later work.", "You will not get smaller.", "Each release still produces a component list that can be queried."),
      o("dd-28-b", "weak", "Pause SBOMs until the next funding round", "Treat governance as something that starts after investment.", [1, 2, 1], "You will be busy later, too.", "Funding is not a control.", "Keep generating SBOMs; they are how you stay able to patch.", "The cheap habit is now.", "Later you is also tired.", "The next round arrives with a larger undocumented dependency tree."),
      o("dd-28-c", "high-risk", "Replace SBOMs with a wiki promise", "Write that the team will inventory libraries when asked.", [0, 2, 0], "Promises do not generate inventories.", "Wikis are not pipelines.", "Keep generating SBOMs; they are how you stay able to patch.", "Automation does not forget.", "A written promise is not provenance.", "The wiki page is edited; no artefact list is produced with the next build."),
    ]),
  q("dd-29", "contain", "Compromised front-end helper already in the customer app",
    "The compromised package is already serving in the customer-facing application. You can disable the helper and serve a static fallback, or leave it in place because it is described as presentation-only.",
    "Front-end helpers are being described as unable to cause harm because they are not the API.",
    "How should the customer-facing app be contained?",
    ["rollback", "incident response"],
    [
      o("dd-29-a", "high-risk", "Leave it in place as presentation-only code", "Treat front-end as decorative and keep serving the helper.", [0, 2, 0], "Code in the customer's browser still executes.", "Browsers do not care about your architecture slide.", "Disable or remove the helper; tell customers what you know.", "Front-end is production.", "The supply chain reaches the browser.", "The helper continues to run in customer sessions."),
      o("dd-29-b", "strong", "Disable the helper, serve a static fallback, and inform customers", "A smaller application that is still yours, with a public sentence.", [3, 3, 3], "Customers get a page that does not run the compromised code.", "Honesty plus a fallback is resilience.", "Disable or remove the helper; tell customers what you know.", "This is containment people can use.", "You can be smaller and safer today.", "The helper is disabled, a static page is served, and a customer notice goes out."),
      o("dd-29-c", "weak", "Silently remove the helper with no customer notice", "Pull the code and say nothing.", [3, 1, 0], "You remove the execution path and leave a rumour.", "People notice. They fill gaps.", "Disable or remove the helper; tell customers what you know.", "Containment includes a sentence.", "Silence becomes a story.", "Public discussion writes the incident advisory before you do."),
    ],
    ["cave-package"]),
  q("dd-30", "assess", "Pipeline using a holidaying human's cloud key",
    "The pipeline uses a person's cloud key because the service-account request form was long. That person is on leave. The key is still in the job and still valid.",
    "An out-of-office message is not a revocation.",
    "How should this pipeline authenticate to the cloud?",
    ["CI/CD access", "least privilege"],
    [
      o("dd-30-a", "strong", "Workload identity and short-lived credentials", "Pipelines are not people. People go on leave.", [3, 2, 3], "Delivery no longer depends on one person's long-lived key.", "This is how CI grows up.", "Replace human keys with workload identity and short-lived credentials.", "Delivery should survive annual leave.", "Human keys in CI are incidents waiting to happen.", "The job assumes a workload role; the human key is revoked."),
      o("dd-30-b", "defensible", "Keep the human key and add a second person as backup", "Copy the same long-lived secret to another person for coverage.", [2, 2, 1], "Now two people can ship production with a shared secret.", "Sharing a secret is not an identity strategy.", "Replace human keys with workload identity and short-lived credentials.", "Increase people, not copies of a key.", "Bus factor is about knowledge, not key duplication.", "Both people now hold the same standing cloud key."),
      o("dd-30-c", "high-risk", "Paste the key into the team wiki for coverage", "Publish the credential so anyone on shift can deploy.", [0, 3, 0], "The wiki is now a searchable key vault.", "Searchable secrets are a known failure mode.", "Replace human keys with workload identity and short-lived credentials.", "Coverage needs a role, not a paste.", "Wikis are not hardware security modules.", "The key is indexed in wiki search and reused from a browser history."),
    ],
    ["cave-secret"]),
  q("dd-31", "start", "Lockfile refresh that adds a post-install network call",
    "A pull request titled 'refresh lockfile' also adds a postinstall script that makes an outbound request. The diff is large because the package manager rewrote the lockfile. The request was opened by an automation account. Nobody has reviewed the new script.",
    "The lockfile change is being treated as bookkeeping, so the script may be skipped in review.",
    "How should this lockfile pull request be handled before merge?",
    ["NIST SSDF", "OWASP"],
    [
      o("dd-31-a", "high-risk", "Merge it because lockfile updates are routine", "Treat the lockfile as a receipt and skip the script review.", [0, 2, 0], "The postinstall runs in CI as the pipeline identity.", "Large lockfile diffs can hide extra scripts. Install hooks are code and need review.", "Review scripts, pin versions, and require review of install hooks.", "A lockfile is still code.", "Receipts can lie.", "The hook runs in CI and the outbound call is attributed to the build identity."),
      o("dd-31-b", "strong", "Block the merge, inspect the postinstall, and split the change", "Treat the huge diff as a signal. Review the hook before any pin update proceeds.", [3, 2, 3], "The hook is refused. CI stays local until the script is understood.", "Install hooks are code review. Pin and require review on hooks.", "Review scripts, pin versions, and require review of install hooks.", "This is supply-chain hygiene.", "Lockfiles are not above suspicion.", "The postinstall is removed or justified, and the lockfile change is re-opened without the hook."),
      o("dd-31-c", "weak", "Ask the automation that opened the pull request to confirm it is safe", "Take assurance from the same change under review.", [1, 1, 1], "The automation confirms in fluent language and the hook still ships.", "Do not take assurance from the change under review. Humans read hooks.", "Review scripts, pin versions, and require review of install hooks.", "Humans read hooks.", "Automation is not an authorisation.", "The automation replies that the change is safe. The hook is unchanged."),
    ]),
  q("dd-32", "close", "Request to promote an unsigned emergency artefact",
    "The trusted build path will only move a signed artefact. A manager wants to promote an unsigned hotfix once because customers are escalating. There is a documented signed emergency lane. Rollback to the last signed build is also available.",
    "Customer pressure is being treated as a reason to skip the signature check.",
    "How should the unsigned hotfix be handled?",
    ["SLSA", "NIST SSDF"],
    [
      o("dd-32-a", "high-risk", "Promote the unsigned artefact and explain later", "Treat customer pressure as authorisation to skip signing.", [0, 3, 0], "An unsigned artefact reaches production and becomes the template for the next emergency.", "Emergency still needs a signature path. Once is how unsigned becomes policy.", "Use the signed emergency path, or roll back to the last signed build — do not promote unsigned artefacts.", "Customer pressure is not a signing key.", "Once is how unsigned becomes policy.", "The unsigned build is in production. The next hotfix request cites this exception."),
      o("dd-32-b", "strong", "Use the signed emergency lane or roll back", "Customers receive a known artefact, either a signed hotfix or the last good signed build.", [3, 2, 3], "You can name the bits in production in the morning.", "Urgency has a procedure. Integrity is the product.", "Use the signed emergency path, or roll back to the last signed build — do not promote unsigned artefacts.", "This is the control the trusted path exists to enforce.", "Integrity is the product.", "A signed emergency build is produced, or the last signed release is restored."),
      o("dd-32-c", "defensible", "Ship unsigned to five percent of customers with extra logging", "Treat a canary as a substitute for a signature.", [1, 2, 1], "Five percent of customers become the experiment, and the artefact is still unsigned.", "Canaries do not replace signatures. Observe after you can name the bits.", "Use the signed emergency path, or roll back to the last signed build — do not promote unsigned artefacts.", "Observe after you can name the bits.", "Partial unsigned is still unsigned.", "Five percent of sessions run an artefact you cannot attest."),
    ]),
];
