import { option, question, scoreTriple } from "../build";
import type { AnswerOption, AnswerQuality, Question, ScorePoints, StoryPhase } from "../types";

const ALL = ["cave-package", "cave-secret", "cave-cloud"] as const;
const KEYS = ["buildIntegrity", "deliveryResilience", "visibility"] as const;

function pts(a: ScorePoints, b: ScorePoints, c: ScorePoints): Record<string, ScorePoints> {
  return scoreTriple(a, b, c, KEYS);
}

function o(
  id: string,
  quality: AnswerQuality,
  title: string,
  summary: string,
  scores: [ScorePoints, ScorePoints, ScorePoints],
  consequence: string,
  explanation: string,
  recommendedAction: string,
  whyRecommended: string,
  learningPoint: string,
  npcReaction: string,
): AnswerOption {
  return option(id, quality, title, summary, pts(...scores), consequence, explanation, recommendedAction, whyRecommended, learningPoint, npcReaction);
}

function q(
  id: string,
  phase: StoryPhase,
  title: string,
  situation: string,
  npcLine: string,
  frameworks: readonly string[],
  options: readonly [AnswerOption, AnswerOption, AnswerOption],
  scenarioIds: readonly string[] = ALL,
): Question {
  return question("dependency-depths", id, phase, scenarioIds, title, situation, npcLine, frameworks, options);
}

export const DEPENDENCY_DEPTHS_QUESTIONS: Question[] = [
  q("dd-01", "start", "The package that arrived smiling",
    "A popular UI helper jumped two major versions overnight. The changelog says 'performance'. The hash does not match last week's pin. Bats are unimpressed.",
    "It worked on my machine. Also it downloaded itself.",
    ["dependency scanning", "OWASP"],
    [
      o("dd-01-a", "high-risk", "Ship it, lockfile is a vibe", "Customers are waiting. The bats can wait.", [0, 3, 0], "A compromised package rides the release train.", "Pins exist for this exact plot twist.", "Pin, verify, and scan before the package joins the build.", "Integrity before velocity.", "Smiling packages still need provenance.", "A crate labelled 'free trust' appears on the tracks."),
      o("dd-01-b", "strong", "Hold, verify, scan, then proceed", "Pin the last good. Explain the delay with a path.", [3, 2, 3], "The rails glow. Delivery still has a route.", "A pause with a plan is still delivery.", "Pin, verify, and scan before the package joins the build.", "This is how you keep shipping.", "Supply chain is part of the product.", "A bat nods, which is rare."),
      o("dd-01-c", "weak", "Delete node_modules and the sprint", "If we cannot see it, it cannot hurt us.", [2, 0, 1], "Work moves to laptops and USB sticks.", "Scorched earth is not a pipeline.", "Pin, verify, and scan before the package joins the build.", "Keep the pipeline, clean the input.", "You can refuse a package without refusing engineering.", "Someone is copying node_modules onto a mystery stick."),
    ],
    ["cave-package"]),
  q("dd-02", "start", "The secret in the pipeline wallpaper",
    "CI logs show a cloud key. It was 'only a debug echo'. The echo is in a public pull request, which is a lot of echo.",
    "Have you tried turning the secret off and on again?",
    ["secrets management"],
    [
      o("dd-02-a", "weak", "Edit the log and hope", "If we delete the comment, the internet forgets.", [1, 1, 1], "The key is still valid and still copied.", "Hope is not rotation.", "Rotate, revoke, purge caches, and stop echoing secrets.", "The internet has screenshots.", "Leaked secrets are incidents, not typos.", "The PR is still in someone's email."),
      o("dd-02-b", "strong", "Rotate, revoke, stop the echo", "Treat the key as burned. Fix the job.", [3, 2, 3], "Torchlight reaches the pipeline walls.", "Rotation is the apology that works.", "Rotate, revoke, purge caches, and stop echoing secrets.", "This is IR for CI.", "Debug logs are data stores.", "A warning sign appears: DO NOT echo(keys)."),
      o("dd-02-c", "high-risk", "Leave it, it is a non-prod key", "Non-prod means non-problem.", [0, 2, 0], "Non-prod keys still open doors, and attackers do not respect labels.", "Labels are not isolation.", "Rotate, revoke, purge caches, and stop echoing secrets.", "Burn it anyway.", "There is no safe public key.", "A bot in a distant region says thank you."),
    ],
    ["cave-secret"]),
  q("dd-03", "start", "IAM as folklore",
    "The cloud app is approaching release. The deploy role can do 'just in case' things, which is all the things. Logging is 'we will add it if something happens'.",
    "The container is running as root because it felt left out.",
    ["cloud IAM", "container security"],
    [
      o("dd-03-a", "high-risk", "Ship with admin, add logs later", "Later is a strategy.", [0, 3, 0], "You launch a powerful, quiet system.", "Later rarely arrives on time.", "Least privilege, non-root, and logs before release.", "Release is a security event.", "You cannot detect what you refused to record.", "A cloud portal flickers red, then shrugs."),
      o("dd-03-b", "strong", "Least privilege, non-root, logs on", "A smaller role, a smaller container, a louder trail.", [3, 2, 3], "A blue portal hums. Release still happens.", "This is how cloud launches stay boring.", "Least privilege, non-root, and logs before release.", "Boring is the goal.", "Architecture is a release checklist.", "The container sits in a chair like a civilian."),
      o("dd-03-c", "defensible", "Admin role but with MFA on the human", "The pipeline is a robot. Robots are fine.", [1, 2, 1], "The robot still has the keys at 3am.", "MFA on people does not leash machines.", "Least privilege, non-root, and logs before release.", "Machine identities need least privilege too.", "Pipelines are users.", "The robot waves an admin badge cheerfully."),
    ],
    ["cave-cloud"]),
  q("dd-04", "start", "Who invited this crate?",
    "A transitive dependency nobody has heard of started posting network calls in the build. The maintainer's account was 'transferred' yesterday.",
    "Open source is a lifestyle.",
    ["third-party components", "SLSA"],
    [
      o("dd-04-a", "strong", "Block, pin, contact, replace", "Treat the transfer as hostile until proven otherwise.", [3, 2, 3], "The crate is quarantined. A path around it appears.", "Maintainer takeovers are a classic.", "Block the new crate, pin known-good, plan a replacement.", "You can keep delivering without the stranger.", "Transitive does not mean invisible.", "A bat carries the crate away. Teamwork."),
      o("dd-04-b", "weak", "Mute the network from CI only", "Builds should not gossip.", [2, 1, 2], "You hide the symptom in CI and ship it to customers.", "CI isolation is not product isolation.", "Block the new crate, pin known-good, plan a replacement.", "Fix the artefact, not only the plumbery.", "The shipped app still phones home.", "CI is quiet. Production is chatty."),
      o("dd-04-c", "high-risk", "Trust the transfer, they sent an emoji", "Community.", [0, 2, 0], "The stranger rides to production.", "Emojis are not attestations.", "Block the new crate, pin known-good, plan a replacement.", "Provenance beats vibes.", "Account transfers need extra suspicion.", "The emoji is a skull. In retrospect, obvious."),
    ]),
  q("dd-05", "assess", "SBOM or soup",
    "Nobody can list what is in the artefact. Someone offers a spreadsheet named libs_final_v3.",
    "I can smell a DLL.",
    ["SBOM", "NIST SSDF"],
    [
      o("dd-05-a", "defensible", "Hand-maintained spreadsheet", "We are very organised.", [2, 1, 2], "It is stale before the meeting ends.", "Inventories that cannot be generated cannot be trusted.", "Generate SBOMs in the pipeline and keep them with the artefact.", "Automation is the inventory.", "You cannot patch what you cannot name.", "The spreadsheet has a tab named 'maybe'."),
      o("dd-05-b", "strong", "Generate SBOMs in the pipeline", "The artefact and its list travel together.", [3, 2, 3], "Torchlight shows the dependency path.", "This is how you see in the dark.", "Generate SBOMs in the pipeline and keep them with the artefact.", "Visibility is a product of the build.", "SBOM is a means, not a poster.", "A glowing list unrolls like a treasure map, but boring."),
      o("dd-05-c", "high-risk", "We will know it when it explodes", "Monitoring by newspaper.", [0, 2, 0], "The first CVE is a scavenger hunt.", "Explosions are a poor inventory tool.", "Generate SBOMs in the pipeline and keep them with the artefact.", "See first, then patch.", "Blind delivery is not resilience.", "A journalist knows your versions first."),
    ]),
  q("dd-06", "assess", "Vulnerability inbox firehose",
    "The scanner reports 400 issues. One is a crypto library on the internet path. 399 are in a tooltip. Leadership wants a single red number.",
    "Prioritise by font size.",
    ["vulnerability prioritisation"],
    [
      o("dd-06-a", "high-risk", "Fix nothing until the count is zero", "Zero is a lifestyle.", [1, 0, 1], "The important one waits behind noise.", "Zero is not a date.", "Fix what is reachable and severe first; accept the rest with owners.", "Prioritisation is how you keep moving.", "Counts are not risk.", "A dashboard weeps in hexadecimal."),
      o("dd-06-b", "strong", "Reachability and severity first", "Internet-facing crypto now. Tooltips later.", [3, 3, 3], "The rails mend on the critical span.", "This is delivery with a spine.", "Fix what is reachable and severe first; accept the rest with owners.", "You can ship and still be serious.", "Triage is a delivery skill.", "Someone finally draws a line labelled 'actually the internet'."),
      o("dd-06-c", "weak", "Silence the scanner to save morale", "Green builds, yellow ethics.", [0, 2, 0], "You lose the map.", "Morale is not a finding.", "Fix what is reachable and severe first; accept the rest with owners.", "Keep the signal, change the workflow.", "Hiding findings hides work, not risk.", "The scanner is in a cupboard with the bats."),
    ]),
  q("dd-07", "assess", "SAST said maybe",
    "SAST found a sink. DAST cannot reach it. The developer says it is a false positive because it worked on their machine.",
    "My machine is a secure enclave. Emotionally.",
    ["SAST and DAST", "code review"],
    [
      o("dd-07-a", "weak", "Close as false positive, no note", "Vibes as a verdict.", [1, 2, 1], "The next person cannot replay the decision.", "False positives need evidence too.", "Review with a second person, record the rationale, add a test if you keep it.", "Decisions should be replayable.", "Worked-on-my-machine is not a review.", "The ticket vanishes into folklore."),
      o("dd-07-b", "strong", "Review, record, test or fix", "A human looks. A test remains.", [3, 2, 3], "Either the bug dies or the exception has a name.", "This is how AppSec and delivery share a brain.", "Review with a second person, record the rationale, add a test if you keep it.", "Collaboration beats a mute button.", "Exceptions are first-class objects.", "A tiny test bat guards the sink."),
      o("dd-07-c", "high-risk", "Disable the rule for the whole org", "One rule to ignore them all.", [0, 3, 0], "You turn off a class of bugs to win an afternoon.", "Org-wide mutes are incidents of their own.", "Review with a second person, record the rationale, add a test if you keep it.", "Mute narrowly if you mute at all.", "Rules are not annoyances; they are memory.", "The rule is gone. So is the memory."),
    ]),
  q("dd-08", "assess", "Threat model on a napkin, again",
    "The new cloud front door was designed in a hallway. Trust boundaries are 'the VPC, probably'.",
    "The hallway is an architecture review board.",
    ["threat modelling", "secure-by-design"],
    [
      o("dd-08-a", "strong", "Hour with a diagram and abuse cases", "Who can call what, from where, with which identity.", [3, 2, 3], "A blue portal appears where the hallway was.", "An hour now saves a month later.", "Sketch trust boundaries, identities, and abuse cases before more IAM is granted.", "This is secure-by-design without a 40-page novel.", "Hallways are not boundaries.", "Someone draws a box labelled 'not the hallway'."),
      o("dd-08-b", "defensible", "Copy last system's diagram", "Reuse is green.", [2, 2, 1], "You inherit last year's wrong trust.", "Reuse the method, not the fiction.", "Sketch trust boundaries, identities, and abuse cases before more IAM is granted.", "Draw this system.", "Context is the point of the model.", "The copied diagram still mentions a data centre that moved."),
      o("dd-08-c", "high-risk", "Skip it, we have a WAF sticker", "Stickers are controls.", [0, 3, 0], "The front door is wide, stickered, and confused.", "Stickers do not model threats.", "Sketch trust boundaries, identities, and abuse cases before more IAM is granted.", "WAFs help; they do not replace thinking.", "Secure-by-design is a conversation.", "The sticker is holographic and powerless."),
    ],
    ["cave-cloud"]),
  q("dd-09", "contain", "Emergency patch vs the train",
    "A critical library CVE is being exploited. The release train leaves in two hours. A developer is already on the platform, literally.",
    "Can't we hotfix in the tunnel?",
    ["emergency patching"],
    [
      o("dd-09-a", "high-risk", "Ship the train, patch next week", "Schedules are sacred.", [0, 3, 0], "Known exploitation rides with the customers.", "Sacred schedules still explode.", "Patch the reachable critical now with a fast, reviewed path.", "A short process beats a long outage.", "Emergency paths should exist before the emergency.", "The train has a CVE for a conductor."),
      o("dd-09-b", "strong", "Fast path: patch, review, tiny release", "Keep the train, change the cargo.", [3, 3, 3], "The track repairs under your feet. You still arrive.", "This is resilience, not heroics.", "Patch the reachable critical now with a fast, reviewed path.", "You can be fast and reviewed.", "Emergency does not mean unreviewed.", "A small, honest release leaves the station."),
      o("dd-09-c", "weak", "Stop all releases for a fortnight", "Maximum freeze.", [3, 0, 2], "Other fixes stall; shadow deploys begin.", "Freeze without a fast path relocates delivery.", "Patch the reachable critical now with a fast, reviewed path.", "Freeze the dangerous bit, not the company.", "Resilience includes a way through.", "Hotfixes happen on laptops in the dark."),
    ]),
  q("dd-10", "contain", "The build machine is possessed",
    "A builder VM has unexpected processes and a new SSH key. It still produces artefacts that look fine.",
    "If the output is green, the ghost is friendly.",
    ["build provenance", "SLSA"],
    [
      o("dd-10-a", "weak", "Reboot the builder", "Have you tried turning the ransomware... wait, the builder, off and on again?", [1, 1, 1], "The key survives. The ghost is patient.", "Reboots are not attestations.", "Isolate the builder, rotate identity, rebuild from a known-good image.", "Treat builders as production.", "Compromised CI is upstream of everything.", "The VM comes back with opinions."),
      o("dd-10-b", "strong", "Isolate, rotate, rebuild, attest", "Do not trust artefacts from a haunted house.", [3, 2, 3], "New rails, new attestations, fewer ghosts.", "Provenance starts at the builder.", "Isolate the builder, rotate identity, rebuild from a known-good image.", "This is how you contain a pipeline.", "Green output is not integrity.", "A fresh builder lights up like a honest lantern."),
      o("dd-10-c", "high-risk", "Keep using it, we have a deadline", "Haunted is a kind of character.", [0, 3, 0], "Every artefact is now a rumour.", "Deadlines do not exorcise keys.", "Isolate the builder, rotate identity, rebuild from a known-good image.", "Slip the date rather than ship a ghost.", "Integrity beats the original date.", "The deadline applauds. The artefacts giggle."),
    ],
    ["cave-secret", "cave-package"]),
  q("dd-11", "contain", "Public bucket, private feelings",
    "A 'temporary' artefact bucket is world-readable. It contains a container image and a comment file named oops.",
    "Temporary is a cloud region.",
    ["cloud security", "least privilege"],
    [
      o("dd-11-a", "high-risk", "Leave it, the name is obscure", "security-through-unspellable.", [0, 2, 0], "Scrapers do not struggle with spelling.", "Obscurity is not an ACL.", "Make it private, scan what leaked, rotate what was inside.", "Buckets are not hiding places.", "Cloud storage is a front door.", "A search engine already has oops."),
      o("dd-11-b", "strong", "Private now, scan, rotate", "Treat the contents as published.", [3, 2, 3], "A blue portal replaces the open hole.", "Publication is an incident.", "Make it private, scan what leaked, rotate what was inside.", "This is cloud IR 101.", "Temporary must still be closed.", "The bucket puts a door on. Growth."),
      o("dd-11-c", "defensible", "Add a password to the URL", "Links are the new IAM.", [1, 2, 1], "The link still travels.", "Shared links are shared incidents.", "Make it private, scan what leaked, rotate what was inside.", "Identity beats a secret URL.", "URLs leak.", "The password is 'oops' as well. Of course it is."),
    ],
    ["cave-cloud"]),
  q("dd-12", "contain", "Branch protection is a suggestion",
    "Main can be pushed by anyone with the org's 'temporary admin'. The temporary admin is three years old.",
    "We trust ourselves. That is the control.",
    ["branch protection", "CI/CD access"],
    [
      o("dd-12-a", "strong", "Protect main, retire temp admin, reviews on", "The vault door gets a lock that works.", [3, 2, 3], "Surprise commits stop being a lifestyle.", "Trust is not an ACL.", "Required reviews, no direct main, time-bound admins.", "This is how you collaborate without chaos.", "Temporary needs an expiry.", "A three-year sticky note is finally peeled off."),
      o("dd-12-b", "weak", "Ask people nicely in Slack", "Culture as a merge gate.", [1, 2, 1], "Someone force-pushes 'just this once' forever.", "Culture needs a setting.", "Required reviews, no direct main, time-bound admins.", "Settings outlive memories.", "Nice is not branch protection.", "Slack pins a plea. Main ignores it."),
      o("dd-12-c", "high-risk", "Disable protection so we can hotfix faster", "Friction is the enemy.", [0, 3, 0], "Hotfixes and surprises share a pipe.", "Speed without a gate is just a leak.", "Required reviews, no direct main, time-bound admins.", "Make a real emergency path instead.", "Hotfix paths can still be narrow.", "Main is now a suggestion box."),
    ]),
  q("dd-13", "control", "Signed artefacts, unsigned vibes",
    "Releases are copied by hand to a server named BOX2. Nobody signs. BOX2 has a sticker that says production-ish.",
    "If it arrived, it is ours.",
    ["signed packages", "SLSA"],
    [
      o("dd-13-a", "defensible", "Checksums in a chat message", "A hash is a vibe with extra steps.", [2, 2, 1], "You can detect some tampering if anyone checks.", "Chat is not a signature store.", "Sign in CI, verify on deploy, refuse unsigned.", "Verification should be automatic.", "A hash nobody verifies is décor.", "The chat hash is scrolled off by GIFs."),
      o("dd-13-b", "strong", "Sign in CI, verify on deploy", "BOX2 learns to reject strangers.", [3, 3, 3], "The vault recognizes its own.", "Provenance is a handshake.", "Sign in CI, verify on deploy, refuse unsigned.", "This is integrity you can operate.", "Deploy is a verifier, not a copy-paste.", "BOX2 sits up straighter."),
      o("dd-13-c", "high-risk", "Copy from a laptop, it is faster", "Laptops are CI if you squint.", [0, 3, 0], "The path is now anyone's USB.", "Squinting is not SLSA.", "Sign in CI, verify on deploy, refuse unsigned.", "Hands are not attestations.", "Human copies skip the evidence.", "A USB labelled YOLO enters the cave."),
    ]),
  q("dd-14", "control", "IaC that drifted out of a novel",
    "The cloud console has buttons. The repo has Terraform from April. They have not spoken since April.",
    "The console is a CI/CD if you believe.",
    ["infrastructure as code"],
    [
      o("dd-14-a", "high-risk", "Keep clicking, repo is documentation", "ClickOps is a culture.", [0, 2, 0], "Nobody can replay the estate.", "Documentation that cannot apply is fiction.", "Make the repo the path; import drift; block silent console changes on the important bits.", "Replayability is resilience.", "If you cannot replay it, you cannot recover it.", "A button is labelled 'surprise'."),
      o("dd-14-b", "strong", "Repo is the path, import the drift", "Console for break-glass only, logged.", [3, 2, 3], "Portals turn a trustworthy blue.", "IaC is how you see tomorrow's change.", "Make the repo the path; import drift; block silent console changes on the important bits.", "This is cloud engineering, not folklore.", "Drift is an incident type.", "Terraform and the console attend couples therapy."),
      o("dd-14-c", "weak", "Freeze the console, freeze delivery", "No clicks, no drift, no releases.", [2, 0, 2], "People open personal clouds.", "A freeze without a path relocates clicking.", "Make the repo the path; import drift; block silent console changes on the important bits.", "Offer a paved road.", "Blocking without a road makes dirt tracks.", "A personal AWS account named 'temp' appears."),
    ],
    ["cave-cloud"]),
  q("dd-15", "control", "Network as a hug",
    "Every microservice can hug every database because 'we'll segment later'. Later is today, accidentally.",
    "East-west is a lifestyle brand.",
    ["network segmentation"],
    [
      o("dd-15-a", "weak", "One big allow-all, a WAF in front", "The front door has a bouncer. The inside is a rave.", [1, 2, 1], "One foothold becomes a tour.", "WAFs do not hug databases for you.", "Segment by sensitivity; default deny east-west where you can.", "Inside is also a perimeter.", "Flat networks make every bug a breach.", "The rave has a database DJ."),
      o("dd-15-b", "strong", "Segment by sensitivity", "The vault is not on the party VLAN.", [3, 2, 3], "A crack in one island stays an island.", "This is architecture as containment.", "Segment by sensitivity; default deny east-west where you can.", "You can still deliver, just with doors.", "Hugs should be intentional.", "A door appears. The bats approve."),
      o("dd-15-c", "high-risk", "Open more so debugging is easier", "Security through convenience.", [0, 3, 0], "Debugging becomes a permanent hole.", "Convenience is how holes retire.", "Segment by sensitivity; default deny east-west where you can.", "Debug with time-bound paths.", "Permanent debug is production.", "A debug rule named tmp_2019 still lives."),
    ],
    ["cave-cloud"]),
  q("dd-16", "control", "Exception with no sunset",
    "A security exception for an unsigned library is four years old and has a smiley in the ticket.",
    "The smiley is still on call.",
    ["security exceptions"],
    [
      o("dd-16-a", "high-risk", "Renew forever, smiley still valid", "Exceptions are heritage.", [0, 2, 0], "A four-year hole remains policy.", "Smileys expire. Risks do not.", "Time-box exceptions, name an owner, track the exit.", "Exceptions are loans, not gifts.", "Heritage holes are still holes.", "The smiley is promoted to staff engineer."),
      o("dd-16-b", "strong", "Time-box, owner, exit plan", "Keep it only if you can see the end.", [3, 2, 3], "Either it leaves or it becomes a real control.", "This is how exceptions stay honest.", "Time-box exceptions, name an owner, track the exit.", "Delivery can keep a loan with a date.", "Open-ended exceptions are silent risk appetite.", "A calendar invite named 'stop smiling' is sent."),
      o("dd-16-c", "weak", "Revoke now and halt the app", "Purity.", [3, 0, 2], "You are right and offline.", "A cliff is not the only exit.", "Time-box exceptions, name an owner, track the exit.", "Plan the landing.", "You can end an exception without ending the product.", "The app is pure and dark."),
    ]),
  q("dd-17", "evidence", "Logs that forget",
    "Cloud logs stop at the load balancer because storage was 'getting spicy'. The spicy bill was last quarter.",
    "If we cannot see it, it cannot bill us.",
    ["logging and monitoring"],
    [
      o("dd-17-a", "strong", "Keep the trail, budget it, alert on gaps", "Missing logs are an incident.", [2, 2, 3], "Torch range grows. Paths show.", "Visibility is paid for on purpose.", "Log the auth and app path; alert if the stream dies.", "This is how you find the next secret leak.", "You cannot respond in the dark.", "A lantern budget line appears. Heroic."),
      o("dd-17-b", "weak", "Log only errors in a shared inbox", "Humans as SIEM.", [1, 1, 1], "Nobody reads the inbox. The bats do.", "Inboxes are not telemetry.", "Log the auth and app path; alert if the stream dies.", "Machines first, inboxes later.", "Detection needs a stream.", "The shared inbox has 14,000 unread errors and a recipe."),
      o("dd-17-c", "high-risk", "Turn logs off to save the quarter", "The CFO will love this incident.", [0, 2, 0], "The next compromise is a silent film.", "Quarters end. Attackers do not.", "Log the auth and app path; alert if the stream dies.", "Save money on noise, not on eyes.", "Blindness is expensive.", "The bill is smaller. So is your future."),
    ]),
  q("dd-18", "evidence", "Container as root, still",
    "The image runs as root, has a shell, and a leftover compiler. It is 'thinner than last year'.",
    "Root is a default, like disappointment.",
    ["container security"],
    [
      o("dd-18-a", "high-risk", "Ship it, thinner is safer", "Diet as a control.", [0, 2, 0], "A thin root is still a god in a can.", "Calories are not least privilege.", "Non-root, no shell in prod, no leftover compilers.", "Hardening is a release task.", "Thin is not the same as tight.", "The compiler in production writes a memoir."),
      o("dd-18-b", "strong", "Non-root, distroless-ish, no souvenirs", "A can that cannot wander.", [3, 2, 3], "Broken machines in the cave start humming in tune.", "This is practical hardening.", "Non-root, no shell in prod, no leftover compilers.", "You still deliver, just less armed.", "Images are attack surface.", "The shell is escorted from the image."),
      o("dd-18-c", "defensible", "Root but read-only filesystem", "Half a sandwich of safety.", [2, 2, 1], "Better, still a privileged process.", "Read-only helps; identity still matters.", "Non-root, no shell in prod, no leftover compilers.", "Stack the controls.", "One control is not a meal.", "The filesystem is read-only and root is bored."),
    ]),
  q("dd-19", "evidence", "Provenance, but handwritten",
    "Someone staples a PDF saying 'we built this on a trustworthy laptop' to the release.",
    "The laptop has stickers, so it is secure.",
    ["build provenance"],
    [
      o("dd-19-a", "weak", "Accept the PDF", "Paper is an attestation.", [1, 1, 1], "You cannot verify a staple.", "Attestations need to be checkable.", "Produce signed provenance from CI and verify it.", "Stickers are not SLSA.", "Handwritten trust does not scale.", "The stapler is the most trusted component."),
      o("dd-19-b", "strong", "CI-signed provenance, verified on entry", "The vault checks homework.", [3, 2, 3], "The Trusted Build Vault recognizes a real handshake.", "This is the destination behaving well.", "Produce signed provenance from CI and verify it.", "This is integrity you can automate.", "SLSA is a ladder, not a poster.", "A tiny seal appears. It is nerdily beautiful."),
      o("dd-19-c", "high-risk", "Skip provenance, we know the intern", "Identity as folklore.", [0, 2, 0], "When the intern leaves, so does the story.", "Knowing someone is not a signature.", "Produce signed provenance from CI and verify it.", "People leave. Signatures remain.", "Trust people to run systems, not to be the system.", "The intern waves from a new job."),
    ]),
  q("dd-20", "communicate", "Developers at the barricade",
    "AppSec blocked a library. Engineering says you are blocking customers. Both are a bit right. The cave is echoey.",
    "Security is just 'no' in a lanyard.",
    ["developer collaboration"],
    [
      o("dd-20-a", "high-risk", "Hold the block with no alternative", "No is a complete sentence.", [2, 0, 1], "A shadow library enters through a laptop.", "No without a path is how dirt roads form.", "Block the bad path and offer a known-good or a time-boxed exception.", "Help them ship the safe thing.", "Security that cannot say how will be routed around.", "A laptop-shaped dirt road appears."),
      o("dd-20-b", "strong", "Block plus a paved alternative", "Here is the version that works. Here is the extra day.", [3, 3, 3], "Tracks repair. People stay on them.", "This is the whole job.", "Block the bad path and offer a known-good or a time-boxed exception.", "You are a delivery partner.", "The best control is a better path.", "Engineering brings tea. A first."),
      o("dd-20-c", "weak", "Lift the block to save the relationship", "Friendship as a CVE.", [0, 3, 0], "The bad library ships with flowers.", "Relationships need honesty, not surrender.", "Block the bad path and offer a known-good or a time-boxed exception.", "Be kind and still specific.", "Friendship does not patch.", "The flowers are lovely. The library is not."),
    ],
    ["cave-package"]),
  q("dd-21", "communicate", "Exception theatre for the board",
    "A leader wants a security exception 'for the quarter' so a partner SDK can skip review. The SDK wants network, contacts, and a little nap on the filesystem.",
    "Partners are basically us.",
    ["third-party components", "balancing security with delivery"],
    [
      o("dd-21-a", "defensible", "Allow with extra monitoring only", "See it misbehave in production, live.", [2, 2, 1], "You might learn. Customers might also learn.", "Monitoring is not a substitute for a review you skipped.", "Review the SDK, minimise permissions, or delay the partner feature.", "Do the work or delay the feature — honestly.", "Partners are third parties. That is the point.", "The SDK takes a nap on the filesystem. Cute. Bad."),
      o("dd-21-b", "strong", "Review, minimise, or delay the feature", "A smaller permission set or a later date.", [3, 2, 3], "The partner still launches, just with pockets.", "This is a grown-up trade.", "Review the SDK, minimise permissions, or delay the partner feature.", "Delivery with a smaller blast radius.", "Dates can move. Permissions should not quietly explode.", "The partner is mildly annoyed and much safer."),
      o("dd-21-c", "high-risk", "Full permissions, smile in the minutes", "The quarter must not be sad.", [0, 3, 0], "The SDK becomes the product.", "Minutes are not a sandbox.", "Review the SDK, minimise permissions, or delay the partner feature.", "Do not launder risk through a calendar.", "Quarters are not threat models.", "The minutes have a smiley. The SDK has your customers."),
    ]),
  q("dd-22", "communicate", "Cloud ticket with feelings",
    "Ops wants to open security groups 'for a vendor workshop'. The workshop is four hours. The group change has no ticket end date.",
    "Vendors love 0.0.0.0/0. It feels like home.",
    ["cloud IAM", "network segmentation"],
    [
      o("dd-22-a", "high-risk", "Open 0.0.0.0/0 until someone remembers", "Hospitality.", [0, 2, 0], "The workshop ends. The hole does not.", "Hospitality is not a CIDR.", "Time-bound, ticketed, least-access for the vendor.", "Workshops need doors that close.", "Temporary must be temporary.", "A bat flies through the security group."),
      o("dd-22-b", "strong", "Time-bound, ticketed, least-access", "Four hours, one port, an alarm when it fails to close.", [3, 2, 3], "The portal stays blue. The vendor still gets in.", "This is cloud manners.", "Time-bound, ticketed, least-access for the vendor.", "You can be welcoming and finite.", "Expiry is a control.", "A clock appears over the security group. Rude. Correct."),
      o("dd-22-c", "weak", "Refuse the workshop entirely", "No vendor, no hole, no knowledge transfer.", [2, 0, 2], "The vendor screenshares a personal hotspot instead.", "Refuse the hole, not the learning.", "Time-bound, ticketed, least-access for the vendor.", "Design the access.", "Learning can happen inside a fence.", "Someone's phone becomes the data centre."),
    ],
    ["cave-cloud"]),
  q("dd-23", "recover", "Rollback, but the button is a myth",
    "The bad package is in production. Rollback is 'redeploy yesterday's vibe'. Yesterday's vibe is untagged.",
    "We will know it when we see it.",
    ["rollback"],
    [
      o("dd-23-a", "weak", "Hunt yesterday in artefact storage by memory", "The intern has a feeling.", [1, 1, 1], "You may roll forward into a different mess.", "Feelings are not tags.", "Tag releases, keep last-known-good, rehearse rollback.", "Myths are not runbooks.", "If you cannot go back, you cannot go fast.", "The intern is very sorry and slightly psychic."),
      o("dd-23-b", "strong", "Last-known-good, tagged, rehearsed", "A real button. A real artefact. A real owner.", [3, 3, 3], "The rails reverse. Customers get yesterday on purpose.", "This is delivery resilience.", "Tag releases, keep last-known-good, rehearse rollback.", "Practice is the control.", "Rollback is a product feature.", "The myth becomes a boring button. Perfect."),
      o("dd-23-c", "high-risk", "Patch forward with an unreviewed one-liner", "Momentum.", [0, 2, 0], "You stack unknown on unknown.", "Forward is not always better.", "Tag releases, keep last-known-good, rehearse rollback.", "One-liners still need a path.", "Unknown plus unknown is a genre of outage.", "The one-liner has a comment: 'trust me'."),
    ]),
  q("dd-24", "recover", "Secure release decision",
    "You can release a reduced build without the bad package, delay for a clean rebuild, or YOLO the original because marketing has balloons.",
    "Balloons are a go-live criterion.",
    ["secure release decisions"],
    [
      o("dd-24-a", "high-risk", "YOLO with balloons", "Brand energy.", [0, 3, 0], "Balloons and malware share a stage.", "Marketing is not an attestator.", "Prefer a reduced clean build or a short delay with a date.", "Dates can be honest.", "Balloons are optional. Integrity is not.", "A balloon pops. Symbolism."),
      o("dd-24-b", "strong", "Reduced clean build today", "Cut the risky feature, keep the promise you can keep.", [3, 3, 3], "The vault accepts a smaller, honest artefact.", "This is balancing security with delivery.", "Prefer a reduced clean build or a short delay with a date.", "Ship the safe subset.", "A smaller yes beats a big maybe.", "Marketing is handed a smaller balloon. They cope."),
      o("dd-24-c", "defensible", "Delay with a public date", "Honesty, slower.", [3, 1, 3], "Trust holds. Revenue waits.", "A named delay is a control.", "Prefer a reduced clean build or a short delay with a date.", "If you cannot reduce, delay out loud.", "Silence is worse than a later date.", "The date is on a cave wall in sensible font."),
    ]),
  q("dd-25", "recover", "Secrets after the leak",
    "You rotated the CI secret. Deployments still fail because three forgotten jobs have the old one baked in. The cave gets darker when jobs fail, which feels personal.",
    "We rotated. Why is the universe like this?",
    ["secrets management", "CI/CD access"],
    [
      o("dd-25-a", "strong", "Find baked secrets, kill jobs, reissue short-lived", "Inventory first, then a new generation.", [3, 2, 3], "Torchlight returns as jobs come back clean.", "Rotation is a search problem.", "Inventory uses of the secret, replace with short-lived credentials, watch for old use.", "This is how rotation actually works.", "Forgotten jobs are living fossils.", "A fossilized job is gently archived."),
      o("dd-25-b", "weak", "Put the old secret back so deploys work", "Availability is a kind of security.", [0, 3, 0], "You un-rotate.", "Availability of a burned key is an incident encore.", "Inventory uses of the secret, replace with short-lived credentials, watch for old use.", "Do not unburn keys.", "Rollback of a leak is not a restore of the leak.", "The old key waves from the logs."),
      o("dd-25-c", "defensible", "Rotate daily forever by hand", "Toil as a lifestyle.", [2, 1, 2], "People will skip a day. Attackers will not.", "Toil is not a control family.", "Inventory uses of the secret, replace with short-lived credentials, watch for old use.", "Automate short-lived instead of heroic calendars.", "Humans are bad cron.", "A calendar reminder named 'rotate or doom' appears."),
    ],
    ["cave-secret"]),
  q("dd-26", "close", "The vault door",
    "The Trusted Build Vault is ahead. You can open it for attested builds only, prop it open for the quarter, or brick it and tell engineers to deploy from laptops.",
    "Laptop deploys are a genre of horror.",
    ["NIST SSDF", "SLSA"],
    [
      o("dd-26-a", "weak", "Brick the vault, deploy from laptops", "If the cave is unsafe, leave the cave.", [1, 0, 1], "The supply chain becomes a backpack.", "Leaving the paved road is not safety.", "Open the vault for attested builds and keep a narrow emergency hatch.", "The vault is the safe path.", "Central builds exist so laptops are not production.", "A laptop LED becomes the new production cluster."),
      o("dd-26-b", "strong", "Attested builds only, narrow hatch", "The door recognises signatures. Emergencies still have a form.", [3, 3, 3], "The vault lights a steady blue. Tracks run true.", "This is the destination used well.", "Open the vault for attested builds and keep a narrow emergency hatch.", "You made delivery safer and still possible.", "A vault that people can use will be used.", "A bat lands on the sign. It looks official."),
      o("dd-26-c", "high-risk", "Prop it open for the quarter", "Friction is for next quarter.", [0, 3, 0], "The door is a decoration.", "Quarters are not locks.", "Open the vault for attested builds and keep a narrow emergency hatch.", "Friction now is cheaper than folklore later.", "Open doors are incidents waiting for a calendar.", "A crate rolls in uninvited, humming."),
    ]),
  q("dd-27", "close", "What we learned in the dark",
    "Someone wants to never speak of the package again. Someone else wants a 90-page SSDF mapping. The bats would like a third option.",
    "Can we put 'culture' in the report and leave?",
    ["NIST CSF", "NIST SSDF"],
    [
      o("dd-27-a", "high-risk", "Never speak of this", "What cave?", [0, 1, 0], "The next package will find you unprepared.", "Silence is not a control objective.", "Write a short living list: pins, provenance, IAM, logs — with owners.", "Memory is a pipeline feature.", "If it is not written, it did not happen.", "The bats will speak of it. They are gossips."),
      o("dd-27-b", "strong", "Short living list with owners", "Four controls, four names, one date to review.", [3, 2, 3], "The cave stays visible after you leave.", "This is improvement as operations.", "Write a short living list: pins, provenance, IAM, logs — with owners.", "Short and owned beats long and abandoned.", "Learning is a delivery system.", "The 90-page draft is recycled into a useful page."),
      o("dd-27-c", "defensible", "90-page mapping, no owners", "Framework karaoke.", [2, 1, 2], "It will be admired and unused.", "Mappings need names to move.", "Write a short living list: pins, provenance, IAM, logs — with owners.", "Frameworks are for steering, not for weight.", "Volume is not adoption.", "An auditor is already lost on page 47."),
    ]),
  q("dd-28", "close", "Next sprint's temptation",
    "Product wants to skip SBOMs 'until we are bigger'. You are already big enough to have bats.",
    "Startups do not have supply chains. They have zip files.",
    ["SBOM", "balancing security with delivery"],
    [
      o("dd-28-a", "strong", "Keep the small SBOM habit", "A tiny list now, a tiny cost, a huge future favour.", [3, 3, 3], "The vault stays honest as you grow.", "Habits are cheaper than archaeology.", "Keep generating SBOMs; they are how you stay able to patch.", "This is enablement for later-you.", "You will not get smaller.", "A small honest list beats a future scavenger hunt."),
      o("dd-28-b", "weak", "Pause SBOMs until series B", "Governance as a funding round.", [1, 2, 1], "You will be busy later, too.", "Funding is not a control.", "Keep generating SBOMs; they are how you stay able to patch.", "The cheap habit is now.", "Later-you is also tired.", "Series B arrives with more zip files."),
      o("dd-28-c", "high-risk", "Replace SBOMs with a wiki promise", "We pinky-swear.", [0, 2, 0], "Promises do not generate inventories.", "Wikis are not pipelines.", "Keep generating SBOMs; they are how you stay able to patch.", "Automation does not forget.", "Pinky-swear is not SLSA.", "The wiki promise is edited by a bat."),
    ]),
  q("dd-29", "contain", "Customer-facing app, dirty helper",
    "The compromised package is already in the customer app. You can pull the feature, serve a static page, or pretend the helper is 'just CSS'.",
    "CSS cannot hurt you. That is a lie we tell children.",
    ["rollback", "incident response"],
    [
      o("dd-29-a", "high-risk", "Leave it, it is just CSS", "Front-end is decorative.", [0, 2, 0], "Decorative code still executes in the customer's browser.", "Browsers do not care about your architecture slide.", "Pull or disable the helper; tell customers what you know.", "Front-end is production.", "Supply chain reaches the eyeball.", "The CSS phones home. Rude."),
      o("dd-29-b", "strong", "Disable helper, static fallback, tell customers", "A smaller app that is still yours.", [3, 3, 3], "Customers get a page that does not bite.", "Honesty plus a fallback is resilience.", "Pull or disable the helper; tell customers what you know.", "This is containment people can use.", "You can be smaller and safer today.", "A static page has never been more heroic."),
      o("dd-29-c", "weak", "Silent pull with no customer note", "No news is good IR.", [3, 1, 0], "You remove the bite and keep the rumour.", "People notice. They fill gaps.", "Pull or disable the helper; tell customers what you know.", "Containment includes a sentence.", "Silence becomes a story.", "Twitter writes your incident advisory for you."),
    ],
    ["cave-package"]),
  q("dd-30", "assess", "CI identities as people",
    "The pipeline uses a human's cloud key because 'the service account form was long'. The human is on holiday. The key is not.",
    "Out of office is not a revocation.",
    ["CI/CD access", "least privilege"],
    [
      o("dd-30-a", "strong", "Service identity, short-lived, no holiday keys", "Pipelines are not people. People go to beaches.", [3, 2, 3], "The tracks stop depending on someone's luggage.", "This is how CI grows up.", "Replace human keys with workload identity and short-lived credentials.", "Delivery should survive annual leave.", "Human keys in CI are incidents in waiting.", "A beach receives a postcard. The pipeline receives a role."),
      o("dd-30-b", "defensible", "Keep the human key, add a second human", "Bus factor as a control.", [2, 2, 1], "Now two luggage sets can ship production.", "Sharing a secret is not an identity strategy.", "Replace human keys with workload identity and short-lived credentials.", "Increase people, not copies of a key.", "Bus factor is about knowledge, not key duplication.", "Both humans are now on the same ferry, cinematically."),
      o("dd-30-c", "high-risk", "Post the key in the team wiki for coverage", "Collaboration.", [0, 3, 0], "The wiki is now a key vault with search.", "Searchable secrets are a genre of disaster.", "Replace human keys with workload identity and short-lived credentials.", "Coverage needs a role, not a paste.", "Wikis are not HSMs.", "A bat bookmarks the wiki. Of course."),
    ],
    ["cave-secret"]),
];
