import type { ArchitectureDecision, ArchitectureOption, DecisionId } from "./types";

function option(
  id: string,
  decisionId: DecisionId,
  title: string,
  fields: Omit<ArchitectureOption, "id" | "decisionId" | "title">,
): ArchitectureOption {
  return { id, decisionId, title, ...fields };
}

export const LAB_DECISIONS: readonly ArchitectureDecision[] = [
  {
    id: "exposure",
    number: 1,
    area: "External exposure",
    question: "The Claims Portal and Claims API sit at the edge of Nordic Shield. How should they be exposed to the internet?",
    nodeId: "waf",
    options: [
      option("exposure-private", "exposure", "WAF and private API endpoint", {
        description: "Publish the Claims Portal through a web application firewall. Keep the Claims API on a private endpoint.",
        challengeDescription: "Put a WAF in front of the portal and keep the Claims API off the public internet.",
        tradeOff: "Strong isolation, but more infrastructure and private-link configuration.",
        confirmation: "The portal now sits behind a WAF. The Claims API is no longer public.",
        architectureUpdate: "Architecture updated: WAF added. Claims API moved off the public internet.",
        riskReduced: "Internet scanning and unauthenticated probing of the Claims API.",
        residualRisk: "The portal is still internet-reachable, so a valid staff session can still upload files.",
        recommended: true,
        strength: "strong",
        icon: "shield",
        mapTitle: "WAF + private API",
        mapDetail: "Portal through WAF. API is private.",
        addsNodes: ["waf"],
        highlightNodes: ["waf", "portal", "api"],
        preventionEffect: 2,
        detectionEffect: 1,
        blastRadiusEffect: 1,
        recoveryEffect: 0,
        campaignStageIds: ["stolen-credentials", "poisoned-document"],
      }),
      option("exposure-waf", "exposure", "WAF in front of public portal and API", {
        description: "Put a WAF in front of both the Claims Portal and the Claims API. Both stay internet-reachable.",
        challengeDescription: "Filter public traffic to the portal and the API through a WAF.",
        tradeOff: "Edge filtering helps, but both services remain reachable from the internet.",
        confirmation: "A WAF now sits in front of the public portal and API.",
        architectureUpdate: "Architecture updated: WAF added in front of the public portal and API.",
        riskReduced: "Common internet probes and some injected requests at the edge.",
        residualRisk: "A stolen session or leaked token still reaches internet-facing services.",
        recommended: false,
        strength: "medium",
        icon: "globe",
        mapTitle: "Public + WAF",
        mapDetail: "Portal and API stay on the internet.",
        addsNodes: ["waf"],
        highlightNodes: ["waf", "portal", "api"],
        preventionEffect: 1,
        detectionEffect: 1,
        blastRadiusEffect: 0,
        recoveryEffect: 0,
        campaignStageIds: ["stolen-credentials", "poisoned-document"],
      }),
      option("exposure-direct", "exposure", "Direct public portal and API", {
        description: "Publish the Claims Portal and Claims API with TLS. No edge filter in front.",
        challengeDescription: "Expose the portal and API directly on the internet with TLS.",
        tradeOff: "Simple to operate, but scanners and stolen sessions reach both services immediately.",
        confirmation: "The portal and API remain directly internet-facing.",
        architectureUpdate: "Architecture updated: Portal and API remain directly internet-facing.",
        riskReduced: "TLS still protects data in transit.",
        residualRisk: "Anything that can reach the internet can try the portal and the API.",
        recommended: false,
        strength: "weak",
        icon: "globe",
        mapTitle: "Direct public edge",
        mapDetail: "No WAF. API is internet-reachable.",
        addsNodes: [],
        highlightNodes: ["portal", "api"],
        preventionEffect: 0,
        detectionEffect: 0,
        blastRadiusEffect: 0,
        recoveryEffect: 0,
        campaignStageIds: ["stolen-credentials", "poisoned-document"],
      }),
    ],
  },
  {
    id: "identity",
    number: 2,
    area: "Identity and access",
    question: "Claims handlers sign in through the Identity Provider to reach the Claims Portal. How should employees authenticate, and how is access assigned?",
    nodeId: "identity",
    options: [
      option("identity-mfa", "identity", "MFA and role-based access", {
        description: "Staff use a second factor. The Identity Provider assigns only the access their role needs.",
        challengeDescription: "Require a second factor and grant portal access by role.",
        tradeOff: "Extra sign-in friction and role administration to keep up to date.",
        confirmation: "The Identity Provider now requires MFA and role-based access.",
        architectureUpdate: "Architecture updated: Identity Provider with MFA and RBAC added.",
        riskReduced: "A stolen password is not enough to open a claims session.",
        residualRisk: "A phished session or compromised device can still be a problem later.",
        recommended: true,
        strength: "strong",
        icon: "shield",
        mapTitle: "MFA + RBAC",
        mapDetail: "Stolen passwords fail at the IdP.",
        addsNodes: ["identity"],
        highlightNodes: ["identity", "employee", "portal"],
        preventionEffect: 2,
        detectionEffect: 1,
        blastRadiusEffect: 1,
        recoveryEffect: 0,
        campaignStageIds: ["stolen-credentials"],
      }),
      option("identity-device-mfa", "identity", "SSO, group roles, MFA on new devices", {
        description: "Staff sign in with SSO. Group membership sets access. A second factor is asked on new browsers.",
        challengeDescription: "Use SSO and groups, with MFA only when a new device appears.",
        tradeOff: "Faster for returning staff, but a stolen password on a remembered device is a working login.",
        confirmation: "Identity now uses SSO and group roles, with MFA on new devices only.",
        architectureUpdate: "Architecture updated: Identity Provider with SSO and group roles added.",
        riskReduced: "Unknown browsers still face a second factor.",
        residualRisk: "A remembered device plus a stolen password is still a valid session.",
        recommended: false,
        strength: "medium",
        icon: "key",
        mapTitle: "SSO + device MFA",
        mapDetail: "Remembered browsers skip the second factor.",
        addsNodes: ["identity"],
        highlightNodes: ["identity", "employee", "portal"],
        preventionEffect: 1,
        detectionEffect: 1,
        blastRadiusEffect: 0,
        recoveryEffect: 0,
        campaignStageIds: ["stolen-credentials"],
      }),
      option("identity-password", "identity", "Shared staff password and wide role", {
        description: "The claims desk shares a portal password and a broad staff role.",
        challengeDescription: "Let the desk share one portal password and a wide claims role.",
        tradeOff: "Cheap to run, but one leaked password covers most of the claims desk.",
        confirmation: "Portal login now uses a shared staff password and a wide role.",
        architectureUpdate: "Architecture updated: Portal login uses a shared staff password.",
        riskReduced: "Staff can still reach the portal without extra identity infrastructure.",
        residualRisk: "A single leaked password becomes a working claims session.",
        recommended: false,
        strength: "weak",
        icon: "key",
        mapTitle: "Shared password",
        mapDetail: "One leaked password covers the desk.",
        addsNodes: ["identity"],
        highlightNodes: ["identity", "employee", "portal"],
        preventionEffect: 0,
        detectionEffect: 0,
        blastRadiusEffect: 0,
        recoveryEffect: 0,
        campaignStageIds: ["stolen-credentials"],
      }),
    ],
  },
  {
    id: "network",
    number: 3,
    area: "Network segmentation",
    question: "The Claims Portal, AI Claims App, Claims API and Claims Database currently share one path. Should they sit in separate security zones?",
    nodeId: "network",
    options: [
      option("network-segmented", "network", "Separate zones with controlled links", {
        description: "Place the portal, AI service, API and database in separate zones. Allow only the links each zone needs.",
        challengeDescription: "Split portal, AI, API and database into zones with controlled links.",
        tradeOff: "Strong isolation, but more routing and firewall rules to maintain.",
        confirmation: "Portal, AI, API and database now sit in separate network zones.",
        architectureUpdate: "Architecture updated: Network zones isolate portal, AI, API and database.",
        riskReduced: "East-west movement from a foothold in the AI app toward the database.",
        residualRisk: "Allowed zone links can still be abused if the calling identity is too broad.",
        recommended: true,
        strength: "strong",
        icon: "network",
        mapTitle: "Segmented zones",
        mapDetail: "Portal, AI, API and data are separated.",
        addsNodes: ["network"],
        highlightNodes: ["network", "portal", "app", "api", "database"],
        preventionEffect: 1,
        detectionEffect: 0,
        blastRadiusEffect: 2,
        recoveryEffect: 1,
        campaignStageIds: ["api-call", "unrelated-claims", "extract-modify"],
      }),
      option("network-ai-only", "network", "Private AI zone, shared app network", {
        description: "Isolate the AI Claims App. Let the portal, API and database share a trusted internal network.",
        challengeDescription: "Fence the AI service, then let portal, API and data share a LAN.",
        tradeOff: "The model is fenced, but a foothold in the app can still walk toward data.",
        confirmation: "The AI zone is private. Portal, API and data still share a network.",
        architectureUpdate: "Architecture updated: AI zone isolated; app and data still share a network.",
        riskReduced: "Direct internet paths into the model are harder.",
        residualRisk: "Compromise of the app still sits on the same network as the database.",
        recommended: false,
        strength: "medium",
        icon: "network",
        mapTitle: "Partial segmentation",
        mapDetail: "AI is fenced. App and data share a LAN.",
        addsNodes: ["network"],
        highlightNodes: ["network", "app", "api", "database"],
        preventionEffect: 0,
        detectionEffect: 0,
        blastRadiusEffect: 1,
        recoveryEffect: 0,
        campaignStageIds: ["api-call", "unrelated-claims", "extract-modify"],
      }),
      option("network-flat", "network", "One internal network for all four", {
        description: "Keep the portal, AI Claims App, Claims API and database on one internal network.",
        challengeDescription: "Let portal, AI, API and database talk freely once inside.",
        tradeOff: "Easy to operate, and one compromised service can reach the others.",
        confirmation: "Portal, AI, API and database now share a flat internal network.",
        architectureUpdate: "Architecture updated: Portal, AI, API and database share a flat network.",
        riskReduced: "Internal traffic needs less firewall maintenance.",
        residualRisk: "A foothold in the AI app can move toward the Claims Database.",
        recommended: false,
        strength: "weak",
        icon: "globe",
        mapTitle: "Flat network",
        mapDetail: "Trusted internals can move freely.",
        addsNodes: ["network"],
        highlightNodes: ["network", "portal", "app", "api", "database"],
        preventionEffect: 0,
        detectionEffect: 0,
        blastRadiusEffect: 0,
        recoveryEffect: 0,
        campaignStageIds: ["api-call", "unrelated-claims", "extract-modify"],
      }),
    ],
  },
  {
    id: "gateway",
    number: 4,
    area: "API protection",
    question: "The Claims Portal must communicate with the Claims API. How should that connection be protected?",
    nodeId: "gateway",
    options: [
      option("gateway-private", "gateway", "Private endpoint, gateway and service identity", {
        description: "Send portal traffic through an API gateway on a private endpoint, with a controlled service identity.",
        challengeDescription: "Put a private API gateway between the portal and the Claims API.",
        tradeOff: "Strong isolation, but more infrastructure and configuration.",
        confirmation: "Portal calls now pass a private API gateway with a controlled identity.",
        architectureUpdate: "Architecture updated: API Gateway, private endpoint and service identity added.",
        riskReduced: "Direct internet calls and unauthenticated traffic to the Claims API.",
        residualRisk: "A compromised internal identity can still call what the gateway allows.",
        recommended: true,
        strength: "strong",
        icon: "lock",
        mapTitle: "Private API gateway",
        mapDetail: "Auth, validation and rate limits on a private path.",
        addsNodes: ["gateway"],
        highlightNodes: ["gateway", "portal", "api"],
        preventionEffect: 2,
        detectionEffect: 1,
        blastRadiusEffect: 1,
        recoveryEffect: 0,
        campaignStageIds: ["api-call", "extract-modify"],
      }),
      option("gateway-public", "gateway", "Public gateway with auth and rate limits", {
        description: "Put an API gateway in front of the public Claims API. Authenticate, validate and rate-limit requests.",
        challengeDescription: "Protect the public Claims API with a gateway, authentication and rate limiting.",
        tradeOff: "Good request protection, but the API remains internet-reachable.",
        confirmation: "The public Claims API now sits behind a gateway with auth and rate limits.",
        architectureUpdate: "Architecture updated: API Gateway and rate limiting added.",
        riskReduced: "Anonymous flooding and some malformed requests to the Claims API.",
        residualRisk: "Anyone who can reach the internet can still find the API.",
        recommended: false,
        strength: "medium",
        icon: "filter",
        mapTitle: "Public API gateway",
        mapDetail: "Auth and rate limits on an internet-facing API.",
        addsNodes: ["gateway"],
        highlightNodes: ["gateway", "portal", "api"],
        preventionEffect: 1,
        detectionEffect: 1,
        blastRadiusEffect: 0,
        recoveryEffect: 0,
        campaignStageIds: ["api-call", "extract-modify"],
      }),
      option("gateway-token", "gateway", "Direct public API with an application token", {
        description: "Let the portal call the public Claims API using an application token.",
        challengeDescription: "Protect the public API with an application token and no gateway.",
        tradeOff: "Simple to operate, but a leaked token provides direct access.",
        confirmation: "The portal now calls the public API with an application token.",
        architectureUpdate: "Architecture updated: Portal calls the public Claims API with an application token.",
        riskReduced: "Casual anonymous clients still need the token.",
        residualRisk: "A leaked token is a working key to the Claims API.",
        recommended: false,
        strength: "weak",
        icon: "key",
        mapTitle: "App token only",
        mapDetail: "No gateway. A leaked token is enough.",
        addsNodes: [],
        highlightNodes: ["portal", "api"],
        preventionEffect: 0,
        detectionEffect: 0,
        blastRadiusEffect: 0,
        recoveryEffect: 0,
        campaignStageIds: ["api-call", "extract-modify"],
      }),
    ],
  },
  {
    id: "secrets",
    number: 5,
    area: "Service authentication",
    question: "The AI Claims App must prove itself to the Claims API. How should internal services authenticate?",
    nodeId: "secrets",
    options: [
      option("secrets-vault", "secrets", "Managed identities and a secrets vault", {
        description: "Issue short-lived identities. Keep no reusable key in the AI Claims App. Store remaining secrets in a vault.",
        challengeDescription: "Use managed identities and a vault instead of a stored API key.",
        tradeOff: "Requires cloud identity configuration and vault operations.",
        confirmation: "Internal calls now use managed identity and a secrets vault.",
        architectureUpdate: "Architecture updated: Secrets Vault and managed identities added.",
        riskReduced: "A compromised app no longer hands over a portable API key.",
        residualRisk: "A live managed identity can still call whatever the API permits.",
        recommended: true,
        strength: "strong",
        icon: "vault",
        mapTitle: "Managed identity",
        mapDetail: "No reusable key in the AI app.",
        addsNodes: ["secrets"],
        highlightNodes: ["secrets", "app", "api"],
        preventionEffect: 2,
        detectionEffect: 0,
        blastRadiusEffect: 1,
        recoveryEffect: 1,
        campaignStageIds: ["api-call", "extract-modify", "contain-recover"],
      }),
      option("secrets-rotated", "secrets", "Stored credentials, rotated quarterly", {
        description: "Keep a reusable service credential in configuration and rotate it on a calendar.",
        challengeDescription: "Store a service credential and rotate it every quarter.",
        tradeOff: "A leaked credential still works until the next rotation window.",
        confirmation: "Internal calls now use a stored credential with quarterly rotation.",
        architectureUpdate: "Architecture updated: Secrets Vault holds a credential rotated quarterly.",
        riskReduced: "Old leaks eventually expire when rotation actually happens.",
        residualRisk: "A leaked key remains reusable between rotation dates.",
        recommended: false,
        strength: "medium",
        icon: "vault",
        mapTitle: "Rotated credential",
        mapDetail: "The key still works until the next rotation.",
        addsNodes: ["secrets"],
        highlightNodes: ["secrets", "app", "api"],
        preventionEffect: 1,
        detectionEffect: 0,
        blastRadiusEffect: 0,
        recoveryEffect: 1,
        campaignStageIds: ["api-call", "extract-modify", "contain-recover"],
      }),
      option("secrets-key", "secrets", "Static API key in the application", {
        description: "Store one reusable API key in the AI Claims App configuration.",
        challengeDescription: "Keep a static API key in the application configuration.",
        tradeOff: "Simple to operate, but a leaked key can be reused outside the app.",
        confirmation: "The AI Claims App now authenticates with a static API key.",
        architectureUpdate: "Architecture updated: AI Claims App authenticates with a static API key.",
        riskReduced: "Services can call each other without extra identity plumbing.",
        residualRisk: "Anyone who copies the key can call the Claims API as the app.",
        recommended: false,
        strength: "weak",
        icon: "file",
        mapTitle: "Static API key",
        mapDetail: "A leaked key can be reused.",
        addsNodes: ["secrets"],
        highlightNodes: ["secrets", "app", "api"],
        preventionEffect: 0,
        detectionEffect: 0,
        blastRadiusEffect: 0,
        recoveryEffect: 0,
        campaignStageIds: ["api-call", "extract-modify", "contain-recover"],
      }),
    ],
  },
  {
    id: "data-access",
    number: 6,
    area: "Database permissions",
    question: "What should the Claims API allow the AI Claims App to read or change in the Claims Database?",
    nodeId: "api",
    options: [
      option("api-restricted", "data-access", "Read-only on the open claim", {
        description: "The Claims API may read the active claim only. The AI cannot change payouts or export the book.",
        challengeDescription: "Limit the API to approved reads on the claim that is open.",
        tradeOff: "Less automation. Handlers still make the high-impact changes.",
        confirmation: "The Claims API is now read-only on the open claim.",
        architectureUpdate: "Architecture updated: Claims API limited to read-only access on the open claim.",
        riskReduced: "A manipulated AI workflow cannot rewrite or bulk-export customer records.",
        residualRisk: "The open claim’s own data can still be read into the prompt.",
        recommended: true,
        strength: "strong",
        icon: "lock",
        mapTitle: "Least-privilege API",
        mapDetail: "Read-only on the active claim.",
        addsNodes: [],
        highlightNodes: ["api", "app", "database"],
        preventionEffect: 1,
        detectionEffect: 0,
        blastRadiusEffect: 2,
        recoveryEffect: 0,
        campaignStageIds: ["unrelated-claims", "extract-modify"],
      }),
      option("api-active-write", "data-access", "Read-write on the active claim", {
        description: "Allow the AI to update the open claim through the API, but not other customers’ records.",
        challengeDescription: "Permit updates on the active claim only.",
        tradeOff: "A manipulated workflow can still alter the case in front of it.",
        confirmation: "The Claims API now allows read-write on the active claim.",
        architectureUpdate: "Architecture updated: Claims API can read and change the open claim only.",
        riskReduced: "Bulk export across the book is still out of reach.",
        residualRisk: "The open case can still be changed, including payout fields.",
        recommended: false,
        strength: "medium",
        icon: "database",
        mapTitle: "Active-claim write",
        mapDetail: "The open case can still be changed.",
        addsNodes: [],
        highlightNodes: ["api", "app", "database"],
        preventionEffect: 0,
        detectionEffect: 0,
        blastRadiusEffect: 1,
        recoveryEffect: 0,
        campaignStageIds: ["unrelated-claims", "extract-modify"],
      }),
      option("api-broad", "data-access", "Shared account across the claims book", {
        description: "Give the AI a shared service account that can read and update claims through the API.",
        challengeDescription: "Let the assistant use a shared service account on the Claims API.",
        tradeOff: "Flexible automation, and a compromised workflow receives a large blast radius.",
        confirmation: "The AI now uses a broad Claims API service account.",
        architectureUpdate: "Architecture updated: Claims API uses a shared account across claims.",
        riskReduced: "The assistant can complete more of the case without extra permissions work.",
        residualRisk: "Unrelated customer records are reachable if the workflow is steered.",
        recommended: false,
        strength: "weak",
        icon: "database",
        mapTitle: "Broad service account",
        mapDetail: "Read and update across claims.",
        addsNodes: [],
        highlightNodes: ["api", "database"],
        preventionEffect: 0,
        detectionEffect: 0,
        blastRadiusEffect: 0,
        recoveryEffect: 0,
        campaignStageIds: ["unrelated-claims", "extract-modify"],
      }),
    ],
  },
  {
    id: "retrieval",
    number: 7,
    area: "AI retrieval boundaries",
    question: "When the AI Claims App asks the retrieval service for context, what may it search?",
    nodeId: "retrieval",
    options: [
      option("retrieval-case", "retrieval", "Only the current claim", {
        description: "The retrieval service returns documents for the open claim and nothing else.",
        challengeDescription: "Limit retrieval to files that belong to the open claim.",
        tradeOff: "The AI may occasionally receive too little neighbouring context.",
        confirmation: "Retrieval is now limited to the current claim.",
        architectureUpdate: "Architecture updated: Retrieval Service limited to the current claim.",
        riskReduced: "A prompt injection cannot turn one claim into a search across customers.",
        residualRisk: "Hostile text inside the open claim can still steer that one case.",
        recommended: true,
        strength: "strong",
        icon: "lock",
        mapTitle: "Case-scoped retrieval",
        mapDetail: "Only the current claim’s files.",
        addsNodes: ["retrieval"],
        highlightNodes: ["retrieval", "app", "database"],
        preventionEffect: 1,
        detectionEffect: 0,
        blastRadiusEffect: 2,
        recoveryEffect: 0,
        campaignStageIds: ["ai-manipulation", "unrelated-claims"],
      }),
      option("retrieval-related", "retrieval", "Current claim plus related policies", {
        description: "Allow retrieval from the open claim and linked policy documents.",
        challengeDescription: "Search the open claim and its related policy files.",
        tradeOff: "A manipulated request may pull neighbouring policy text it should not see.",
        confirmation: "Retrieval now includes related policy documents.",
        architectureUpdate: "Architecture updated: Retrieval Service includes related policies.",
        riskReduced: "The full shared claims index is still out of scope.",
        residualRisk: "Linked policies can leak into a steered prompt.",
        recommended: false,
        strength: "medium",
        icon: "copy",
        mapTitle: "Claim + policies",
        mapDetail: "Linked files are in scope.",
        addsNodes: ["retrieval"],
        highlightNodes: ["retrieval", "app"],
        preventionEffect: 0,
        detectionEffect: 0,
        blastRadiusEffect: 1,
        recoveryEffect: 0,
        campaignStageIds: ["ai-manipulation", "unrelated-claims"],
      }),
      option("retrieval-index", "retrieval", "The shared claims index", {
        description: "Let the retrieval service search across all available claims.",
        challengeDescription: "Allow the assistant to search the shared claims index.",
        tradeOff: "Richer answers, and one manipulated request may expose unrelated customers.",
        confirmation: "The AI can now search the shared claims index.",
        architectureUpdate: "Architecture updated: Retrieval Service searches the shared claims index.",
        riskReduced: "Handlers get more context without extra lookups.",
        residualRisk: "Unrelated customer documents can enter the prompt.",
        recommended: false,
        strength: "weak",
        icon: "copy",
        mapTitle: "Shared claims index",
        mapDetail: "Search across other customers.",
        addsNodes: ["retrieval"],
        highlightNodes: ["retrieval", "app", "database"],
        preventionEffect: 0,
        detectionEffect: 0,
        blastRadiusEffect: 0,
        recoveryEffect: 0,
        campaignStageIds: ["ai-manipulation", "unrelated-claims"],
      }),
    ],
  },
  {
    id: "input",
    number: 8,
    area: "Malicious input protection",
    question: "Claim documents and prompts reach the AI Claims App through the portal. How should they be checked before that workflow?",
    nodeId: "scanner",
    options: [
      option("input-sandbox", "input", "Validate, scan and isolate uploads", {
        description: "Validate the file, malware-scan it, and isolate it in a document scanner before the AI Claims App reads it.",
        challengeDescription: "Inspect, sanitise and isolate uploads before they reach the AI workflow.",
        tradeOff: "Adds processing time and a scanner to operate.",
        confirmation: "Uploads now pass a document scanner before the AI workflow.",
        architectureUpdate: "Architecture updated: Document Scanner added before the AI Claims App.",
        riskReduced: "Hidden instructions and active content in uploaded claims files.",
        residualRisk: "A novel payload that looks like a normal document may still pass.",
        recommended: true,
        strength: "strong",
        icon: "scan",
        mapTitle: "Document scanner",
        mapDetail: "Validates, scans and isolates uploads.",
        addsNodes: ["scanner"],
        highlightNodes: ["scanner", "portal", "app"],
        preventionEffect: 2,
        detectionEffect: 1,
        blastRadiusEffect: 0,
        recoveryEffect: 0,
        campaignStageIds: ["poisoned-document", "ai-manipulation"],
      }),
      option("input-malware", "input", "Antivirus scan, then into the AI workflow", {
        description: "Scan uploads for known malware, then let the file enter the AI Claims App as it arrived.",
        challengeDescription: "Malware-scan the file, but do not isolate or strip hidden instructions.",
        tradeOff: "Known malware is caught. A clean PDF can still carry prompt-injection text.",
        confirmation: "Uploads now get a malware scan, then enter the AI workflow.",
        architectureUpdate: "Architecture updated: Document Scanner added for malware checks only.",
        riskReduced: "Common malware in claim attachments.",
        residualRisk: "Prompt-injection text in an otherwise clean document still reaches the AI.",
        recommended: false,
        strength: "medium",
        icon: "filter",
        mapTitle: "Malware scan",
        mapDetail: "Hidden instructions can survive.",
        addsNodes: ["scanner"],
        highlightNodes: ["scanner", "portal", "app"],
        preventionEffect: 1,
        detectionEffect: 0,
        blastRadiusEffect: 0,
        recoveryEffect: 0,
        campaignStageIds: ["poisoned-document", "ai-manipulation"],
      }),
      option("input-typecheck", "input", "Allow listed file types only", {
        description: "Accept the document when the extension and format look allowed, then send it to the AI.",
        challengeDescription: "Check the file type, then let the content go straight to the AI Claims App.",
        tradeOff: "Fast for handlers, and hidden or obfuscated content may survive.",
        confirmation: "Uploads are accepted after a file-type check only.",
        architectureUpdate: "Architecture updated: Uploads go to the AI Claims App after a file-type check.",
        riskReduced: "Obviously wrong file types are rejected.",
        residualRisk: "A poisoned PDF with an allowed type reaches the AI workflow.",
        recommended: false,
        strength: "weak",
        icon: "file",
        mapTitle: "Type check only",
        mapDetail: "Content goes straight to the AI.",
        addsNodes: [],
        highlightNodes: ["portal", "app"],
        preventionEffect: 0,
        detectionEffect: 0,
        blastRadiusEffect: 0,
        recoveryEffect: 0,
        campaignStageIds: ["poisoned-document", "ai-manipulation"],
      }),
    ],
  },
  {
    id: "detection",
    number: 9,
    area: "Logging and detection",
    question: "Which authentication events, API calls, AI actions and database queries should be logged and monitored?",
    nodeId: "detection",
    options: [
      option("detection-siem", "detection", "SIEM on identity, API, AI and data", {
        description: "Send authentication, gateway, AI, API and database events to a SIEM with an owned response playbook.",
        challengeDescription: "Correlate identity, API, AI and database events in one monitoring service.",
        tradeOff: "Requires monitoring people and a playbook someone actually owns.",
        confirmation: "Monitoring now correlates the campaign in a SIEM with a response playbook.",
        architectureUpdate: "Architecture updated: Monitoring/SIEM added across identity, API, AI and data.",
        riskReduced: "A multi-step campaign that would otherwise look like isolated log lines.",
        residualRisk: "Alerts still need someone to act before containment starts.",
        recommended: true,
        strength: "strong",
        icon: "radar",
        mapTitle: "SIEM + playbook",
        mapDetail: "Auth, API, AI and data events in one place.",
        addsNodes: ["detection"],
        highlightNodes: ["detection", "identity", "api", "app", "database"],
        preventionEffect: 0,
        detectionEffect: 2,
        blastRadiusEffect: 0,
        recoveryEffect: 1,
        campaignStageIds: ["monitoring", "contain-recover"],
      }),
      option("detection-central", "detection", "Central logs, no owned playbook", {
        description: "Ship identity, API, AI and database events to one store. Nobody owns a joined-up response.",
        challengeDescription: "Collect the logs centrally without a named incident playbook.",
        tradeOff: "You may reconstruct this later, but not contain it in time.",
        confirmation: "Events now land in a central log store without a playbook.",
        architectureUpdate: "Architecture updated: Central monitoring added, without a response playbook.",
        riskReduced: "Investigators can eventually join the events.",
        residualRisk: "No one is tasked to notice the campaign while it is still moving.",
        recommended: false,
        strength: "medium",
        icon: "list",
        mapTitle: "Central logs",
        mapDetail: "No owned response playbook.",
        addsNodes: ["detection"],
        highlightNodes: ["detection", "api", "app"],
        preventionEffect: 0,
        detectionEffect: 1,
        blastRadiusEffect: 0,
        recoveryEffect: 0,
        campaignStageIds: ["monitoring", "contain-recover"],
      }),
      option("detection-logs", "detection", "Each service keeps its own logs", {
        description: "Leave authentication, API, AI and database events inside each service.",
        challengeDescription: "Keep events inside each service’s own logs.",
        tradeOff: "Cheap to run. The organisation may see isolated events but miss the campaign.",
        confirmation: "Each service now keeps its own application logs.",
        architectureUpdate: "Architecture updated: Logging stays inside each service.",
        riskReduced: "Engineers can still debug a single service.",
        residualRisk: "Nobody sees identity, AI and database events as one incident.",
        recommended: false,
        strength: "weak",
        icon: "list",
        mapTitle: "App logs only",
        mapDetail: "Events stay inside each service.",
        addsNodes: ["detection"],
        highlightNodes: ["detection"],
        preventionEffect: 0,
        detectionEffect: 0,
        blastRadiusEffect: 0,
        recoveryEffect: 0,
        campaignStageIds: ["monitoring", "contain-recover"],
      }),
    ],
  },
  {
    id: "recovery",
    number: 10,
    area: "Containment and recovery",
    question: "If this architecture is abused, can Nordic Shield isolate systems, revoke access, restore data and follow a tested process?",
    nodeId: "backup",
    options: [
      option("recovery-tested", "recovery", "Isolation, revocation, protected backups, tested IR", {
        description: "Zone isolation, credential revocation, backups off the live account, and an incident-response process that has been rehearsed.",
        challengeDescription: "Put isolation, revocation, protected backups and a tested IR process in place.",
        tradeOff: "Time, drills and a backup system that is not just another copy of production.",
        confirmation: "Containment and recovery controls are now in place and tested.",
        architectureUpdate: "Architecture updated: Protected Backup and isolation controls added.",
        riskReduced: "Lasting damage after a foothold, including silent changes to claims data.",
        residualRisk: "Recovery still takes time. Some open claims may need manual review.",
        recommended: true,
        strength: "strong",
        icon: "contained",
        mapTitle: "Tested recovery",
        mapDetail: "Isolate, revoke, restore from protected backups.",
        addsNodes: ["backup"],
        highlightNodes: ["backup", "database", "identity", "network"],
        preventionEffect: 0,
        detectionEffect: 0,
        blastRadiusEffect: 1,
        recoveryEffect: 2,
        campaignStageIds: ["contain-recover"],
      }),
      option("recovery-backups", "recovery", "Backups exist, isolation untested", {
        description: "Keep backups of the Claims Database. Isolation and incident response are written down but not rehearsed.",
        challengeDescription: "Keep backups, with isolation and IR documented rather than drilled.",
        tradeOff: "You can restore data later. You may not contain the live incident quickly.",
        confirmation: "Protected backups exist. Isolation and IR remain untested.",
        architectureUpdate: "Architecture updated: Protected Backup added. Isolation remains untested.",
        riskReduced: "A destroyed database is not the end of the records.",
        residualRisk: "Credential revocation and zone isolation may stall during the real incident.",
        recommended: false,
        strength: "medium",
        icon: "database",
        mapTitle: "Untested backups",
        mapDetail: "Restore is possible. Containment is slow.",
        addsNodes: ["backup"],
        highlightNodes: ["backup", "database"],
        preventionEffect: 0,
        detectionEffect: 0,
        blastRadiusEffect: 0,
        recoveryEffect: 1,
        campaignStageIds: ["contain-recover"],
      }),
      option("recovery-live", "recovery", "Live-account backups, no practised isolation", {
        description: "Copy the Claims Database into the same account. There is no practised isolation or revocation path.",
        challengeDescription: "Keep a live-account copy of the database without a drilled containment process.",
        tradeOff: "Cheap to store. An attacker who reaches production can often reach the copy too.",
        confirmation: "Backups sit in the live account. Isolation is not practised.",
        architectureUpdate: "Architecture updated: Database copies stay in the live account.",
        riskReduced: "Accidental deletion might still be undoable if the copy is intact.",
        residualRisk: "No tested way to isolate, revoke or restore after a real incident.",
        recommended: false,
        strength: "weak",
        icon: "database",
        mapTitle: "Live-account copies",
        mapDetail: "No practised isolation or revocation.",
        addsNodes: [],
        highlightNodes: ["database"],
        preventionEffect: 0,
        detectionEffect: 0,
        blastRadiusEffect: 0,
        recoveryEffect: 0,
        campaignStageIds: ["contain-recover"],
      }),
    ],
  },
];
