import type { ArchitectureDecision, ArchitectureOption, DecisionId } from "./types";

function option(
  id: string,
  decisionId: DecisionId,
  title: string,
  fields: Omit<ArchitectureOption, "id" | "decisionId" | "title">,
): ArchitectureOption {
  return { id, decisionId, title, ...fields };
}

export const LAB_DECISIONS: readonly ArchitectureDecision[] = [
  {
    id: "identity",
    number: 1,
    question: "Who should be allowed to access the claims application?",
    nodeId: "identity",
    options: [
      option("identity-mfa", "identity", "MFA and role-based access", {
        description: "Staff must use a second factor and only receive access required for their role.",
        challengeDescription: "Staff authenticate with a second factor and receive access by role.",
        tradeOff: "Slightly more friction during sign-in.",
        confirmation: "Identity now requires MFA and role-based access.",
        recommended: true,
        strength: "strong",
        icon: "shield",
        mapTitle: "MFA + RBAC",
        mapDetail: "Stops stolen-password login.",
      }),
      option("identity-password", "identity", "Password-only access", {
        description: "Faster and cheaper to introduce.",
        challengeDescription: "Staff sign in with a password and a shared claims role.",
        tradeOff: "A stolen password becomes a valid login.",
        confirmation: "Identity now accepts password-only sign-in.",
        recommended: false,
        strength: "weak",
        icon: "key",
        mapTitle: "Password only",
        mapDetail: "A stolen password is a working login.",
      }),
    ],
  },
  {
    id: "input",
    number: 2,
    question: "What should happen before an uploaded claims document reaches the AI?",
    nodeId: "input",
    options: [
      option("input-sandbox", "input", "Sandbox and sanitise the document", {
        description: "Inspect the file, remove active content and flag suspicious instructions.",
        challengeDescription: "Inspect uploads, strip active content and flag hidden instructions.",
        tradeOff: "Adds processing time.",
        confirmation: "Uploads now pass through a file sandbox.",
        recommended: true,
        strength: "strong",
        icon: "scan",
        mapTitle: "File Sandbox",
        mapDetail: "Scans and sanitises uploads.",
      }),
      option("input-typecheck", "input", "Check file type only", {
        description: "Accept the document if its extension and format are allowed.",
        challengeDescription: "Accept the file when the extension and format look allowed.",
        tradeOff: "Hidden or obfuscated content may survive.",
        confirmation: "Uploads are accepted after a file-type check only.",
        recommended: false,
        strength: "weak",
        icon: "filter",
        mapTitle: "Type check",
        mapDetail: "Hidden content may survive.",
      }),
    ],
  },
  {
    id: "model",
    number: 3,
    question: "Where should the claims model run?",
    nodeId: "model",
    options: [
      option("model-private", "model", "Private enterprise LLM", {
        description: "Use a private endpoint with controlled retention and no training on prompts.",
        challengeDescription: "Run the model on a private endpoint with controlled retention.",
        tradeOff: "More cost and configuration.",
        confirmation: "The claims model now runs on a private enterprise endpoint.",
        recommended: true,
        strength: "strong",
        icon: "cpu",
        mapTitle: "Private LLM",
        mapDetail: "No prompt training or retention.",
      }),
      option("model-public", "model", "Public hosted AI service", {
        description: "Send prompts directly to a standard external AI endpoint.",
        challengeDescription: "Send prompts to a standard hosted AI endpoint.",
        tradeOff: "Less control over prompts, logs and data handling.",
        confirmation: "Prompts now go to a public hosted AI service.",
        recommended: false,
        strength: "weak",
        icon: "cloud",
        mapTitle: "Public AI",
        mapDetail: "Less control of prompts and logs.",
      }),
    ],
  },
  {
    id: "retrieval",
    number: 4,
    question: "What information may the AI retrieve while processing a claim?",
    nodeId: "retrieval",
    options: [
      option("retrieval-case", "retrieval", "Only the current claim", {
        description: "Use case-scoped retrieval and access filters.",
        challengeDescription: "Limit retrieval to documents for the open claim.",
        tradeOff: "The AI may occasionally receive too little context.",
        confirmation: "Retrieval is now limited to the current claim.",
        recommended: true,
        strength: "strong",
        icon: "lock",
        mapTitle: "Case-scoped RAG",
        mapDetail: "Only current claim documents.",
      }),
      option("retrieval-index", "retrieval", "The shared claims index", {
        description: "Allow the AI to search across all available claims.",
        challengeDescription: "Let the assistant search the shared claims index.",
        tradeOff: "One manipulated request may expose unrelated customers.",
        confirmation: "The AI can now search the shared claims index.",
        recommended: false,
        strength: "weak",
        icon: "copy",
        mapTitle: "Shared claims index",
        mapDetail: "Search across other customers.",
      }),
    ],
  },
  {
    id: "secrets",
    number: 5,
    question: "How should the AI authenticate to internal services?",
    nodeId: "secrets",
    options: [
      option("secrets-vault", "secrets", "Managed identity and secrets vault", {
        description: "Use short-lived identities without reusable credentials in the application.",
        challengeDescription: "Use short-lived workload identity instead of a stored password.",
        tradeOff: "Requires cloud identity configuration.",
        confirmation: "Internal calls now use managed identity and a secrets vault.",
        recommended: true,
        strength: "strong",
        icon: "vault",
        mapTitle: "Managed Identity",
        mapDetail: "No reusable API credentials.",
      }),
      option("secrets-key", "secrets", "Static API key", {
        description: "Store one reusable key in the application configuration.",
        challengeDescription: "Keep one reusable service key in application configuration.",
        tradeOff: "A leaked key can be reused outside the application.",
        confirmation: "The AI now authenticates with a static API key.",
        recommended: false,
        strength: "weak",
        icon: "file",
        mapTitle: "Static API key",
        mapDetail: "A leaked key can be reused.",
      }),
    ],
  },
  {
    id: "data-access",
    number: 6,
    question: "What may the AI do through the Claims API?",
    nodeId: "data-access",
    options: [
      option("api-restricted", "data-access", "Restricted read-only access", {
        description: "Allow access only to the active claim and explicitly approved functions.",
        challengeDescription: "Limit the API to the active claim and approved read functions.",
        tradeOff: "Less flexibility for automation.",
        confirmation: "The Claims API is now restricted and read-only.",
        recommended: true,
        strength: "strong",
        icon: "lock",
        mapTitle: "Restricted API",
        mapDetail: "Read-only + least privilege.",
      }),
      option("api-broad", "data-access", "Broad service account", {
        description: "Allow the AI to read and update claims through a shared service identity.",
        challengeDescription: "Let the assistant use a shared service account on the Claims API.",
        tradeOff: "A compromised AI workflow receives a large blast radius.",
        confirmation: "The AI now uses a broad Claims API service account.",
        recommended: false,
        strength: "weak",
        icon: "database",
        mapTitle: "Broad service account",
        mapDetail: "Read and update across claims.",
      }),
    ],
  },
  {
    id: "oversight",
    number: 7,
    question: "Who should approve payout changes and customer-facing actions?",
    nodeId: "oversight",
    options: [
      option("oversight-human", "oversight", "Human approval", {
        description: "Require a claims handler to approve high-impact actions.",
        challengeDescription: "A claims handler must approve payout changes and customer-facing actions.",
        tradeOff: "Some cases take longer to complete.",
        confirmation: "High-impact actions now wait for human approval.",
        recommended: true,
        strength: "strong",
        icon: "person",
        mapTitle: "Human Approval",
        mapDetail: "Required for payout changes.",
      }),
      option("oversight-auto", "oversight", "AI executes automatically", {
        description: "Allow the AI to complete actions without additional approval.",
        challengeDescription: "Let the assistant complete high-impact actions on its own.",
        tradeOff: "Manipulated output can become a real business action.",
        confirmation: "The AI can now execute payout and customer actions automatically.",
        recommended: false,
        strength: "weak",
        icon: "bolt",
        mapTitle: "Automatic execution",
        mapDetail: "No extra approval on payouts.",
      }),
    ],
  },
  {
    id: "network",
    number: 8,
    question: "How should the AI services connect to internal systems?",
    nodeId: "network",
    options: [
      option("network-segmented", "network", "Private segmented services", {
        description: "Use private endpoints and separate the AI, application and data zones.",
        challengeDescription: "Place AI, application and data on separate private segments.",
        tradeOff: "More network and operational complexity.",
        confirmation: "AI services now sit on private, segmented networks.",
        recommended: true,
        strength: "strong",
        icon: "network",
        mapTitle: "Network Segmentation",
        mapDetail: "Limits lateral movement.",
      }),
      option("network-flat", "network", "Flat internal network", {
        description: "Let trusted internal services communicate freely.",
        challengeDescription: "Let internal services talk freely once they are on the network.",
        tradeOff: "One compromised service can move toward other systems.",
        confirmation: "Internal services now share a flat network.",
        recommended: false,
        strength: "weak",
        icon: "globe",
        mapTitle: "Flat network",
        mapDetail: "Trusted services can move freely.",
      }),
    ],
  },
  {
    id: "supply-chain",
    number: 9,
    question: "How should releases and dependencies reach production?",
    nodeId: "supply-chain",
    options: [
      option("supply-signed", "supply-chain", "Signed, pinned and scanned builds", {
        description: "Pin dependencies, scan releases and verify signed deployment artefacts.",
        challengeDescription: "Pin dependencies, scan releases and require signed artefacts.",
        tradeOff: "Updates require more validation.",
        confirmation: "Releases now require signed, pinned and scanned builds.",
        recommended: true,
        strength: "strong",
        icon: "pipeline",
        mapTitle: "Signed Builds",
        mapDetail: "Pinned and scanned dependencies.",
      }),
      option("supply-latest", "supply-chain", "Automatically use the latest versions", {
        description: "Update dependencies quickly with minimal release checks.",
        challengeDescription: "Pull the latest packages with light release checks.",
        tradeOff: "A compromised dependency may enter production.",
        confirmation: "Production now pulls the latest dependencies automatically.",
        recommended: false,
        strength: "weak",
        icon: "box",
        mapTitle: "Latest versions",
        mapDetail: "Minimal release checks.",
      }),
    ],
  },
  {
    id: "detection",
    number: 10,
    question: "How should suspicious behaviour be detected?",
    nodeId: "detection",
    options: [
      option("detection-siem", "detection", "Central SIEM and response playbook", {
        description: "Correlate identity, upload, AI, API and database events.",
        challengeDescription: "Correlate identity, upload, AI, API and database events in one place.",
        tradeOff: "Requires monitoring and response resources.",
        confirmation: "Detection now correlates the campaign in a SIEM with a response playbook.",
        recommended: true,
        strength: "strong",
        icon: "radar",
        mapTitle: "SIEM",
        mapDetail: "Correlates the full campaign.",
      }),
      option("detection-logs", "detection", "Application logs only", {
        description: "Keep logs inside the individual services.",
        challengeDescription: "Keep events inside each service’s own logs.",
        tradeOff: "The organisation may see isolated events but miss the campaign.",
        confirmation: "Each service now keeps its own application logs.",
        recommended: false,
        strength: "weak",
        icon: "list",
        mapTitle: "App logs",
        mapDetail: "Events stay inside each service.",
      }),
    ],
  },
];
