import type { MapEdgeDefinition, MapNodeDefinition } from "./types";

export const LAB_NODES: readonly MapNodeDefinition[] = [
  {
    id: "portal",
    name: "Claims Portal",
    kind: "core",
    decisionId: null,
    description: "Staff login and document upload.",
    column: 0,
    row: 1,
  },
  {
    id: "identity",
    name: "Identity",
    kind: "control",
    decisionId: "identity",
    description: "Who can sign in, and with what proof.",
    column: 1,
    row: 0,
  },
  {
    id: "input",
    name: "Document upload",
    kind: "control",
    decisionId: "input",
    description: "What happens to a claims file before the AI reads it.",
    column: 1,
    row: 1,
  },
  {
    id: "network",
    name: "Network",
    kind: "control",
    decisionId: "network",
    description: "How AI services reach the rest of the estate.",
    column: 1,
    row: 2,
  },
  {
    id: "model",
    name: "AI model",
    kind: "control",
    decisionId: "model",
    description: "Where prompts are processed.",
    column: 2,
    row: 0,
  },
  {
    id: "app",
    name: "AI Claims App",
    kind: "core",
    decisionId: null,
    description: "Summarises cases and drafts replies.",
    column: 2,
    row: 1,
  },
  {
    id: "supply-chain",
    name: "Software delivery",
    kind: "control",
    decisionId: "supply-chain",
    description: "How code and dependencies reach production.",
    column: 2,
    row: 2,
  },
  {
    id: "retrieval",
    name: "Retrieval",
    kind: "control",
    decisionId: "retrieval",
    description: "What the model is allowed to search.",
    column: 3,
    row: 0,
  },
  {
    id: "secrets",
    name: "Secrets + tools",
    kind: "control",
    decisionId: "secrets",
    description: "How the app proves itself to internal services.",
    column: 3,
    row: 1,
  },
  {
    id: "detection",
    name: "Monitoring",
    kind: "control",
    decisionId: "detection",
    description: "Whether events become one incident.",
    column: 3,
    row: 2,
  },
  {
    id: "data-access",
    name: "Claims API",
    kind: "control",
    decisionId: "data-access",
    description: "What the assistant may read or change.",
    column: 4,
    row: 0,
  },
  {
    id: "database",
    name: "Claims Database",
    kind: "asset",
    decisionId: null,
    description: "Customer and payout data.",
    column: 4,
    row: 1,
  },
  {
    id: "oversight",
    name: "Oversight",
    kind: "control",
    decisionId: "oversight",
    description: "Who can turn a draft into a payout.",
    column: 4,
    row: 2,
  },
];

export const LAB_EDGES: readonly MapEdgeDefinition[] = [
  { id: "portal-identity", from: "portal", to: "identity" },
  { id: "portal-input", from: "portal", to: "input" },
  { id: "portal-network", from: "portal", to: "network" },
  { id: "identity-app", from: "identity", to: "app" },
  { id: "input-app", from: "input", to: "app" },
  { id: "network-app", from: "network", to: "app" },
  { id: "app-model", from: "app", to: "model" },
  { id: "app-supply", from: "app", to: "supply-chain" },
  { id: "app-detection", from: "app", to: "detection" },
  { id: "model-retrieval", from: "model", to: "retrieval" },
  { id: "app-secrets", from: "app", to: "secrets" },
  { id: "retrieval-api", from: "retrieval", to: "data-access" },
  { id: "secrets-api", from: "secrets", to: "data-access" },
  { id: "api-database", from: "data-access", to: "database" },
  { id: "oversight-database", from: "oversight", to: "database" },
  { id: "app-oversight", from: "app", to: "oversight" },
];
