import type { AttackTechniqueDefinition } from "./types";

export const LAB_TECHNIQUES: readonly AttackTechniqueDefinition[] = [
  {
    id: "stolen-credentials",
    number: 1,
    name: "Stolen credentials",
    summary: "The Red Team tries stolen staff passwords against the claims portal.",
    entryNode: "portal",
    path: ["portal", "identity"],
    checks: [
      {
        decisionId: "identity",
        strongOptionId: "identity-mfa",
        stopNode: "identity",
        outcome: "blocked",
        attackerAction: "Reuse a stolen claims-handler password.",
        controlResponse: "MFA rejects the password. Role access would have been limited anyway.",
        explanation: "The stolen password is not enough. This technique ends at identity.",
        impact: "No working session from password replay.",
      },
    ],
    successAction: "Reuse a stolen claims-handler password.",
    successResponse: "Password-only sign-in accepts the credential.",
    successExplanation: "The attacker now has a working claims session.",
    successImpact: "The portal treats the thief as a staff member.",
  },
  {
    id: "poisoned-document",
    number: 2,
    name: "Poisoned claims document",
    summary: "A weaponised claims file is sent through the upload flow.",
    entryNode: "portal",
    path: ["portal", "input"],
    checks: [
      {
        decisionId: "input",
        strongOptionId: "input-sandbox",
        stopNode: "input",
        outcome: "blocked",
        attackerAction: "Upload a claims PDF with hidden instructions.",
        controlResponse: "The sandbox strips active content and flags the payload.",
        explanation: "The poisoned document never becomes trusted input for the AI.",
        impact: "This upload route is closed.",
      },
    ],
    successAction: "Upload a claims file that only needs an allowed extension.",
    successResponse: "The type check accepts the file. Hidden content survives.",
    successExplanation: "The weaponised document is now in the processing path.",
    successImpact: "The AI will later retrieve untrusted file content.",
  },
  {
    id: "prompt-injection",
    number: 3,
    name: "Obfuscated prompt injection",
    summary: "Hidden instructions try to steer the model and widen retrieval.",
    entryNode: "input",
    path: ["input", "app", "model", "retrieval"],
    checks: [
      {
        decisionId: "input",
        strongOptionId: "input-sandbox",
        stopNode: "input",
        outcome: "blocked",
        attackerAction: "Hide obfuscated instructions in retrieved claim text.",
        controlResponse: "Sanitised documents never carry executable instructions.",
        explanation: "Document processing stops the injection before the model is asked to obey it.",
        impact: "The model is not given hostile retrieved content.",
      },
      {
        decisionId: "model",
        strongOptionId: "model-private",
        stopNode: "model",
        outcome: "partial",
        attackerAction: "Push injected context into the hosted model.",
        controlResponse: "The private endpoint keeps prompts inside the approved boundary.",
        explanation: "Isolation limits damage, but retrieved content still reached the model.",
        impact: "No public-model leak. Injection is only partly effective.",
      },
      {
        decisionId: "retrieval",
        strongOptionId: "retrieval-case",
        stopNode: "retrieval",
        outcome: "contained",
        attackerAction: "Ask the model to search neighbouring claims.",
        controlResponse: "Case-scoped retrieval refuses other customers’ documents.",
        explanation: "The attacker cannot turn one claim into a search across the book.",
        impact: "Context stays on the current case.",
      },
    ],
    successAction: "Use retrieved file text to search the shared claims index.",
    successResponse: "The public model and shared index treat the injection as ordinary context.",
    successExplanation: "Hostile instructions now shape what the assistant retrieves.",
    successImpact: "Unrelated customer documents can enter the prompt.",
  },
  {
    id: "api-abuse",
    number: 4,
    name: "AI tool or API abuse",
    summary: "The assistant tries to reuse credentials and over-reach the Claims API.",
    entryNode: "app",
    path: ["app", "secrets", "data-access"],
    checks: [
      {
        decisionId: "secrets",
        strongOptionId: "secrets-vault",
        stopNode: "secrets",
        outcome: "blocked",
        attackerAction: "Read a reusable key from the application and call internal APIs.",
        controlResponse: "There is no static key to steal. Managed identity issues a short-lived token.",
        explanation: "Compromising the app does not hand over a portable credential.",
        impact: "This credential-reuse technique ends at secrets.",
      },
      {
        decisionId: "data-access",
        strongOptionId: "api-restricted",
        stopNode: "data-access",
        outcome: "blocked",
        attackerAction: "Request bulk claims through the service account.",
        controlResponse: "The restricted API allows only the active claim and approved reads.",
        explanation: "Least privilege stops the blast radius even if the workflow is manipulated.",
        impact: "No bulk export through the Claims API.",
      },
    ],
    successAction: "Reuse the static key and read widely through the service account.",
    successResponse: "The broad API accepts the call with the stored key.",
    successExplanation: "The manipulated workflow now has a large data path.",
    successImpact: "Customer records beyond the open case are readable.",
  },
  {
    id: "payout-manipulation",
    number: 5,
    name: "Payout manipulation",
    summary: "The attacker tries to turn a drafted change into a real payout.",
    entryNode: "app",
    path: ["app", "oversight", "database"],
    checks: [
      {
        decisionId: "oversight",
        strongOptionId: "oversight-human",
        stopNode: "oversight",
        outcome: "blocked",
        attackerAction: "Submit a payout change as if the model were confident.",
        controlResponse: "The action waits for a claims handler and is refused.",
        explanation: "Manipulated output cannot become a business action on its own.",
        impact: "No payout leaves without a person.",
      },
    ],
    successAction: "Let the assistant complete the payout change automatically.",
    successResponse: "Automatic execution treats the draft as an approved action.",
    successExplanation: "A manipulated instruction became a real payout change.",
    successImpact: "Customer-facing money movement is no longer gated.",
  },
  {
    id: "lateral-movement",
    number: 6,
    name: "Lateral movement or compromised dependency",
    summary: "The campaign tries to move across the estate or ride a tainted package.",
    entryNode: "app",
    path: ["app", "network", "supply-chain"],
    checks: [
      {
        decisionId: "network",
        strongOptionId: "network-segmented",
        stopNode: "network",
        outcome: "blocked",
        attackerAction: "Move from the AI zone toward neighbouring internal systems.",
        controlResponse: "Private segments refuse east-west movement from the AI services.",
        explanation: "A foothold in the assistant does not become a tour of the estate.",
        impact: "This lateral path ends at the network boundary.",
      },
      {
        decisionId: "supply-chain",
        strongOptionId: "supply-signed",
        stopNode: "supply-chain",
        outcome: "blocked",
        attackerAction: "Land a compromised dependency in the next release.",
        controlResponse: "Pinned, scanned and signed builds reject the artefact.",
        explanation: "The software delivery control stops this supply-chain attempt.",
        impact: "The tainted package does not reach production.",
      },
    ],
    successAction: "Walk the flat network or slip a latest-version dependency into production.",
    successResponse: "Internal trust and light release checks let the attempt through.",
    successExplanation: "The campaign can move toward other systems or ship hostile code.",
    successImpact: "The blast radius is no longer limited to the claims assistant.",
  },
  {
    id: "detection",
    number: 7,
    name: "Detection and containment",
    summary: "The last question is whether anyone can see the campaign as one incident.",
    entryNode: "app",
    path: ["app", "detection"],
    checks: [
      {
        decisionId: "detection",
        strongOptionId: "detection-siem",
        stopNode: "detection",
        outcome: "detected",
        attackerAction: "Leave traces across identity, upload, AI, API and data.",
        controlResponse: "The SIEM correlates the events and the playbook names the campaign.",
        explanation: "Monitoring connects the pivots instead of storing isolated logs.",
        impact: "The organisation can contain what is still in motion.",
      },
    ],
    successAction: "Leave a breadcrumb in each service log.",
    successResponse: "Each service kept its own events. Nobody joined them in time.",
    successExplanation: "The organisation may reconstruct this later. It does not see a campaign now.",
    successImpact: "Containment depends on luck and after-the-fact forensics.",
  },
];
