import type { AttackTechniqueDefinition } from "./types";

export const LAB_TECHNIQUES: readonly AttackTechniqueDefinition[] = [
  {
    id: "initial-foothold",
    number: 1,
    name: "Initial foothold",
    summary: "The Red Team uses a stolen authenticated low-privilege claims-handler session.",
    role: "offensive",
    requiredAccess: "None. This is the scenario assumption.",
    target: "Authenticated employee session",
    attemptedAction: "Reuse an already authenticated claims-handler session.",
    controlTested: "MFA + RBAC",
    accessIfSuccessful: "A working low-privilege staff session.",
    nextStageIds: ["claims-portal"],
    entryNode: "employee",
    path: ["employee", "portal"],
    primaryDecisionId: "identity",
    influencingDecisionIds: ["exposure"],
  },
  {
    id: "claims-portal",
    number: 2,
    name: "Claims Portal",
    summary: "The stolen session is used to open the Claims Portal.",
    role: "offensive",
    requiredAccess: "Authenticated employee session.",
    target: "Claims Portal",
    attemptedAction: "Sign in to the portal with the stolen session.",
    controlTested: "MFA + RBAC and edge exposure",
    accessIfSuccessful: "Portal access as a claims handler.",
    nextStageIds: ["poisoned-document"],
    entryNode: "employee",
    path: ["employee", "portal"],
    primaryDecisionId: "identity",
    influencingDecisionIds: ["exposure"],
  },
  {
    id: "poisoned-document",
    number: 3,
    name: "Poisoned document upload",
    summary: "A claims file carrying prompt-injection text is uploaded through the portal.",
    role: "offensive",
    requiredAccess: "Claims Portal session.",
    target: "Document path into the AI Claims App",
    attemptedAction: "Upload a claims document that hides prompt-injection text.",
    controlTested: "Document Scanner",
    accessIfSuccessful: "Untrusted document content in the AI workflow.",
    nextStageIds: ["ai-manipulation"],
    entryNode: "portal",
    path: ["portal", "app"],
    primaryDecisionId: "input",
    influencingDecisionIds: ["exposure"],
  },
  {
    id: "ai-manipulation",
    number: 4,
    name: "AI manipulation attempt",
    summary: "Hidden instructions try to make the AI Claims App take unauthorised actions.",
    role: "offensive",
    requiredAccess: "Document content in the AI workflow.",
    target: "AI Claims App",
    attemptedAction: "Steer the assistant into unauthorised retrieval or tool use.",
    controlTested: "AI input controls, case-scoped retrieval and restricted tools",
    accessIfSuccessful: "A steered AI workflow that can call internal services.",
    nextStageIds: ["api-call"],
    entryNode: "app",
    path: ["app"],
    primaryDecisionId: "retrieval",
    influencingDecisionIds: ["input", "data-access"],
  },
  {
    id: "api-call",
    number: 5,
    name: "Claims API abuse",
    summary: "The steered AI Claims App tries to call the Claims API as an internal service.",
    role: "offensive",
    requiredAccess: "Unauthorised influence over the AI Claims App.",
    target: "Claims API",
    attemptedAction: "Call the Claims API with a prompted or stolen service identity.",
    controlTested: "Private API gateway and managed identity",
    accessIfSuccessful: "Working Claims API calls.",
    nextStageIds: ["unrelated-claims"],
    entryNode: "app",
    path: ["app", "api"],
    primaryDecisionId: "gateway",
    influencingDecisionIds: ["secrets", "network"],
  },
  {
    id: "unrelated-claims",
    number: 6,
    name: "Unrelated claims access",
    summary: "The attacker tries to pull customer records that are not the open case.",
    role: "offensive",
    requiredAccess: "Claims API access.",
    target: "Unrelated claims in the Claims Database",
    attemptedAction: "Search or query claims that belong to other customers.",
    controlTested: "Case-scoped retrieval and least privilege",
    accessIfSuccessful: "Other customers’ claims.",
    nextStageIds: ["extract-modify"],
    entryNode: "api",
    path: ["api", "database"],
    primaryDecisionId: "retrieval",
    influencingDecisionIds: ["data-access"],
  },
  {
    id: "extract-modify",
    number: 7,
    name: "Data extraction or modification",
    summary: "The attacker tries to read or change records in the Claims Database.",
    role: "offensive",
    requiredAccess: "Claims API access.",
    target: "Claims Database",
    attemptedAction: "Export or change claims records through the API.",
    controlTested: "Least-privilege API permissions",
    accessIfSuccessful: "Read or write on claims data.",
    nextStageIds: ["payout-manipulation"],
    entryNode: "api",
    path: ["api", "database"],
    primaryDecisionId: "data-access",
    influencingDecisionIds: ["network", "secrets"],
  },
  {
    id: "payout-manipulation",
    number: 8,
    name: "Payout manipulation",
    summary: "The attacker tries to change a payout without human approval.",
    role: "offensive",
    requiredAccess: "Write access to claims data.",
    target: "Payout functions",
    attemptedAction: "Change payout fields on a claim.",
    controlTested: "Human approval and read-only API limits",
    accessIfSuccessful: "A modified payout.",
    nextStageIds: ["monitoring"],
    entryNode: "api",
    path: ["api", "database"],
    primaryDecisionId: "data-access",
    influencingDecisionIds: ["recovery"],
  },
  {
    id: "monitoring",
    number: 9,
    name: "Monitoring",
    summary: "Unusual session behaviour, document processing and AI activity may become one incident.",
    role: "detection",
    requiredAccess: "Any activity on the path. Detection does not require a later offensive success.",
    target: "SIEM",
    attemptedAction: "Leave traces across session, upload, AI and API activity.",
    controlTested: "SIEM and response playbook",
    accessIfSuccessful: "The attacker stays unseen.",
    nextStageIds: ["contain-recover"],
    entryNode: "portal",
    path: ["portal", "app"],
    primaryDecisionId: "detection",
    influencingDecisionIds: [],
  },
  {
    id: "contain-recover",
    number: 10,
    name: "Session revocation and isolation",
    summary: "The organisation may revoke the session, isolate the case and restore from backups if needed.",
    role: "response",
    requiredAccess: "Detection or a practised containment process.",
    target: "Stolen session and affected case",
    attemptedAction: "Keep using the stolen session, including any changes already made.",
    controlTested: "Isolation, revocation and protected backups",
    accessIfSuccessful: "Continued access after the organisation should have cut it off.",
    nextStageIds: [],
    entryNode: "portal",
    path: ["portal"],
    primaryDecisionId: "recovery",
    influencingDecisionIds: ["detection"],
  },
];
