import type { AttackTechniqueDefinition } from "./types";

export const LAB_TECHNIQUES: readonly AttackTechniqueDefinition[] = [
  {
    id: "stolen-credentials",
    number: 1,
    name: "Stolen credentials",
    summary: "An attacker tries a stolen employee password against the Claims Portal.",
    entryNode: "employee",
    path: ["employee", "waf", "portal", "identity"],
    primaryDecisionId: "identity",
    influencingDecisionIds: ["exposure"],
  },
  {
    id: "poisoned-document",
    number: 2,
    name: "Poisoned claims document",
    summary: "A claim file carrying prompt-injection text is uploaded through the portal.",
    entryNode: "portal",
    path: ["portal", "waf", "scanner", "app"],
    primaryDecisionId: "input",
    influencingDecisionIds: ["exposure"],
  },
  {
    id: "ai-manipulation",
    number: 3,
    name: "AI assistant manipulation",
    summary: "Hidden instructions try to steer the AI Claims App.",
    entryNode: "scanner",
    path: ["scanner", "app", "retrieval"],
    primaryDecisionId: "retrieval",
    influencingDecisionIds: ["input"],
  },
  {
    id: "api-call",
    number: 4,
    name: "Claims API call",
    summary: "The AI Claims App tries to call the Claims API as an internal service.",
    entryNode: "app",
    path: ["app", "secrets", "gateway", "api"],
    primaryDecisionId: "gateway",
    influencingDecisionIds: ["secrets", "network"],
  },
  {
    id: "unrelated-claims",
    number: 5,
    name: "Unrelated claims access",
    summary: "The attacker tries to pull customer records that are not the open case.",
    entryNode: "retrieval",
    path: ["retrieval", "api", "database"],
    primaryDecisionId: "retrieval",
    influencingDecisionIds: ["data-access"],
  },
  {
    id: "extract-modify",
    number: 6,
    name: "Extract or modify data",
    summary: "The attacker tries to read or change records in the Claims Database.",
    entryNode: "api",
    path: ["api", "network", "database"],
    primaryDecisionId: "data-access",
    influencingDecisionIds: ["network", "secrets"],
  },
  {
    id: "monitoring",
    number: 7,
    name: "Monitoring and detection",
    summary: "Authentication, API, AI and database events may become one incident — or stay isolated.",
    entryNode: "detection",
    path: ["identity", "app", "api", "detection"],
    primaryDecisionId: "detection",
    influencingDecisionIds: [],
  },
  {
    id: "contain-recover",
    number: 8,
    name: "Containment and recovery",
    summary: "The organisation may isolate systems, revoke access and restore from protected backups.",
    entryNode: "detection",
    path: ["detection", "backup", "database"],
    primaryDecisionId: "recovery",
    influencingDecisionIds: ["detection"],
  },
];
